// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package System_Reg_pkg;

    localparam SYSTEM_REG_DATA_WIDTH = 32;
    localparam SYSTEM_REG_MIN_ADDR_WIDTH = 8;
    localparam SYSTEM_REG_SIZE = 'hc4;

    typedef struct {
        logic hwset;
    } System_Reg__SysInterrupt__gpio_interrupt__in_t;

    typedef struct {
        System_Reg__SysInterrupt__gpio_interrupt__in_t gpio_interrupt;
    } System_Reg__SysInterrupt__in_t;

    typedef struct {
        logic hwset;
    } System_Reg__SoftReset__cpu_warm_reset__in_t;

    typedef struct {
        System_Reg__SoftReset__cpu_warm_reset__in_t cpu_warm_reset;
    } System_Reg__SoftReset__in_t;

    typedef struct {
        logic next;
    } System_Reg__ResetCause__por__in_t;

    typedef struct {
        logic next;
    } System_Reg__ResetCause__watchdog_timedout__in_t;

    typedef struct {
        logic next;
    } System_Reg__ResetCause__sysreset_req__in_t;

    typedef struct {
        logic next;
    } System_Reg__ResetCause__brownout__in_t;

    typedef struct {
        logic next;
    } System_Reg__ResetCause__softreset__in_t;

    typedef struct {
        logic next;
        logic hwset;
    } System_Reg__ResetCause__cpu_warm_reset__in_t;

    typedef struct {
        System_Reg__ResetCause__por__in_t por;
        System_Reg__ResetCause__watchdog_timedout__in_t watchdog_timedout;
        System_Reg__ResetCause__sysreset_req__in_t sysreset_req;
        System_Reg__ResetCause__brownout__in_t brownout;
        System_Reg__ResetCause__softreset__in_t softreset;
        System_Reg__ResetCause__cpu_warm_reset__in_t cpu_warm_reset;
    } System_Reg__ResetCause__in_t;

    typedef struct {
        logic next;
    } System_Reg__PowerDomainAck__cpu_pd_ack__in_t;

    typedef struct {
        logic next;
    } System_Reg__PowerDomainAck__sram_pd_ack__in_t;

    typedef struct {
        logic next;
    } System_Reg__PowerDomainAck__chiplet_pd_ack__in_t;

    typedef struct {
        logic next;
    } System_Reg__PowerDomainAck__mram_pd_ack__in_t;

    typedef struct {
        logic next;
    } System_Reg__PowerDomainAck__system_pd_ack__in_t;

    typedef struct {
        logic next;
    } System_Reg__PowerDomainAck__hyperbus_pd_ack__in_t;

    typedef struct {
        logic [7:0] next;
    } System_Reg__PowerDomainAck__minion_pd_ack__in_t;

    typedef struct {
        System_Reg__PowerDomainAck__cpu_pd_ack__in_t cpu_pd_ack;
        System_Reg__PowerDomainAck__sram_pd_ack__in_t sram_pd_ack;
        System_Reg__PowerDomainAck__chiplet_pd_ack__in_t chiplet_pd_ack;
        System_Reg__PowerDomainAck__mram_pd_ack__in_t mram_pd_ack;
        System_Reg__PowerDomainAck__system_pd_ack__in_t system_pd_ack;
        System_Reg__PowerDomainAck__hyperbus_pd_ack__in_t hyperbus_pd_ack;
        System_Reg__PowerDomainAck__minion_pd_ack__in_t minion_pd_ack;
    } System_Reg__PowerDomainAck__in_t;

    typedef struct {
        logic [20:0] next;
    } System_Reg__PowerGood__counter__in_t;

    typedef struct {
        System_Reg__PowerGood__counter__in_t counter;
    } System_Reg__PowerGood__in_t;

    typedef struct {
        logic [1:0] next;
    } System_Reg__ChipMode__chip_mode__in_t;

    typedef struct {
        logic next;
    } System_Reg__ChipMode__ifc_width__in_t;

    typedef struct {
        System_Reg__ChipMode__chip_mode__in_t chip_mode;
        System_Reg__ChipMode__ifc_width__in_t ifc_width;
    } System_Reg__ChipMode__in_t;

    typedef struct {
        logic [10:0] next;
    } System_Reg__GPIO_I__gpio_i__in_t;

    typedef struct {
        System_Reg__GPIO_I__gpio_i__in_t gpio_i;
    } System_Reg__GPIO_I__in_t;

    typedef struct {
        logic [3:0] next;
    } tsense_status__data__in_t;

    typedef struct {
        logic next;
    } tsense_status__valid__in_t;

    typedef struct {
        logic next;
    } tsense_status__conv_b__in_t;

    typedef struct {
        tsense_status__data__in_t data;
        tsense_status__valid__in_t valid;
        tsense_status__conv_b__in_t conv_b;
    } tsense_status__in_t;

    typedef struct {
        System_Reg__SysInterrupt__in_t SysInterrupt;
        System_Reg__SoftReset__in_t SoftReset;
        System_Reg__ResetCause__in_t ResetCause;
        System_Reg__PowerDomainAck__in_t PowerDomainAck;
        System_Reg__PowerGood__in_t PowerGood;
        System_Reg__ChipMode__in_t ChipMode;
        System_Reg__GPIO_I__in_t GPIO_I;
        tsense_status__in_t tsense_status;
    } System_Reg__in_t;

    typedef struct {
        logic value;
    } System_Reg__SystemConfig__sys_interrupt_enable__out_t;

    typedef struct {
        logic value;
    } System_Reg__SystemConfig__mram_startup_bypass__out_t;

    typedef struct {
        logic value;
        logic swmod;
    } System_Reg__SystemConfig__wdog_disable__out_t;

    typedef struct {
        logic value;
    } System_Reg__SystemConfig__i2c_enable__out_t;

    typedef struct {
        logic value;
    } System_Reg__SystemConfig__spi_enable__out_t;

    typedef struct {
        logic value;
    } System_Reg__SystemConfig__qspi_enable__out_t;

    typedef struct {
        logic value;
    } System_Reg__SystemConfig__uart_enable__out_t;

    typedef struct {
        logic value;
    } System_Reg__SystemConfig__osc_out_enable__out_t;

    typedef struct {
        System_Reg__SystemConfig__sys_interrupt_enable__out_t sys_interrupt_enable;
        System_Reg__SystemConfig__mram_startup_bypass__out_t mram_startup_bypass;
        System_Reg__SystemConfig__wdog_disable__out_t wdog_disable;
        System_Reg__SystemConfig__i2c_enable__out_t i2c_enable;
        System_Reg__SystemConfig__spi_enable__out_t spi_enable;
        System_Reg__SystemConfig__qspi_enable__out_t qspi_enable;
        System_Reg__SystemConfig__uart_enable__out_t uart_enable;
        System_Reg__SystemConfig__osc_out_enable__out_t osc_out_enable;
    } System_Reg__SystemConfig__out_t;

    typedef struct {
        logic [31:0] value;
    } System_Reg__watchdog_count__watchdog_count__out_t;

    typedef struct {
        System_Reg__watchdog_count__watchdog_count__out_t watchdog_count;
    } System_Reg__watchdog_count__out_t;

    typedef struct {
        logic value;
    } System_Reg__Watchdog__kick__out_t;

    typedef struct {
        System_Reg__Watchdog__kick__out_t kick;
    } System_Reg__Watchdog__out_t;

    typedef struct {
        logic value;
    } System_Reg__SysInterrupt__interrupt__out_t;

    typedef struct {
        logic value;
    } System_Reg__SysInterrupt__gpio_interrupt__out_t;

    typedef struct {
        System_Reg__SysInterrupt__interrupt__out_t interrupt;
        System_Reg__SysInterrupt__gpio_interrupt__out_t gpio_interrupt;
    } System_Reg__SysInterrupt__out_t;

    typedef struct {
        logic value;
    } System_Reg__SoftReset__soft_reset__out_t;

    typedef struct {
        logic value;
    } System_Reg__SoftReset__cpu_warm_reset__out_t;

    typedef struct {
        logic value;
    } System_Reg__SoftReset__mram_rst_b__out_t;

    typedef struct {
        logic value;
    } System_Reg__SoftReset__cpu_soft_reset__out_t;

    typedef struct {
        System_Reg__SoftReset__soft_reset__out_t soft_reset;
        System_Reg__SoftReset__cpu_warm_reset__out_t cpu_warm_reset;
        System_Reg__SoftReset__mram_rst_b__out_t mram_rst_b;
        System_Reg__SoftReset__cpu_soft_reset__out_t cpu_soft_reset;
    } System_Reg__SoftReset__out_t;

    typedef struct {
        logic swacc;
    } System_Reg__ResetCause__por__out_t;

    typedef struct {
        logic swacc;
    } System_Reg__ResetCause__watchdog_timedout__out_t;

    typedef struct {
        logic swacc;
    } System_Reg__ResetCause__sysreset_req__out_t;

    typedef struct {
        logic swacc;
    } System_Reg__ResetCause__brownout__out_t;

    typedef struct {
        logic swacc;
    } System_Reg__ResetCause__softreset__out_t;

    typedef struct {
        logic swacc;
    } System_Reg__ResetCause__cpu_warm_reset__out_t;

    typedef struct {
        System_Reg__ResetCause__por__out_t por;
        System_Reg__ResetCause__watchdog_timedout__out_t watchdog_timedout;
        System_Reg__ResetCause__sysreset_req__out_t sysreset_req;
        System_Reg__ResetCause__brownout__out_t brownout;
        System_Reg__ResetCause__softreset__out_t softreset;
        System_Reg__ResetCause__cpu_warm_reset__out_t cpu_warm_reset;
    } System_Reg__ResetCause__out_t;

    typedef struct {
        logic value;
    } System_Reg__PowerDomainReq__cpu_pd__out_t;

    typedef struct {
        logic value;
    } System_Reg__PowerDomainReq__cpu_rom_powerdown__out_t;

    typedef struct {
        logic value;
    } System_Reg__PowerDomainReq__cpu_ram_powerdown__out_t;

    typedef struct {
        logic value;
    } System_Reg__PowerDomainReq__chiplet_pd__out_t;

    typedef struct {
        logic value;
    } System_Reg__PowerDomainReq__mram_pd__out_t;

    typedef struct {
        logic value;
    } System_Reg__PowerDomainReq__system_poweroff__out_t;

    typedef struct {
        logic value;
    } System_Reg__PowerDomainReq__xspi_pd__out_t;

    typedef struct {
        logic [7:0] value;
    } System_Reg__PowerDomainReq__minion_pd__out_t;

    typedef struct {
        logic value;
    } System_Reg__PowerDomainReq__mram_dsleep_en__out_t;

    typedef struct {
        logic value;
    } System_Reg__PowerDomainReq__cpu_sleep_en__out_t;

    typedef struct {
        System_Reg__PowerDomainReq__cpu_pd__out_t cpu_pd;
        System_Reg__PowerDomainReq__cpu_rom_powerdown__out_t cpu_rom_powerdown;
        System_Reg__PowerDomainReq__cpu_ram_powerdown__out_t cpu_ram_powerdown;
        System_Reg__PowerDomainReq__chiplet_pd__out_t chiplet_pd;
        System_Reg__PowerDomainReq__mram_pd__out_t mram_pd;
        System_Reg__PowerDomainReq__system_poweroff__out_t system_poweroff;
        System_Reg__PowerDomainReq__xspi_pd__out_t xspi_pd;
        System_Reg__PowerDomainReq__minion_pd__out_t minion_pd;
        System_Reg__PowerDomainReq__mram_dsleep_en__out_t mram_dsleep_en;
        System_Reg__PowerDomainReq__cpu_sleep_en__out_t cpu_sleep_en;
    } System_Reg__PowerDomainReq__out_t;

    typedef struct {
        logic [20:0] value;
        logic swmod;
    } System_Reg__PowerGood__counter__out_t;

    typedef struct {
        System_Reg__PowerGood__counter__out_t counter;
    } System_Reg__PowerGood__out_t;

    typedef struct {
        logic [1:0] value;
    } System_Reg__ChipMode__bootload__out_t;

    typedef struct {
        logic [1:0] value;
    } System_Reg__ChipMode__load_external__out_t;

    typedef struct {
        System_Reg__ChipMode__bootload__out_t bootload;
        System_Reg__ChipMode__load_external__out_t load_external;
    } System_Reg__ChipMode__out_t;

    typedef struct {
        logic [31:0] value;
    } System_Reg__Mailbox0__mbox0__out_t;

    typedef struct {
        System_Reg__Mailbox0__mbox0__out_t mbox0;
    } System_Reg__Mailbox0__out_t;

    typedef struct {
        logic [31:0] value;
    } System_Reg__Mailbox1__mbox1__out_t;

    typedef struct {
        System_Reg__Mailbox1__mbox1__out_t mbox1;
    } System_Reg__Mailbox1__out_t;

    typedef struct {
        logic [10:0] value;
    } System_Reg__GPIO_OE__gpio_oe__out_t;

    typedef struct {
        System_Reg__GPIO_OE__gpio_oe__out_t gpio_oe;
    } System_Reg__GPIO_OE__out_t;

    typedef struct {
        logic [10:0] value;
    } System_Reg__GPIO_O__gpio_o__out_t;

    typedef struct {
        System_Reg__GPIO_O__gpio_o__out_t gpio_o;
    } System_Reg__GPIO_O__out_t;

    typedef struct {
        logic [10:0] value;
    } System_Reg__GPIO_Interrupt_Enable__gpio_interrupt_en__out_t;

    typedef struct {
        System_Reg__GPIO_Interrupt_Enable__gpio_interrupt_en__out_t gpio_interrupt_en;
    } System_Reg__GPIO_Interrupt_Enable__out_t;

    typedef struct {
        logic value;
    } ring_osc_ctrl__en__out_t;

    typedef struct {
        logic value;
    } ring_osc_ctrl__divby2_sel__out_t;

    typedef struct {
        logic [4:0] value;
    } ring_osc_ctrl__trm__out_t;

    typedef struct {
        logic value;
    } ring_osc_ctrl__dbg_en__out_t;

    typedef struct {
        logic value;
    } ring_osc_ctrl__dbg_anachip_en__out_t;

    typedef struct {
        logic value;
    } ring_osc_ctrl__dbg_rohcip_en__out_t;

    typedef struct {
        logic value;
    } ring_osc_ctrl__dbg_sah_en_b__out_t;

    typedef struct {
        ring_osc_ctrl__en__out_t en;
        ring_osc_ctrl__divby2_sel__out_t divby2_sel;
        ring_osc_ctrl__trm__out_t trm;
        ring_osc_ctrl__dbg_en__out_t dbg_en;
        ring_osc_ctrl__dbg_anachip_en__out_t dbg_anachip_en;
        ring_osc_ctrl__dbg_rohcip_en__out_t dbg_rohcip_en;
        ring_osc_ctrl__dbg_sah_en_b__out_t dbg_sah_en_b;
    } ring_osc_ctrl__out_t;

    typedef struct {
        logic [3:0] value;
    } clock_divider__count__out_t;

    typedef struct {
        logic value;
    } clock_divider__div_enable__out_t;

    typedef struct {
        clock_divider__count__out_t count;
        clock_divider__div_enable__out_t div_enable;
    } clock_divider__out_t;

    typedef struct {
        logic value;
    } tsense_ctrl__conv__out_t;

    typedef struct {
        logic value;
    } tsense_ctrl__sen_en__out_t;

    typedef struct {
        logic [1:0] value;
    } tsense_ctrl__sen_sel__out_t;

    typedef struct {
        logic [7:0] value;
    } tsense_ctrl__clk_div__out_t;

    typedef struct {
        tsense_ctrl__conv__out_t conv;
        tsense_ctrl__sen_en__out_t sen_en;
        tsense_ctrl__sen_sel__out_t sen_sel;
        tsense_ctrl__clk_div__out_t clk_div;
    } tsense_ctrl__out_t;

    typedef struct {
        System_Reg__SystemConfig__out_t SystemConfig;
        System_Reg__watchdog_count__out_t watchdog_count;
        System_Reg__Watchdog__out_t Watchdog;
        System_Reg__SysInterrupt__out_t SysInterrupt;
        System_Reg__SoftReset__out_t SoftReset;
        System_Reg__ResetCause__out_t ResetCause;
        System_Reg__PowerDomainReq__out_t PowerDomainReq;
        System_Reg__PowerGood__out_t PowerGood;
        System_Reg__ChipMode__out_t ChipMode;
        System_Reg__Mailbox0__out_t Mailbox0;
        System_Reg__Mailbox1__out_t Mailbox1;
        System_Reg__GPIO_OE__out_t GPIO_OE;
        System_Reg__GPIO_O__out_t GPIO_O;
        System_Reg__GPIO_Interrupt_Enable__out_t GPIO_Interrupt_Enable;
        ring_osc_ctrl__out_t ring_osc;
        clock_divider__out_t cpu_divider;
        clock_divider__out_t system_divider;
        clock_divider__out_t periph_divider;
        tsense_ctrl__out_t tsense_ctrl;
    } System_Reg__out_t;
endpackage
