../deps/tech_cells_generic/src/rtl/tc_sram.sv
../deps/tech_cells_generic/src/rtl/tc_sram_impl.sv
../deps/tech_cells_generic/src/rtl/tc_clk.sv
../deps/tech_cells_generic/src/tc_pwr.sv
+incdir+../deps/common_cells/include
../deps/common_cells/src/binary_to_gray.sv
../deps/common_cells/src/cb_filter_pkg.sv
../deps/common_cells/src/cc_onehot.sv
../deps/common_cells/src/cdc_reset_ctrlr_pkg.sv
../deps/common_cells/src/cf_math_pkg.sv
../deps/common_cells/src/clk_int_div.sv
../deps/common_cells/src/credit_counter.sv
../deps/common_cells/src/delta_counter.sv
../deps/common_cells/src/ecc_pkg.sv
../deps/common_cells/src/edge_propagator_tx.sv
../deps/common_cells/src/exp_backoff.sv
../deps/common_cells/src/fifo_v3.sv
../deps/common_cells/src/gray_to_binary.sv
../deps/common_cells/src/heaviside.sv
../deps/common_cells/src/isochronous_4phase_handshake.sv
../deps/common_cells/src/isochronous_spill_register.sv
../deps/common_cells/src/lfsr.sv
../deps/common_cells/src/lfsr_16bit.sv
../deps/common_cells/src/lfsr_8bit.sv
../deps/common_cells/src/lossy_valid_to_stream.sv
../deps/common_cells/src/mv_filter.sv
../deps/common_cells/src/onehot_to_bin.sv
../deps/common_cells/src/plru_tree.sv
../deps/common_cells/src/passthrough_stream_fifo.sv
../deps/common_cells/src/popcount.sv
../deps/common_cells/src/ring_buffer.sv
../deps/common_cells/src/rr_arb_tree.sv
../deps/common_cells/src/rstgen_bypass.sv
../deps/common_cells/src/serial_deglitch.sv
../deps/common_cells/src/shift_reg.sv
../deps/common_cells/src/shift_reg_gated.sv
../deps/common_cells/src/spill_register_flushable.sv
../deps/common_cells/src/stream_demux.sv
../deps/common_cells/src/stream_filter.sv
../deps/common_cells/src/stream_fork.sv
../deps/common_cells/src/stream_intf.sv
../deps/common_cells/src/stream_join_dynamic.sv
../deps/common_cells/src/stream_mux.sv
../deps/common_cells/src/stream_throttle.sv
../deps/common_cells/src/sub_per_hash.sv
../deps/common_cells/src/sync.sv
../deps/common_cells/src/sync_wedge.sv
../deps/common_cells/src/unread.sv
../deps/common_cells/src/read.sv
../deps/common_cells/src/addr_decode_dync.sv
../deps/common_cells/src/boxcar.sv
../deps/common_cells/src/cdc_2phase.sv
../deps/common_cells/src/cdc_4phase.sv
../deps/common_cells/src/clk_int_div_static.sv
../deps/common_cells/src/trip_counter.sv
../deps/common_cells/src/addr_decode.sv
../deps/common_cells/src/addr_decode_napot.sv
../deps/common_cells/src/multiaddr_decode.sv
../deps/common_cells/src/cb_filter.sv
../deps/common_cells/src/cdc_fifo_2phase.sv
../deps/common_cells/src/clk_mux_glitch_free.sv
../deps/common_cells/src/counter.sv
../deps/common_cells/src/ecc_decode.sv
../deps/common_cells/src/ecc_encode.sv
../deps/common_cells/src/edge_detect.sv
../deps/common_cells/src/lzc.sv
../deps/common_cells/src/max_counter.sv
../deps/common_cells/src/rstgen.sv
../deps/common_cells/src/spill_register.sv
../deps/common_cells/src/stream_delay.sv
../deps/common_cells/src/stream_fifo.sv
../deps/common_cells/src/stream_fork_dynamic.sv
../deps/common_cells/src/stream_join.sv
../deps/common_cells/src/cdc_reset_ctrlr.sv
../deps/common_cells/src/cdc_fifo_gray.sv
../deps/common_cells/src/fall_through_register.sv
../deps/common_cells/src/id_queue.sv
../deps/common_cells/src/stream_to_mem.sv
../deps/common_cells/src/stream_arbiter_flushable.sv
../deps/common_cells/src/stream_fifo_optimal_wrap.sv
../deps/common_cells/src/stream_register.sv
../deps/common_cells/src/stream_xbar.sv
../deps/common_cells/src/cdc_fifo_gray_clearable.sv
../deps/common_cells/src/cdc_2phase_clearable.sv
../deps/common_cells/src/mem_to_banks_detailed.sv
../deps/common_cells/src/stream_arbiter.sv
../deps/common_cells/src/stream_omega_net.sv
../deps/common_cells/src/mem_to_banks.sv
../deps/common_cells/src/edge_propagator_ack.sv
../deps/common_cells/src/edge_propagator.sv
../deps/common_cells/src/edge_propagator_rx.sv
+incdir+../deps/axi/include
../deps/axi/src/axi_pkg.sv
../deps/axi/src/axi_demux_id_counters.sv
../deps/axi/src/axi_intf.sv
../deps/axi/src/axi_atop_filter.sv
../deps/axi/src/axi_burst_splitter_gran.sv
../deps/axi/src/axi_burst_unwrap.sv
../deps/axi/src/axi_bus_compare.sv
../deps/axi/src/axi_cdc_dst.sv
../deps/axi/src/axi_cdc_src.sv
../deps/axi/src/axi_cut.sv
../deps/axi/src/axi_delayer.sv
../deps/axi/src/axi_demux_simple.sv
../deps/axi/src/axi_dw_downsizer.sv
../deps/axi/src/axi_dw_upsizer.sv
../deps/axi/src/axi_fifo.sv
../deps/axi/src/axi_fifo_delay_dyn.sv
../deps/axi/src/axi_id_remap.sv
../deps/axi/src/axi_id_prepend.sv
../deps/axi/src/axi_inval_filter.sv
../deps/axi/src/axi_isolate.sv
../deps/axi/src/axi_join.sv
../deps/axi/src/axi_lite_demux.sv
../deps/axi/src/axi_lite_dw_converter.sv
../deps/axi/src/axi_lite_from_mem.sv
../deps/axi/src/axi_lite_join.sv
../deps/axi/src/axi_lite_lfsr.sv
../deps/axi/src/axi_lite_mailbox.sv
../deps/axi/src/axi_lite_mux.sv
../deps/axi/src/axi_lite_regs.sv
../deps/axi/src/axi_lite_to_apb.sv
../deps/axi/src/axi_lite_to_axi.sv
../deps/axi/src/axi_modify_address.sv
../deps/axi/src/axi_mux.sv
../deps/axi/src/axi_rw_join.sv
../deps/axi/src/axi_rw_split.sv
../deps/axi/src/axi_serializer.sv
../deps/axi/src/axi_slave_compare.sv
../deps/axi/src/axi_throttle.sv
../deps/axi/src/axi_to_detailed_mem.sv
../deps/axi/src/axi_burst_splitter.sv
../deps/axi/src/axi_cdc.sv
../deps/axi/src/axi_demux.sv
../deps/axi/src/axi_err_slv.sv
../deps/axi/src/axi_dw_converter.sv
../deps/axi/src/axi_from_mem.sv
../deps/axi/src/axi_id_serialize.sv
../deps/axi/src/axi_lfsr.sv
../deps/axi/src/axi_multicut.sv
../deps/axi/src/axi_to_axi_lite.sv
../deps/axi/src/axi_to_mem.sv
../deps/axi/src/axi_zero_mem.sv
../deps/axi/src/axi_interleaved_xbar.sv
../deps/axi/src/axi_iw_converter.sv
../deps/axi/src/axi_lite_xbar.sv
../deps/axi/src/axi_xbar_unmuxed.sv
../deps/axi/src/axi_to_mem_banked.sv
../deps/axi/src/axi_to_mem_interleaved.sv
../deps/axi/src/axi_to_mem_split.sv
../deps/axi/src/axi_xbar.sv
../deps/axi/src/axi_xp.sv
// --- leaf blocks ---
../rtl/blocks/erbium_noc_excl_monitor.sv
../rtl/blocks/erbium_noc_gpv.sv
../rtl/blocks/erbium_noc_pchannel.sv
../rtl/blocks/erbium_noc_qchannel.sv
../rtl/blocks/erbium_noc_reset_sync.sv
// --- top + ni700_ErbiumET integration wrapper ---
../rtl/erbium_noc_top.sv
../rtl/ni700_ErbiumET.sv
