// SPDX-License-Identifier: Apache-2.0
// GENERATED TB harness (see flow/gen_tb.py). Net decls + DUT instance.
// Drive/observe these `tb_<PORT>` nets from the test body.
  logic tb_CPU_CLK;
  logic tb_SYSTEM_CLK;
  logic tb_XSPI_CLK;
  logic tb_PERIPH_CLK;
  logic tb_CPU_RESETn;
  logic tb_SYSTEM_RESETn;
  logic tb_XSPI_RESETn;
  logic tb_PERIPH_RESETn;
  logic [8-1:0] tb_AXI_SLAVE_S_CPU_AWID;
  logic [32-1:0] tb_AXI_SLAVE_S_CPU_AWADDR;
  logic [8-1:0] tb_AXI_SLAVE_S_CPU_AWLEN;
  logic [3-1:0] tb_AXI_SLAVE_S_CPU_AWSIZE;
  logic [2-1:0] tb_AXI_SLAVE_S_CPU_AWBURST;
  logic tb_AXI_SLAVE_S_CPU_AWLOCK;
  logic [4-1:0] tb_AXI_SLAVE_S_CPU_AWCACHE;
  logic [3-1:0] tb_AXI_SLAVE_S_CPU_AWPROT;
  logic [4-1:0] tb_AXI_SLAVE_S_CPU_AWQOS;
  logic tb_AXI_SLAVE_S_CPU_AWVALID;
  logic [512-1:0] tb_AXI_SLAVE_S_CPU_WDATA;
  logic [64-1:0] tb_AXI_SLAVE_S_CPU_WSTRB;
  logic tb_AXI_SLAVE_S_CPU_WLAST;
  logic tb_AXI_SLAVE_S_CPU_WVALID;
  logic tb_AXI_SLAVE_S_CPU_BREADY;
  logic [8-1:0] tb_AXI_SLAVE_S_CPU_ARID;
  logic [32-1:0] tb_AXI_SLAVE_S_CPU_ARADDR;
  logic [8-1:0] tb_AXI_SLAVE_S_CPU_ARLEN;
  logic [3-1:0] tb_AXI_SLAVE_S_CPU_ARSIZE;
  logic [2-1:0] tb_AXI_SLAVE_S_CPU_ARBURST;
  logic tb_AXI_SLAVE_S_CPU_ARLOCK;
  logic [4-1:0] tb_AXI_SLAVE_S_CPU_ARCACHE;
  logic [3-1:0] tb_AXI_SLAVE_S_CPU_ARPROT;
  logic [4-1:0] tb_AXI_SLAVE_S_CPU_ARQOS;
  logic tb_AXI_SLAVE_S_CPU_ARVALID;
  logic tb_AXI_SLAVE_S_CPU_RREADY;
  logic tb_AXI_SLAVE_S_CPU_AWREADY;
  logic tb_AXI_SLAVE_S_CPU_WREADY;
  logic [8-1:0] tb_AXI_SLAVE_S_CPU_BID;
  logic [2-1:0] tb_AXI_SLAVE_S_CPU_BRESP;
  logic tb_AXI_SLAVE_S_CPU_BVALID;
  logic tb_AXI_SLAVE_S_CPU_ARREADY;
  logic [8-1:0] tb_AXI_SLAVE_S_CPU_RID;
  logic [512-1:0] tb_AXI_SLAVE_S_CPU_RDATA;
  logic [2-1:0] tb_AXI_SLAVE_S_CPU_RRESP;
  logic tb_AXI_SLAVE_S_CPU_RLAST;
  logic tb_AXI_SLAVE_S_CPU_RVALID;
  logic tb_AXI_SLAVE_S_XSPI_AWID;
  logic [32-1:0] tb_AXI_SLAVE_S_XSPI_AWADDR;
  logic [8-1:0] tb_AXI_SLAVE_S_XSPI_AWLEN;
  logic [3-1:0] tb_AXI_SLAVE_S_XSPI_AWSIZE;
  logic [2-1:0] tb_AXI_SLAVE_S_XSPI_AWBURST;
  logic tb_AXI_SLAVE_S_XSPI_AWLOCK;
  logic [4-1:0] tb_AXI_SLAVE_S_XSPI_AWCACHE;
  logic [3-1:0] tb_AXI_SLAVE_S_XSPI_AWPROT;
  logic [4-1:0] tb_AXI_SLAVE_S_XSPI_AWQOS;
  logic tb_AXI_SLAVE_S_XSPI_AWVALID;
  logic [64-1:0] tb_AXI_SLAVE_S_XSPI_WDATA;
  logic [8-1:0] tb_AXI_SLAVE_S_XSPI_WSTRB;
  logic tb_AXI_SLAVE_S_XSPI_WLAST;
  logic tb_AXI_SLAVE_S_XSPI_WVALID;
  logic tb_AXI_SLAVE_S_XSPI_BREADY;
  logic tb_AXI_SLAVE_S_XSPI_ARID;
  logic [32-1:0] tb_AXI_SLAVE_S_XSPI_ARADDR;
  logic [8-1:0] tb_AXI_SLAVE_S_XSPI_ARLEN;
  logic [3-1:0] tb_AXI_SLAVE_S_XSPI_ARSIZE;
  logic [2-1:0] tb_AXI_SLAVE_S_XSPI_ARBURST;
  logic tb_AXI_SLAVE_S_XSPI_ARLOCK;
  logic [4-1:0] tb_AXI_SLAVE_S_XSPI_ARCACHE;
  logic [3-1:0] tb_AXI_SLAVE_S_XSPI_ARPROT;
  logic [4-1:0] tb_AXI_SLAVE_S_XSPI_ARQOS;
  logic tb_AXI_SLAVE_S_XSPI_ARVALID;
  logic tb_AXI_SLAVE_S_XSPI_RREADY;
  logic tb_AXI_SLAVE_S_XSPI_AWREADY;
  logic tb_AXI_SLAVE_S_XSPI_WREADY;
  logic tb_AXI_SLAVE_S_XSPI_BID;
  logic [2-1:0] tb_AXI_SLAVE_S_XSPI_BRESP;
  logic tb_AXI_SLAVE_S_XSPI_BVALID;
  logic tb_AXI_SLAVE_S_XSPI_ARREADY;
  logic tb_AXI_SLAVE_S_XSPI_RID;
  logic [64-1:0] tb_AXI_SLAVE_S_XSPI_RDATA;
  logic [2-1:0] tb_AXI_SLAVE_S_XSPI_RRESP;
  logic tb_AXI_SLAVE_S_XSPI_RLAST;
  logic tb_AXI_SLAVE_S_XSPI_RVALID;
  logic [9-1:0] tb_AXI_MASTER_M_MRAM_AWID;
  logic [32-1:0] tb_AXI_MASTER_M_MRAM_AWADDR;
  logic [8-1:0] tb_AXI_MASTER_M_MRAM_AWLEN;
  logic [3-1:0] tb_AXI_MASTER_M_MRAM_AWSIZE;
  logic [2-1:0] tb_AXI_MASTER_M_MRAM_AWBURST;
  logic tb_AXI_MASTER_M_MRAM_AWLOCK;
  logic [4-1:0] tb_AXI_MASTER_M_MRAM_AWCACHE;
  logic [3-1:0] tb_AXI_MASTER_M_MRAM_AWPROT;
  logic [4-1:0] tb_AXI_MASTER_M_MRAM_AWQOS;
  logic tb_AXI_MASTER_M_MRAM_AWVALID;
  logic [512-1:0] tb_AXI_MASTER_M_MRAM_WDATA;
  logic [64-1:0] tb_AXI_MASTER_M_MRAM_WSTRB;
  logic tb_AXI_MASTER_M_MRAM_WLAST;
  logic tb_AXI_MASTER_M_MRAM_WVALID;
  logic tb_AXI_MASTER_M_MRAM_BREADY;
  logic [9-1:0] tb_AXI_MASTER_M_MRAM_ARID;
  logic [32-1:0] tb_AXI_MASTER_M_MRAM_ARADDR;
  logic [8-1:0] tb_AXI_MASTER_M_MRAM_ARLEN;
  logic [3-1:0] tb_AXI_MASTER_M_MRAM_ARSIZE;
  logic [2-1:0] tb_AXI_MASTER_M_MRAM_ARBURST;
  logic tb_AXI_MASTER_M_MRAM_ARLOCK;
  logic [4-1:0] tb_AXI_MASTER_M_MRAM_ARCACHE;
  logic [3-1:0] tb_AXI_MASTER_M_MRAM_ARPROT;
  logic [4-1:0] tb_AXI_MASTER_M_MRAM_ARQOS;
  logic tb_AXI_MASTER_M_MRAM_ARVALID;
  logic tb_AXI_MASTER_M_MRAM_RREADY;
  logic tb_AXI_MASTER_M_MRAM_AWREADY;
  logic tb_AXI_MASTER_M_MRAM_WREADY;
  logic [9-1:0] tb_AXI_MASTER_M_MRAM_BID;
  logic [2-1:0] tb_AXI_MASTER_M_MRAM_BRESP;
  logic tb_AXI_MASTER_M_MRAM_BVALID;
  logic tb_AXI_MASTER_M_MRAM_ARREADY;
  logic [9-1:0] tb_AXI_MASTER_M_MRAM_RID;
  logic [512-1:0] tb_AXI_MASTER_M_MRAM_RDATA;
  logic [2-1:0] tb_AXI_MASTER_M_MRAM_RRESP;
  logic tb_AXI_MASTER_M_MRAM_RLAST;
  logic tb_AXI_MASTER_M_MRAM_RVALID;
  logic [9-1:0] tb_AXI_MASTER_M_CPU_REG_AWID;
  logic [32-1:0] tb_AXI_MASTER_M_CPU_REG_AWADDR;
  logic [8-1:0] tb_AXI_MASTER_M_CPU_REG_AWLEN;
  logic [3-1:0] tb_AXI_MASTER_M_CPU_REG_AWSIZE;
  logic [2-1:0] tb_AXI_MASTER_M_CPU_REG_AWBURST;
  logic tb_AXI_MASTER_M_CPU_REG_AWLOCK;
  logic [4-1:0] tb_AXI_MASTER_M_CPU_REG_AWCACHE;
  logic [3-1:0] tb_AXI_MASTER_M_CPU_REG_AWPROT;
  logic [4-1:0] tb_AXI_MASTER_M_CPU_REG_AWQOS;
  logic tb_AXI_MASTER_M_CPU_REG_AWVALID;
  logic [64-1:0] tb_AXI_MASTER_M_CPU_REG_WDATA;
  logic [8-1:0] tb_AXI_MASTER_M_CPU_REG_WSTRB;
  logic tb_AXI_MASTER_M_CPU_REG_WLAST;
  logic tb_AXI_MASTER_M_CPU_REG_WVALID;
  logic tb_AXI_MASTER_M_CPU_REG_BREADY;
  logic [9-1:0] tb_AXI_MASTER_M_CPU_REG_ARID;
  logic [32-1:0] tb_AXI_MASTER_M_CPU_REG_ARADDR;
  logic [8-1:0] tb_AXI_MASTER_M_CPU_REG_ARLEN;
  logic [3-1:0] tb_AXI_MASTER_M_CPU_REG_ARSIZE;
  logic [2-1:0] tb_AXI_MASTER_M_CPU_REG_ARBURST;
  logic tb_AXI_MASTER_M_CPU_REG_ARLOCK;
  logic [4-1:0] tb_AXI_MASTER_M_CPU_REG_ARCACHE;
  logic [3-1:0] tb_AXI_MASTER_M_CPU_REG_ARPROT;
  logic [4-1:0] tb_AXI_MASTER_M_CPU_REG_ARQOS;
  logic tb_AXI_MASTER_M_CPU_REG_ARVALID;
  logic tb_AXI_MASTER_M_CPU_REG_RREADY;
  logic tb_AXI_MASTER_M_CPU_REG_AWREADY;
  logic tb_AXI_MASTER_M_CPU_REG_WREADY;
  logic [9-1:0] tb_AXI_MASTER_M_CPU_REG_BID;
  logic [2-1:0] tb_AXI_MASTER_M_CPU_REG_BRESP;
  logic tb_AXI_MASTER_M_CPU_REG_BVALID;
  logic tb_AXI_MASTER_M_CPU_REG_ARREADY;
  logic [9-1:0] tb_AXI_MASTER_M_CPU_REG_RID;
  logic [64-1:0] tb_AXI_MASTER_M_CPU_REG_RDATA;
  logic [2-1:0] tb_AXI_MASTER_M_CPU_REG_RRESP;
  logic tb_AXI_MASTER_M_CPU_REG_RLAST;
  logic tb_AXI_MASTER_M_CPU_REG_RVALID;
  logic [9-1:0] tb_AXI_MASTER_M_SYSTEM_REG_AWID;
  logic [32-1:0] tb_AXI_MASTER_M_SYSTEM_REG_AWADDR;
  logic [8-1:0] tb_AXI_MASTER_M_SYSTEM_REG_AWLEN;
  logic [3-1:0] tb_AXI_MASTER_M_SYSTEM_REG_AWSIZE;
  logic [2-1:0] tb_AXI_MASTER_M_SYSTEM_REG_AWBURST;
  logic tb_AXI_MASTER_M_SYSTEM_REG_AWLOCK;
  logic [4-1:0] tb_AXI_MASTER_M_SYSTEM_REG_AWCACHE;
  logic [3-1:0] tb_AXI_MASTER_M_SYSTEM_REG_AWPROT;
  logic [4-1:0] tb_AXI_MASTER_M_SYSTEM_REG_AWQOS;
  logic tb_AXI_MASTER_M_SYSTEM_REG_AWVALID;
  logic [64-1:0] tb_AXI_MASTER_M_SYSTEM_REG_WDATA;
  logic [8-1:0] tb_AXI_MASTER_M_SYSTEM_REG_WSTRB;
  logic tb_AXI_MASTER_M_SYSTEM_REG_WLAST;
  logic tb_AXI_MASTER_M_SYSTEM_REG_WVALID;
  logic tb_AXI_MASTER_M_SYSTEM_REG_BREADY;
  logic [9-1:0] tb_AXI_MASTER_M_SYSTEM_REG_ARID;
  logic [32-1:0] tb_AXI_MASTER_M_SYSTEM_REG_ARADDR;
  logic [8-1:0] tb_AXI_MASTER_M_SYSTEM_REG_ARLEN;
  logic [3-1:0] tb_AXI_MASTER_M_SYSTEM_REG_ARSIZE;
  logic [2-1:0] tb_AXI_MASTER_M_SYSTEM_REG_ARBURST;
  logic tb_AXI_MASTER_M_SYSTEM_REG_ARLOCK;
  logic [4-1:0] tb_AXI_MASTER_M_SYSTEM_REG_ARCACHE;
  logic [3-1:0] tb_AXI_MASTER_M_SYSTEM_REG_ARPROT;
  logic [4-1:0] tb_AXI_MASTER_M_SYSTEM_REG_ARQOS;
  logic tb_AXI_MASTER_M_SYSTEM_REG_ARVALID;
  logic tb_AXI_MASTER_M_SYSTEM_REG_RREADY;
  logic tb_AXI_MASTER_M_SYSTEM_REG_AWREADY;
  logic tb_AXI_MASTER_M_SYSTEM_REG_WREADY;
  logic [9-1:0] tb_AXI_MASTER_M_SYSTEM_REG_BID;
  logic [2-1:0] tb_AXI_MASTER_M_SYSTEM_REG_BRESP;
  logic tb_AXI_MASTER_M_SYSTEM_REG_BVALID;
  logic tb_AXI_MASTER_M_SYSTEM_REG_ARREADY;
  logic [9-1:0] tb_AXI_MASTER_M_SYSTEM_REG_RID;
  logic [64-1:0] tb_AXI_MASTER_M_SYSTEM_REG_RDATA;
  logic [2-1:0] tb_AXI_MASTER_M_SYSTEM_REG_RRESP;
  logic tb_AXI_MASTER_M_SYSTEM_REG_RLAST;
  logic tb_AXI_MASTER_M_SYSTEM_REG_RVALID;
  logic [9-1:0] tb_AXI_MASTER_M_MRAM_REG_AWID;
  logic [32-1:0] tb_AXI_MASTER_M_MRAM_REG_AWADDR;
  logic [8-1:0] tb_AXI_MASTER_M_MRAM_REG_AWLEN;
  logic [3-1:0] tb_AXI_MASTER_M_MRAM_REG_AWSIZE;
  logic [2-1:0] tb_AXI_MASTER_M_MRAM_REG_AWBURST;
  logic tb_AXI_MASTER_M_MRAM_REG_AWLOCK;
  logic [4-1:0] tb_AXI_MASTER_M_MRAM_REG_AWCACHE;
  logic [3-1:0] tb_AXI_MASTER_M_MRAM_REG_AWPROT;
  logic [4-1:0] tb_AXI_MASTER_M_MRAM_REG_AWQOS;
  logic tb_AXI_MASTER_M_MRAM_REG_AWVALID;
  logic [64-1:0] tb_AXI_MASTER_M_MRAM_REG_WDATA;
  logic [8-1:0] tb_AXI_MASTER_M_MRAM_REG_WSTRB;
  logic tb_AXI_MASTER_M_MRAM_REG_WLAST;
  logic tb_AXI_MASTER_M_MRAM_REG_WVALID;
  logic tb_AXI_MASTER_M_MRAM_REG_BREADY;
  logic [9-1:0] tb_AXI_MASTER_M_MRAM_REG_ARID;
  logic [32-1:0] tb_AXI_MASTER_M_MRAM_REG_ARADDR;
  logic [8-1:0] tb_AXI_MASTER_M_MRAM_REG_ARLEN;
  logic [3-1:0] tb_AXI_MASTER_M_MRAM_REG_ARSIZE;
  logic [2-1:0] tb_AXI_MASTER_M_MRAM_REG_ARBURST;
  logic tb_AXI_MASTER_M_MRAM_REG_ARLOCK;
  logic [4-1:0] tb_AXI_MASTER_M_MRAM_REG_ARCACHE;
  logic [3-1:0] tb_AXI_MASTER_M_MRAM_REG_ARPROT;
  logic [4-1:0] tb_AXI_MASTER_M_MRAM_REG_ARQOS;
  logic tb_AXI_MASTER_M_MRAM_REG_ARVALID;
  logic tb_AXI_MASTER_M_MRAM_REG_RREADY;
  logic tb_AXI_MASTER_M_MRAM_REG_AWREADY;
  logic tb_AXI_MASTER_M_MRAM_REG_WREADY;
  logic [9-1:0] tb_AXI_MASTER_M_MRAM_REG_BID;
  logic [2-1:0] tb_AXI_MASTER_M_MRAM_REG_BRESP;
  logic tb_AXI_MASTER_M_MRAM_REG_BVALID;
  logic tb_AXI_MASTER_M_MRAM_REG_ARREADY;
  logic [9-1:0] tb_AXI_MASTER_M_MRAM_REG_RID;
  logic [64-1:0] tb_AXI_MASTER_M_MRAM_REG_RDATA;
  logic [2-1:0] tb_AXI_MASTER_M_MRAM_REG_RRESP;
  logic tb_AXI_MASTER_M_MRAM_REG_RLAST;
  logic tb_AXI_MASTER_M_MRAM_REG_RVALID;
  logic [9-1:0] tb_AXI_MASTER_M_SPI_REG_AWID;
  logic [32-1:0] tb_AXI_MASTER_M_SPI_REG_AWADDR;
  logic [8-1:0] tb_AXI_MASTER_M_SPI_REG_AWLEN;
  logic [3-1:0] tb_AXI_MASTER_M_SPI_REG_AWSIZE;
  logic [2-1:0] tb_AXI_MASTER_M_SPI_REG_AWBURST;
  logic tb_AXI_MASTER_M_SPI_REG_AWLOCK;
  logic [4-1:0] tb_AXI_MASTER_M_SPI_REG_AWCACHE;
  logic [3-1:0] tb_AXI_MASTER_M_SPI_REG_AWPROT;
  logic [4-1:0] tb_AXI_MASTER_M_SPI_REG_AWQOS;
  logic tb_AXI_MASTER_M_SPI_REG_AWVALID;
  logic [64-1:0] tb_AXI_MASTER_M_SPI_REG_WDATA;
  logic [8-1:0] tb_AXI_MASTER_M_SPI_REG_WSTRB;
  logic tb_AXI_MASTER_M_SPI_REG_WLAST;
  logic tb_AXI_MASTER_M_SPI_REG_WVALID;
  logic tb_AXI_MASTER_M_SPI_REG_BREADY;
  logic [9-1:0] tb_AXI_MASTER_M_SPI_REG_ARID;
  logic [32-1:0] tb_AXI_MASTER_M_SPI_REG_ARADDR;
  logic [8-1:0] tb_AXI_MASTER_M_SPI_REG_ARLEN;
  logic [3-1:0] tb_AXI_MASTER_M_SPI_REG_ARSIZE;
  logic [2-1:0] tb_AXI_MASTER_M_SPI_REG_ARBURST;
  logic tb_AXI_MASTER_M_SPI_REG_ARLOCK;
  logic [4-1:0] tb_AXI_MASTER_M_SPI_REG_ARCACHE;
  logic [3-1:0] tb_AXI_MASTER_M_SPI_REG_ARPROT;
  logic [4-1:0] tb_AXI_MASTER_M_SPI_REG_ARQOS;
  logic tb_AXI_MASTER_M_SPI_REG_ARVALID;
  logic tb_AXI_MASTER_M_SPI_REG_RREADY;
  logic tb_AXI_MASTER_M_SPI_REG_AWREADY;
  logic tb_AXI_MASTER_M_SPI_REG_WREADY;
  logic [9-1:0] tb_AXI_MASTER_M_SPI_REG_BID;
  logic [2-1:0] tb_AXI_MASTER_M_SPI_REG_BRESP;
  logic tb_AXI_MASTER_M_SPI_REG_BVALID;
  logic tb_AXI_MASTER_M_SPI_REG_ARREADY;
  logic [9-1:0] tb_AXI_MASTER_M_SPI_REG_RID;
  logic [64-1:0] tb_AXI_MASTER_M_SPI_REG_RDATA;
  logic [2-1:0] tb_AXI_MASTER_M_SPI_REG_RRESP;
  logic tb_AXI_MASTER_M_SPI_REG_RLAST;
  logic tb_AXI_MASTER_M_SPI_REG_RVALID;
  logic [9-1:0] tb_AXI_MASTER_M_UART_REG_AWID;
  logic [32-1:0] tb_AXI_MASTER_M_UART_REG_AWADDR;
  logic [8-1:0] tb_AXI_MASTER_M_UART_REG_AWLEN;
  logic [3-1:0] tb_AXI_MASTER_M_UART_REG_AWSIZE;
  logic [2-1:0] tb_AXI_MASTER_M_UART_REG_AWBURST;
  logic tb_AXI_MASTER_M_UART_REG_AWLOCK;
  logic [4-1:0] tb_AXI_MASTER_M_UART_REG_AWCACHE;
  logic [3-1:0] tb_AXI_MASTER_M_UART_REG_AWPROT;
  logic [4-1:0] tb_AXI_MASTER_M_UART_REG_AWQOS;
  logic tb_AXI_MASTER_M_UART_REG_AWVALID;
  logic [64-1:0] tb_AXI_MASTER_M_UART_REG_WDATA;
  logic [8-1:0] tb_AXI_MASTER_M_UART_REG_WSTRB;
  logic tb_AXI_MASTER_M_UART_REG_WLAST;
  logic tb_AXI_MASTER_M_UART_REG_WVALID;
  logic tb_AXI_MASTER_M_UART_REG_BREADY;
  logic [9-1:0] tb_AXI_MASTER_M_UART_REG_ARID;
  logic [32-1:0] tb_AXI_MASTER_M_UART_REG_ARADDR;
  logic [8-1:0] tb_AXI_MASTER_M_UART_REG_ARLEN;
  logic [3-1:0] tb_AXI_MASTER_M_UART_REG_ARSIZE;
  logic [2-1:0] tb_AXI_MASTER_M_UART_REG_ARBURST;
  logic tb_AXI_MASTER_M_UART_REG_ARLOCK;
  logic [4-1:0] tb_AXI_MASTER_M_UART_REG_ARCACHE;
  logic [3-1:0] tb_AXI_MASTER_M_UART_REG_ARPROT;
  logic [4-1:0] tb_AXI_MASTER_M_UART_REG_ARQOS;
  logic tb_AXI_MASTER_M_UART_REG_ARVALID;
  logic tb_AXI_MASTER_M_UART_REG_RREADY;
  logic tb_AXI_MASTER_M_UART_REG_AWREADY;
  logic tb_AXI_MASTER_M_UART_REG_WREADY;
  logic [9-1:0] tb_AXI_MASTER_M_UART_REG_BID;
  logic [2-1:0] tb_AXI_MASTER_M_UART_REG_BRESP;
  logic tb_AXI_MASTER_M_UART_REG_BVALID;
  logic tb_AXI_MASTER_M_UART_REG_ARREADY;
  logic [9-1:0] tb_AXI_MASTER_M_UART_REG_RID;
  logic [64-1:0] tb_AXI_MASTER_M_UART_REG_RDATA;
  logic [2-1:0] tb_AXI_MASTER_M_UART_REG_RRESP;
  logic tb_AXI_MASTER_M_UART_REG_RLAST;
  logic tb_AXI_MASTER_M_UART_REG_RVALID;
  logic [9-1:0] tb_AXI_MASTER_M_SRAM_AWID;
  logic [32-1:0] tb_AXI_MASTER_M_SRAM_AWADDR;
  logic [8-1:0] tb_AXI_MASTER_M_SRAM_AWLEN;
  logic [3-1:0] tb_AXI_MASTER_M_SRAM_AWSIZE;
  logic [2-1:0] tb_AXI_MASTER_M_SRAM_AWBURST;
  logic tb_AXI_MASTER_M_SRAM_AWLOCK;
  logic [4-1:0] tb_AXI_MASTER_M_SRAM_AWCACHE;
  logic [3-1:0] tb_AXI_MASTER_M_SRAM_AWPROT;
  logic [4-1:0] tb_AXI_MASTER_M_SRAM_AWQOS;
  logic tb_AXI_MASTER_M_SRAM_AWVALID;
  logic [64-1:0] tb_AXI_MASTER_M_SRAM_WDATA;
  logic [8-1:0] tb_AXI_MASTER_M_SRAM_WSTRB;
  logic tb_AXI_MASTER_M_SRAM_WLAST;
  logic tb_AXI_MASTER_M_SRAM_WVALID;
  logic tb_AXI_MASTER_M_SRAM_BREADY;
  logic [9-1:0] tb_AXI_MASTER_M_SRAM_ARID;
  logic [32-1:0] tb_AXI_MASTER_M_SRAM_ARADDR;
  logic [8-1:0] tb_AXI_MASTER_M_SRAM_ARLEN;
  logic [3-1:0] tb_AXI_MASTER_M_SRAM_ARSIZE;
  logic [2-1:0] tb_AXI_MASTER_M_SRAM_ARBURST;
  logic tb_AXI_MASTER_M_SRAM_ARLOCK;
  logic [4-1:0] tb_AXI_MASTER_M_SRAM_ARCACHE;
  logic [3-1:0] tb_AXI_MASTER_M_SRAM_ARPROT;
  logic [4-1:0] tb_AXI_MASTER_M_SRAM_ARQOS;
  logic tb_AXI_MASTER_M_SRAM_ARVALID;
  logic tb_AXI_MASTER_M_SRAM_RREADY;
  logic tb_AXI_MASTER_M_SRAM_AWREADY;
  logic tb_AXI_MASTER_M_SRAM_WREADY;
  logic [9-1:0] tb_AXI_MASTER_M_SRAM_BID;
  logic [2-1:0] tb_AXI_MASTER_M_SRAM_BRESP;
  logic tb_AXI_MASTER_M_SRAM_BVALID;
  logic tb_AXI_MASTER_M_SRAM_ARREADY;
  logic [9-1:0] tb_AXI_MASTER_M_SRAM_RID;
  logic [64-1:0] tb_AXI_MASTER_M_SRAM_RDATA;
  logic [2-1:0] tb_AXI_MASTER_M_SRAM_RRESP;
  logic tb_AXI_MASTER_M_SRAM_RLAST;
  logic tb_AXI_MASTER_M_SRAM_RVALID;
  logic [9-1:0] tb_AXI_MASTER_M_XSPI_AWID;
  logic [32-1:0] tb_AXI_MASTER_M_XSPI_AWADDR;
  logic [8-1:0] tb_AXI_MASTER_M_XSPI_AWLEN;
  logic [3-1:0] tb_AXI_MASTER_M_XSPI_AWSIZE;
  logic [2-1:0] tb_AXI_MASTER_M_XSPI_AWBURST;
  logic tb_AXI_MASTER_M_XSPI_AWLOCK;
  logic [4-1:0] tb_AXI_MASTER_M_XSPI_AWCACHE;
  logic [3-1:0] tb_AXI_MASTER_M_XSPI_AWPROT;
  logic [4-1:0] tb_AXI_MASTER_M_XSPI_AWQOS;
  logic tb_AXI_MASTER_M_XSPI_AWVALID;
  logic [64-1:0] tb_AXI_MASTER_M_XSPI_WDATA;
  logic [8-1:0] tb_AXI_MASTER_M_XSPI_WSTRB;
  logic tb_AXI_MASTER_M_XSPI_WLAST;
  logic tb_AXI_MASTER_M_XSPI_WVALID;
  logic tb_AXI_MASTER_M_XSPI_BREADY;
  logic [9-1:0] tb_AXI_MASTER_M_XSPI_ARID;
  logic [32-1:0] tb_AXI_MASTER_M_XSPI_ARADDR;
  logic [8-1:0] tb_AXI_MASTER_M_XSPI_ARLEN;
  logic [3-1:0] tb_AXI_MASTER_M_XSPI_ARSIZE;
  logic [2-1:0] tb_AXI_MASTER_M_XSPI_ARBURST;
  logic tb_AXI_MASTER_M_XSPI_ARLOCK;
  logic [4-1:0] tb_AXI_MASTER_M_XSPI_ARCACHE;
  logic [3-1:0] tb_AXI_MASTER_M_XSPI_ARPROT;
  logic [4-1:0] tb_AXI_MASTER_M_XSPI_ARQOS;
  logic tb_AXI_MASTER_M_XSPI_ARVALID;
  logic tb_AXI_MASTER_M_XSPI_RREADY;
  logic tb_AXI_MASTER_M_XSPI_AWREADY;
  logic tb_AXI_MASTER_M_XSPI_WREADY;
  logic [9-1:0] tb_AXI_MASTER_M_XSPI_BID;
  logic [2-1:0] tb_AXI_MASTER_M_XSPI_BRESP;
  logic tb_AXI_MASTER_M_XSPI_BVALID;
  logic tb_AXI_MASTER_M_XSPI_ARREADY;
  logic [9-1:0] tb_AXI_MASTER_M_XSPI_RID;
  logic [64-1:0] tb_AXI_MASTER_M_XSPI_RDATA;
  logic [2-1:0] tb_AXI_MASTER_M_XSPI_RRESP;
  logic tb_AXI_MASTER_M_XSPI_RLAST;
  logic tb_AXI_MASTER_M_XSPI_RVALID;
  logic [31:0] tb_APB_MASTER_M_I2C_REG_PADDR;
  logic [2:0] tb_APB_MASTER_M_I2C_REG_PPROT;
  logic tb_APB_MASTER_M_I2C_REG_PSEL;
  logic tb_APB_MASTER_M_I2C_REG_PENABLE;
  logic tb_APB_MASTER_M_I2C_REG_PWRITE;
  logic [31:0] tb_APB_MASTER_M_I2C_REG_PWDATA;
  logic [3:0] tb_APB_MASTER_M_I2C_REG_PSTRB;
  logic tb_APB_MASTER_M_I2C_REG_PREADY;
  logic [31:0] tb_APB_MASTER_M_I2C_REG_PRDATA;
  logic tb_APB_MASTER_M_I2C_REG_PSLVERR;
  logic tb_CPU_QACTIVE;
  logic tb_CPU_QREQn;
  logic tb_CPU_QACCEPTn;
  logic tb_CPU_QDENY;
  logic tb_CPU_SPIDEN;
  logic tb_CPU_NIDEN;
  logic tb_CPU_DBGEN;
  logic tb_CPU_SPNIDEN;
  logic tb_CPU_PMUSNAPSHOTREQ;
  logic tb_CPU_PMUSNAPSHOTACK;
  logic tb_CPU_nPMUINTERRUPT;
  logic tb_DFTCPUDISABLE;
  logic tb_SYSTEM_QACTIVE;
  logic tb_SYSTEM_QREQn;
  logic tb_SYSTEM_QACCEPTn;
  logic tb_SYSTEM_QDENY;
  logic tb_SYSTEM_SPIDEN;
  logic tb_SYSTEM_NIDEN;
  logic tb_SYSTEM_DBGEN;
  logic tb_SYSTEM_SPNIDEN;
  logic tb_SYSTEM_PMUSNAPSHOTREQ;
  logic tb_SYSTEM_PMUSNAPSHOTACK;
  logic tb_SYSTEM_nPMUINTERRUPT;
  logic tb_DFTSYSTEMDISABLE;
  logic tb_XSPI_QACTIVE;
  logic tb_XSPI_QREQn;
  logic tb_XSPI_QACCEPTn;
  logic tb_XSPI_QDENY;
  logic tb_XSPI_SPIDEN;
  logic tb_XSPI_NIDEN;
  logic tb_XSPI_DBGEN;
  logic tb_XSPI_SPNIDEN;
  logic tb_XSPI_PMUSNAPSHOTREQ;
  logic tb_XSPI_PMUSNAPSHOTACK;
  logic tb_XSPI_nPMUINTERRUPT;
  logic tb_DFTXSPIDISABLE;
  logic tb_PERIPH_QACTIVE;
  logic tb_PERIPH_QREQn;
  logic tb_PERIPH_QACCEPTn;
  logic tb_PERIPH_QDENY;
  logic tb_PERIPH_SPIDEN;
  logic tb_PERIPH_NIDEN;
  logic tb_PERIPH_DBGEN;
  logic tb_PERIPH_SPNIDEN;
  logic tb_PERIPH_PMUSNAPSHOTREQ;
  logic tb_PERIPH_PMUSNAPSHOTACK;
  logic tb_PERIPH_nPMUINTERRUPT;
  logic tb_DFTPERIPHDISABLE;
  logic tb_PD_0_PACTIVE;
  logic tb_PD_0_PREQ;
  logic [3:0] tb_PD_0_PSTATE;
  logic tb_PD_0_PACCEPT;
  logic tb_PD_0_PDENY;
  logic tb_PD_0_INTERRUPT;
  logic tb_PD_0_NS_INTERRUPT;
  logic tb_AXI_SLAVE_S_CPU_AWAKEUP;
  logic tb_AXI_SLAVE_S_XSPI_AWAKEUP;
  logic tb_AXI_MASTER_M_MRAM_AWAKEUP;
  logic tb_AXI_MASTER_M_CPU_REG_AWAKEUP;
  logic tb_AXI_MASTER_M_SYSTEM_REG_AWAKEUP;
  logic tb_AXI_MASTER_M_MRAM_REG_AWAKEUP;
  logic tb_AXI_MASTER_M_SPI_REG_AWAKEUP;
  logic tb_AXI_MASTER_M_UART_REG_AWAKEUP;
  logic tb_AXI_MASTER_M_SRAM_AWAKEUP;
  logic tb_AXI_MASTER_M_XSPI_AWAKEUP;
  logic [31:0] tb_ECOREVNUM;
  logic tb_S_CPU_CONFIG_ACCESS;
  logic tb_S_XSPI_CONFIG_ACCESS;
  logic tb_DFTCGEN;
  logic tb_DFTRSTDISABLE;

  erbium_noc_top i_dut (
    .CPU_CLK(tb_CPU_CLK),
    .SYSTEM_CLK(tb_SYSTEM_CLK),
    .XSPI_CLK(tb_XSPI_CLK),
    .PERIPH_CLK(tb_PERIPH_CLK),
    .CPU_RESETn(tb_CPU_RESETn),
    .SYSTEM_RESETn(tb_SYSTEM_RESETn),
    .XSPI_RESETn(tb_XSPI_RESETn),
    .PERIPH_RESETn(tb_PERIPH_RESETn),
    .AXI_SLAVE_S_CPU_AWID(tb_AXI_SLAVE_S_CPU_AWID),
    .AXI_SLAVE_S_CPU_AWADDR(tb_AXI_SLAVE_S_CPU_AWADDR),
    .AXI_SLAVE_S_CPU_AWLEN(tb_AXI_SLAVE_S_CPU_AWLEN),
    .AXI_SLAVE_S_CPU_AWSIZE(tb_AXI_SLAVE_S_CPU_AWSIZE),
    .AXI_SLAVE_S_CPU_AWBURST(tb_AXI_SLAVE_S_CPU_AWBURST),
    .AXI_SLAVE_S_CPU_AWLOCK(tb_AXI_SLAVE_S_CPU_AWLOCK),
    .AXI_SLAVE_S_CPU_AWCACHE(tb_AXI_SLAVE_S_CPU_AWCACHE),
    .AXI_SLAVE_S_CPU_AWPROT(tb_AXI_SLAVE_S_CPU_AWPROT),
    .AXI_SLAVE_S_CPU_AWQOS(tb_AXI_SLAVE_S_CPU_AWQOS),
    .AXI_SLAVE_S_CPU_AWVALID(tb_AXI_SLAVE_S_CPU_AWVALID),
    .AXI_SLAVE_S_CPU_WDATA(tb_AXI_SLAVE_S_CPU_WDATA),
    .AXI_SLAVE_S_CPU_WSTRB(tb_AXI_SLAVE_S_CPU_WSTRB),
    .AXI_SLAVE_S_CPU_WLAST(tb_AXI_SLAVE_S_CPU_WLAST),
    .AXI_SLAVE_S_CPU_WVALID(tb_AXI_SLAVE_S_CPU_WVALID),
    .AXI_SLAVE_S_CPU_BREADY(tb_AXI_SLAVE_S_CPU_BREADY),
    .AXI_SLAVE_S_CPU_ARID(tb_AXI_SLAVE_S_CPU_ARID),
    .AXI_SLAVE_S_CPU_ARADDR(tb_AXI_SLAVE_S_CPU_ARADDR),
    .AXI_SLAVE_S_CPU_ARLEN(tb_AXI_SLAVE_S_CPU_ARLEN),
    .AXI_SLAVE_S_CPU_ARSIZE(tb_AXI_SLAVE_S_CPU_ARSIZE),
    .AXI_SLAVE_S_CPU_ARBURST(tb_AXI_SLAVE_S_CPU_ARBURST),
    .AXI_SLAVE_S_CPU_ARLOCK(tb_AXI_SLAVE_S_CPU_ARLOCK),
    .AXI_SLAVE_S_CPU_ARCACHE(tb_AXI_SLAVE_S_CPU_ARCACHE),
    .AXI_SLAVE_S_CPU_ARPROT(tb_AXI_SLAVE_S_CPU_ARPROT),
    .AXI_SLAVE_S_CPU_ARQOS(tb_AXI_SLAVE_S_CPU_ARQOS),
    .AXI_SLAVE_S_CPU_ARVALID(tb_AXI_SLAVE_S_CPU_ARVALID),
    .AXI_SLAVE_S_CPU_RREADY(tb_AXI_SLAVE_S_CPU_RREADY),
    .AXI_SLAVE_S_CPU_AWREADY(tb_AXI_SLAVE_S_CPU_AWREADY),
    .AXI_SLAVE_S_CPU_WREADY(tb_AXI_SLAVE_S_CPU_WREADY),
    .AXI_SLAVE_S_CPU_BID(tb_AXI_SLAVE_S_CPU_BID),
    .AXI_SLAVE_S_CPU_BRESP(tb_AXI_SLAVE_S_CPU_BRESP),
    .AXI_SLAVE_S_CPU_BVALID(tb_AXI_SLAVE_S_CPU_BVALID),
    .AXI_SLAVE_S_CPU_ARREADY(tb_AXI_SLAVE_S_CPU_ARREADY),
    .AXI_SLAVE_S_CPU_RID(tb_AXI_SLAVE_S_CPU_RID),
    .AXI_SLAVE_S_CPU_RDATA(tb_AXI_SLAVE_S_CPU_RDATA),
    .AXI_SLAVE_S_CPU_RRESP(tb_AXI_SLAVE_S_CPU_RRESP),
    .AXI_SLAVE_S_CPU_RLAST(tb_AXI_SLAVE_S_CPU_RLAST),
    .AXI_SLAVE_S_CPU_RVALID(tb_AXI_SLAVE_S_CPU_RVALID),
    .AXI_SLAVE_S_XSPI_AWID(tb_AXI_SLAVE_S_XSPI_AWID),
    .AXI_SLAVE_S_XSPI_AWADDR(tb_AXI_SLAVE_S_XSPI_AWADDR),
    .AXI_SLAVE_S_XSPI_AWLEN(tb_AXI_SLAVE_S_XSPI_AWLEN),
    .AXI_SLAVE_S_XSPI_AWSIZE(tb_AXI_SLAVE_S_XSPI_AWSIZE),
    .AXI_SLAVE_S_XSPI_AWBURST(tb_AXI_SLAVE_S_XSPI_AWBURST),
    .AXI_SLAVE_S_XSPI_AWLOCK(tb_AXI_SLAVE_S_XSPI_AWLOCK),
    .AXI_SLAVE_S_XSPI_AWCACHE(tb_AXI_SLAVE_S_XSPI_AWCACHE),
    .AXI_SLAVE_S_XSPI_AWPROT(tb_AXI_SLAVE_S_XSPI_AWPROT),
    .AXI_SLAVE_S_XSPI_AWQOS(tb_AXI_SLAVE_S_XSPI_AWQOS),
    .AXI_SLAVE_S_XSPI_AWVALID(tb_AXI_SLAVE_S_XSPI_AWVALID),
    .AXI_SLAVE_S_XSPI_WDATA(tb_AXI_SLAVE_S_XSPI_WDATA),
    .AXI_SLAVE_S_XSPI_WSTRB(tb_AXI_SLAVE_S_XSPI_WSTRB),
    .AXI_SLAVE_S_XSPI_WLAST(tb_AXI_SLAVE_S_XSPI_WLAST),
    .AXI_SLAVE_S_XSPI_WVALID(tb_AXI_SLAVE_S_XSPI_WVALID),
    .AXI_SLAVE_S_XSPI_BREADY(tb_AXI_SLAVE_S_XSPI_BREADY),
    .AXI_SLAVE_S_XSPI_ARID(tb_AXI_SLAVE_S_XSPI_ARID),
    .AXI_SLAVE_S_XSPI_ARADDR(tb_AXI_SLAVE_S_XSPI_ARADDR),
    .AXI_SLAVE_S_XSPI_ARLEN(tb_AXI_SLAVE_S_XSPI_ARLEN),
    .AXI_SLAVE_S_XSPI_ARSIZE(tb_AXI_SLAVE_S_XSPI_ARSIZE),
    .AXI_SLAVE_S_XSPI_ARBURST(tb_AXI_SLAVE_S_XSPI_ARBURST),
    .AXI_SLAVE_S_XSPI_ARLOCK(tb_AXI_SLAVE_S_XSPI_ARLOCK),
    .AXI_SLAVE_S_XSPI_ARCACHE(tb_AXI_SLAVE_S_XSPI_ARCACHE),
    .AXI_SLAVE_S_XSPI_ARPROT(tb_AXI_SLAVE_S_XSPI_ARPROT),
    .AXI_SLAVE_S_XSPI_ARQOS(tb_AXI_SLAVE_S_XSPI_ARQOS),
    .AXI_SLAVE_S_XSPI_ARVALID(tb_AXI_SLAVE_S_XSPI_ARVALID),
    .AXI_SLAVE_S_XSPI_RREADY(tb_AXI_SLAVE_S_XSPI_RREADY),
    .AXI_SLAVE_S_XSPI_AWREADY(tb_AXI_SLAVE_S_XSPI_AWREADY),
    .AXI_SLAVE_S_XSPI_WREADY(tb_AXI_SLAVE_S_XSPI_WREADY),
    .AXI_SLAVE_S_XSPI_BID(tb_AXI_SLAVE_S_XSPI_BID),
    .AXI_SLAVE_S_XSPI_BRESP(tb_AXI_SLAVE_S_XSPI_BRESP),
    .AXI_SLAVE_S_XSPI_BVALID(tb_AXI_SLAVE_S_XSPI_BVALID),
    .AXI_SLAVE_S_XSPI_ARREADY(tb_AXI_SLAVE_S_XSPI_ARREADY),
    .AXI_SLAVE_S_XSPI_RID(tb_AXI_SLAVE_S_XSPI_RID),
    .AXI_SLAVE_S_XSPI_RDATA(tb_AXI_SLAVE_S_XSPI_RDATA),
    .AXI_SLAVE_S_XSPI_RRESP(tb_AXI_SLAVE_S_XSPI_RRESP),
    .AXI_SLAVE_S_XSPI_RLAST(tb_AXI_SLAVE_S_XSPI_RLAST),
    .AXI_SLAVE_S_XSPI_RVALID(tb_AXI_SLAVE_S_XSPI_RVALID),
    .AXI_MASTER_M_MRAM_AWID(tb_AXI_MASTER_M_MRAM_AWID),
    .AXI_MASTER_M_MRAM_AWADDR(tb_AXI_MASTER_M_MRAM_AWADDR),
    .AXI_MASTER_M_MRAM_AWLEN(tb_AXI_MASTER_M_MRAM_AWLEN),
    .AXI_MASTER_M_MRAM_AWSIZE(tb_AXI_MASTER_M_MRAM_AWSIZE),
    .AXI_MASTER_M_MRAM_AWBURST(tb_AXI_MASTER_M_MRAM_AWBURST),
    .AXI_MASTER_M_MRAM_AWLOCK(tb_AXI_MASTER_M_MRAM_AWLOCK),
    .AXI_MASTER_M_MRAM_AWCACHE(tb_AXI_MASTER_M_MRAM_AWCACHE),
    .AXI_MASTER_M_MRAM_AWPROT(tb_AXI_MASTER_M_MRAM_AWPROT),
    .AXI_MASTER_M_MRAM_AWQOS(tb_AXI_MASTER_M_MRAM_AWQOS),
    .AXI_MASTER_M_MRAM_AWVALID(tb_AXI_MASTER_M_MRAM_AWVALID),
    .AXI_MASTER_M_MRAM_WDATA(tb_AXI_MASTER_M_MRAM_WDATA),
    .AXI_MASTER_M_MRAM_WSTRB(tb_AXI_MASTER_M_MRAM_WSTRB),
    .AXI_MASTER_M_MRAM_WLAST(tb_AXI_MASTER_M_MRAM_WLAST),
    .AXI_MASTER_M_MRAM_WVALID(tb_AXI_MASTER_M_MRAM_WVALID),
    .AXI_MASTER_M_MRAM_BREADY(tb_AXI_MASTER_M_MRAM_BREADY),
    .AXI_MASTER_M_MRAM_ARID(tb_AXI_MASTER_M_MRAM_ARID),
    .AXI_MASTER_M_MRAM_ARADDR(tb_AXI_MASTER_M_MRAM_ARADDR),
    .AXI_MASTER_M_MRAM_ARLEN(tb_AXI_MASTER_M_MRAM_ARLEN),
    .AXI_MASTER_M_MRAM_ARSIZE(tb_AXI_MASTER_M_MRAM_ARSIZE),
    .AXI_MASTER_M_MRAM_ARBURST(tb_AXI_MASTER_M_MRAM_ARBURST),
    .AXI_MASTER_M_MRAM_ARLOCK(tb_AXI_MASTER_M_MRAM_ARLOCK),
    .AXI_MASTER_M_MRAM_ARCACHE(tb_AXI_MASTER_M_MRAM_ARCACHE),
    .AXI_MASTER_M_MRAM_ARPROT(tb_AXI_MASTER_M_MRAM_ARPROT),
    .AXI_MASTER_M_MRAM_ARQOS(tb_AXI_MASTER_M_MRAM_ARQOS),
    .AXI_MASTER_M_MRAM_ARVALID(tb_AXI_MASTER_M_MRAM_ARVALID),
    .AXI_MASTER_M_MRAM_RREADY(tb_AXI_MASTER_M_MRAM_RREADY),
    .AXI_MASTER_M_MRAM_AWREADY(tb_AXI_MASTER_M_MRAM_AWREADY),
    .AXI_MASTER_M_MRAM_WREADY(tb_AXI_MASTER_M_MRAM_WREADY),
    .AXI_MASTER_M_MRAM_BID(tb_AXI_MASTER_M_MRAM_BID),
    .AXI_MASTER_M_MRAM_BRESP(tb_AXI_MASTER_M_MRAM_BRESP),
    .AXI_MASTER_M_MRAM_BVALID(tb_AXI_MASTER_M_MRAM_BVALID),
    .AXI_MASTER_M_MRAM_ARREADY(tb_AXI_MASTER_M_MRAM_ARREADY),
    .AXI_MASTER_M_MRAM_RID(tb_AXI_MASTER_M_MRAM_RID),
    .AXI_MASTER_M_MRAM_RDATA(tb_AXI_MASTER_M_MRAM_RDATA),
    .AXI_MASTER_M_MRAM_RRESP(tb_AXI_MASTER_M_MRAM_RRESP),
    .AXI_MASTER_M_MRAM_RLAST(tb_AXI_MASTER_M_MRAM_RLAST),
    .AXI_MASTER_M_MRAM_RVALID(tb_AXI_MASTER_M_MRAM_RVALID),
    .AXI_MASTER_M_CPU_REG_AWID(tb_AXI_MASTER_M_CPU_REG_AWID),
    .AXI_MASTER_M_CPU_REG_AWADDR(tb_AXI_MASTER_M_CPU_REG_AWADDR),
    .AXI_MASTER_M_CPU_REG_AWLEN(tb_AXI_MASTER_M_CPU_REG_AWLEN),
    .AXI_MASTER_M_CPU_REG_AWSIZE(tb_AXI_MASTER_M_CPU_REG_AWSIZE),
    .AXI_MASTER_M_CPU_REG_AWBURST(tb_AXI_MASTER_M_CPU_REG_AWBURST),
    .AXI_MASTER_M_CPU_REG_AWLOCK(tb_AXI_MASTER_M_CPU_REG_AWLOCK),
    .AXI_MASTER_M_CPU_REG_AWCACHE(tb_AXI_MASTER_M_CPU_REG_AWCACHE),
    .AXI_MASTER_M_CPU_REG_AWPROT(tb_AXI_MASTER_M_CPU_REG_AWPROT),
    .AXI_MASTER_M_CPU_REG_AWQOS(tb_AXI_MASTER_M_CPU_REG_AWQOS),
    .AXI_MASTER_M_CPU_REG_AWVALID(tb_AXI_MASTER_M_CPU_REG_AWVALID),
    .AXI_MASTER_M_CPU_REG_WDATA(tb_AXI_MASTER_M_CPU_REG_WDATA),
    .AXI_MASTER_M_CPU_REG_WSTRB(tb_AXI_MASTER_M_CPU_REG_WSTRB),
    .AXI_MASTER_M_CPU_REG_WLAST(tb_AXI_MASTER_M_CPU_REG_WLAST),
    .AXI_MASTER_M_CPU_REG_WVALID(tb_AXI_MASTER_M_CPU_REG_WVALID),
    .AXI_MASTER_M_CPU_REG_BREADY(tb_AXI_MASTER_M_CPU_REG_BREADY),
    .AXI_MASTER_M_CPU_REG_ARID(tb_AXI_MASTER_M_CPU_REG_ARID),
    .AXI_MASTER_M_CPU_REG_ARADDR(tb_AXI_MASTER_M_CPU_REG_ARADDR),
    .AXI_MASTER_M_CPU_REG_ARLEN(tb_AXI_MASTER_M_CPU_REG_ARLEN),
    .AXI_MASTER_M_CPU_REG_ARSIZE(tb_AXI_MASTER_M_CPU_REG_ARSIZE),
    .AXI_MASTER_M_CPU_REG_ARBURST(tb_AXI_MASTER_M_CPU_REG_ARBURST),
    .AXI_MASTER_M_CPU_REG_ARLOCK(tb_AXI_MASTER_M_CPU_REG_ARLOCK),
    .AXI_MASTER_M_CPU_REG_ARCACHE(tb_AXI_MASTER_M_CPU_REG_ARCACHE),
    .AXI_MASTER_M_CPU_REG_ARPROT(tb_AXI_MASTER_M_CPU_REG_ARPROT),
    .AXI_MASTER_M_CPU_REG_ARQOS(tb_AXI_MASTER_M_CPU_REG_ARQOS),
    .AXI_MASTER_M_CPU_REG_ARVALID(tb_AXI_MASTER_M_CPU_REG_ARVALID),
    .AXI_MASTER_M_CPU_REG_RREADY(tb_AXI_MASTER_M_CPU_REG_RREADY),
    .AXI_MASTER_M_CPU_REG_AWREADY(tb_AXI_MASTER_M_CPU_REG_AWREADY),
    .AXI_MASTER_M_CPU_REG_WREADY(tb_AXI_MASTER_M_CPU_REG_WREADY),
    .AXI_MASTER_M_CPU_REG_BID(tb_AXI_MASTER_M_CPU_REG_BID),
    .AXI_MASTER_M_CPU_REG_BRESP(tb_AXI_MASTER_M_CPU_REG_BRESP),
    .AXI_MASTER_M_CPU_REG_BVALID(tb_AXI_MASTER_M_CPU_REG_BVALID),
    .AXI_MASTER_M_CPU_REG_ARREADY(tb_AXI_MASTER_M_CPU_REG_ARREADY),
    .AXI_MASTER_M_CPU_REG_RID(tb_AXI_MASTER_M_CPU_REG_RID),
    .AXI_MASTER_M_CPU_REG_RDATA(tb_AXI_MASTER_M_CPU_REG_RDATA),
    .AXI_MASTER_M_CPU_REG_RRESP(tb_AXI_MASTER_M_CPU_REG_RRESP),
    .AXI_MASTER_M_CPU_REG_RLAST(tb_AXI_MASTER_M_CPU_REG_RLAST),
    .AXI_MASTER_M_CPU_REG_RVALID(tb_AXI_MASTER_M_CPU_REG_RVALID),
    .AXI_MASTER_M_SYSTEM_REG_AWID(tb_AXI_MASTER_M_SYSTEM_REG_AWID),
    .AXI_MASTER_M_SYSTEM_REG_AWADDR(tb_AXI_MASTER_M_SYSTEM_REG_AWADDR),
    .AXI_MASTER_M_SYSTEM_REG_AWLEN(tb_AXI_MASTER_M_SYSTEM_REG_AWLEN),
    .AXI_MASTER_M_SYSTEM_REG_AWSIZE(tb_AXI_MASTER_M_SYSTEM_REG_AWSIZE),
    .AXI_MASTER_M_SYSTEM_REG_AWBURST(tb_AXI_MASTER_M_SYSTEM_REG_AWBURST),
    .AXI_MASTER_M_SYSTEM_REG_AWLOCK(tb_AXI_MASTER_M_SYSTEM_REG_AWLOCK),
    .AXI_MASTER_M_SYSTEM_REG_AWCACHE(tb_AXI_MASTER_M_SYSTEM_REG_AWCACHE),
    .AXI_MASTER_M_SYSTEM_REG_AWPROT(tb_AXI_MASTER_M_SYSTEM_REG_AWPROT),
    .AXI_MASTER_M_SYSTEM_REG_AWQOS(tb_AXI_MASTER_M_SYSTEM_REG_AWQOS),
    .AXI_MASTER_M_SYSTEM_REG_AWVALID(tb_AXI_MASTER_M_SYSTEM_REG_AWVALID),
    .AXI_MASTER_M_SYSTEM_REG_WDATA(tb_AXI_MASTER_M_SYSTEM_REG_WDATA),
    .AXI_MASTER_M_SYSTEM_REG_WSTRB(tb_AXI_MASTER_M_SYSTEM_REG_WSTRB),
    .AXI_MASTER_M_SYSTEM_REG_WLAST(tb_AXI_MASTER_M_SYSTEM_REG_WLAST),
    .AXI_MASTER_M_SYSTEM_REG_WVALID(tb_AXI_MASTER_M_SYSTEM_REG_WVALID),
    .AXI_MASTER_M_SYSTEM_REG_BREADY(tb_AXI_MASTER_M_SYSTEM_REG_BREADY),
    .AXI_MASTER_M_SYSTEM_REG_ARID(tb_AXI_MASTER_M_SYSTEM_REG_ARID),
    .AXI_MASTER_M_SYSTEM_REG_ARADDR(tb_AXI_MASTER_M_SYSTEM_REG_ARADDR),
    .AXI_MASTER_M_SYSTEM_REG_ARLEN(tb_AXI_MASTER_M_SYSTEM_REG_ARLEN),
    .AXI_MASTER_M_SYSTEM_REG_ARSIZE(tb_AXI_MASTER_M_SYSTEM_REG_ARSIZE),
    .AXI_MASTER_M_SYSTEM_REG_ARBURST(tb_AXI_MASTER_M_SYSTEM_REG_ARBURST),
    .AXI_MASTER_M_SYSTEM_REG_ARLOCK(tb_AXI_MASTER_M_SYSTEM_REG_ARLOCK),
    .AXI_MASTER_M_SYSTEM_REG_ARCACHE(tb_AXI_MASTER_M_SYSTEM_REG_ARCACHE),
    .AXI_MASTER_M_SYSTEM_REG_ARPROT(tb_AXI_MASTER_M_SYSTEM_REG_ARPROT),
    .AXI_MASTER_M_SYSTEM_REG_ARQOS(tb_AXI_MASTER_M_SYSTEM_REG_ARQOS),
    .AXI_MASTER_M_SYSTEM_REG_ARVALID(tb_AXI_MASTER_M_SYSTEM_REG_ARVALID),
    .AXI_MASTER_M_SYSTEM_REG_RREADY(tb_AXI_MASTER_M_SYSTEM_REG_RREADY),
    .AXI_MASTER_M_SYSTEM_REG_AWREADY(tb_AXI_MASTER_M_SYSTEM_REG_AWREADY),
    .AXI_MASTER_M_SYSTEM_REG_WREADY(tb_AXI_MASTER_M_SYSTEM_REG_WREADY),
    .AXI_MASTER_M_SYSTEM_REG_BID(tb_AXI_MASTER_M_SYSTEM_REG_BID),
    .AXI_MASTER_M_SYSTEM_REG_BRESP(tb_AXI_MASTER_M_SYSTEM_REG_BRESP),
    .AXI_MASTER_M_SYSTEM_REG_BVALID(tb_AXI_MASTER_M_SYSTEM_REG_BVALID),
    .AXI_MASTER_M_SYSTEM_REG_ARREADY(tb_AXI_MASTER_M_SYSTEM_REG_ARREADY),
    .AXI_MASTER_M_SYSTEM_REG_RID(tb_AXI_MASTER_M_SYSTEM_REG_RID),
    .AXI_MASTER_M_SYSTEM_REG_RDATA(tb_AXI_MASTER_M_SYSTEM_REG_RDATA),
    .AXI_MASTER_M_SYSTEM_REG_RRESP(tb_AXI_MASTER_M_SYSTEM_REG_RRESP),
    .AXI_MASTER_M_SYSTEM_REG_RLAST(tb_AXI_MASTER_M_SYSTEM_REG_RLAST),
    .AXI_MASTER_M_SYSTEM_REG_RVALID(tb_AXI_MASTER_M_SYSTEM_REG_RVALID),
    .AXI_MASTER_M_MRAM_REG_AWID(tb_AXI_MASTER_M_MRAM_REG_AWID),
    .AXI_MASTER_M_MRAM_REG_AWADDR(tb_AXI_MASTER_M_MRAM_REG_AWADDR),
    .AXI_MASTER_M_MRAM_REG_AWLEN(tb_AXI_MASTER_M_MRAM_REG_AWLEN),
    .AXI_MASTER_M_MRAM_REG_AWSIZE(tb_AXI_MASTER_M_MRAM_REG_AWSIZE),
    .AXI_MASTER_M_MRAM_REG_AWBURST(tb_AXI_MASTER_M_MRAM_REG_AWBURST),
    .AXI_MASTER_M_MRAM_REG_AWLOCK(tb_AXI_MASTER_M_MRAM_REG_AWLOCK),
    .AXI_MASTER_M_MRAM_REG_AWCACHE(tb_AXI_MASTER_M_MRAM_REG_AWCACHE),
    .AXI_MASTER_M_MRAM_REG_AWPROT(tb_AXI_MASTER_M_MRAM_REG_AWPROT),
    .AXI_MASTER_M_MRAM_REG_AWQOS(tb_AXI_MASTER_M_MRAM_REG_AWQOS),
    .AXI_MASTER_M_MRAM_REG_AWVALID(tb_AXI_MASTER_M_MRAM_REG_AWVALID),
    .AXI_MASTER_M_MRAM_REG_WDATA(tb_AXI_MASTER_M_MRAM_REG_WDATA),
    .AXI_MASTER_M_MRAM_REG_WSTRB(tb_AXI_MASTER_M_MRAM_REG_WSTRB),
    .AXI_MASTER_M_MRAM_REG_WLAST(tb_AXI_MASTER_M_MRAM_REG_WLAST),
    .AXI_MASTER_M_MRAM_REG_WVALID(tb_AXI_MASTER_M_MRAM_REG_WVALID),
    .AXI_MASTER_M_MRAM_REG_BREADY(tb_AXI_MASTER_M_MRAM_REG_BREADY),
    .AXI_MASTER_M_MRAM_REG_ARID(tb_AXI_MASTER_M_MRAM_REG_ARID),
    .AXI_MASTER_M_MRAM_REG_ARADDR(tb_AXI_MASTER_M_MRAM_REG_ARADDR),
    .AXI_MASTER_M_MRAM_REG_ARLEN(tb_AXI_MASTER_M_MRAM_REG_ARLEN),
    .AXI_MASTER_M_MRAM_REG_ARSIZE(tb_AXI_MASTER_M_MRAM_REG_ARSIZE),
    .AXI_MASTER_M_MRAM_REG_ARBURST(tb_AXI_MASTER_M_MRAM_REG_ARBURST),
    .AXI_MASTER_M_MRAM_REG_ARLOCK(tb_AXI_MASTER_M_MRAM_REG_ARLOCK),
    .AXI_MASTER_M_MRAM_REG_ARCACHE(tb_AXI_MASTER_M_MRAM_REG_ARCACHE),
    .AXI_MASTER_M_MRAM_REG_ARPROT(tb_AXI_MASTER_M_MRAM_REG_ARPROT),
    .AXI_MASTER_M_MRAM_REG_ARQOS(tb_AXI_MASTER_M_MRAM_REG_ARQOS),
    .AXI_MASTER_M_MRAM_REG_ARVALID(tb_AXI_MASTER_M_MRAM_REG_ARVALID),
    .AXI_MASTER_M_MRAM_REG_RREADY(tb_AXI_MASTER_M_MRAM_REG_RREADY),
    .AXI_MASTER_M_MRAM_REG_AWREADY(tb_AXI_MASTER_M_MRAM_REG_AWREADY),
    .AXI_MASTER_M_MRAM_REG_WREADY(tb_AXI_MASTER_M_MRAM_REG_WREADY),
    .AXI_MASTER_M_MRAM_REG_BID(tb_AXI_MASTER_M_MRAM_REG_BID),
    .AXI_MASTER_M_MRAM_REG_BRESP(tb_AXI_MASTER_M_MRAM_REG_BRESP),
    .AXI_MASTER_M_MRAM_REG_BVALID(tb_AXI_MASTER_M_MRAM_REG_BVALID),
    .AXI_MASTER_M_MRAM_REG_ARREADY(tb_AXI_MASTER_M_MRAM_REG_ARREADY),
    .AXI_MASTER_M_MRAM_REG_RID(tb_AXI_MASTER_M_MRAM_REG_RID),
    .AXI_MASTER_M_MRAM_REG_RDATA(tb_AXI_MASTER_M_MRAM_REG_RDATA),
    .AXI_MASTER_M_MRAM_REG_RRESP(tb_AXI_MASTER_M_MRAM_REG_RRESP),
    .AXI_MASTER_M_MRAM_REG_RLAST(tb_AXI_MASTER_M_MRAM_REG_RLAST),
    .AXI_MASTER_M_MRAM_REG_RVALID(tb_AXI_MASTER_M_MRAM_REG_RVALID),
    .AXI_MASTER_M_SPI_REG_AWID(tb_AXI_MASTER_M_SPI_REG_AWID),
    .AXI_MASTER_M_SPI_REG_AWADDR(tb_AXI_MASTER_M_SPI_REG_AWADDR),
    .AXI_MASTER_M_SPI_REG_AWLEN(tb_AXI_MASTER_M_SPI_REG_AWLEN),
    .AXI_MASTER_M_SPI_REG_AWSIZE(tb_AXI_MASTER_M_SPI_REG_AWSIZE),
    .AXI_MASTER_M_SPI_REG_AWBURST(tb_AXI_MASTER_M_SPI_REG_AWBURST),
    .AXI_MASTER_M_SPI_REG_AWLOCK(tb_AXI_MASTER_M_SPI_REG_AWLOCK),
    .AXI_MASTER_M_SPI_REG_AWCACHE(tb_AXI_MASTER_M_SPI_REG_AWCACHE),
    .AXI_MASTER_M_SPI_REG_AWPROT(tb_AXI_MASTER_M_SPI_REG_AWPROT),
    .AXI_MASTER_M_SPI_REG_AWQOS(tb_AXI_MASTER_M_SPI_REG_AWQOS),
    .AXI_MASTER_M_SPI_REG_AWVALID(tb_AXI_MASTER_M_SPI_REG_AWVALID),
    .AXI_MASTER_M_SPI_REG_WDATA(tb_AXI_MASTER_M_SPI_REG_WDATA),
    .AXI_MASTER_M_SPI_REG_WSTRB(tb_AXI_MASTER_M_SPI_REG_WSTRB),
    .AXI_MASTER_M_SPI_REG_WLAST(tb_AXI_MASTER_M_SPI_REG_WLAST),
    .AXI_MASTER_M_SPI_REG_WVALID(tb_AXI_MASTER_M_SPI_REG_WVALID),
    .AXI_MASTER_M_SPI_REG_BREADY(tb_AXI_MASTER_M_SPI_REG_BREADY),
    .AXI_MASTER_M_SPI_REG_ARID(tb_AXI_MASTER_M_SPI_REG_ARID),
    .AXI_MASTER_M_SPI_REG_ARADDR(tb_AXI_MASTER_M_SPI_REG_ARADDR),
    .AXI_MASTER_M_SPI_REG_ARLEN(tb_AXI_MASTER_M_SPI_REG_ARLEN),
    .AXI_MASTER_M_SPI_REG_ARSIZE(tb_AXI_MASTER_M_SPI_REG_ARSIZE),
    .AXI_MASTER_M_SPI_REG_ARBURST(tb_AXI_MASTER_M_SPI_REG_ARBURST),
    .AXI_MASTER_M_SPI_REG_ARLOCK(tb_AXI_MASTER_M_SPI_REG_ARLOCK),
    .AXI_MASTER_M_SPI_REG_ARCACHE(tb_AXI_MASTER_M_SPI_REG_ARCACHE),
    .AXI_MASTER_M_SPI_REG_ARPROT(tb_AXI_MASTER_M_SPI_REG_ARPROT),
    .AXI_MASTER_M_SPI_REG_ARQOS(tb_AXI_MASTER_M_SPI_REG_ARQOS),
    .AXI_MASTER_M_SPI_REG_ARVALID(tb_AXI_MASTER_M_SPI_REG_ARVALID),
    .AXI_MASTER_M_SPI_REG_RREADY(tb_AXI_MASTER_M_SPI_REG_RREADY),
    .AXI_MASTER_M_SPI_REG_AWREADY(tb_AXI_MASTER_M_SPI_REG_AWREADY),
    .AXI_MASTER_M_SPI_REG_WREADY(tb_AXI_MASTER_M_SPI_REG_WREADY),
    .AXI_MASTER_M_SPI_REG_BID(tb_AXI_MASTER_M_SPI_REG_BID),
    .AXI_MASTER_M_SPI_REG_BRESP(tb_AXI_MASTER_M_SPI_REG_BRESP),
    .AXI_MASTER_M_SPI_REG_BVALID(tb_AXI_MASTER_M_SPI_REG_BVALID),
    .AXI_MASTER_M_SPI_REG_ARREADY(tb_AXI_MASTER_M_SPI_REG_ARREADY),
    .AXI_MASTER_M_SPI_REG_RID(tb_AXI_MASTER_M_SPI_REG_RID),
    .AXI_MASTER_M_SPI_REG_RDATA(tb_AXI_MASTER_M_SPI_REG_RDATA),
    .AXI_MASTER_M_SPI_REG_RRESP(tb_AXI_MASTER_M_SPI_REG_RRESP),
    .AXI_MASTER_M_SPI_REG_RLAST(tb_AXI_MASTER_M_SPI_REG_RLAST),
    .AXI_MASTER_M_SPI_REG_RVALID(tb_AXI_MASTER_M_SPI_REG_RVALID),
    .AXI_MASTER_M_UART_REG_AWID(tb_AXI_MASTER_M_UART_REG_AWID),
    .AXI_MASTER_M_UART_REG_AWADDR(tb_AXI_MASTER_M_UART_REG_AWADDR),
    .AXI_MASTER_M_UART_REG_AWLEN(tb_AXI_MASTER_M_UART_REG_AWLEN),
    .AXI_MASTER_M_UART_REG_AWSIZE(tb_AXI_MASTER_M_UART_REG_AWSIZE),
    .AXI_MASTER_M_UART_REG_AWBURST(tb_AXI_MASTER_M_UART_REG_AWBURST),
    .AXI_MASTER_M_UART_REG_AWLOCK(tb_AXI_MASTER_M_UART_REG_AWLOCK),
    .AXI_MASTER_M_UART_REG_AWCACHE(tb_AXI_MASTER_M_UART_REG_AWCACHE),
    .AXI_MASTER_M_UART_REG_AWPROT(tb_AXI_MASTER_M_UART_REG_AWPROT),
    .AXI_MASTER_M_UART_REG_AWQOS(tb_AXI_MASTER_M_UART_REG_AWQOS),
    .AXI_MASTER_M_UART_REG_AWVALID(tb_AXI_MASTER_M_UART_REG_AWVALID),
    .AXI_MASTER_M_UART_REG_WDATA(tb_AXI_MASTER_M_UART_REG_WDATA),
    .AXI_MASTER_M_UART_REG_WSTRB(tb_AXI_MASTER_M_UART_REG_WSTRB),
    .AXI_MASTER_M_UART_REG_WLAST(tb_AXI_MASTER_M_UART_REG_WLAST),
    .AXI_MASTER_M_UART_REG_WVALID(tb_AXI_MASTER_M_UART_REG_WVALID),
    .AXI_MASTER_M_UART_REG_BREADY(tb_AXI_MASTER_M_UART_REG_BREADY),
    .AXI_MASTER_M_UART_REG_ARID(tb_AXI_MASTER_M_UART_REG_ARID),
    .AXI_MASTER_M_UART_REG_ARADDR(tb_AXI_MASTER_M_UART_REG_ARADDR),
    .AXI_MASTER_M_UART_REG_ARLEN(tb_AXI_MASTER_M_UART_REG_ARLEN),
    .AXI_MASTER_M_UART_REG_ARSIZE(tb_AXI_MASTER_M_UART_REG_ARSIZE),
    .AXI_MASTER_M_UART_REG_ARBURST(tb_AXI_MASTER_M_UART_REG_ARBURST),
    .AXI_MASTER_M_UART_REG_ARLOCK(tb_AXI_MASTER_M_UART_REG_ARLOCK),
    .AXI_MASTER_M_UART_REG_ARCACHE(tb_AXI_MASTER_M_UART_REG_ARCACHE),
    .AXI_MASTER_M_UART_REG_ARPROT(tb_AXI_MASTER_M_UART_REG_ARPROT),
    .AXI_MASTER_M_UART_REG_ARQOS(tb_AXI_MASTER_M_UART_REG_ARQOS),
    .AXI_MASTER_M_UART_REG_ARVALID(tb_AXI_MASTER_M_UART_REG_ARVALID),
    .AXI_MASTER_M_UART_REG_RREADY(tb_AXI_MASTER_M_UART_REG_RREADY),
    .AXI_MASTER_M_UART_REG_AWREADY(tb_AXI_MASTER_M_UART_REG_AWREADY),
    .AXI_MASTER_M_UART_REG_WREADY(tb_AXI_MASTER_M_UART_REG_WREADY),
    .AXI_MASTER_M_UART_REG_BID(tb_AXI_MASTER_M_UART_REG_BID),
    .AXI_MASTER_M_UART_REG_BRESP(tb_AXI_MASTER_M_UART_REG_BRESP),
    .AXI_MASTER_M_UART_REG_BVALID(tb_AXI_MASTER_M_UART_REG_BVALID),
    .AXI_MASTER_M_UART_REG_ARREADY(tb_AXI_MASTER_M_UART_REG_ARREADY),
    .AXI_MASTER_M_UART_REG_RID(tb_AXI_MASTER_M_UART_REG_RID),
    .AXI_MASTER_M_UART_REG_RDATA(tb_AXI_MASTER_M_UART_REG_RDATA),
    .AXI_MASTER_M_UART_REG_RRESP(tb_AXI_MASTER_M_UART_REG_RRESP),
    .AXI_MASTER_M_UART_REG_RLAST(tb_AXI_MASTER_M_UART_REG_RLAST),
    .AXI_MASTER_M_UART_REG_RVALID(tb_AXI_MASTER_M_UART_REG_RVALID),
    .AXI_MASTER_M_SRAM_AWID(tb_AXI_MASTER_M_SRAM_AWID),
    .AXI_MASTER_M_SRAM_AWADDR(tb_AXI_MASTER_M_SRAM_AWADDR),
    .AXI_MASTER_M_SRAM_AWLEN(tb_AXI_MASTER_M_SRAM_AWLEN),
    .AXI_MASTER_M_SRAM_AWSIZE(tb_AXI_MASTER_M_SRAM_AWSIZE),
    .AXI_MASTER_M_SRAM_AWBURST(tb_AXI_MASTER_M_SRAM_AWBURST),
    .AXI_MASTER_M_SRAM_AWLOCK(tb_AXI_MASTER_M_SRAM_AWLOCK),
    .AXI_MASTER_M_SRAM_AWCACHE(tb_AXI_MASTER_M_SRAM_AWCACHE),
    .AXI_MASTER_M_SRAM_AWPROT(tb_AXI_MASTER_M_SRAM_AWPROT),
    .AXI_MASTER_M_SRAM_AWQOS(tb_AXI_MASTER_M_SRAM_AWQOS),
    .AXI_MASTER_M_SRAM_AWVALID(tb_AXI_MASTER_M_SRAM_AWVALID),
    .AXI_MASTER_M_SRAM_WDATA(tb_AXI_MASTER_M_SRAM_WDATA),
    .AXI_MASTER_M_SRAM_WSTRB(tb_AXI_MASTER_M_SRAM_WSTRB),
    .AXI_MASTER_M_SRAM_WLAST(tb_AXI_MASTER_M_SRAM_WLAST),
    .AXI_MASTER_M_SRAM_WVALID(tb_AXI_MASTER_M_SRAM_WVALID),
    .AXI_MASTER_M_SRAM_BREADY(tb_AXI_MASTER_M_SRAM_BREADY),
    .AXI_MASTER_M_SRAM_ARID(tb_AXI_MASTER_M_SRAM_ARID),
    .AXI_MASTER_M_SRAM_ARADDR(tb_AXI_MASTER_M_SRAM_ARADDR),
    .AXI_MASTER_M_SRAM_ARLEN(tb_AXI_MASTER_M_SRAM_ARLEN),
    .AXI_MASTER_M_SRAM_ARSIZE(tb_AXI_MASTER_M_SRAM_ARSIZE),
    .AXI_MASTER_M_SRAM_ARBURST(tb_AXI_MASTER_M_SRAM_ARBURST),
    .AXI_MASTER_M_SRAM_ARLOCK(tb_AXI_MASTER_M_SRAM_ARLOCK),
    .AXI_MASTER_M_SRAM_ARCACHE(tb_AXI_MASTER_M_SRAM_ARCACHE),
    .AXI_MASTER_M_SRAM_ARPROT(tb_AXI_MASTER_M_SRAM_ARPROT),
    .AXI_MASTER_M_SRAM_ARQOS(tb_AXI_MASTER_M_SRAM_ARQOS),
    .AXI_MASTER_M_SRAM_ARVALID(tb_AXI_MASTER_M_SRAM_ARVALID),
    .AXI_MASTER_M_SRAM_RREADY(tb_AXI_MASTER_M_SRAM_RREADY),
    .AXI_MASTER_M_SRAM_AWREADY(tb_AXI_MASTER_M_SRAM_AWREADY),
    .AXI_MASTER_M_SRAM_WREADY(tb_AXI_MASTER_M_SRAM_WREADY),
    .AXI_MASTER_M_SRAM_BID(tb_AXI_MASTER_M_SRAM_BID),
    .AXI_MASTER_M_SRAM_BRESP(tb_AXI_MASTER_M_SRAM_BRESP),
    .AXI_MASTER_M_SRAM_BVALID(tb_AXI_MASTER_M_SRAM_BVALID),
    .AXI_MASTER_M_SRAM_ARREADY(tb_AXI_MASTER_M_SRAM_ARREADY),
    .AXI_MASTER_M_SRAM_RID(tb_AXI_MASTER_M_SRAM_RID),
    .AXI_MASTER_M_SRAM_RDATA(tb_AXI_MASTER_M_SRAM_RDATA),
    .AXI_MASTER_M_SRAM_RRESP(tb_AXI_MASTER_M_SRAM_RRESP),
    .AXI_MASTER_M_SRAM_RLAST(tb_AXI_MASTER_M_SRAM_RLAST),
    .AXI_MASTER_M_SRAM_RVALID(tb_AXI_MASTER_M_SRAM_RVALID),
    .AXI_MASTER_M_XSPI_AWID(tb_AXI_MASTER_M_XSPI_AWID),
    .AXI_MASTER_M_XSPI_AWADDR(tb_AXI_MASTER_M_XSPI_AWADDR),
    .AXI_MASTER_M_XSPI_AWLEN(tb_AXI_MASTER_M_XSPI_AWLEN),
    .AXI_MASTER_M_XSPI_AWSIZE(tb_AXI_MASTER_M_XSPI_AWSIZE),
    .AXI_MASTER_M_XSPI_AWBURST(tb_AXI_MASTER_M_XSPI_AWBURST),
    .AXI_MASTER_M_XSPI_AWLOCK(tb_AXI_MASTER_M_XSPI_AWLOCK),
    .AXI_MASTER_M_XSPI_AWCACHE(tb_AXI_MASTER_M_XSPI_AWCACHE),
    .AXI_MASTER_M_XSPI_AWPROT(tb_AXI_MASTER_M_XSPI_AWPROT),
    .AXI_MASTER_M_XSPI_AWQOS(tb_AXI_MASTER_M_XSPI_AWQOS),
    .AXI_MASTER_M_XSPI_AWVALID(tb_AXI_MASTER_M_XSPI_AWVALID),
    .AXI_MASTER_M_XSPI_WDATA(tb_AXI_MASTER_M_XSPI_WDATA),
    .AXI_MASTER_M_XSPI_WSTRB(tb_AXI_MASTER_M_XSPI_WSTRB),
    .AXI_MASTER_M_XSPI_WLAST(tb_AXI_MASTER_M_XSPI_WLAST),
    .AXI_MASTER_M_XSPI_WVALID(tb_AXI_MASTER_M_XSPI_WVALID),
    .AXI_MASTER_M_XSPI_BREADY(tb_AXI_MASTER_M_XSPI_BREADY),
    .AXI_MASTER_M_XSPI_ARID(tb_AXI_MASTER_M_XSPI_ARID),
    .AXI_MASTER_M_XSPI_ARADDR(tb_AXI_MASTER_M_XSPI_ARADDR),
    .AXI_MASTER_M_XSPI_ARLEN(tb_AXI_MASTER_M_XSPI_ARLEN),
    .AXI_MASTER_M_XSPI_ARSIZE(tb_AXI_MASTER_M_XSPI_ARSIZE),
    .AXI_MASTER_M_XSPI_ARBURST(tb_AXI_MASTER_M_XSPI_ARBURST),
    .AXI_MASTER_M_XSPI_ARLOCK(tb_AXI_MASTER_M_XSPI_ARLOCK),
    .AXI_MASTER_M_XSPI_ARCACHE(tb_AXI_MASTER_M_XSPI_ARCACHE),
    .AXI_MASTER_M_XSPI_ARPROT(tb_AXI_MASTER_M_XSPI_ARPROT),
    .AXI_MASTER_M_XSPI_ARQOS(tb_AXI_MASTER_M_XSPI_ARQOS),
    .AXI_MASTER_M_XSPI_ARVALID(tb_AXI_MASTER_M_XSPI_ARVALID),
    .AXI_MASTER_M_XSPI_RREADY(tb_AXI_MASTER_M_XSPI_RREADY),
    .AXI_MASTER_M_XSPI_AWREADY(tb_AXI_MASTER_M_XSPI_AWREADY),
    .AXI_MASTER_M_XSPI_WREADY(tb_AXI_MASTER_M_XSPI_WREADY),
    .AXI_MASTER_M_XSPI_BID(tb_AXI_MASTER_M_XSPI_BID),
    .AXI_MASTER_M_XSPI_BRESP(tb_AXI_MASTER_M_XSPI_BRESP),
    .AXI_MASTER_M_XSPI_BVALID(tb_AXI_MASTER_M_XSPI_BVALID),
    .AXI_MASTER_M_XSPI_ARREADY(tb_AXI_MASTER_M_XSPI_ARREADY),
    .AXI_MASTER_M_XSPI_RID(tb_AXI_MASTER_M_XSPI_RID),
    .AXI_MASTER_M_XSPI_RDATA(tb_AXI_MASTER_M_XSPI_RDATA),
    .AXI_MASTER_M_XSPI_RRESP(tb_AXI_MASTER_M_XSPI_RRESP),
    .AXI_MASTER_M_XSPI_RLAST(tb_AXI_MASTER_M_XSPI_RLAST),
    .AXI_MASTER_M_XSPI_RVALID(tb_AXI_MASTER_M_XSPI_RVALID),
    .APB_MASTER_M_I2C_REG_PADDR(tb_APB_MASTER_M_I2C_REG_PADDR),
    .APB_MASTER_M_I2C_REG_PPROT(tb_APB_MASTER_M_I2C_REG_PPROT),
    .APB_MASTER_M_I2C_REG_PSEL(tb_APB_MASTER_M_I2C_REG_PSEL),
    .APB_MASTER_M_I2C_REG_PENABLE(tb_APB_MASTER_M_I2C_REG_PENABLE),
    .APB_MASTER_M_I2C_REG_PWRITE(tb_APB_MASTER_M_I2C_REG_PWRITE),
    .APB_MASTER_M_I2C_REG_PWDATA(tb_APB_MASTER_M_I2C_REG_PWDATA),
    .APB_MASTER_M_I2C_REG_PSTRB(tb_APB_MASTER_M_I2C_REG_PSTRB),
    .APB_MASTER_M_I2C_REG_PREADY(tb_APB_MASTER_M_I2C_REG_PREADY),
    .APB_MASTER_M_I2C_REG_PRDATA(tb_APB_MASTER_M_I2C_REG_PRDATA),
    .APB_MASTER_M_I2C_REG_PSLVERR(tb_APB_MASTER_M_I2C_REG_PSLVERR),
    .CPU_QACTIVE(tb_CPU_QACTIVE),
    .CPU_QREQn(tb_CPU_QREQn),
    .CPU_QACCEPTn(tb_CPU_QACCEPTn),
    .CPU_QDENY(tb_CPU_QDENY),
    .CPU_SPIDEN(tb_CPU_SPIDEN),
    .CPU_NIDEN(tb_CPU_NIDEN),
    .CPU_DBGEN(tb_CPU_DBGEN),
    .CPU_SPNIDEN(tb_CPU_SPNIDEN),
    .CPU_PMUSNAPSHOTREQ(tb_CPU_PMUSNAPSHOTREQ),
    .CPU_PMUSNAPSHOTACK(tb_CPU_PMUSNAPSHOTACK),
    .CPU_nPMUINTERRUPT(tb_CPU_nPMUINTERRUPT),
    .DFTCPUDISABLE(tb_DFTCPUDISABLE),
    .SYSTEM_QACTIVE(tb_SYSTEM_QACTIVE),
    .SYSTEM_QREQn(tb_SYSTEM_QREQn),
    .SYSTEM_QACCEPTn(tb_SYSTEM_QACCEPTn),
    .SYSTEM_QDENY(tb_SYSTEM_QDENY),
    .SYSTEM_SPIDEN(tb_SYSTEM_SPIDEN),
    .SYSTEM_NIDEN(tb_SYSTEM_NIDEN),
    .SYSTEM_DBGEN(tb_SYSTEM_DBGEN),
    .SYSTEM_SPNIDEN(tb_SYSTEM_SPNIDEN),
    .SYSTEM_PMUSNAPSHOTREQ(tb_SYSTEM_PMUSNAPSHOTREQ),
    .SYSTEM_PMUSNAPSHOTACK(tb_SYSTEM_PMUSNAPSHOTACK),
    .SYSTEM_nPMUINTERRUPT(tb_SYSTEM_nPMUINTERRUPT),
    .DFTSYSTEMDISABLE(tb_DFTSYSTEMDISABLE),
    .XSPI_QACTIVE(tb_XSPI_QACTIVE),
    .XSPI_QREQn(tb_XSPI_QREQn),
    .XSPI_QACCEPTn(tb_XSPI_QACCEPTn),
    .XSPI_QDENY(tb_XSPI_QDENY),
    .XSPI_SPIDEN(tb_XSPI_SPIDEN),
    .XSPI_NIDEN(tb_XSPI_NIDEN),
    .XSPI_DBGEN(tb_XSPI_DBGEN),
    .XSPI_SPNIDEN(tb_XSPI_SPNIDEN),
    .XSPI_PMUSNAPSHOTREQ(tb_XSPI_PMUSNAPSHOTREQ),
    .XSPI_PMUSNAPSHOTACK(tb_XSPI_PMUSNAPSHOTACK),
    .XSPI_nPMUINTERRUPT(tb_XSPI_nPMUINTERRUPT),
    .DFTXSPIDISABLE(tb_DFTXSPIDISABLE),
    .PERIPH_QACTIVE(tb_PERIPH_QACTIVE),
    .PERIPH_QREQn(tb_PERIPH_QREQn),
    .PERIPH_QACCEPTn(tb_PERIPH_QACCEPTn),
    .PERIPH_QDENY(tb_PERIPH_QDENY),
    .PERIPH_SPIDEN(tb_PERIPH_SPIDEN),
    .PERIPH_NIDEN(tb_PERIPH_NIDEN),
    .PERIPH_DBGEN(tb_PERIPH_DBGEN),
    .PERIPH_SPNIDEN(tb_PERIPH_SPNIDEN),
    .PERIPH_PMUSNAPSHOTREQ(tb_PERIPH_PMUSNAPSHOTREQ),
    .PERIPH_PMUSNAPSHOTACK(tb_PERIPH_PMUSNAPSHOTACK),
    .PERIPH_nPMUINTERRUPT(tb_PERIPH_nPMUINTERRUPT),
    .DFTPERIPHDISABLE(tb_DFTPERIPHDISABLE),
    .PD_0_PACTIVE(tb_PD_0_PACTIVE),
    .PD_0_PREQ(tb_PD_0_PREQ),
    .PD_0_PSTATE(tb_PD_0_PSTATE),
    .PD_0_PACCEPT(tb_PD_0_PACCEPT),
    .PD_0_PDENY(tb_PD_0_PDENY),
    .PD_0_INTERRUPT(tb_PD_0_INTERRUPT),
    .PD_0_NS_INTERRUPT(tb_PD_0_NS_INTERRUPT),
    .AXI_SLAVE_S_CPU_AWAKEUP(tb_AXI_SLAVE_S_CPU_AWAKEUP),
    .AXI_SLAVE_S_XSPI_AWAKEUP(tb_AXI_SLAVE_S_XSPI_AWAKEUP),
    .AXI_MASTER_M_MRAM_AWAKEUP(tb_AXI_MASTER_M_MRAM_AWAKEUP),
    .AXI_MASTER_M_CPU_REG_AWAKEUP(tb_AXI_MASTER_M_CPU_REG_AWAKEUP),
    .AXI_MASTER_M_SYSTEM_REG_AWAKEUP(tb_AXI_MASTER_M_SYSTEM_REG_AWAKEUP),
    .AXI_MASTER_M_MRAM_REG_AWAKEUP(tb_AXI_MASTER_M_MRAM_REG_AWAKEUP),
    .AXI_MASTER_M_SPI_REG_AWAKEUP(tb_AXI_MASTER_M_SPI_REG_AWAKEUP),
    .AXI_MASTER_M_UART_REG_AWAKEUP(tb_AXI_MASTER_M_UART_REG_AWAKEUP),
    .AXI_MASTER_M_SRAM_AWAKEUP(tb_AXI_MASTER_M_SRAM_AWAKEUP),
    .AXI_MASTER_M_XSPI_AWAKEUP(tb_AXI_MASTER_M_XSPI_AWAKEUP),
    .ECOREVNUM(tb_ECOREVNUM),
    .S_CPU_CONFIG_ACCESS(tb_S_CPU_CONFIG_ACCESS),
    .S_XSPI_CONFIG_ACCESS(tb_S_XSPI_CONFIG_ACCESS),
    .DFTCGEN(tb_DFTCGEN),
    .DFTRSTDISABLE(tb_DFTRSTDISABLE)
  );
