//
// Generated by Bluespec Compiler, version 2025.07-40-g5dccc4ba (build 5dccc4ba)
//
//
// Ports:
// Name                         I/O  size props
// RDY_id0_smgf_id_clear          O     1 const
// RDY_id0_sdevid0_clear          O     1 const
// id0_value                      O    64 const
// RDY_id0_value                  O     1 const
// RDY_id1_sdev_type_clear        O     1 const
// RDY_id1_sdevid1_clear          O     1 const
// id1_value                      O    64 const
// RDY_id1_value                  O     1 const
// cfg_sBurstLength__read         O     2 reg
// RDY_cfg_sBurstLength__read     O     1 const
// RDY_cfg_sBurstLength_clear     O     1 const
// cfg_sHybridBurstEnable__read   O     1 reg
// RDY_cfg_sHybridBurstEnable__read  O     1 const
// RDY_cfg_sHybridBurstEnable_clear  O     1 const
// cfg_sFixedLatency__read        O     1 reg
// RDY_cfg_sFixedLatency__read    O     1 const
// RDY_cfg_sFixedLatency_clear    O     1 const
// cfg_sInitialLatency__read      O     4 reg
// RDY_cfg_sInitialLatency__read  O     1 const
// RDY_cfg_sInitialLatency_clear  O     1 const
// RDY_cfg_sReserved_clear        O     1 const
// cfg_sDriveStrength__read       O     3 reg
// RDY_cfg_sDriveStrength__read   O     1 const
// RDY_cfg_sDriveStrength_clear   O     1 const
// cfg_sDeepPowerDown__read       O     1 reg
// RDY_cfg_sDeepPowerDown__read   O     1 const
// RDY_cfg_sDeepPowerDown_clear   O     1 const
// cfg_sBurstEnable__read         O     1 reg
// RDY_cfg_sBurstEnable__read     O     1 const
// RDY_cfg_sBurstEnable_clear     O     1 const
// cfg_sUltraDeepPowerDown__read  O     1 reg
// RDY_cfg_sUltraDeepPowerDown__read  O     1 const
// RDY_cfg_sUltraDeepPowerDown_clear  O     1 const
// cfg_value                      O    64
// RDY_cfg_value                  O     1 const
// RDY_xspi_status_swip__write    O     1 const
// RDY_xspi_status_swip_clear     O     1 const
// xspi_status_value              O    64 const
// RDY_xspi_status_value          O     1 const
// xspi_control_suse_xspi_clk__read  O     1 reg
// RDY_xspi_control_suse_xspi_clk__read  O     1 const
// RDY_xspi_control_suse_xspi_clk_clear  O     1 const
// xspi_control_sinterrupt_enable__read  O     1 reg
// RDY_xspi_control_sinterrupt_enable__read  O     1 const
// RDY_xspi_control_sinterrupt_enable_clear  O     1 const
// xspi_control_value             O    64
// RDY_xspi_control_value         O     1 const
// RDY_xspi_rates_scmd_rate__write  O     1 const
// xspi_rates_scmd_rate__read     O     8 reg
// RDY_xspi_rates_scmd_rate__read  O     1 const
// RDY_xspi_rates_scmd_rate_clear  O     1 const
// RDY_xspi_rates_saddr_rate__write  O     1 const
// xspi_rates_saddr_rate__read    O     8 reg
// RDY_xspi_rates_saddr_rate__read  O     1 const
// RDY_xspi_rates_saddr_rate_clear  O     1 const
// RDY_xspi_rates_sdata_rate__write  O     1 const
// xspi_rates_sdata_rate__read    O     8 reg
// RDY_xspi_rates_sdata_rate__read  O     1 const
// RDY_xspi_rates_sdata_rate_clear  O     1 const
// xspi_rates_value               O    64
// RDY_xspi_rates_value           O     1 const
// RDY_interrupt_status_saxi_resp__write  O     1 const
// interrupt_status_saxi_resp__read  O     2 reg
// RDY_interrupt_status_saxi_resp__read  O     1 const
// RDY_interrupt_status_saxi_resp_clear  O     1 const
// RDY_interrupt_status_sread_underflow__write  O     1 const
// interrupt_status_sread_underflow__read  O     1 reg
// RDY_interrupt_status_sread_underflow__read  O     1 const
// RDY_interrupt_status_sread_underflow_clear  O     1 const
// RDY_interrupt_status_swrite_overflow__write  O     1 const
// interrupt_status_swrite_overflow__read  O     1 reg
// RDY_interrupt_status_swrite_overflow__read  O     1 const
// RDY_interrupt_status_swrite_overflow_clear  O     1 const
// interrupt_status_value         O    64
// RDY_interrupt_status_value     O     1 const
// RDY_write                      O     1 const
// read                           O    64
// RDY_read                       O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// xspi_status_swip__write_data   I     1
// xspi_rates_scmd_rate__write_data  I     8
// xspi_rates_saddr_rate__write_data  I     8
// xspi_rates_sdata_rate__write_data  I     8
// interrupt_status_saxi_resp__write_data  I     2
// interrupt_status_sread_underflow__write_data  I     1
// interrupt_status_swrite_overflow__write_data  I     1
// write_address                  I     6
// write_data                     I    64
// write_wstrb                    I     8
// read_address                   I     6
// EN_id0_smgf_id_clear           I     1
// EN_id0_sdevid0_clear           I     1
// EN_id1_sdev_type_clear         I     1
// EN_id1_sdevid1_clear           I     1
// EN_cfg_sBurstLength_clear      I     1
// EN_cfg_sHybridBurstEnable_clear  I     1
// EN_cfg_sFixedLatency_clear     I     1
// EN_cfg_sInitialLatency_clear   I     1
// EN_cfg_sReserved_clear         I     1
// EN_cfg_sDriveStrength_clear    I     1
// EN_cfg_sDeepPowerDown_clear    I     1
// EN_cfg_sBurstEnable_clear      I     1
// EN_cfg_sUltraDeepPowerDown_clear  I     1
// EN_xspi_status_swip__write     I     1
// EN_xspi_status_swip_clear      I     1
// EN_xspi_control_suse_xspi_clk_clear  I     1
// EN_xspi_control_sinterrupt_enable_clear  I     1
// EN_xspi_rates_scmd_rate__write  I     1
// EN_xspi_rates_scmd_rate_clear  I     1
// EN_xspi_rates_saddr_rate__write  I     1
// EN_xspi_rates_saddr_rate_clear  I     1
// EN_xspi_rates_sdata_rate__write  I     1
// EN_xspi_rates_sdata_rate_clear  I     1
// EN_interrupt_status_saxi_resp__write  I     1
// EN_interrupt_status_saxi_resp_clear  I     1
// EN_interrupt_status_sread_underflow__write  I     1
// EN_interrupt_status_sread_underflow_clear  I     1
// EN_interrupt_status_swrite_overflow__write  I     1
// EN_interrupt_status_swrite_overflow_clear  I     1
// EN_write                       I     1
// EN_read                        I     1
//
// Combinational paths from inputs to outputs:
//   read_address -> read
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkConfigCSR_SCCR_Reg(CLK,
			    RST_N,

			    EN_id0_smgf_id_clear,
			    RDY_id0_smgf_id_clear,

			    EN_id0_sdevid0_clear,
			    RDY_id0_sdevid0_clear,

			    id0_value,
			    RDY_id0_value,

			    EN_id1_sdev_type_clear,
			    RDY_id1_sdev_type_clear,

			    EN_id1_sdevid1_clear,
			    RDY_id1_sdevid1_clear,

			    id1_value,
			    RDY_id1_value,

			    cfg_sBurstLength__read,
			    RDY_cfg_sBurstLength__read,

			    EN_cfg_sBurstLength_clear,
			    RDY_cfg_sBurstLength_clear,

			    cfg_sHybridBurstEnable__read,
			    RDY_cfg_sHybridBurstEnable__read,

			    EN_cfg_sHybridBurstEnable_clear,
			    RDY_cfg_sHybridBurstEnable_clear,

			    cfg_sFixedLatency__read,
			    RDY_cfg_sFixedLatency__read,

			    EN_cfg_sFixedLatency_clear,
			    RDY_cfg_sFixedLatency_clear,

			    cfg_sInitialLatency__read,
			    RDY_cfg_sInitialLatency__read,

			    EN_cfg_sInitialLatency_clear,
			    RDY_cfg_sInitialLatency_clear,

			    EN_cfg_sReserved_clear,
			    RDY_cfg_sReserved_clear,

			    cfg_sDriveStrength__read,
			    RDY_cfg_sDriveStrength__read,

			    EN_cfg_sDriveStrength_clear,
			    RDY_cfg_sDriveStrength_clear,

			    cfg_sDeepPowerDown__read,
			    RDY_cfg_sDeepPowerDown__read,

			    EN_cfg_sDeepPowerDown_clear,
			    RDY_cfg_sDeepPowerDown_clear,

			    cfg_sBurstEnable__read,
			    RDY_cfg_sBurstEnable__read,

			    EN_cfg_sBurstEnable_clear,
			    RDY_cfg_sBurstEnable_clear,

			    cfg_sUltraDeepPowerDown__read,
			    RDY_cfg_sUltraDeepPowerDown__read,

			    EN_cfg_sUltraDeepPowerDown_clear,
			    RDY_cfg_sUltraDeepPowerDown_clear,

			    cfg_value,
			    RDY_cfg_value,

			    xspi_status_swip__write_data,
			    EN_xspi_status_swip__write,
			    RDY_xspi_status_swip__write,

			    EN_xspi_status_swip_clear,
			    RDY_xspi_status_swip_clear,

			    xspi_status_value,
			    RDY_xspi_status_value,

			    xspi_control_suse_xspi_clk__read,
			    RDY_xspi_control_suse_xspi_clk__read,

			    EN_xspi_control_suse_xspi_clk_clear,
			    RDY_xspi_control_suse_xspi_clk_clear,

			    xspi_control_sinterrupt_enable__read,
			    RDY_xspi_control_sinterrupt_enable__read,

			    EN_xspi_control_sinterrupt_enable_clear,
			    RDY_xspi_control_sinterrupt_enable_clear,

			    xspi_control_value,
			    RDY_xspi_control_value,

			    xspi_rates_scmd_rate__write_data,
			    EN_xspi_rates_scmd_rate__write,
			    RDY_xspi_rates_scmd_rate__write,

			    xspi_rates_scmd_rate__read,
			    RDY_xspi_rates_scmd_rate__read,

			    EN_xspi_rates_scmd_rate_clear,
			    RDY_xspi_rates_scmd_rate_clear,

			    xspi_rates_saddr_rate__write_data,
			    EN_xspi_rates_saddr_rate__write,
			    RDY_xspi_rates_saddr_rate__write,

			    xspi_rates_saddr_rate__read,
			    RDY_xspi_rates_saddr_rate__read,

			    EN_xspi_rates_saddr_rate_clear,
			    RDY_xspi_rates_saddr_rate_clear,

			    xspi_rates_sdata_rate__write_data,
			    EN_xspi_rates_sdata_rate__write,
			    RDY_xspi_rates_sdata_rate__write,

			    xspi_rates_sdata_rate__read,
			    RDY_xspi_rates_sdata_rate__read,

			    EN_xspi_rates_sdata_rate_clear,
			    RDY_xspi_rates_sdata_rate_clear,

			    xspi_rates_value,
			    RDY_xspi_rates_value,

			    interrupt_status_saxi_resp__write_data,
			    EN_interrupt_status_saxi_resp__write,
			    RDY_interrupt_status_saxi_resp__write,

			    interrupt_status_saxi_resp__read,
			    RDY_interrupt_status_saxi_resp__read,

			    EN_interrupt_status_saxi_resp_clear,
			    RDY_interrupt_status_saxi_resp_clear,

			    interrupt_status_sread_underflow__write_data,
			    EN_interrupt_status_sread_underflow__write,
			    RDY_interrupt_status_sread_underflow__write,

			    interrupt_status_sread_underflow__read,
			    RDY_interrupt_status_sread_underflow__read,

			    EN_interrupt_status_sread_underflow_clear,
			    RDY_interrupt_status_sread_underflow_clear,

			    interrupt_status_swrite_overflow__write_data,
			    EN_interrupt_status_swrite_overflow__write,
			    RDY_interrupt_status_swrite_overflow__write,

			    interrupt_status_swrite_overflow__read,
			    RDY_interrupt_status_swrite_overflow__read,

			    EN_interrupt_status_swrite_overflow_clear,
			    RDY_interrupt_status_swrite_overflow_clear,

			    interrupt_status_value,
			    RDY_interrupt_status_value,

			    write_address,
			    write_data,
			    write_wstrb,
			    EN_write,
			    RDY_write,

			    read_address,
			    EN_read,
			    read,
			    RDY_read);
  input  CLK;
  input  RST_N;

  // action method id0_smgf_id_clear
  input  EN_id0_smgf_id_clear;
  output RDY_id0_smgf_id_clear;

  // action method id0_sdevid0_clear
  input  EN_id0_sdevid0_clear;
  output RDY_id0_sdevid0_clear;

  // value method id0_value
  output [63 : 0] id0_value;
  output RDY_id0_value;

  // action method id1_sdev_type_clear
  input  EN_id1_sdev_type_clear;
  output RDY_id1_sdev_type_clear;

  // action method id1_sdevid1_clear
  input  EN_id1_sdevid1_clear;
  output RDY_id1_sdevid1_clear;

  // value method id1_value
  output [63 : 0] id1_value;
  output RDY_id1_value;

  // value method cfg_sBurstLength__read
  output [1 : 0] cfg_sBurstLength__read;
  output RDY_cfg_sBurstLength__read;

  // action method cfg_sBurstLength_clear
  input  EN_cfg_sBurstLength_clear;
  output RDY_cfg_sBurstLength_clear;

  // value method cfg_sHybridBurstEnable__read
  output cfg_sHybridBurstEnable__read;
  output RDY_cfg_sHybridBurstEnable__read;

  // action method cfg_sHybridBurstEnable_clear
  input  EN_cfg_sHybridBurstEnable_clear;
  output RDY_cfg_sHybridBurstEnable_clear;

  // value method cfg_sFixedLatency__read
  output cfg_sFixedLatency__read;
  output RDY_cfg_sFixedLatency__read;

  // action method cfg_sFixedLatency_clear
  input  EN_cfg_sFixedLatency_clear;
  output RDY_cfg_sFixedLatency_clear;

  // value method cfg_sInitialLatency__read
  output [3 : 0] cfg_sInitialLatency__read;
  output RDY_cfg_sInitialLatency__read;

  // action method cfg_sInitialLatency_clear
  input  EN_cfg_sInitialLatency_clear;
  output RDY_cfg_sInitialLatency_clear;

  // action method cfg_sReserved_clear
  input  EN_cfg_sReserved_clear;
  output RDY_cfg_sReserved_clear;

  // value method cfg_sDriveStrength__read
  output [2 : 0] cfg_sDriveStrength__read;
  output RDY_cfg_sDriveStrength__read;

  // action method cfg_sDriveStrength_clear
  input  EN_cfg_sDriveStrength_clear;
  output RDY_cfg_sDriveStrength_clear;

  // value method cfg_sDeepPowerDown__read
  output cfg_sDeepPowerDown__read;
  output RDY_cfg_sDeepPowerDown__read;

  // action method cfg_sDeepPowerDown_clear
  input  EN_cfg_sDeepPowerDown_clear;
  output RDY_cfg_sDeepPowerDown_clear;

  // value method cfg_sBurstEnable__read
  output cfg_sBurstEnable__read;
  output RDY_cfg_sBurstEnable__read;

  // action method cfg_sBurstEnable_clear
  input  EN_cfg_sBurstEnable_clear;
  output RDY_cfg_sBurstEnable_clear;

  // value method cfg_sUltraDeepPowerDown__read
  output cfg_sUltraDeepPowerDown__read;
  output RDY_cfg_sUltraDeepPowerDown__read;

  // action method cfg_sUltraDeepPowerDown_clear
  input  EN_cfg_sUltraDeepPowerDown_clear;
  output RDY_cfg_sUltraDeepPowerDown_clear;

  // value method cfg_value
  output [63 : 0] cfg_value;
  output RDY_cfg_value;

  // action method xspi_status_swip__write
  input  xspi_status_swip__write_data;
  input  EN_xspi_status_swip__write;
  output RDY_xspi_status_swip__write;

  // action method xspi_status_swip_clear
  input  EN_xspi_status_swip_clear;
  output RDY_xspi_status_swip_clear;

  // value method xspi_status_value
  output [63 : 0] xspi_status_value;
  output RDY_xspi_status_value;

  // value method xspi_control_suse_xspi_clk__read
  output xspi_control_suse_xspi_clk__read;
  output RDY_xspi_control_suse_xspi_clk__read;

  // action method xspi_control_suse_xspi_clk_clear
  input  EN_xspi_control_suse_xspi_clk_clear;
  output RDY_xspi_control_suse_xspi_clk_clear;

  // value method xspi_control_sinterrupt_enable__read
  output xspi_control_sinterrupt_enable__read;
  output RDY_xspi_control_sinterrupt_enable__read;

  // action method xspi_control_sinterrupt_enable_clear
  input  EN_xspi_control_sinterrupt_enable_clear;
  output RDY_xspi_control_sinterrupt_enable_clear;

  // value method xspi_control_value
  output [63 : 0] xspi_control_value;
  output RDY_xspi_control_value;

  // action method xspi_rates_scmd_rate__write
  input  [7 : 0] xspi_rates_scmd_rate__write_data;
  input  EN_xspi_rates_scmd_rate__write;
  output RDY_xspi_rates_scmd_rate__write;

  // value method xspi_rates_scmd_rate__read
  output [7 : 0] xspi_rates_scmd_rate__read;
  output RDY_xspi_rates_scmd_rate__read;

  // action method xspi_rates_scmd_rate_clear
  input  EN_xspi_rates_scmd_rate_clear;
  output RDY_xspi_rates_scmd_rate_clear;

  // action method xspi_rates_saddr_rate__write
  input  [7 : 0] xspi_rates_saddr_rate__write_data;
  input  EN_xspi_rates_saddr_rate__write;
  output RDY_xspi_rates_saddr_rate__write;

  // value method xspi_rates_saddr_rate__read
  output [7 : 0] xspi_rates_saddr_rate__read;
  output RDY_xspi_rates_saddr_rate__read;

  // action method xspi_rates_saddr_rate_clear
  input  EN_xspi_rates_saddr_rate_clear;
  output RDY_xspi_rates_saddr_rate_clear;

  // action method xspi_rates_sdata_rate__write
  input  [7 : 0] xspi_rates_sdata_rate__write_data;
  input  EN_xspi_rates_sdata_rate__write;
  output RDY_xspi_rates_sdata_rate__write;

  // value method xspi_rates_sdata_rate__read
  output [7 : 0] xspi_rates_sdata_rate__read;
  output RDY_xspi_rates_sdata_rate__read;

  // action method xspi_rates_sdata_rate_clear
  input  EN_xspi_rates_sdata_rate_clear;
  output RDY_xspi_rates_sdata_rate_clear;

  // value method xspi_rates_value
  output [63 : 0] xspi_rates_value;
  output RDY_xspi_rates_value;

  // action method interrupt_status_saxi_resp__write
  input  [1 : 0] interrupt_status_saxi_resp__write_data;
  input  EN_interrupt_status_saxi_resp__write;
  output RDY_interrupt_status_saxi_resp__write;

  // value method interrupt_status_saxi_resp__read
  output [1 : 0] interrupt_status_saxi_resp__read;
  output RDY_interrupt_status_saxi_resp__read;

  // action method interrupt_status_saxi_resp_clear
  input  EN_interrupt_status_saxi_resp_clear;
  output RDY_interrupt_status_saxi_resp_clear;

  // action method interrupt_status_sread_underflow__write
  input  interrupt_status_sread_underflow__write_data;
  input  EN_interrupt_status_sread_underflow__write;
  output RDY_interrupt_status_sread_underflow__write;

  // value method interrupt_status_sread_underflow__read
  output interrupt_status_sread_underflow__read;
  output RDY_interrupt_status_sread_underflow__read;

  // action method interrupt_status_sread_underflow_clear
  input  EN_interrupt_status_sread_underflow_clear;
  output RDY_interrupt_status_sread_underflow_clear;

  // action method interrupt_status_swrite_overflow__write
  input  interrupt_status_swrite_overflow__write_data;
  input  EN_interrupt_status_swrite_overflow__write;
  output RDY_interrupt_status_swrite_overflow__write;

  // value method interrupt_status_swrite_overflow__read
  output interrupt_status_swrite_overflow__read;
  output RDY_interrupt_status_swrite_overflow__read;

  // action method interrupt_status_swrite_overflow_clear
  input  EN_interrupt_status_swrite_overflow_clear;
  output RDY_interrupt_status_swrite_overflow_clear;

  // value method interrupt_status_value
  output [63 : 0] interrupt_status_value;
  output RDY_interrupt_status_value;

  // action method write
  input  [5 : 0] write_address;
  input  [63 : 0] write_data;
  input  [7 : 0] write_wstrb;
  input  EN_write;
  output RDY_write;

  // actionvalue method read
  input  [5 : 0] read_address;
  input  EN_read;
  output [63 : 0] read;
  output RDY_read;

  // signals for module outputs
  reg [63 : 0] read;
  wire [63 : 0] cfg_value,
		id0_value,
		id1_value,
		interrupt_status_value,
		xspi_control_value,
		xspi_rates_value,
		xspi_status_value;
  wire [7 : 0] xspi_rates_saddr_rate__read,
	       xspi_rates_scmd_rate__read,
	       xspi_rates_sdata_rate__read;
  wire [3 : 0] cfg_sInitialLatency__read;
  wire [2 : 0] cfg_sDriveStrength__read;
  wire [1 : 0] cfg_sBurstLength__read, interrupt_status_saxi_resp__read;
  wire RDY_cfg_sBurstEnable__read,
       RDY_cfg_sBurstEnable_clear,
       RDY_cfg_sBurstLength__read,
       RDY_cfg_sBurstLength_clear,
       RDY_cfg_sDeepPowerDown__read,
       RDY_cfg_sDeepPowerDown_clear,
       RDY_cfg_sDriveStrength__read,
       RDY_cfg_sDriveStrength_clear,
       RDY_cfg_sFixedLatency__read,
       RDY_cfg_sFixedLatency_clear,
       RDY_cfg_sHybridBurstEnable__read,
       RDY_cfg_sHybridBurstEnable_clear,
       RDY_cfg_sInitialLatency__read,
       RDY_cfg_sInitialLatency_clear,
       RDY_cfg_sReserved_clear,
       RDY_cfg_sUltraDeepPowerDown__read,
       RDY_cfg_sUltraDeepPowerDown_clear,
       RDY_cfg_value,
       RDY_id0_sdevid0_clear,
       RDY_id0_smgf_id_clear,
       RDY_id0_value,
       RDY_id1_sdev_type_clear,
       RDY_id1_sdevid1_clear,
       RDY_id1_value,
       RDY_interrupt_status_saxi_resp__read,
       RDY_interrupt_status_saxi_resp__write,
       RDY_interrupt_status_saxi_resp_clear,
       RDY_interrupt_status_sread_underflow__read,
       RDY_interrupt_status_sread_underflow__write,
       RDY_interrupt_status_sread_underflow_clear,
       RDY_interrupt_status_swrite_overflow__read,
       RDY_interrupt_status_swrite_overflow__write,
       RDY_interrupt_status_swrite_overflow_clear,
       RDY_interrupt_status_value,
       RDY_read,
       RDY_write,
       RDY_xspi_control_sinterrupt_enable__read,
       RDY_xspi_control_sinterrupt_enable_clear,
       RDY_xspi_control_suse_xspi_clk__read,
       RDY_xspi_control_suse_xspi_clk_clear,
       RDY_xspi_control_value,
       RDY_xspi_rates_saddr_rate__read,
       RDY_xspi_rates_saddr_rate__write,
       RDY_xspi_rates_saddr_rate_clear,
       RDY_xspi_rates_scmd_rate__read,
       RDY_xspi_rates_scmd_rate__write,
       RDY_xspi_rates_scmd_rate_clear,
       RDY_xspi_rates_sdata_rate__read,
       RDY_xspi_rates_sdata_rate__write,
       RDY_xspi_rates_sdata_rate_clear,
       RDY_xspi_rates_value,
       RDY_xspi_status_swip__write,
       RDY_xspi_status_swip_clear,
       RDY_xspi_status_value,
       cfg_sBurstEnable__read,
       cfg_sDeepPowerDown__read,
       cfg_sFixedLatency__read,
       cfg_sHybridBurstEnable__read,
       cfg_sUltraDeepPowerDown__read,
       interrupt_status_sread_underflow__read,
       interrupt_status_swrite_overflow__read,
       xspi_control_sinterrupt_enable__read,
       xspi_control_suse_xspi_clk__read;

  // inlined wires
  wire [23 : 0] reg_ID0_sig_devid0_sw_wdata_wget,
		reg_ID1_sig_devid1_sw_wdata_wget;
  wire [15 : 0] reg_xspi_rates_sig_addr_rate_sw_wdata_wget,
		reg_xspi_rates_sig_cmd_rate_sw_wdata_wget,
		reg_xspi_rates_sig_data_rate_sw_wdata_wget;
  wire [11 : 0] reg_ID0_sig_devid0_hw_wdata_wget,
		reg_ID0_sig_devid0_r_decr_wget,
		reg_ID0_sig_devid0_r_incr_wget,
		reg_ID1_sig_devid1_hw_wdata_wget,
		reg_ID1_sig_devid1_r_decr_wget,
		reg_ID1_sig_devid1_r_incr_wget;
  wire [7 : 0] reg_CFG_sig_InitialLatency_sw_wdata_wget,
	       reg_CFG_sig_Reserved_sw_wdata_wget,
	       reg_ID0_sig_mgf_id_sw_wdata_wget,
	       reg_ID1_sig_dev_type_sw_wdata_wget,
	       reg_xspi_rates_sig_addr_rate_hw_wdata_wget,
	       reg_xspi_rates_sig_addr_rate_r_decr_wget,
	       reg_xspi_rates_sig_addr_rate_r_incr_wget,
	       reg_xspi_rates_sig_cmd_rate_hw_wdata_wget,
	       reg_xspi_rates_sig_cmd_rate_r_decr_wget,
	       reg_xspi_rates_sig_cmd_rate_r_incr_wget,
	       reg_xspi_rates_sig_data_rate_hw_wdata_wget,
	       reg_xspi_rates_sig_data_rate_r_decr_wget,
	       reg_xspi_rates_sig_data_rate_r_incr_wget;
  wire [5 : 0] reg_CFG_sig_DriveStrength_sw_wdata_wget;
  wire [3 : 0] reg_CFG_sig_BurstLength_sw_wdata_wget,
	       reg_CFG_sig_InitialLatency_hw_wdata_wget,
	       reg_CFG_sig_InitialLatency_r_decr_wget,
	       reg_CFG_sig_InitialLatency_r_incr_wget,
	       reg_CFG_sig_Reserved_hw_wdata_wget,
	       reg_CFG_sig_Reserved_r_decr_wget,
	       reg_CFG_sig_Reserved_r_incr_wget,
	       reg_ID0_sig_mgf_id_hw_wdata_wget,
	       reg_ID0_sig_mgf_id_r_decr_wget,
	       reg_ID0_sig_mgf_id_r_incr_wget,
	       reg_ID1_sig_dev_type_hw_wdata_wget,
	       reg_ID1_sig_dev_type_r_decr_wget,
	       reg_ID1_sig_dev_type_r_incr_wget,
	       reg_interrupt_status_sig_axi_resp_sw_wdata_wget;
  wire [2 : 0] reg_CFG_sig_DriveStrength_hw_wdata_wget,
	       reg_CFG_sig_DriveStrength_r_decr_wget,
	       reg_CFG_sig_DriveStrength_r_incr_wget;
  wire [1 : 0] reg_CFG_sig_BurstEnable_sw_wdata_wget,
	       reg_CFG_sig_BurstLength_hw_wdata_wget,
	       reg_CFG_sig_BurstLength_r_decr_wget,
	       reg_CFG_sig_BurstLength_r_incr_wget,
	       reg_CFG_sig_DeepPowerDown_sw_wdata_wget,
	       reg_CFG_sig_FixedLatency_sw_wdata_wget,
	       reg_CFG_sig_HybridBurstEnable_sw_wdata_wget,
	       reg_CFG_sig_UltraDeepPowerDown_sw_wdata_wget,
	       reg_interrupt_status_sig_axi_resp_hw_wdata_wget,
	       reg_interrupt_status_sig_axi_resp_r_decr_wget,
	       reg_interrupt_status_sig_axi_resp_r_incr_wget,
	       reg_interrupt_status_sig_read_underflow_sw_wdata_wget,
	       reg_interrupt_status_sig_write_overflow_sw_wdata_wget,
	       reg_xspi_control_sig_interrupt_enable_sw_wdata_wget,
	       reg_xspi_control_sig_use_xspi_clk_sw_wdata_wget,
	       reg_xspi_status_sig_wip_sw_wdata_wget;
  wire reg_CFG_sig_BurstEnable_hw_wdata_wget,
       reg_CFG_sig_BurstEnable_hw_wdata_whas,
       reg_CFG_sig_BurstEnable_pw_clear_whas,
       reg_CFG_sig_BurstEnable_pw_set_whas,
       reg_CFG_sig_BurstEnable_pw_swacc_whas,
       reg_CFG_sig_BurstEnable_pw_swmod_whas,
       reg_CFG_sig_BurstEnable_r_decr_wget,
       reg_CFG_sig_BurstEnable_r_decr_whas,
       reg_CFG_sig_BurstEnable_r_incr_wget,
       reg_CFG_sig_BurstEnable_r_incr_whas,
       reg_CFG_sig_BurstEnable_sw_wdata_whas,
       reg_CFG_sig_BurstLength_hw_wdata_whas,
       reg_CFG_sig_BurstLength_pw_clear_whas,
       reg_CFG_sig_BurstLength_pw_set_whas,
       reg_CFG_sig_BurstLength_pw_swacc_whas,
       reg_CFG_sig_BurstLength_pw_swmod_whas,
       reg_CFG_sig_BurstLength_r_decr_whas,
       reg_CFG_sig_BurstLength_r_incr_whas,
       reg_CFG_sig_BurstLength_sw_wdata_whas,
       reg_CFG_sig_DeepPowerDown_hw_wdata_wget,
       reg_CFG_sig_DeepPowerDown_hw_wdata_whas,
       reg_CFG_sig_DeepPowerDown_pw_clear_whas,
       reg_CFG_sig_DeepPowerDown_pw_set_whas,
       reg_CFG_sig_DeepPowerDown_pw_swacc_whas,
       reg_CFG_sig_DeepPowerDown_pw_swmod_whas,
       reg_CFG_sig_DeepPowerDown_r_decr_wget,
       reg_CFG_sig_DeepPowerDown_r_decr_whas,
       reg_CFG_sig_DeepPowerDown_r_incr_wget,
       reg_CFG_sig_DeepPowerDown_r_incr_whas,
       reg_CFG_sig_DeepPowerDown_sw_wdata_whas,
       reg_CFG_sig_DriveStrength_hw_wdata_whas,
       reg_CFG_sig_DriveStrength_pw_clear_whas,
       reg_CFG_sig_DriveStrength_pw_set_whas,
       reg_CFG_sig_DriveStrength_pw_swacc_whas,
       reg_CFG_sig_DriveStrength_pw_swmod_whas,
       reg_CFG_sig_DriveStrength_r_decr_whas,
       reg_CFG_sig_DriveStrength_r_incr_whas,
       reg_CFG_sig_DriveStrength_sw_wdata_whas,
       reg_CFG_sig_FixedLatency_hw_wdata_wget,
       reg_CFG_sig_FixedLatency_hw_wdata_whas,
       reg_CFG_sig_FixedLatency_pw_clear_whas,
       reg_CFG_sig_FixedLatency_pw_set_whas,
       reg_CFG_sig_FixedLatency_pw_swacc_whas,
       reg_CFG_sig_FixedLatency_pw_swmod_whas,
       reg_CFG_sig_FixedLatency_r_decr_wget,
       reg_CFG_sig_FixedLatency_r_decr_whas,
       reg_CFG_sig_FixedLatency_r_incr_wget,
       reg_CFG_sig_FixedLatency_r_incr_whas,
       reg_CFG_sig_FixedLatency_sw_wdata_whas,
       reg_CFG_sig_HybridBurstEnable_hw_wdata_wget,
       reg_CFG_sig_HybridBurstEnable_hw_wdata_whas,
       reg_CFG_sig_HybridBurstEnable_pw_clear_whas,
       reg_CFG_sig_HybridBurstEnable_pw_set_whas,
       reg_CFG_sig_HybridBurstEnable_pw_swacc_whas,
       reg_CFG_sig_HybridBurstEnable_pw_swmod_whas,
       reg_CFG_sig_HybridBurstEnable_r_decr_wget,
       reg_CFG_sig_HybridBurstEnable_r_decr_whas,
       reg_CFG_sig_HybridBurstEnable_r_incr_wget,
       reg_CFG_sig_HybridBurstEnable_r_incr_whas,
       reg_CFG_sig_HybridBurstEnable_sw_wdata_whas,
       reg_CFG_sig_InitialLatency_hw_wdata_whas,
       reg_CFG_sig_InitialLatency_pw_clear_whas,
       reg_CFG_sig_InitialLatency_pw_set_whas,
       reg_CFG_sig_InitialLatency_pw_swacc_whas,
       reg_CFG_sig_InitialLatency_pw_swmod_whas,
       reg_CFG_sig_InitialLatency_r_decr_whas,
       reg_CFG_sig_InitialLatency_r_incr_whas,
       reg_CFG_sig_InitialLatency_sw_wdata_whas,
       reg_CFG_sig_Reserved_hw_wdata_whas,
       reg_CFG_sig_Reserved_pw_clear_whas,
       reg_CFG_sig_Reserved_pw_set_whas,
       reg_CFG_sig_Reserved_pw_swacc_whas,
       reg_CFG_sig_Reserved_pw_swmod_whas,
       reg_CFG_sig_Reserved_r_decr_whas,
       reg_CFG_sig_Reserved_r_incr_whas,
       reg_CFG_sig_Reserved_sw_wdata_whas,
       reg_CFG_sig_UltraDeepPowerDown_hw_wdata_wget,
       reg_CFG_sig_UltraDeepPowerDown_hw_wdata_whas,
       reg_CFG_sig_UltraDeepPowerDown_pw_clear_whas,
       reg_CFG_sig_UltraDeepPowerDown_pw_set_whas,
       reg_CFG_sig_UltraDeepPowerDown_pw_swacc_whas,
       reg_CFG_sig_UltraDeepPowerDown_pw_swmod_whas,
       reg_CFG_sig_UltraDeepPowerDown_r_decr_wget,
       reg_CFG_sig_UltraDeepPowerDown_r_decr_whas,
       reg_CFG_sig_UltraDeepPowerDown_r_incr_wget,
       reg_CFG_sig_UltraDeepPowerDown_r_incr_whas,
       reg_CFG_sig_UltraDeepPowerDown_sw_wdata_whas,
       reg_ID0_sig_devid0_hw_wdata_whas,
       reg_ID0_sig_devid0_pw_clear_whas,
       reg_ID0_sig_devid0_pw_set_whas,
       reg_ID0_sig_devid0_pw_swacc_whas,
       reg_ID0_sig_devid0_pw_swmod_whas,
       reg_ID0_sig_devid0_r_decr_whas,
       reg_ID0_sig_devid0_r_incr_whas,
       reg_ID0_sig_devid0_sw_wdata_whas,
       reg_ID0_sig_mgf_id_hw_wdata_whas,
       reg_ID0_sig_mgf_id_pw_clear_whas,
       reg_ID0_sig_mgf_id_pw_set_whas,
       reg_ID0_sig_mgf_id_pw_swacc_whas,
       reg_ID0_sig_mgf_id_pw_swmod_whas,
       reg_ID0_sig_mgf_id_r_decr_whas,
       reg_ID0_sig_mgf_id_r_incr_whas,
       reg_ID0_sig_mgf_id_sw_wdata_whas,
       reg_ID1_sig_dev_type_hw_wdata_whas,
       reg_ID1_sig_dev_type_pw_clear_whas,
       reg_ID1_sig_dev_type_pw_set_whas,
       reg_ID1_sig_dev_type_pw_swacc_whas,
       reg_ID1_sig_dev_type_pw_swmod_whas,
       reg_ID1_sig_dev_type_r_decr_whas,
       reg_ID1_sig_dev_type_r_incr_whas,
       reg_ID1_sig_dev_type_sw_wdata_whas,
       reg_ID1_sig_devid1_hw_wdata_whas,
       reg_ID1_sig_devid1_pw_clear_whas,
       reg_ID1_sig_devid1_pw_set_whas,
       reg_ID1_sig_devid1_pw_swacc_whas,
       reg_ID1_sig_devid1_pw_swmod_whas,
       reg_ID1_sig_devid1_r_decr_whas,
       reg_ID1_sig_devid1_r_incr_whas,
       reg_ID1_sig_devid1_sw_wdata_whas,
       reg_interrupt_status_sig_axi_resp_hw_wdata_whas,
       reg_interrupt_status_sig_axi_resp_pw_clear_whas,
       reg_interrupt_status_sig_axi_resp_pw_set_whas,
       reg_interrupt_status_sig_axi_resp_pw_swacc_whas,
       reg_interrupt_status_sig_axi_resp_pw_swmod_whas,
       reg_interrupt_status_sig_axi_resp_r_decr_whas,
       reg_interrupt_status_sig_axi_resp_r_incr_whas,
       reg_interrupt_status_sig_axi_resp_sw_wdata_whas,
       reg_interrupt_status_sig_read_underflow_hw_wdata_wget,
       reg_interrupt_status_sig_read_underflow_hw_wdata_whas,
       reg_interrupt_status_sig_read_underflow_pw_clear_whas,
       reg_interrupt_status_sig_read_underflow_pw_set_whas,
       reg_interrupt_status_sig_read_underflow_pw_swacc_whas,
       reg_interrupt_status_sig_read_underflow_pw_swmod_whas,
       reg_interrupt_status_sig_read_underflow_r_decr_wget,
       reg_interrupt_status_sig_read_underflow_r_decr_whas,
       reg_interrupt_status_sig_read_underflow_r_incr_wget,
       reg_interrupt_status_sig_read_underflow_r_incr_whas,
       reg_interrupt_status_sig_read_underflow_sw_wdata_whas,
       reg_interrupt_status_sig_write_overflow_hw_wdata_wget,
       reg_interrupt_status_sig_write_overflow_hw_wdata_whas,
       reg_interrupt_status_sig_write_overflow_pw_clear_whas,
       reg_interrupt_status_sig_write_overflow_pw_set_whas,
       reg_interrupt_status_sig_write_overflow_pw_swacc_whas,
       reg_interrupt_status_sig_write_overflow_pw_swmod_whas,
       reg_interrupt_status_sig_write_overflow_r_decr_wget,
       reg_interrupt_status_sig_write_overflow_r_decr_whas,
       reg_interrupt_status_sig_write_overflow_r_incr_wget,
       reg_interrupt_status_sig_write_overflow_r_incr_whas,
       reg_interrupt_status_sig_write_overflow_sw_wdata_whas,
       reg_xspi_control_sig_interrupt_enable_hw_wdata_wget,
       reg_xspi_control_sig_interrupt_enable_hw_wdata_whas,
       reg_xspi_control_sig_interrupt_enable_pw_clear_whas,
       reg_xspi_control_sig_interrupt_enable_pw_set_whas,
       reg_xspi_control_sig_interrupt_enable_pw_swacc_whas,
       reg_xspi_control_sig_interrupt_enable_pw_swmod_whas,
       reg_xspi_control_sig_interrupt_enable_r_decr_wget,
       reg_xspi_control_sig_interrupt_enable_r_decr_whas,
       reg_xspi_control_sig_interrupt_enable_r_incr_wget,
       reg_xspi_control_sig_interrupt_enable_r_incr_whas,
       reg_xspi_control_sig_interrupt_enable_sw_wdata_whas,
       reg_xspi_control_sig_use_xspi_clk_hw_wdata_wget,
       reg_xspi_control_sig_use_xspi_clk_hw_wdata_whas,
       reg_xspi_control_sig_use_xspi_clk_pw_clear_whas,
       reg_xspi_control_sig_use_xspi_clk_pw_set_whas,
       reg_xspi_control_sig_use_xspi_clk_pw_swacc_whas,
       reg_xspi_control_sig_use_xspi_clk_pw_swmod_whas,
       reg_xspi_control_sig_use_xspi_clk_r_decr_wget,
       reg_xspi_control_sig_use_xspi_clk_r_decr_whas,
       reg_xspi_control_sig_use_xspi_clk_r_incr_wget,
       reg_xspi_control_sig_use_xspi_clk_r_incr_whas,
       reg_xspi_control_sig_use_xspi_clk_sw_wdata_whas,
       reg_xspi_rates_sig_addr_rate_hw_wdata_whas,
       reg_xspi_rates_sig_addr_rate_pw_clear_whas,
       reg_xspi_rates_sig_addr_rate_pw_set_whas,
       reg_xspi_rates_sig_addr_rate_pw_swacc_whas,
       reg_xspi_rates_sig_addr_rate_pw_swmod_whas,
       reg_xspi_rates_sig_addr_rate_r_decr_whas,
       reg_xspi_rates_sig_addr_rate_r_incr_whas,
       reg_xspi_rates_sig_addr_rate_sw_wdata_whas,
       reg_xspi_rates_sig_cmd_rate_hw_wdata_whas,
       reg_xspi_rates_sig_cmd_rate_pw_clear_whas,
       reg_xspi_rates_sig_cmd_rate_pw_set_whas,
       reg_xspi_rates_sig_cmd_rate_pw_swacc_whas,
       reg_xspi_rates_sig_cmd_rate_pw_swmod_whas,
       reg_xspi_rates_sig_cmd_rate_r_decr_whas,
       reg_xspi_rates_sig_cmd_rate_r_incr_whas,
       reg_xspi_rates_sig_cmd_rate_sw_wdata_whas,
       reg_xspi_rates_sig_data_rate_hw_wdata_whas,
       reg_xspi_rates_sig_data_rate_pw_clear_whas,
       reg_xspi_rates_sig_data_rate_pw_set_whas,
       reg_xspi_rates_sig_data_rate_pw_swacc_whas,
       reg_xspi_rates_sig_data_rate_pw_swmod_whas,
       reg_xspi_rates_sig_data_rate_r_decr_whas,
       reg_xspi_rates_sig_data_rate_r_incr_whas,
       reg_xspi_rates_sig_data_rate_sw_wdata_whas,
       reg_xspi_status_sig_wip_hw_wdata_wget,
       reg_xspi_status_sig_wip_hw_wdata_whas,
       reg_xspi_status_sig_wip_pw_clear_whas,
       reg_xspi_status_sig_wip_pw_set_whas,
       reg_xspi_status_sig_wip_pw_swacc_whas,
       reg_xspi_status_sig_wip_pw_swmod_whas,
       reg_xspi_status_sig_wip_r_decr_wget,
       reg_xspi_status_sig_wip_r_decr_whas,
       reg_xspi_status_sig_wip_r_incr_wget,
       reg_xspi_status_sig_wip_r_incr_whas,
       reg_xspi_status_sig_wip_sw_wdata_whas;

  // register reg_CFG_sig_BurstEnable_r
  reg reg_CFG_sig_BurstEnable_r;
  wire reg_CFG_sig_BurstEnable_r_D_IN, reg_CFG_sig_BurstEnable_r_EN;

  // register reg_CFG_sig_BurstLength_r
  reg [1 : 0] reg_CFG_sig_BurstLength_r;
  wire [1 : 0] reg_CFG_sig_BurstLength_r_D_IN;
  wire reg_CFG_sig_BurstLength_r_EN;

  // register reg_CFG_sig_DeepPowerDown_r
  reg reg_CFG_sig_DeepPowerDown_r;
  wire reg_CFG_sig_DeepPowerDown_r_D_IN, reg_CFG_sig_DeepPowerDown_r_EN;

  // register reg_CFG_sig_DriveStrength_r
  reg [2 : 0] reg_CFG_sig_DriveStrength_r;
  wire [2 : 0] reg_CFG_sig_DriveStrength_r_D_IN;
  wire reg_CFG_sig_DriveStrength_r_EN;

  // register reg_CFG_sig_FixedLatency_r
  reg reg_CFG_sig_FixedLatency_r;
  wire reg_CFG_sig_FixedLatency_r_D_IN, reg_CFG_sig_FixedLatency_r_EN;

  // register reg_CFG_sig_HybridBurstEnable_r
  reg reg_CFG_sig_HybridBurstEnable_r;
  wire reg_CFG_sig_HybridBurstEnable_r_D_IN,
       reg_CFG_sig_HybridBurstEnable_r_EN;

  // register reg_CFG_sig_InitialLatency_r
  reg [3 : 0] reg_CFG_sig_InitialLatency_r;
  wire [3 : 0] reg_CFG_sig_InitialLatency_r_D_IN;
  wire reg_CFG_sig_InitialLatency_r_EN;

  // register reg_CFG_sig_Reserved_r
  reg [3 : 0] reg_CFG_sig_Reserved_r;
  wire [3 : 0] reg_CFG_sig_Reserved_r_D_IN;
  wire reg_CFG_sig_Reserved_r_EN;

  // register reg_CFG_sig_UltraDeepPowerDown_r
  reg reg_CFG_sig_UltraDeepPowerDown_r;
  wire reg_CFG_sig_UltraDeepPowerDown_r_D_IN,
       reg_CFG_sig_UltraDeepPowerDown_r_EN;

  // register reg_ID0_sig_devid0_r
  reg [11 : 0] reg_ID0_sig_devid0_r;
  wire [11 : 0] reg_ID0_sig_devid0_r_D_IN;
  wire reg_ID0_sig_devid0_r_EN;

  // register reg_ID0_sig_mgf_id_r
  reg [3 : 0] reg_ID0_sig_mgf_id_r;
  wire [3 : 0] reg_ID0_sig_mgf_id_r_D_IN;
  wire reg_ID0_sig_mgf_id_r_EN;

  // register reg_ID1_sig_dev_type_r
  reg [3 : 0] reg_ID1_sig_dev_type_r;
  wire [3 : 0] reg_ID1_sig_dev_type_r_D_IN;
  wire reg_ID1_sig_dev_type_r_EN;

  // register reg_ID1_sig_devid1_r
  reg [11 : 0] reg_ID1_sig_devid1_r;
  wire [11 : 0] reg_ID1_sig_devid1_r_D_IN;
  wire reg_ID1_sig_devid1_r_EN;

  // register reg_interrupt_status_sig_axi_resp_r
  reg [1 : 0] reg_interrupt_status_sig_axi_resp_r;
  wire [1 : 0] reg_interrupt_status_sig_axi_resp_r_D_IN;
  wire reg_interrupt_status_sig_axi_resp_r_EN;

  // register reg_interrupt_status_sig_read_underflow_r
  reg reg_interrupt_status_sig_read_underflow_r;
  wire reg_interrupt_status_sig_read_underflow_r_D_IN,
       reg_interrupt_status_sig_read_underflow_r_EN;

  // register reg_interrupt_status_sig_write_overflow_r
  reg reg_interrupt_status_sig_write_overflow_r;
  wire reg_interrupt_status_sig_write_overflow_r_D_IN,
       reg_interrupt_status_sig_write_overflow_r_EN;

  // register reg_xspi_control_sig_interrupt_enable_r
  reg reg_xspi_control_sig_interrupt_enable_r;
  wire reg_xspi_control_sig_interrupt_enable_r_D_IN,
       reg_xspi_control_sig_interrupt_enable_r_EN;

  // register reg_xspi_control_sig_use_xspi_clk_r
  reg reg_xspi_control_sig_use_xspi_clk_r;
  wire reg_xspi_control_sig_use_xspi_clk_r_D_IN,
       reg_xspi_control_sig_use_xspi_clk_r_EN;

  // register reg_xspi_rates_sig_addr_rate_r
  reg [7 : 0] reg_xspi_rates_sig_addr_rate_r;
  wire [7 : 0] reg_xspi_rates_sig_addr_rate_r_D_IN;
  wire reg_xspi_rates_sig_addr_rate_r_EN;

  // register reg_xspi_rates_sig_cmd_rate_r
  reg [7 : 0] reg_xspi_rates_sig_cmd_rate_r;
  wire [7 : 0] reg_xspi_rates_sig_cmd_rate_r_D_IN;
  wire reg_xspi_rates_sig_cmd_rate_r_EN;

  // register reg_xspi_rates_sig_data_rate_r
  reg [7 : 0] reg_xspi_rates_sig_data_rate_r;
  wire [7 : 0] reg_xspi_rates_sig_data_rate_r_D_IN;
  wire reg_xspi_rates_sig_data_rate_r_EN;

  // register reg_xspi_status_sig_wip_r
  reg reg_xspi_status_sig_wip_r;
  wire reg_xspi_status_sig_wip_r_D_IN, reg_xspi_status_sig_wip_r_EN;

  // rule scheduling signals
  wire CAN_FIRE_RL_reg_CFG_sig_BurstEnable_r_write,
       CAN_FIRE_RL_reg_CFG_sig_BurstLength_r_write,
       CAN_FIRE_RL_reg_CFG_sig_DeepPowerDown_r_write,
       CAN_FIRE_RL_reg_CFG_sig_DriveStrength_r_write,
       CAN_FIRE_RL_reg_CFG_sig_FixedLatency_r_write,
       CAN_FIRE_RL_reg_CFG_sig_HybridBurstEnable_r_write,
       CAN_FIRE_RL_reg_CFG_sig_InitialLatency_r_write,
       CAN_FIRE_RL_reg_CFG_sig_Reserved_r_write,
       CAN_FIRE_RL_reg_CFG_sig_UltraDeepPowerDown_r_write,
       CAN_FIRE_RL_reg_ID0_sig_devid0_r_write,
       CAN_FIRE_RL_reg_ID0_sig_mgf_id_r_write,
       CAN_FIRE_RL_reg_ID1_sig_dev_type_r_write,
       CAN_FIRE_RL_reg_ID1_sig_devid1_r_write,
       CAN_FIRE_RL_reg_interrupt_status_sig_axi_resp_r_write,
       CAN_FIRE_RL_reg_interrupt_status_sig_read_underflow_r_write,
       CAN_FIRE_RL_reg_interrupt_status_sig_write_overflow_r_write,
       CAN_FIRE_RL_reg_xspi_control_sig_interrupt_enable_r_write,
       CAN_FIRE_RL_reg_xspi_control_sig_use_xspi_clk_r_write,
       CAN_FIRE_RL_reg_xspi_rates_sig_addr_rate_r_write,
       CAN_FIRE_RL_reg_xspi_rates_sig_cmd_rate_r_write,
       CAN_FIRE_RL_reg_xspi_rates_sig_data_rate_r_write,
       CAN_FIRE_RL_reg_xspi_status_sig_wip_r_write,
       CAN_FIRE_cfg_sBurstEnable_clear,
       CAN_FIRE_cfg_sBurstLength_clear,
       CAN_FIRE_cfg_sDeepPowerDown_clear,
       CAN_FIRE_cfg_sDriveStrength_clear,
       CAN_FIRE_cfg_sFixedLatency_clear,
       CAN_FIRE_cfg_sHybridBurstEnable_clear,
       CAN_FIRE_cfg_sInitialLatency_clear,
       CAN_FIRE_cfg_sReserved_clear,
       CAN_FIRE_cfg_sUltraDeepPowerDown_clear,
       CAN_FIRE_id0_sdevid0_clear,
       CAN_FIRE_id0_smgf_id_clear,
       CAN_FIRE_id1_sdev_type_clear,
       CAN_FIRE_id1_sdevid1_clear,
       CAN_FIRE_interrupt_status_saxi_resp__write,
       CAN_FIRE_interrupt_status_saxi_resp_clear,
       CAN_FIRE_interrupt_status_sread_underflow__write,
       CAN_FIRE_interrupt_status_sread_underflow_clear,
       CAN_FIRE_interrupt_status_swrite_overflow__write,
       CAN_FIRE_interrupt_status_swrite_overflow_clear,
       CAN_FIRE_read,
       CAN_FIRE_write,
       CAN_FIRE_xspi_control_sinterrupt_enable_clear,
       CAN_FIRE_xspi_control_suse_xspi_clk_clear,
       CAN_FIRE_xspi_rates_saddr_rate__write,
       CAN_FIRE_xspi_rates_saddr_rate_clear,
       CAN_FIRE_xspi_rates_scmd_rate__write,
       CAN_FIRE_xspi_rates_scmd_rate_clear,
       CAN_FIRE_xspi_rates_sdata_rate__write,
       CAN_FIRE_xspi_rates_sdata_rate_clear,
       CAN_FIRE_xspi_status_swip__write,
       CAN_FIRE_xspi_status_swip_clear,
       WILL_FIRE_RL_reg_CFG_sig_BurstEnable_r_write,
       WILL_FIRE_RL_reg_CFG_sig_BurstLength_r_write,
       WILL_FIRE_RL_reg_CFG_sig_DeepPowerDown_r_write,
       WILL_FIRE_RL_reg_CFG_sig_DriveStrength_r_write,
       WILL_FIRE_RL_reg_CFG_sig_FixedLatency_r_write,
       WILL_FIRE_RL_reg_CFG_sig_HybridBurstEnable_r_write,
       WILL_FIRE_RL_reg_CFG_sig_InitialLatency_r_write,
       WILL_FIRE_RL_reg_CFG_sig_Reserved_r_write,
       WILL_FIRE_RL_reg_CFG_sig_UltraDeepPowerDown_r_write,
       WILL_FIRE_RL_reg_ID0_sig_devid0_r_write,
       WILL_FIRE_RL_reg_ID0_sig_mgf_id_r_write,
       WILL_FIRE_RL_reg_ID1_sig_dev_type_r_write,
       WILL_FIRE_RL_reg_ID1_sig_devid1_r_write,
       WILL_FIRE_RL_reg_interrupt_status_sig_axi_resp_r_write,
       WILL_FIRE_RL_reg_interrupt_status_sig_read_underflow_r_write,
       WILL_FIRE_RL_reg_interrupt_status_sig_write_overflow_r_write,
       WILL_FIRE_RL_reg_xspi_control_sig_interrupt_enable_r_write,
       WILL_FIRE_RL_reg_xspi_control_sig_use_xspi_clk_r_write,
       WILL_FIRE_RL_reg_xspi_rates_sig_addr_rate_r_write,
       WILL_FIRE_RL_reg_xspi_rates_sig_cmd_rate_r_write,
       WILL_FIRE_RL_reg_xspi_rates_sig_data_rate_r_write,
       WILL_FIRE_RL_reg_xspi_status_sig_wip_r_write,
       WILL_FIRE_cfg_sBurstEnable_clear,
       WILL_FIRE_cfg_sBurstLength_clear,
       WILL_FIRE_cfg_sDeepPowerDown_clear,
       WILL_FIRE_cfg_sDriveStrength_clear,
       WILL_FIRE_cfg_sFixedLatency_clear,
       WILL_FIRE_cfg_sHybridBurstEnable_clear,
       WILL_FIRE_cfg_sInitialLatency_clear,
       WILL_FIRE_cfg_sReserved_clear,
       WILL_FIRE_cfg_sUltraDeepPowerDown_clear,
       WILL_FIRE_id0_sdevid0_clear,
       WILL_FIRE_id0_smgf_id_clear,
       WILL_FIRE_id1_sdev_type_clear,
       WILL_FIRE_id1_sdevid1_clear,
       WILL_FIRE_interrupt_status_saxi_resp__write,
       WILL_FIRE_interrupt_status_saxi_resp_clear,
       WILL_FIRE_interrupt_status_sread_underflow__write,
       WILL_FIRE_interrupt_status_sread_underflow_clear,
       WILL_FIRE_interrupt_status_swrite_overflow__write,
       WILL_FIRE_interrupt_status_swrite_overflow_clear,
       WILL_FIRE_read,
       WILL_FIRE_write,
       WILL_FIRE_xspi_control_sinterrupt_enable_clear,
       WILL_FIRE_xspi_control_suse_xspi_clk_clear,
       WILL_FIRE_xspi_rates_saddr_rate__write,
       WILL_FIRE_xspi_rates_saddr_rate_clear,
       WILL_FIRE_xspi_rates_scmd_rate__write,
       WILL_FIRE_xspi_rates_scmd_rate_clear,
       WILL_FIRE_xspi_rates_sdata_rate__write,
       WILL_FIRE_xspi_rates_sdata_rate_clear,
       WILL_FIRE_xspi_status_swip__write,
       WILL_FIRE_xspi_status_swip_clear;

  // remaining internal signals
  wire [63 : 0] v__h24965,
		v__h25147,
		v__h25326,
		v__h26048,
		v__h26152,
		v__h26331,
		v__h26587;
  wire [11 : 0] rr__h1029,
		rr__h2115,
		x__h1042,
		x__h1064,
		x__h2128,
		x__h2150,
		x__h23754,
		y__h1043,
		y__h2129;
  wire [7 : 0] IF_reg_xspi_rates_sig_addr_rate_sw_wdata_whas__ETC___d510,
	       IF_reg_xspi_rates_sig_cmd_rate_sw_wdata_whas___ETC___d482,
	       IF_reg_xspi_rates_sig_data_rate_sw_wdata_whas__ETC___d538,
	       rr__h10248,
	       rr__h9170,
	       rr__h9709,
	       x__h10261,
	       x__h10283,
	       x__h24742,
	       x__h24826,
	       x__h24897,
	       x__h9183,
	       x__h9205,
	       x__h9722,
	       x__h9744,
	       y__h10262,
	       y__h9184,
	       y__h9723;
  wire [3 : 0] rr__h1576,
	       rr__h4283,
	       rr__h490,
	       x__h1589,
	       x__h1611,
	       x__h24152,
	       x__h4296,
	       x__h4318,
	       x__h503,
	       x__h525,
	       y__h1590,
	       y__h4297,
	       y__h504;
  wire [1 : 0] rr__h2662, x__h24068, x__h2675, x__h2697, y__h2676;
  wire rr__h5900,
       rr__h6441,
       rr__h6982,
       rr__h8080,
       rr__h8621,
       x__h5913,
       x__h5935,
       x__h6454,
       x__h6476,
       x__h6995,
       x__h7017,
       x__h8093,
       x__h8115,
       x__h8634,
       x__h8656,
       y__h5914,
       y__h6455,
       y__h6996,
       y__h8094,
       y__h8635;

  // action method id0_smgf_id_clear
  assign RDY_id0_smgf_id_clear = 1'd1 ;
  assign CAN_FIRE_id0_smgf_id_clear = 1'd1 ;
  assign WILL_FIRE_id0_smgf_id_clear = EN_id0_smgf_id_clear ;

  // action method id0_sdevid0_clear
  assign RDY_id0_sdevid0_clear = 1'd1 ;
  assign CAN_FIRE_id0_sdevid0_clear = 1'd1 ;
  assign WILL_FIRE_id0_sdevid0_clear = EN_id0_sdevid0_clear ;

  // value method id0_value
  assign id0_value = 64'd0 ;
  assign RDY_id0_value = 1'd1 ;

  // action method id1_sdev_type_clear
  assign RDY_id1_sdev_type_clear = 1'd1 ;
  assign CAN_FIRE_id1_sdev_type_clear = 1'd1 ;
  assign WILL_FIRE_id1_sdev_type_clear = EN_id1_sdev_type_clear ;

  // action method id1_sdevid1_clear
  assign RDY_id1_sdevid1_clear = 1'd1 ;
  assign CAN_FIRE_id1_sdevid1_clear = 1'd1 ;
  assign WILL_FIRE_id1_sdevid1_clear = EN_id1_sdevid1_clear ;

  // value method id1_value
  assign id1_value = 64'd0 ;
  assign RDY_id1_value = 1'd1 ;

  // value method cfg_sBurstLength__read
  assign cfg_sBurstLength__read = reg_CFG_sig_BurstLength_r ;
  assign RDY_cfg_sBurstLength__read = 1'd1 ;

  // action method cfg_sBurstLength_clear
  assign RDY_cfg_sBurstLength_clear = 1'd1 ;
  assign CAN_FIRE_cfg_sBurstLength_clear = 1'd1 ;
  assign WILL_FIRE_cfg_sBurstLength_clear = EN_cfg_sBurstLength_clear ;

  // value method cfg_sHybridBurstEnable__read
  assign cfg_sHybridBurstEnable__read = reg_CFG_sig_HybridBurstEnable_r ;
  assign RDY_cfg_sHybridBurstEnable__read = 1'd1 ;

  // action method cfg_sHybridBurstEnable_clear
  assign RDY_cfg_sHybridBurstEnable_clear = 1'd1 ;
  assign CAN_FIRE_cfg_sHybridBurstEnable_clear = 1'd1 ;
  assign WILL_FIRE_cfg_sHybridBurstEnable_clear =
	     EN_cfg_sHybridBurstEnable_clear ;

  // value method cfg_sFixedLatency__read
  assign cfg_sFixedLatency__read = reg_CFG_sig_FixedLatency_r ;
  assign RDY_cfg_sFixedLatency__read = 1'd1 ;

  // action method cfg_sFixedLatency_clear
  assign RDY_cfg_sFixedLatency_clear = 1'd1 ;
  assign CAN_FIRE_cfg_sFixedLatency_clear = 1'd1 ;
  assign WILL_FIRE_cfg_sFixedLatency_clear = EN_cfg_sFixedLatency_clear ;

  // value method cfg_sInitialLatency__read
  assign cfg_sInitialLatency__read = reg_CFG_sig_InitialLatency_r ;
  assign RDY_cfg_sInitialLatency__read = 1'd1 ;

  // action method cfg_sInitialLatency_clear
  assign RDY_cfg_sInitialLatency_clear = 1'd1 ;
  assign CAN_FIRE_cfg_sInitialLatency_clear = 1'd1 ;
  assign WILL_FIRE_cfg_sInitialLatency_clear = EN_cfg_sInitialLatency_clear ;

  // action method cfg_sReserved_clear
  assign RDY_cfg_sReserved_clear = 1'd1 ;
  assign CAN_FIRE_cfg_sReserved_clear = 1'd1 ;
  assign WILL_FIRE_cfg_sReserved_clear = EN_cfg_sReserved_clear ;

  // value method cfg_sDriveStrength__read
  assign cfg_sDriveStrength__read = reg_CFG_sig_DriveStrength_r ;
  assign RDY_cfg_sDriveStrength__read = 1'd1 ;

  // action method cfg_sDriveStrength_clear
  assign RDY_cfg_sDriveStrength_clear = 1'd1 ;
  assign CAN_FIRE_cfg_sDriveStrength_clear = 1'd1 ;
  assign WILL_FIRE_cfg_sDriveStrength_clear = EN_cfg_sDriveStrength_clear ;

  // value method cfg_sDeepPowerDown__read
  assign cfg_sDeepPowerDown__read = reg_CFG_sig_DeepPowerDown_r ;
  assign RDY_cfg_sDeepPowerDown__read = 1'd1 ;

  // action method cfg_sDeepPowerDown_clear
  assign RDY_cfg_sDeepPowerDown_clear = 1'd1 ;
  assign CAN_FIRE_cfg_sDeepPowerDown_clear = 1'd1 ;
  assign WILL_FIRE_cfg_sDeepPowerDown_clear = EN_cfg_sDeepPowerDown_clear ;

  // value method cfg_sBurstEnable__read
  assign cfg_sBurstEnable__read = reg_CFG_sig_BurstEnable_r ;
  assign RDY_cfg_sBurstEnable__read = 1'd1 ;

  // action method cfg_sBurstEnable_clear
  assign RDY_cfg_sBurstEnable_clear = 1'd1 ;
  assign CAN_FIRE_cfg_sBurstEnable_clear = 1'd1 ;
  assign WILL_FIRE_cfg_sBurstEnable_clear = EN_cfg_sBurstEnable_clear ;

  // value method cfg_sUltraDeepPowerDown__read
  assign cfg_sUltraDeepPowerDown__read = reg_CFG_sig_UltraDeepPowerDown_r ;
  assign RDY_cfg_sUltraDeepPowerDown__read = 1'd1 ;

  // action method cfg_sUltraDeepPowerDown_clear
  assign RDY_cfg_sUltraDeepPowerDown_clear = 1'd1 ;
  assign CAN_FIRE_cfg_sUltraDeepPowerDown_clear = 1'd1 ;
  assign WILL_FIRE_cfg_sUltraDeepPowerDown_clear =
	     EN_cfg_sUltraDeepPowerDown_clear ;

  // value method cfg_value
  assign cfg_value =
	     { 46'd0,
	       reg_CFG_sig_UltraDeepPowerDown_r,
	       reg_CFG_sig_BurstEnable_r,
	       reg_CFG_sig_DeepPowerDown_r,
	       reg_CFG_sig_DriveStrength_r,
	       4'd0,
	       reg_CFG_sig_InitialLatency_r,
	       reg_CFG_sig_FixedLatency_r,
	       reg_CFG_sig_HybridBurstEnable_r,
	       reg_CFG_sig_BurstLength_r } ;
  assign RDY_cfg_value = 1'd1 ;

  // action method xspi_status_swip__write
  assign RDY_xspi_status_swip__write = 1'd1 ;
  assign CAN_FIRE_xspi_status_swip__write = 1'd1 ;
  assign WILL_FIRE_xspi_status_swip__write = EN_xspi_status_swip__write ;

  // action method xspi_status_swip_clear
  assign RDY_xspi_status_swip_clear = 1'd1 ;
  assign CAN_FIRE_xspi_status_swip_clear = 1'd1 ;
  assign WILL_FIRE_xspi_status_swip_clear = EN_xspi_status_swip_clear ;

  // value method xspi_status_value
  assign xspi_status_value = 64'd0 ;
  assign RDY_xspi_status_value = 1'd1 ;

  // value method xspi_control_suse_xspi_clk__read
  assign xspi_control_suse_xspi_clk__read =
	     reg_xspi_control_sig_use_xspi_clk_r ;
  assign RDY_xspi_control_suse_xspi_clk__read = 1'd1 ;

  // action method xspi_control_suse_xspi_clk_clear
  assign RDY_xspi_control_suse_xspi_clk_clear = 1'd1 ;
  assign CAN_FIRE_xspi_control_suse_xspi_clk_clear = 1'd1 ;
  assign WILL_FIRE_xspi_control_suse_xspi_clk_clear =
	     EN_xspi_control_suse_xspi_clk_clear ;

  // value method xspi_control_sinterrupt_enable__read
  assign xspi_control_sinterrupt_enable__read =
	     reg_xspi_control_sig_interrupt_enable_r ;
  assign RDY_xspi_control_sinterrupt_enable__read = 1'd1 ;

  // action method xspi_control_sinterrupt_enable_clear
  assign RDY_xspi_control_sinterrupt_enable_clear = 1'd1 ;
  assign CAN_FIRE_xspi_control_sinterrupt_enable_clear = 1'd1 ;
  assign WILL_FIRE_xspi_control_sinterrupt_enable_clear =
	     EN_xspi_control_sinterrupt_enable_clear ;

  // value method xspi_control_value
  assign xspi_control_value =
	     { 62'd0,
	       reg_xspi_control_sig_interrupt_enable_r,
	       reg_xspi_control_sig_use_xspi_clk_r } ;
  assign RDY_xspi_control_value = 1'd1 ;

  // action method xspi_rates_scmd_rate__write
  assign RDY_xspi_rates_scmd_rate__write = 1'd1 ;
  assign CAN_FIRE_xspi_rates_scmd_rate__write = 1'd1 ;
  assign WILL_FIRE_xspi_rates_scmd_rate__write =
	     EN_xspi_rates_scmd_rate__write ;

  // value method xspi_rates_scmd_rate__read
  assign xspi_rates_scmd_rate__read = reg_xspi_rates_sig_cmd_rate_r ;
  assign RDY_xspi_rates_scmd_rate__read = 1'd1 ;

  // action method xspi_rates_scmd_rate_clear
  assign RDY_xspi_rates_scmd_rate_clear = 1'd1 ;
  assign CAN_FIRE_xspi_rates_scmd_rate_clear = 1'd1 ;
  assign WILL_FIRE_xspi_rates_scmd_rate_clear =
	     EN_xspi_rates_scmd_rate_clear ;

  // action method xspi_rates_saddr_rate__write
  assign RDY_xspi_rates_saddr_rate__write = 1'd1 ;
  assign CAN_FIRE_xspi_rates_saddr_rate__write = 1'd1 ;
  assign WILL_FIRE_xspi_rates_saddr_rate__write =
	     EN_xspi_rates_saddr_rate__write ;

  // value method xspi_rates_saddr_rate__read
  assign xspi_rates_saddr_rate__read = reg_xspi_rates_sig_addr_rate_r ;
  assign RDY_xspi_rates_saddr_rate__read = 1'd1 ;

  // action method xspi_rates_saddr_rate_clear
  assign RDY_xspi_rates_saddr_rate_clear = 1'd1 ;
  assign CAN_FIRE_xspi_rates_saddr_rate_clear = 1'd1 ;
  assign WILL_FIRE_xspi_rates_saddr_rate_clear =
	     EN_xspi_rates_saddr_rate_clear ;

  // action method xspi_rates_sdata_rate__write
  assign RDY_xspi_rates_sdata_rate__write = 1'd1 ;
  assign CAN_FIRE_xspi_rates_sdata_rate__write = 1'd1 ;
  assign WILL_FIRE_xspi_rates_sdata_rate__write =
	     EN_xspi_rates_sdata_rate__write ;

  // value method xspi_rates_sdata_rate__read
  assign xspi_rates_sdata_rate__read = reg_xspi_rates_sig_data_rate_r ;
  assign RDY_xspi_rates_sdata_rate__read = 1'd1 ;

  // action method xspi_rates_sdata_rate_clear
  assign RDY_xspi_rates_sdata_rate_clear = 1'd1 ;
  assign CAN_FIRE_xspi_rates_sdata_rate_clear = 1'd1 ;
  assign WILL_FIRE_xspi_rates_sdata_rate_clear =
	     EN_xspi_rates_sdata_rate_clear ;

  // value method xspi_rates_value
  assign xspi_rates_value =
	     { 40'd0,
	       reg_xspi_rates_sig_data_rate_r,
	       reg_xspi_rates_sig_addr_rate_r,
	       reg_xspi_rates_sig_cmd_rate_r } ;
  assign RDY_xspi_rates_value = 1'd1 ;

  // action method interrupt_status_saxi_resp__write
  assign RDY_interrupt_status_saxi_resp__write = 1'd1 ;
  assign CAN_FIRE_interrupt_status_saxi_resp__write = 1'd1 ;
  assign WILL_FIRE_interrupt_status_saxi_resp__write =
	     EN_interrupt_status_saxi_resp__write ;

  // value method interrupt_status_saxi_resp__read
  assign interrupt_status_saxi_resp__read =
	     reg_interrupt_status_sig_axi_resp_r ;
  assign RDY_interrupt_status_saxi_resp__read = 1'd1 ;

  // action method interrupt_status_saxi_resp_clear
  assign RDY_interrupt_status_saxi_resp_clear = 1'd1 ;
  assign CAN_FIRE_interrupt_status_saxi_resp_clear = 1'd1 ;
  assign WILL_FIRE_interrupt_status_saxi_resp_clear =
	     EN_interrupt_status_saxi_resp_clear ;

  // action method interrupt_status_sread_underflow__write
  assign RDY_interrupt_status_sread_underflow__write = 1'd1 ;
  assign CAN_FIRE_interrupt_status_sread_underflow__write = 1'd1 ;
  assign WILL_FIRE_interrupt_status_sread_underflow__write =
	     EN_interrupt_status_sread_underflow__write ;

  // value method interrupt_status_sread_underflow__read
  assign interrupt_status_sread_underflow__read =
	     reg_interrupt_status_sig_read_underflow_r ;
  assign RDY_interrupt_status_sread_underflow__read = 1'd1 ;

  // action method interrupt_status_sread_underflow_clear
  assign RDY_interrupt_status_sread_underflow_clear = 1'd1 ;
  assign CAN_FIRE_interrupt_status_sread_underflow_clear = 1'd1 ;
  assign WILL_FIRE_interrupt_status_sread_underflow_clear =
	     EN_interrupt_status_sread_underflow_clear ;

  // action method interrupt_status_swrite_overflow__write
  assign RDY_interrupt_status_swrite_overflow__write = 1'd1 ;
  assign CAN_FIRE_interrupt_status_swrite_overflow__write = 1'd1 ;
  assign WILL_FIRE_interrupt_status_swrite_overflow__write =
	     EN_interrupt_status_swrite_overflow__write ;

  // value method interrupt_status_swrite_overflow__read
  assign interrupt_status_swrite_overflow__read =
	     reg_interrupt_status_sig_write_overflow_r ;
  assign RDY_interrupt_status_swrite_overflow__read = 1'd1 ;

  // action method interrupt_status_swrite_overflow_clear
  assign RDY_interrupt_status_swrite_overflow_clear = 1'd1 ;
  assign CAN_FIRE_interrupt_status_swrite_overflow_clear = 1'd1 ;
  assign WILL_FIRE_interrupt_status_swrite_overflow_clear =
	     EN_interrupt_status_swrite_overflow_clear ;

  // value method interrupt_status_value
  assign interrupt_status_value =
	     { 60'd0,
	       reg_interrupt_status_sig_write_overflow_r,
	       reg_interrupt_status_sig_read_underflow_r,
	       reg_interrupt_status_sig_axi_resp_r } ;
  assign RDY_interrupt_status_value = 1'd1 ;

  // action method write
  assign RDY_write = 1'd1 ;
  assign CAN_FIRE_write = 1'd1 ;
  assign WILL_FIRE_write = EN_write ;

  // actionvalue method read
  always@(read_address or
	  v__h24965 or
	  v__h25147 or
	  v__h25326 or v__h26048 or v__h26152 or v__h26331 or v__h26587)
  begin
    case (read_address)
      6'd0: read = v__h24965;
      6'd8: read = v__h25147;
      6'd16: read = v__h25326;
      6'd24: read = v__h26048;
      6'd32: read = v__h26152;
      6'd40: read = v__h26331;
      6'd48: read = v__h26587;
      default: read = 64'd0;
    endcase
  end
  assign RDY_read = 1'd1 ;
  assign CAN_FIRE_read = 1'd1 ;
  assign WILL_FIRE_read = EN_read ;

  // rule RL_reg_ID0_sig_mgf_id_r_write
  assign CAN_FIRE_RL_reg_ID0_sig_mgf_id_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_ID0_sig_mgf_id_r_write = 1'd1 ;

  // rule RL_reg_ID0_sig_devid0_r_write
  assign CAN_FIRE_RL_reg_ID0_sig_devid0_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_ID0_sig_devid0_r_write = 1'd1 ;

  // rule RL_reg_ID1_sig_dev_type_r_write
  assign CAN_FIRE_RL_reg_ID1_sig_dev_type_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_ID1_sig_dev_type_r_write = 1'd1 ;

  // rule RL_reg_ID1_sig_devid1_r_write
  assign CAN_FIRE_RL_reg_ID1_sig_devid1_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_ID1_sig_devid1_r_write = 1'd1 ;

  // rule RL_reg_CFG_sig_BurstLength_r_write
  assign CAN_FIRE_RL_reg_CFG_sig_BurstLength_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_CFG_sig_BurstLength_r_write = 1'd1 ;

  // rule RL_reg_CFG_sig_HybridBurstEnable_r_write
  assign CAN_FIRE_RL_reg_CFG_sig_HybridBurstEnable_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_CFG_sig_HybridBurstEnable_r_write = 1'd1 ;

  // rule RL_reg_CFG_sig_FixedLatency_r_write
  assign CAN_FIRE_RL_reg_CFG_sig_FixedLatency_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_CFG_sig_FixedLatency_r_write = 1'd1 ;

  // rule RL_reg_CFG_sig_InitialLatency_r_write
  assign CAN_FIRE_RL_reg_CFG_sig_InitialLatency_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_CFG_sig_InitialLatency_r_write = 1'd1 ;

  // rule RL_reg_CFG_sig_Reserved_r_write
  assign CAN_FIRE_RL_reg_CFG_sig_Reserved_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_CFG_sig_Reserved_r_write = 1'd1 ;

  // rule RL_reg_CFG_sig_DriveStrength_r_write
  assign CAN_FIRE_RL_reg_CFG_sig_DriveStrength_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_CFG_sig_DriveStrength_r_write = 1'd1 ;

  // rule RL_reg_CFG_sig_DeepPowerDown_r_write
  assign CAN_FIRE_RL_reg_CFG_sig_DeepPowerDown_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_CFG_sig_DeepPowerDown_r_write = 1'd1 ;

  // rule RL_reg_CFG_sig_BurstEnable_r_write
  assign CAN_FIRE_RL_reg_CFG_sig_BurstEnable_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_CFG_sig_BurstEnable_r_write = 1'd1 ;

  // rule RL_reg_CFG_sig_UltraDeepPowerDown_r_write
  assign CAN_FIRE_RL_reg_CFG_sig_UltraDeepPowerDown_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_CFG_sig_UltraDeepPowerDown_r_write = 1'd1 ;

  // rule RL_reg_xspi_status_sig_wip_r_write
  assign CAN_FIRE_RL_reg_xspi_status_sig_wip_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_xspi_status_sig_wip_r_write = 1'd1 ;

  // rule RL_reg_xspi_control_sig_use_xspi_clk_r_write
  assign CAN_FIRE_RL_reg_xspi_control_sig_use_xspi_clk_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_xspi_control_sig_use_xspi_clk_r_write = 1'd1 ;

  // rule RL_reg_xspi_control_sig_interrupt_enable_r_write
  assign CAN_FIRE_RL_reg_xspi_control_sig_interrupt_enable_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_xspi_control_sig_interrupt_enable_r_write = 1'd1 ;

  // rule RL_reg_xspi_rates_sig_cmd_rate_r_write
  assign CAN_FIRE_RL_reg_xspi_rates_sig_cmd_rate_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_xspi_rates_sig_cmd_rate_r_write = 1'd1 ;

  // rule RL_reg_xspi_rates_sig_addr_rate_r_write
  assign CAN_FIRE_RL_reg_xspi_rates_sig_addr_rate_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_xspi_rates_sig_addr_rate_r_write = 1'd1 ;

  // rule RL_reg_xspi_rates_sig_data_rate_r_write
  assign CAN_FIRE_RL_reg_xspi_rates_sig_data_rate_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_xspi_rates_sig_data_rate_r_write = 1'd1 ;

  // rule RL_reg_interrupt_status_sig_axi_resp_r_write
  assign CAN_FIRE_RL_reg_interrupt_status_sig_axi_resp_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_interrupt_status_sig_axi_resp_r_write = 1'd1 ;

  // rule RL_reg_interrupt_status_sig_read_underflow_r_write
  assign CAN_FIRE_RL_reg_interrupt_status_sig_read_underflow_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_interrupt_status_sig_read_underflow_r_write = 1'd1 ;

  // rule RL_reg_interrupt_status_sig_write_overflow_r_write
  assign CAN_FIRE_RL_reg_interrupt_status_sig_write_overflow_r_write = 1'd1 ;
  assign WILL_FIRE_RL_reg_interrupt_status_sig_write_overflow_r_write = 1'd1 ;

  // inlined wires
  assign reg_ID0_sig_mgf_id_sw_wdata_wget = { write_data[3:0], x__h24152 } ;
  assign reg_ID0_sig_mgf_id_sw_wdata_whas =
	     EN_write && write_address == 6'd0 ;
  assign reg_ID0_sig_mgf_id_hw_wdata_wget = 4'h0 ;
  assign reg_ID0_sig_mgf_id_hw_wdata_whas = 1'b0 ;
  assign reg_ID0_sig_mgf_id_r_incr_wget = 4'h0 ;
  assign reg_ID0_sig_mgf_id_r_incr_whas = 1'b0 ;
  assign reg_ID0_sig_mgf_id_r_decr_wget = 4'h0 ;
  assign reg_ID0_sig_mgf_id_r_decr_whas = 1'b0 ;
  assign reg_ID0_sig_devid0_sw_wdata_wget = { write_data[15:4], x__h23754 } ;
  assign reg_ID0_sig_devid0_sw_wdata_whas = reg_ID0_sig_mgf_id_sw_wdata_whas ;
  assign reg_ID0_sig_devid0_hw_wdata_wget = 12'h0 ;
  assign reg_ID0_sig_devid0_hw_wdata_whas = 1'b0 ;
  assign reg_ID0_sig_devid0_r_incr_wget = 12'h0 ;
  assign reg_ID0_sig_devid0_r_incr_whas = 1'b0 ;
  assign reg_ID0_sig_devid0_r_decr_wget = 12'h0 ;
  assign reg_ID0_sig_devid0_r_decr_whas = 1'b0 ;
  assign reg_ID1_sig_dev_type_sw_wdata_wget =
	     reg_ID0_sig_mgf_id_sw_wdata_wget ;
  assign reg_ID1_sig_dev_type_sw_wdata_whas =
	     EN_write && write_address == 6'd8 ;
  assign reg_ID1_sig_dev_type_hw_wdata_wget = 4'h0 ;
  assign reg_ID1_sig_dev_type_hw_wdata_whas = 1'b0 ;
  assign reg_ID1_sig_dev_type_r_incr_wget = 4'h0 ;
  assign reg_ID1_sig_dev_type_r_incr_whas = 1'b0 ;
  assign reg_ID1_sig_dev_type_r_decr_wget = 4'h0 ;
  assign reg_ID1_sig_dev_type_r_decr_whas = 1'b0 ;
  assign reg_ID1_sig_devid1_sw_wdata_wget = reg_ID0_sig_devid0_sw_wdata_wget ;
  assign reg_ID1_sig_devid1_sw_wdata_whas =
	     reg_ID1_sig_dev_type_sw_wdata_whas ;
  assign reg_ID1_sig_devid1_hw_wdata_wget = 12'h0 ;
  assign reg_ID1_sig_devid1_hw_wdata_whas = 1'b0 ;
  assign reg_ID1_sig_devid1_r_incr_wget = 12'h0 ;
  assign reg_ID1_sig_devid1_r_incr_whas = 1'b0 ;
  assign reg_ID1_sig_devid1_r_decr_wget = 12'h0 ;
  assign reg_ID1_sig_devid1_r_decr_whas = 1'b0 ;
  assign reg_CFG_sig_BurstLength_sw_wdata_wget =
	     { write_data[1:0], x__h24068 } ;
  assign reg_CFG_sig_BurstLength_sw_wdata_whas =
	     EN_write && write_address == 6'd16 ;
  assign reg_CFG_sig_BurstLength_hw_wdata_wget = 2'h0 ;
  assign reg_CFG_sig_BurstLength_hw_wdata_whas = 1'b0 ;
  assign reg_CFG_sig_BurstLength_r_incr_wget = 2'h0 ;
  assign reg_CFG_sig_BurstLength_r_incr_whas = 1'b0 ;
  assign reg_CFG_sig_BurstLength_r_decr_wget = 2'h0 ;
  assign reg_CFG_sig_BurstLength_r_decr_whas = 1'b0 ;
  assign reg_CFG_sig_HybridBurstEnable_sw_wdata_wget = 2'h0 ;
  assign reg_CFG_sig_HybridBurstEnable_sw_wdata_whas = 1'b0 ;
  assign reg_CFG_sig_HybridBurstEnable_hw_wdata_wget = 1'b0 ;
  assign reg_CFG_sig_HybridBurstEnable_hw_wdata_whas = 1'b0 ;
  assign reg_CFG_sig_HybridBurstEnable_r_incr_wget = 1'b0 ;
  assign reg_CFG_sig_HybridBurstEnable_r_incr_whas = 1'b0 ;
  assign reg_CFG_sig_HybridBurstEnable_r_decr_wget = 1'b0 ;
  assign reg_CFG_sig_HybridBurstEnable_r_decr_whas = 1'b0 ;
  assign reg_CFG_sig_FixedLatency_sw_wdata_wget = 2'h0 ;
  assign reg_CFG_sig_FixedLatency_sw_wdata_whas = 1'b0 ;
  assign reg_CFG_sig_FixedLatency_hw_wdata_wget = 1'b0 ;
  assign reg_CFG_sig_FixedLatency_hw_wdata_whas = 1'b0 ;
  assign reg_CFG_sig_FixedLatency_r_incr_wget = 1'b0 ;
  assign reg_CFG_sig_FixedLatency_r_incr_whas = 1'b0 ;
  assign reg_CFG_sig_FixedLatency_r_decr_wget = 1'b0 ;
  assign reg_CFG_sig_FixedLatency_r_decr_whas = 1'b0 ;
  assign reg_CFG_sig_InitialLatency_sw_wdata_wget =
	     { write_data[7:4], x__h24152 } ;
  assign reg_CFG_sig_InitialLatency_sw_wdata_whas =
	     reg_CFG_sig_BurstLength_sw_wdata_whas ;
  assign reg_CFG_sig_InitialLatency_hw_wdata_wget = 4'h0 ;
  assign reg_CFG_sig_InitialLatency_hw_wdata_whas = 1'b0 ;
  assign reg_CFG_sig_InitialLatency_r_incr_wget = 4'h0 ;
  assign reg_CFG_sig_InitialLatency_r_incr_whas = 1'b0 ;
  assign reg_CFG_sig_InitialLatency_r_decr_wget = 4'h0 ;
  assign reg_CFG_sig_InitialLatency_r_decr_whas = 1'b0 ;
  assign reg_CFG_sig_Reserved_sw_wdata_wget = 8'h0 ;
  assign reg_CFG_sig_Reserved_sw_wdata_whas = 1'b0 ;
  assign reg_CFG_sig_Reserved_hw_wdata_wget = 4'h0 ;
  assign reg_CFG_sig_Reserved_hw_wdata_whas = 1'b0 ;
  assign reg_CFG_sig_Reserved_r_incr_wget = 4'h0 ;
  assign reg_CFG_sig_Reserved_r_incr_whas = 1'b0 ;
  assign reg_CFG_sig_Reserved_r_decr_wget = 4'h0 ;
  assign reg_CFG_sig_Reserved_r_decr_whas = 1'b0 ;
  assign reg_CFG_sig_DriveStrength_sw_wdata_wget = 6'h0 ;
  assign reg_CFG_sig_DriveStrength_sw_wdata_whas = 1'b0 ;
  assign reg_CFG_sig_DriveStrength_hw_wdata_wget = 3'h0 ;
  assign reg_CFG_sig_DriveStrength_hw_wdata_whas = 1'b0 ;
  assign reg_CFG_sig_DriveStrength_r_incr_wget = 3'h0 ;
  assign reg_CFG_sig_DriveStrength_r_incr_whas = 1'b0 ;
  assign reg_CFG_sig_DriveStrength_r_decr_wget = 3'h0 ;
  assign reg_CFG_sig_DriveStrength_r_decr_whas = 1'b0 ;
  assign reg_CFG_sig_DeepPowerDown_sw_wdata_wget =
	     { write_data[15], write_wstrb[1] } ;
  assign reg_CFG_sig_DeepPowerDown_sw_wdata_whas =
	     reg_CFG_sig_BurstLength_sw_wdata_whas ;
  assign reg_CFG_sig_DeepPowerDown_hw_wdata_wget = 1'b0 ;
  assign reg_CFG_sig_DeepPowerDown_hw_wdata_whas = 1'b0 ;
  assign reg_CFG_sig_DeepPowerDown_r_incr_wget = 1'b0 ;
  assign reg_CFG_sig_DeepPowerDown_r_incr_whas = 1'b0 ;
  assign reg_CFG_sig_DeepPowerDown_r_decr_wget = 1'b0 ;
  assign reg_CFG_sig_DeepPowerDown_r_decr_whas = 1'b0 ;
  assign reg_CFG_sig_BurstEnable_sw_wdata_wget =
	     { write_data[16], write_wstrb[2] } ;
  assign reg_CFG_sig_BurstEnable_sw_wdata_whas =
	     reg_CFG_sig_BurstLength_sw_wdata_whas ;
  assign reg_CFG_sig_BurstEnable_hw_wdata_wget = 1'b0 ;
  assign reg_CFG_sig_BurstEnable_hw_wdata_whas = 1'b0 ;
  assign reg_CFG_sig_BurstEnable_r_incr_wget = 1'b0 ;
  assign reg_CFG_sig_BurstEnable_r_incr_whas = 1'b0 ;
  assign reg_CFG_sig_BurstEnable_r_decr_wget = 1'b0 ;
  assign reg_CFG_sig_BurstEnable_r_decr_whas = 1'b0 ;
  assign reg_CFG_sig_UltraDeepPowerDown_sw_wdata_wget =
	     { write_data[17], write_wstrb[2] } ;
  assign reg_CFG_sig_UltraDeepPowerDown_sw_wdata_whas =
	     reg_CFG_sig_BurstLength_sw_wdata_whas ;
  assign reg_CFG_sig_UltraDeepPowerDown_hw_wdata_wget = 1'b0 ;
  assign reg_CFG_sig_UltraDeepPowerDown_hw_wdata_whas = 1'b0 ;
  assign reg_CFG_sig_UltraDeepPowerDown_r_incr_wget = 1'b0 ;
  assign reg_CFG_sig_UltraDeepPowerDown_r_incr_whas = 1'b0 ;
  assign reg_CFG_sig_UltraDeepPowerDown_r_decr_wget = 1'b0 ;
  assign reg_CFG_sig_UltraDeepPowerDown_r_decr_whas = 1'b0 ;
  assign reg_xspi_status_sig_wip_sw_wdata_wget = 2'h0 ;
  assign reg_xspi_status_sig_wip_sw_wdata_whas = 1'b0 ;
  assign reg_xspi_status_sig_wip_hw_wdata_wget =
	     xspi_status_swip__write_data ;
  assign reg_xspi_status_sig_wip_hw_wdata_whas = EN_xspi_status_swip__write ;
  assign reg_xspi_status_sig_wip_r_incr_wget = 1'b0 ;
  assign reg_xspi_status_sig_wip_r_incr_whas = 1'b0 ;
  assign reg_xspi_status_sig_wip_r_decr_wget = 1'b0 ;
  assign reg_xspi_status_sig_wip_r_decr_whas = 1'b0 ;
  assign reg_xspi_control_sig_use_xspi_clk_sw_wdata_wget =
	     { write_data[0], write_wstrb[0] } ;
  assign reg_xspi_control_sig_use_xspi_clk_sw_wdata_whas =
	     EN_write && write_address == 6'd32 ;
  assign reg_xspi_control_sig_use_xspi_clk_hw_wdata_wget = 1'b0 ;
  assign reg_xspi_control_sig_use_xspi_clk_hw_wdata_whas = 1'b0 ;
  assign reg_xspi_control_sig_use_xspi_clk_r_incr_wget = 1'b0 ;
  assign reg_xspi_control_sig_use_xspi_clk_r_incr_whas = 1'b0 ;
  assign reg_xspi_control_sig_use_xspi_clk_r_decr_wget = 1'b0 ;
  assign reg_xspi_control_sig_use_xspi_clk_r_decr_whas = 1'b0 ;
  assign reg_xspi_control_sig_interrupt_enable_sw_wdata_wget =
	     { write_data[1], write_wstrb[0] } ;
  assign reg_xspi_control_sig_interrupt_enable_sw_wdata_whas =
	     reg_xspi_control_sig_use_xspi_clk_sw_wdata_whas ;
  assign reg_xspi_control_sig_interrupt_enable_hw_wdata_wget = 1'b0 ;
  assign reg_xspi_control_sig_interrupt_enable_hw_wdata_whas = 1'b0 ;
  assign reg_xspi_control_sig_interrupt_enable_r_incr_wget = 1'b0 ;
  assign reg_xspi_control_sig_interrupt_enable_r_incr_whas = 1'b0 ;
  assign reg_xspi_control_sig_interrupt_enable_r_decr_wget = 1'b0 ;
  assign reg_xspi_control_sig_interrupt_enable_r_decr_whas = 1'b0 ;
  assign reg_xspi_rates_sig_cmd_rate_sw_wdata_wget =
	     { write_data[7:0], x__h24742 } ;
  assign reg_xspi_rates_sig_cmd_rate_sw_wdata_whas =
	     EN_write && write_address == 6'd40 ;
  assign reg_xspi_rates_sig_cmd_rate_hw_wdata_wget =
	     xspi_rates_scmd_rate__write_data ;
  assign reg_xspi_rates_sig_cmd_rate_hw_wdata_whas =
	     EN_xspi_rates_scmd_rate__write ;
  assign reg_xspi_rates_sig_cmd_rate_r_incr_wget = 8'h0 ;
  assign reg_xspi_rates_sig_cmd_rate_r_incr_whas = 1'b0 ;
  assign reg_xspi_rates_sig_cmd_rate_r_decr_wget = 8'h0 ;
  assign reg_xspi_rates_sig_cmd_rate_r_decr_whas = 1'b0 ;
  assign reg_xspi_rates_sig_addr_rate_sw_wdata_wget =
	     { write_data[15:8], x__h24826 } ;
  assign reg_xspi_rates_sig_addr_rate_sw_wdata_whas =
	     reg_xspi_rates_sig_cmd_rate_sw_wdata_whas ;
  assign reg_xspi_rates_sig_addr_rate_hw_wdata_wget =
	     xspi_rates_saddr_rate__write_data ;
  assign reg_xspi_rates_sig_addr_rate_hw_wdata_whas =
	     EN_xspi_rates_saddr_rate__write ;
  assign reg_xspi_rates_sig_addr_rate_r_incr_wget = 8'h0 ;
  assign reg_xspi_rates_sig_addr_rate_r_incr_whas = 1'b0 ;
  assign reg_xspi_rates_sig_addr_rate_r_decr_wget = 8'h0 ;
  assign reg_xspi_rates_sig_addr_rate_r_decr_whas = 1'b0 ;
  assign reg_xspi_rates_sig_data_rate_sw_wdata_wget =
	     { write_data[23:16], x__h24897 } ;
  assign reg_xspi_rates_sig_data_rate_sw_wdata_whas =
	     reg_xspi_rates_sig_cmd_rate_sw_wdata_whas ;
  assign reg_xspi_rates_sig_data_rate_hw_wdata_wget =
	     xspi_rates_sdata_rate__write_data ;
  assign reg_xspi_rates_sig_data_rate_hw_wdata_whas =
	     EN_xspi_rates_sdata_rate__write ;
  assign reg_xspi_rates_sig_data_rate_r_incr_wget = 8'h0 ;
  assign reg_xspi_rates_sig_data_rate_r_incr_whas = 1'b0 ;
  assign reg_xspi_rates_sig_data_rate_r_decr_wget = 8'h0 ;
  assign reg_xspi_rates_sig_data_rate_r_decr_whas = 1'b0 ;
  assign reg_interrupt_status_sig_axi_resp_sw_wdata_wget = 4'h0 ;
  assign reg_interrupt_status_sig_axi_resp_sw_wdata_whas = 1'b0 ;
  assign reg_interrupt_status_sig_axi_resp_hw_wdata_wget =
	     interrupt_status_saxi_resp__write_data ;
  assign reg_interrupt_status_sig_axi_resp_hw_wdata_whas =
	     EN_interrupt_status_saxi_resp__write ;
  assign reg_interrupt_status_sig_axi_resp_r_incr_wget = 2'h0 ;
  assign reg_interrupt_status_sig_axi_resp_r_incr_whas = 1'b0 ;
  assign reg_interrupt_status_sig_axi_resp_r_decr_wget = 2'h0 ;
  assign reg_interrupt_status_sig_axi_resp_r_decr_whas = 1'b0 ;
  assign reg_interrupt_status_sig_read_underflow_sw_wdata_wget = 2'h0 ;
  assign reg_interrupt_status_sig_read_underflow_sw_wdata_whas = 1'b0 ;
  assign reg_interrupt_status_sig_read_underflow_hw_wdata_wget =
	     interrupt_status_sread_underflow__write_data ;
  assign reg_interrupt_status_sig_read_underflow_hw_wdata_whas =
	     EN_interrupt_status_sread_underflow__write ;
  assign reg_interrupt_status_sig_read_underflow_r_incr_wget = 1'b0 ;
  assign reg_interrupt_status_sig_read_underflow_r_incr_whas = 1'b0 ;
  assign reg_interrupt_status_sig_read_underflow_r_decr_wget = 1'b0 ;
  assign reg_interrupt_status_sig_read_underflow_r_decr_whas = 1'b0 ;
  assign reg_interrupt_status_sig_write_overflow_sw_wdata_wget = 2'h0 ;
  assign reg_interrupt_status_sig_write_overflow_sw_wdata_whas = 1'b0 ;
  assign reg_interrupt_status_sig_write_overflow_hw_wdata_wget =
	     interrupt_status_swrite_overflow__write_data ;
  assign reg_interrupt_status_sig_write_overflow_hw_wdata_whas =
	     EN_interrupt_status_swrite_overflow__write ;
  assign reg_interrupt_status_sig_write_overflow_r_incr_wget = 1'b0 ;
  assign reg_interrupt_status_sig_write_overflow_r_incr_whas = 1'b0 ;
  assign reg_interrupt_status_sig_write_overflow_r_decr_wget = 1'b0 ;
  assign reg_interrupt_status_sig_write_overflow_r_decr_whas = 1'b0 ;
  assign reg_ID0_sig_mgf_id_pw_set_whas = 1'b0 ;
  assign reg_ID0_sig_mgf_id_pw_clear_whas = EN_id0_smgf_id_clear ;
  assign reg_ID0_sig_mgf_id_pw_swacc_whas = 1'b0 ;
  assign reg_ID0_sig_mgf_id_pw_swmod_whas = 1'b0 ;
  assign reg_ID0_sig_devid0_pw_set_whas = 1'b0 ;
  assign reg_ID0_sig_devid0_pw_clear_whas = EN_id0_sdevid0_clear ;
  assign reg_ID0_sig_devid0_pw_swacc_whas = 1'b0 ;
  assign reg_ID0_sig_devid0_pw_swmod_whas = 1'b0 ;
  assign reg_ID1_sig_dev_type_pw_set_whas = 1'b0 ;
  assign reg_ID1_sig_dev_type_pw_clear_whas = EN_id1_sdev_type_clear ;
  assign reg_ID1_sig_dev_type_pw_swacc_whas = 1'b0 ;
  assign reg_ID1_sig_dev_type_pw_swmod_whas = 1'b0 ;
  assign reg_ID1_sig_devid1_pw_set_whas = 1'b0 ;
  assign reg_ID1_sig_devid1_pw_clear_whas = EN_id1_sdevid1_clear ;
  assign reg_ID1_sig_devid1_pw_swacc_whas = 1'b0 ;
  assign reg_ID1_sig_devid1_pw_swmod_whas = 1'b0 ;
  assign reg_CFG_sig_BurstLength_pw_set_whas = 1'b0 ;
  assign reg_CFG_sig_BurstLength_pw_clear_whas = EN_cfg_sBurstLength_clear ;
  assign reg_CFG_sig_BurstLength_pw_swacc_whas = 1'b0 ;
  assign reg_CFG_sig_BurstLength_pw_swmod_whas = 1'b0 ;
  assign reg_CFG_sig_HybridBurstEnable_pw_set_whas = 1'b0 ;
  assign reg_CFG_sig_HybridBurstEnable_pw_clear_whas =
	     EN_cfg_sHybridBurstEnable_clear ;
  assign reg_CFG_sig_HybridBurstEnable_pw_swacc_whas = 1'b0 ;
  assign reg_CFG_sig_HybridBurstEnable_pw_swmod_whas = 1'b0 ;
  assign reg_CFG_sig_FixedLatency_pw_set_whas = 1'b0 ;
  assign reg_CFG_sig_FixedLatency_pw_clear_whas = EN_cfg_sFixedLatency_clear ;
  assign reg_CFG_sig_FixedLatency_pw_swacc_whas = 1'b0 ;
  assign reg_CFG_sig_FixedLatency_pw_swmod_whas = 1'b0 ;
  assign reg_CFG_sig_InitialLatency_pw_set_whas = 1'b0 ;
  assign reg_CFG_sig_InitialLatency_pw_clear_whas =
	     EN_cfg_sInitialLatency_clear ;
  assign reg_CFG_sig_InitialLatency_pw_swacc_whas = 1'b0 ;
  assign reg_CFG_sig_InitialLatency_pw_swmod_whas = 1'b0 ;
  assign reg_CFG_sig_Reserved_pw_set_whas = 1'b0 ;
  assign reg_CFG_sig_Reserved_pw_clear_whas = EN_cfg_sReserved_clear ;
  assign reg_CFG_sig_Reserved_pw_swacc_whas = 1'b0 ;
  assign reg_CFG_sig_Reserved_pw_swmod_whas = 1'b0 ;
  assign reg_CFG_sig_DriveStrength_pw_set_whas = 1'b0 ;
  assign reg_CFG_sig_DriveStrength_pw_clear_whas =
	     EN_cfg_sDriveStrength_clear ;
  assign reg_CFG_sig_DriveStrength_pw_swacc_whas = 1'b0 ;
  assign reg_CFG_sig_DriveStrength_pw_swmod_whas = 1'b0 ;
  assign reg_CFG_sig_DeepPowerDown_pw_set_whas = 1'b0 ;
  assign reg_CFG_sig_DeepPowerDown_pw_clear_whas =
	     EN_cfg_sDeepPowerDown_clear ;
  assign reg_CFG_sig_DeepPowerDown_pw_swacc_whas = 1'b0 ;
  assign reg_CFG_sig_DeepPowerDown_pw_swmod_whas = 1'b0 ;
  assign reg_CFG_sig_BurstEnable_pw_set_whas = 1'b0 ;
  assign reg_CFG_sig_BurstEnable_pw_clear_whas = EN_cfg_sBurstEnable_clear ;
  assign reg_CFG_sig_BurstEnable_pw_swacc_whas = 1'b0 ;
  assign reg_CFG_sig_BurstEnable_pw_swmod_whas = 1'b0 ;
  assign reg_CFG_sig_UltraDeepPowerDown_pw_set_whas = 1'b0 ;
  assign reg_CFG_sig_UltraDeepPowerDown_pw_clear_whas =
	     EN_cfg_sUltraDeepPowerDown_clear ;
  assign reg_CFG_sig_UltraDeepPowerDown_pw_swacc_whas = 1'b0 ;
  assign reg_CFG_sig_UltraDeepPowerDown_pw_swmod_whas = 1'b0 ;
  assign reg_xspi_status_sig_wip_pw_set_whas = 1'b0 ;
  assign reg_xspi_status_sig_wip_pw_clear_whas = EN_xspi_status_swip_clear ;
  assign reg_xspi_status_sig_wip_pw_swacc_whas = 1'b0 ;
  assign reg_xspi_status_sig_wip_pw_swmod_whas = 1'b0 ;
  assign reg_xspi_control_sig_use_xspi_clk_pw_set_whas = 1'b0 ;
  assign reg_xspi_control_sig_use_xspi_clk_pw_clear_whas =
	     EN_xspi_control_suse_xspi_clk_clear ;
  assign reg_xspi_control_sig_use_xspi_clk_pw_swacc_whas = 1'b0 ;
  assign reg_xspi_control_sig_use_xspi_clk_pw_swmod_whas = 1'b0 ;
  assign reg_xspi_control_sig_interrupt_enable_pw_set_whas = 1'b0 ;
  assign reg_xspi_control_sig_interrupt_enable_pw_clear_whas =
	     EN_xspi_control_sinterrupt_enable_clear ;
  assign reg_xspi_control_sig_interrupt_enable_pw_swacc_whas = 1'b0 ;
  assign reg_xspi_control_sig_interrupt_enable_pw_swmod_whas = 1'b0 ;
  assign reg_xspi_rates_sig_cmd_rate_pw_set_whas = 1'b0 ;
  assign reg_xspi_rates_sig_cmd_rate_pw_clear_whas =
	     EN_xspi_rates_scmd_rate_clear ;
  assign reg_xspi_rates_sig_cmd_rate_pw_swacc_whas = 1'b0 ;
  assign reg_xspi_rates_sig_cmd_rate_pw_swmod_whas = 1'b0 ;
  assign reg_xspi_rates_sig_addr_rate_pw_set_whas = 1'b0 ;
  assign reg_xspi_rates_sig_addr_rate_pw_clear_whas =
	     EN_xspi_rates_saddr_rate_clear ;
  assign reg_xspi_rates_sig_addr_rate_pw_swacc_whas = 1'b0 ;
  assign reg_xspi_rates_sig_addr_rate_pw_swmod_whas = 1'b0 ;
  assign reg_xspi_rates_sig_data_rate_pw_set_whas = 1'b0 ;
  assign reg_xspi_rates_sig_data_rate_pw_clear_whas =
	     EN_xspi_rates_sdata_rate_clear ;
  assign reg_xspi_rates_sig_data_rate_pw_swacc_whas = 1'b0 ;
  assign reg_xspi_rates_sig_data_rate_pw_swmod_whas = 1'b0 ;
  assign reg_interrupt_status_sig_axi_resp_pw_set_whas = 1'b0 ;
  assign reg_interrupt_status_sig_axi_resp_pw_clear_whas =
	     EN_read && read_address == 6'd48 ||
	     EN_interrupt_status_saxi_resp_clear ;
  assign reg_interrupt_status_sig_axi_resp_pw_swacc_whas = 1'b0 ;
  assign reg_interrupt_status_sig_axi_resp_pw_swmod_whas = 1'b0 ;
  assign reg_interrupt_status_sig_read_underflow_pw_set_whas = 1'b0 ;
  assign reg_interrupt_status_sig_read_underflow_pw_clear_whas =
	     EN_read && read_address == 6'd48 ||
	     EN_interrupt_status_sread_underflow_clear ;
  assign reg_interrupt_status_sig_read_underflow_pw_swacc_whas = 1'b0 ;
  assign reg_interrupt_status_sig_read_underflow_pw_swmod_whas = 1'b0 ;
  assign reg_interrupt_status_sig_write_overflow_pw_set_whas = 1'b0 ;
  assign reg_interrupt_status_sig_write_overflow_pw_clear_whas =
	     EN_read && read_address == 6'd48 ||
	     EN_interrupt_status_swrite_overflow_clear ;
  assign reg_interrupt_status_sig_write_overflow_pw_swacc_whas = 1'b0 ;
  assign reg_interrupt_status_sig_write_overflow_pw_swmod_whas = 1'b0 ;

  // register reg_CFG_sig_BurstEnable_r
  assign reg_CFG_sig_BurstEnable_r_D_IN =
	     !EN_cfg_sBurstEnable_clear &&
	     (reg_CFG_sig_BurstLength_sw_wdata_whas ?
		rr__h6441 :
		reg_CFG_sig_BurstEnable_r) ;
  assign reg_CFG_sig_BurstEnable_r_EN = 1'd1 ;

  // register reg_CFG_sig_BurstLength_r
  assign reg_CFG_sig_BurstLength_r_D_IN =
	     EN_cfg_sBurstLength_clear ?
	       2'd0 :
	       (reg_CFG_sig_BurstLength_sw_wdata_whas ?
		  rr__h2662 :
		  reg_CFG_sig_BurstLength_r) ;
  assign reg_CFG_sig_BurstLength_r_EN = 1'd1 ;

  // register reg_CFG_sig_DeepPowerDown_r
  assign reg_CFG_sig_DeepPowerDown_r_D_IN =
	     !EN_cfg_sDeepPowerDown_clear &&
	     (reg_CFG_sig_BurstLength_sw_wdata_whas ?
		rr__h5900 :
		reg_CFG_sig_DeepPowerDown_r) ;
  assign reg_CFG_sig_DeepPowerDown_r_EN = 1'd1 ;

  // register reg_CFG_sig_DriveStrength_r
  assign reg_CFG_sig_DriveStrength_r_D_IN =
	     EN_cfg_sDriveStrength_clear ?
	       3'd0 :
	       reg_CFG_sig_DriveStrength_r ;
  assign reg_CFG_sig_DriveStrength_r_EN = 1'd1 ;

  // register reg_CFG_sig_FixedLatency_r
  assign reg_CFG_sig_FixedLatency_r_D_IN =
	     !EN_cfg_sFixedLatency_clear && reg_CFG_sig_FixedLatency_r ;
  assign reg_CFG_sig_FixedLatency_r_EN = 1'd1 ;

  // register reg_CFG_sig_HybridBurstEnable_r
  assign reg_CFG_sig_HybridBurstEnable_r_D_IN =
	     !EN_cfg_sHybridBurstEnable_clear &&
	     reg_CFG_sig_HybridBurstEnable_r ;
  assign reg_CFG_sig_HybridBurstEnable_r_EN = 1'd1 ;

  // register reg_CFG_sig_InitialLatency_r
  assign reg_CFG_sig_InitialLatency_r_D_IN =
	     EN_cfg_sInitialLatency_clear ?
	       4'd0 :
	       (reg_CFG_sig_BurstLength_sw_wdata_whas ?
		  rr__h4283 :
		  reg_CFG_sig_InitialLatency_r) ;
  assign reg_CFG_sig_InitialLatency_r_EN = 1'd1 ;

  // register reg_CFG_sig_Reserved_r
  assign reg_CFG_sig_Reserved_r_D_IN =
	     EN_cfg_sReserved_clear ? 4'd0 : reg_CFG_sig_Reserved_r ;
  assign reg_CFG_sig_Reserved_r_EN = 1'd1 ;

  // register reg_CFG_sig_UltraDeepPowerDown_r
  assign reg_CFG_sig_UltraDeepPowerDown_r_D_IN =
	     !EN_cfg_sUltraDeepPowerDown_clear &&
	     (reg_CFG_sig_BurstLength_sw_wdata_whas ?
		rr__h6982 :
		reg_CFG_sig_UltraDeepPowerDown_r) ;
  assign reg_CFG_sig_UltraDeepPowerDown_r_EN = 1'd1 ;

  // register reg_ID0_sig_devid0_r
  assign reg_ID0_sig_devid0_r_D_IN =
	     EN_id0_sdevid0_clear ?
	       12'd0 :
	       (reg_ID0_sig_mgf_id_sw_wdata_whas ?
		  rr__h1029 :
		  reg_ID0_sig_devid0_r) ;
  assign reg_ID0_sig_devid0_r_EN = 1'd1 ;

  // register reg_ID0_sig_mgf_id_r
  assign reg_ID0_sig_mgf_id_r_D_IN =
	     EN_id0_smgf_id_clear ?
	       4'd0 :
	       (reg_ID0_sig_mgf_id_sw_wdata_whas ?
		  rr__h490 :
		  reg_ID0_sig_mgf_id_r) ;
  assign reg_ID0_sig_mgf_id_r_EN = 1'd1 ;

  // register reg_ID1_sig_dev_type_r
  assign reg_ID1_sig_dev_type_r_D_IN =
	     EN_id1_sdev_type_clear ?
	       4'd0 :
	       (reg_ID1_sig_dev_type_sw_wdata_whas ?
		  rr__h1576 :
		  reg_ID1_sig_dev_type_r) ;
  assign reg_ID1_sig_dev_type_r_EN = 1'd1 ;

  // register reg_ID1_sig_devid1_r
  assign reg_ID1_sig_devid1_r_D_IN =
	     EN_id1_sdevid1_clear ?
	       12'd0 :
	       (reg_ID1_sig_dev_type_sw_wdata_whas ?
		  rr__h2115 :
		  reg_ID1_sig_devid1_r) ;
  assign reg_ID1_sig_devid1_r_EN = 1'd1 ;

  // register reg_interrupt_status_sig_axi_resp_r
  assign reg_interrupt_status_sig_axi_resp_r_D_IN =
	     reg_interrupt_status_sig_axi_resp_pw_clear_whas ?
	       2'd0 :
	       (EN_interrupt_status_saxi_resp__write ?
		  interrupt_status_saxi_resp__write_data :
		  reg_interrupt_status_sig_axi_resp_r) ;
  assign reg_interrupt_status_sig_axi_resp_r_EN = 1'd1 ;

  // register reg_interrupt_status_sig_read_underflow_r
  assign reg_interrupt_status_sig_read_underflow_r_D_IN =
	     !reg_interrupt_status_sig_read_underflow_pw_clear_whas &&
	     (EN_interrupt_status_sread_underflow__write ?
		interrupt_status_sread_underflow__write_data :
		reg_interrupt_status_sig_read_underflow_r) ;
  assign reg_interrupt_status_sig_read_underflow_r_EN = 1'd1 ;

  // register reg_interrupt_status_sig_write_overflow_r
  assign reg_interrupt_status_sig_write_overflow_r_D_IN =
	     !reg_interrupt_status_sig_write_overflow_pw_clear_whas &&
	     (EN_interrupt_status_swrite_overflow__write ?
		interrupt_status_swrite_overflow__write_data :
		reg_interrupt_status_sig_write_overflow_r) ;
  assign reg_interrupt_status_sig_write_overflow_r_EN = 1'd1 ;

  // register reg_xspi_control_sig_interrupt_enable_r
  assign reg_xspi_control_sig_interrupt_enable_r_D_IN =
	     !EN_xspi_control_sinterrupt_enable_clear &&
	     (reg_xspi_control_sig_use_xspi_clk_sw_wdata_whas ?
		rr__h8621 :
		reg_xspi_control_sig_interrupt_enable_r) ;
  assign reg_xspi_control_sig_interrupt_enable_r_EN = 1'd1 ;

  // register reg_xspi_control_sig_use_xspi_clk_r
  assign reg_xspi_control_sig_use_xspi_clk_r_D_IN =
	     !EN_xspi_control_suse_xspi_clk_clear &&
	     (reg_xspi_control_sig_use_xspi_clk_sw_wdata_whas ?
		rr__h8080 :
		reg_xspi_control_sig_use_xspi_clk_r) ;
  assign reg_xspi_control_sig_use_xspi_clk_r_EN = 1'd1 ;

  // register reg_xspi_rates_sig_addr_rate_r
  assign reg_xspi_rates_sig_addr_rate_r_D_IN =
	     EN_xspi_rates_saddr_rate_clear ?
	       8'd0 :
	       IF_reg_xspi_rates_sig_addr_rate_sw_wdata_whas__ETC___d510 ;
  assign reg_xspi_rates_sig_addr_rate_r_EN = 1'd1 ;

  // register reg_xspi_rates_sig_cmd_rate_r
  assign reg_xspi_rates_sig_cmd_rate_r_D_IN =
	     EN_xspi_rates_scmd_rate_clear ?
	       8'd0 :
	       IF_reg_xspi_rates_sig_cmd_rate_sw_wdata_whas___ETC___d482 ;
  assign reg_xspi_rates_sig_cmd_rate_r_EN = 1'd1 ;

  // register reg_xspi_rates_sig_data_rate_r
  assign reg_xspi_rates_sig_data_rate_r_D_IN =
	     EN_xspi_rates_sdata_rate_clear ?
	       8'd0 :
	       IF_reg_xspi_rates_sig_data_rate_sw_wdata_whas__ETC___d538 ;
  assign reg_xspi_rates_sig_data_rate_r_EN = 1'd1 ;

  // register reg_xspi_status_sig_wip_r
  assign reg_xspi_status_sig_wip_r_D_IN =
	     !EN_xspi_status_swip_clear &&
	     (EN_xspi_status_swip__write ?
		xspi_status_swip__write_data :
		reg_xspi_status_sig_wip_r) ;
  assign reg_xspi_status_sig_wip_r_EN = 1'd1 ;

  // remaining internal signals
  assign IF_reg_xspi_rates_sig_addr_rate_sw_wdata_whas__ETC___d510 =
	     reg_xspi_rates_sig_cmd_rate_sw_wdata_whas ?
	       rr__h9709 :
	       (EN_xspi_rates_saddr_rate__write ?
		  xspi_rates_saddr_rate__write_data :
		  reg_xspi_rates_sig_addr_rate_r) ;
  assign IF_reg_xspi_rates_sig_cmd_rate_sw_wdata_whas___ETC___d482 =
	     reg_xspi_rates_sig_cmd_rate_sw_wdata_whas ?
	       rr__h9170 :
	       (EN_xspi_rates_scmd_rate__write ?
		  xspi_rates_scmd_rate__write_data :
		  reg_xspi_rates_sig_cmd_rate_r) ;
  assign IF_reg_xspi_rates_sig_data_rate_sw_wdata_whas__ETC___d538 =
	     reg_xspi_rates_sig_cmd_rate_sw_wdata_whas ?
	       rr__h10248 :
	       (EN_xspi_rates_sdata_rate__write ?
		  xspi_rates_sdata_rate__write_data :
		  reg_xspi_rates_sig_data_rate_r) ;
  assign rr__h10248 = x__h10261 | y__h10262 ;
  assign rr__h1029 = x__h1042 | y__h1043 ;
  assign rr__h1576 = x__h1589 | y__h1590 ;
  assign rr__h2115 = x__h2128 | y__h2129 ;
  assign rr__h2662 = x__h2675 | y__h2676 ;
  assign rr__h4283 = x__h4296 | y__h4297 ;
  assign rr__h490 = x__h503 | y__h504 ;
  assign rr__h5900 = x__h5913 | y__h5914 ;
  assign rr__h6441 = x__h6454 | y__h6455 ;
  assign rr__h6982 = x__h6995 | y__h6996 ;
  assign rr__h8080 = x__h8093 | y__h8094 ;
  assign rr__h8621 = x__h8634 | y__h8635 ;
  assign rr__h9170 = x__h9183 | y__h9184 ;
  assign rr__h9709 = x__h9722 | y__h9723 ;
  assign v__h24965 = { 48'd0, reg_ID0_sig_devid0_r, reg_ID0_sig_mgf_id_r } ;
  assign v__h25147 = { 48'd0, reg_ID1_sig_devid1_r, reg_ID1_sig_dev_type_r } ;
  assign v__h25326 =
	     { 46'd0,
	       reg_CFG_sig_UltraDeepPowerDown_r,
	       reg_CFG_sig_BurstEnable_r,
	       reg_CFG_sig_DeepPowerDown_r,
	       reg_CFG_sig_DriveStrength_r,
	       reg_CFG_sig_Reserved_r,
	       reg_CFG_sig_InitialLatency_r,
	       reg_CFG_sig_FixedLatency_r,
	       reg_CFG_sig_HybridBurstEnable_r,
	       reg_CFG_sig_BurstLength_r } ;
  assign v__h26048 = { 63'd0, reg_xspi_status_sig_wip_r } ;
  assign v__h26152 =
	     { 62'd0,
	       reg_xspi_control_sig_interrupt_enable_r,
	       reg_xspi_control_sig_use_xspi_clk_r } ;
  assign v__h26331 =
	     { 40'd0,
	       reg_xspi_rates_sig_data_rate_r,
	       reg_xspi_rates_sig_addr_rate_r,
	       reg_xspi_rates_sig_cmd_rate_r } ;
  assign v__h26587 =
	     { 60'd0,
	       reg_interrupt_status_sig_write_overflow_r,
	       reg_interrupt_status_sig_read_underflow_r,
	       reg_interrupt_status_sig_axi_resp_r } ;
  assign x__h10261 =
	     reg_xspi_rates_sig_data_rate_sw_wdata_wget[15:8] &
	     reg_xspi_rates_sig_data_rate_sw_wdata_wget[7:0] ;
  assign x__h10283 = ~reg_xspi_rates_sig_data_rate_sw_wdata_wget[7:0] ;
  assign x__h1042 =
	     reg_ID0_sig_devid0_sw_wdata_wget[23:12] &
	     reg_ID0_sig_devid0_sw_wdata_wget[11:0] ;
  assign x__h1064 = ~reg_ID0_sig_devid0_sw_wdata_wget[11:0] ;
  assign x__h1589 =
	     reg_ID0_sig_mgf_id_sw_wdata_wget[7:4] &
	     reg_ID0_sig_mgf_id_sw_wdata_wget[3:0] ;
  assign x__h1611 = ~reg_ID0_sig_mgf_id_sw_wdata_wget[3:0] ;
  assign x__h2128 =
	     reg_ID0_sig_devid0_sw_wdata_wget[23:12] &
	     reg_ID0_sig_devid0_sw_wdata_wget[11:0] ;
  assign x__h2150 = ~reg_ID0_sig_devid0_sw_wdata_wget[11:0] ;
  assign x__h23754 =
	     { write_wstrb[1],
	       write_wstrb[1],
	       write_wstrb[1],
	       write_wstrb[1],
	       write_wstrb[1],
	       write_wstrb[1],
	       write_wstrb[1],
	       write_wstrb[1:0],
	       write_wstrb[0],
	       write_wstrb[0],
	       write_wstrb[0] } ;
  assign x__h24068 = {2{write_wstrb[0]}} ;
  assign x__h24152 = { x__h24068, write_wstrb[0], write_wstrb[0] } ;
  assign x__h24742 =
	     { x__h24152,
	       write_wstrb[0],
	       write_wstrb[0],
	       write_wstrb[0],
	       write_wstrb[0] } ;
  assign x__h24826 = {8{write_wstrb[1]}} ;
  assign x__h24897 = {8{write_wstrb[2]}} ;
  assign x__h2675 =
	     reg_CFG_sig_BurstLength_sw_wdata_wget[3:2] &
	     reg_CFG_sig_BurstLength_sw_wdata_wget[1:0] ;
  assign x__h2697 = ~reg_CFG_sig_BurstLength_sw_wdata_wget[1:0] ;
  assign x__h4296 =
	     reg_CFG_sig_InitialLatency_sw_wdata_wget[7:4] &
	     reg_CFG_sig_InitialLatency_sw_wdata_wget[3:0] ;
  assign x__h4318 = ~reg_CFG_sig_InitialLatency_sw_wdata_wget[3:0] ;
  assign x__h503 =
	     reg_ID0_sig_mgf_id_sw_wdata_wget[7:4] &
	     reg_ID0_sig_mgf_id_sw_wdata_wget[3:0] ;
  assign x__h525 = ~reg_ID0_sig_mgf_id_sw_wdata_wget[3:0] ;
  assign x__h5913 =
	     reg_CFG_sig_DeepPowerDown_sw_wdata_wget[1] &
	     reg_CFG_sig_DeepPowerDown_sw_wdata_wget[0] ;
  assign x__h5935 = ~reg_CFG_sig_DeepPowerDown_sw_wdata_wget[0] ;
  assign x__h6454 =
	     reg_CFG_sig_BurstEnable_sw_wdata_wget[1] &
	     reg_CFG_sig_BurstEnable_sw_wdata_wget[0] ;
  assign x__h6476 = ~reg_CFG_sig_BurstEnable_sw_wdata_wget[0] ;
  assign x__h6995 =
	     reg_CFG_sig_UltraDeepPowerDown_sw_wdata_wget[1] &
	     reg_CFG_sig_UltraDeepPowerDown_sw_wdata_wget[0] ;
  assign x__h7017 = ~reg_CFG_sig_UltraDeepPowerDown_sw_wdata_wget[0] ;
  assign x__h8093 =
	     reg_xspi_control_sig_use_xspi_clk_sw_wdata_wget[1] &
	     reg_xspi_control_sig_use_xspi_clk_sw_wdata_wget[0] ;
  assign x__h8115 = ~reg_xspi_control_sig_use_xspi_clk_sw_wdata_wget[0] ;
  assign x__h8634 =
	     reg_xspi_control_sig_interrupt_enable_sw_wdata_wget[1] &
	     reg_xspi_control_sig_interrupt_enable_sw_wdata_wget[0] ;
  assign x__h8656 = ~reg_xspi_control_sig_interrupt_enable_sw_wdata_wget[0] ;
  assign x__h9183 =
	     reg_xspi_rates_sig_cmd_rate_sw_wdata_wget[15:8] &
	     reg_xspi_rates_sig_cmd_rate_sw_wdata_wget[7:0] ;
  assign x__h9205 = ~reg_xspi_rates_sig_cmd_rate_sw_wdata_wget[7:0] ;
  assign x__h9722 =
	     reg_xspi_rates_sig_addr_rate_sw_wdata_wget[15:8] &
	     reg_xspi_rates_sig_addr_rate_sw_wdata_wget[7:0] ;
  assign x__h9744 = ~reg_xspi_rates_sig_addr_rate_sw_wdata_wget[7:0] ;
  assign y__h10262 = x__h10283 & reg_xspi_rates_sig_data_rate_r ;
  assign y__h1043 = x__h1064 & reg_ID0_sig_devid0_r ;
  assign y__h1590 = x__h1611 & reg_ID1_sig_dev_type_r ;
  assign y__h2129 = x__h2150 & reg_ID1_sig_devid1_r ;
  assign y__h2676 = x__h2697 & reg_CFG_sig_BurstLength_r ;
  assign y__h4297 = x__h4318 & reg_CFG_sig_InitialLatency_r ;
  assign y__h504 = x__h525 & reg_ID0_sig_mgf_id_r ;
  assign y__h5914 = x__h5935 & reg_CFG_sig_DeepPowerDown_r ;
  assign y__h6455 = x__h6476 & reg_CFG_sig_BurstEnable_r ;
  assign y__h6996 = x__h7017 & reg_CFG_sig_UltraDeepPowerDown_r ;
  assign y__h8094 = x__h8115 & reg_xspi_control_sig_use_xspi_clk_r ;
  assign y__h8635 = x__h8656 & reg_xspi_control_sig_interrupt_enable_r ;
  assign y__h9184 = x__h9205 & reg_xspi_rates_sig_cmd_rate_r ;
  assign y__h9723 = x__h9744 & reg_xspi_rates_sig_addr_rate_r ;

  // handling of inlined registers

  always@(posedge CLK or `BSV_RESET_EDGE RST_N)
  if (RST_N == `BSV_RESET_VALUE)
    begin
      reg_CFG_sig_BurstEnable_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
      reg_CFG_sig_BurstLength_r <= `BSV_ASSIGNMENT_DELAY 2'd2;
      reg_CFG_sig_DeepPowerDown_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
      reg_CFG_sig_DriveStrength_r <= `BSV_ASSIGNMENT_DELAY 3'd3;
      reg_CFG_sig_FixedLatency_r <= `BSV_ASSIGNMENT_DELAY 1'd1;
      reg_CFG_sig_HybridBurstEnable_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
      reg_CFG_sig_InitialLatency_r <= `BSV_ASSIGNMENT_DELAY 4'd8;
      reg_CFG_sig_Reserved_r <= `BSV_ASSIGNMENT_DELAY 4'd1;
      reg_CFG_sig_UltraDeepPowerDown_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
      reg_ID0_sig_devid0_r <= `BSV_ASSIGNMENT_DELAY 12'd0;
      reg_ID0_sig_mgf_id_r <= `BSV_ASSIGNMENT_DELAY 4'd2;
      reg_ID1_sig_dev_type_r <= `BSV_ASSIGNMENT_DELAY 4'd0;
      reg_ID1_sig_devid1_r <= `BSV_ASSIGNMENT_DELAY 12'd0;
      reg_interrupt_status_sig_axi_resp_r <= `BSV_ASSIGNMENT_DELAY 2'd0;
      reg_interrupt_status_sig_read_underflow_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
      reg_interrupt_status_sig_write_overflow_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
      reg_xspi_control_sig_interrupt_enable_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
      reg_xspi_control_sig_use_xspi_clk_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
      reg_xspi_rates_sig_addr_rate_r <= `BSV_ASSIGNMENT_DELAY 8'd0;
      reg_xspi_rates_sig_cmd_rate_r <= `BSV_ASSIGNMENT_DELAY 8'd0;
      reg_xspi_rates_sig_data_rate_r <= `BSV_ASSIGNMENT_DELAY 8'd0;
      reg_xspi_status_sig_wip_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
    end
  else
    begin
      if (reg_CFG_sig_BurstEnable_r_EN)
	reg_CFG_sig_BurstEnable_r <= `BSV_ASSIGNMENT_DELAY
	    reg_CFG_sig_BurstEnable_r_D_IN;
      if (reg_CFG_sig_BurstLength_r_EN)
	reg_CFG_sig_BurstLength_r <= `BSV_ASSIGNMENT_DELAY
	    reg_CFG_sig_BurstLength_r_D_IN;
      if (reg_CFG_sig_DeepPowerDown_r_EN)
	reg_CFG_sig_DeepPowerDown_r <= `BSV_ASSIGNMENT_DELAY
	    reg_CFG_sig_DeepPowerDown_r_D_IN;
      if (reg_CFG_sig_DriveStrength_r_EN)
	reg_CFG_sig_DriveStrength_r <= `BSV_ASSIGNMENT_DELAY
	    reg_CFG_sig_DriveStrength_r_D_IN;
      if (reg_CFG_sig_FixedLatency_r_EN)
	reg_CFG_sig_FixedLatency_r <= `BSV_ASSIGNMENT_DELAY
	    reg_CFG_sig_FixedLatency_r_D_IN;
      if (reg_CFG_sig_HybridBurstEnable_r_EN)
	reg_CFG_sig_HybridBurstEnable_r <= `BSV_ASSIGNMENT_DELAY
	    reg_CFG_sig_HybridBurstEnable_r_D_IN;
      if (reg_CFG_sig_InitialLatency_r_EN)
	reg_CFG_sig_InitialLatency_r <= `BSV_ASSIGNMENT_DELAY
	    reg_CFG_sig_InitialLatency_r_D_IN;
      if (reg_CFG_sig_Reserved_r_EN)
	reg_CFG_sig_Reserved_r <= `BSV_ASSIGNMENT_DELAY
	    reg_CFG_sig_Reserved_r_D_IN;
      if (reg_CFG_sig_UltraDeepPowerDown_r_EN)
	reg_CFG_sig_UltraDeepPowerDown_r <= `BSV_ASSIGNMENT_DELAY
	    reg_CFG_sig_UltraDeepPowerDown_r_D_IN;
      if (reg_ID0_sig_devid0_r_EN)
	reg_ID0_sig_devid0_r <= `BSV_ASSIGNMENT_DELAY
	    reg_ID0_sig_devid0_r_D_IN;
      if (reg_ID0_sig_mgf_id_r_EN)
	reg_ID0_sig_mgf_id_r <= `BSV_ASSIGNMENT_DELAY
	    reg_ID0_sig_mgf_id_r_D_IN;
      if (reg_ID1_sig_dev_type_r_EN)
	reg_ID1_sig_dev_type_r <= `BSV_ASSIGNMENT_DELAY
	    reg_ID1_sig_dev_type_r_D_IN;
      if (reg_ID1_sig_devid1_r_EN)
	reg_ID1_sig_devid1_r <= `BSV_ASSIGNMENT_DELAY
	    reg_ID1_sig_devid1_r_D_IN;
      if (reg_interrupt_status_sig_axi_resp_r_EN)
	reg_interrupt_status_sig_axi_resp_r <= `BSV_ASSIGNMENT_DELAY
	    reg_interrupt_status_sig_axi_resp_r_D_IN;
      if (reg_interrupt_status_sig_read_underflow_r_EN)
	reg_interrupt_status_sig_read_underflow_r <= `BSV_ASSIGNMENT_DELAY
	    reg_interrupt_status_sig_read_underflow_r_D_IN;
      if (reg_interrupt_status_sig_write_overflow_r_EN)
	reg_interrupt_status_sig_write_overflow_r <= `BSV_ASSIGNMENT_DELAY
	    reg_interrupt_status_sig_write_overflow_r_D_IN;
      if (reg_xspi_control_sig_interrupt_enable_r_EN)
	reg_xspi_control_sig_interrupt_enable_r <= `BSV_ASSIGNMENT_DELAY
	    reg_xspi_control_sig_interrupt_enable_r_D_IN;
      if (reg_xspi_control_sig_use_xspi_clk_r_EN)
	reg_xspi_control_sig_use_xspi_clk_r <= `BSV_ASSIGNMENT_DELAY
	    reg_xspi_control_sig_use_xspi_clk_r_D_IN;
      if (reg_xspi_rates_sig_addr_rate_r_EN)
	reg_xspi_rates_sig_addr_rate_r <= `BSV_ASSIGNMENT_DELAY
	    reg_xspi_rates_sig_addr_rate_r_D_IN;
      if (reg_xspi_rates_sig_cmd_rate_r_EN)
	reg_xspi_rates_sig_cmd_rate_r <= `BSV_ASSIGNMENT_DELAY
	    reg_xspi_rates_sig_cmd_rate_r_D_IN;
      if (reg_xspi_rates_sig_data_rate_r_EN)
	reg_xspi_rates_sig_data_rate_r <= `BSV_ASSIGNMENT_DELAY
	    reg_xspi_rates_sig_data_rate_r_D_IN;
      if (reg_xspi_status_sig_wip_r_EN)
	reg_xspi_status_sig_wip_r <= `BSV_ASSIGNMENT_DELAY
	    reg_xspi_status_sig_wip_r_D_IN;
    end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    reg_CFG_sig_BurstEnable_r = 1'h0;
    reg_CFG_sig_BurstLength_r = 2'h2;
    reg_CFG_sig_DeepPowerDown_r = 1'h0;
    reg_CFG_sig_DriveStrength_r = 3'h2;
    reg_CFG_sig_FixedLatency_r = 1'h0;
    reg_CFG_sig_HybridBurstEnable_r = 1'h0;
    reg_CFG_sig_InitialLatency_r = 4'hA;
    reg_CFG_sig_Reserved_r = 4'hA;
    reg_CFG_sig_UltraDeepPowerDown_r = 1'h0;
    reg_ID0_sig_devid0_r = 12'hAAA;
    reg_ID0_sig_mgf_id_r = 4'hA;
    reg_ID1_sig_dev_type_r = 4'hA;
    reg_ID1_sig_devid1_r = 12'hAAA;
    reg_interrupt_status_sig_axi_resp_r = 2'h2;
    reg_interrupt_status_sig_read_underflow_r = 1'h0;
    reg_interrupt_status_sig_write_overflow_r = 1'h0;
    reg_xspi_control_sig_interrupt_enable_r = 1'h0;
    reg_xspi_control_sig_use_xspi_clk_r = 1'h0;
    reg_xspi_rates_sig_addr_rate_r = 8'hAA;
    reg_xspi_rates_sig_cmd_rate_r = 8'hAA;
    reg_xspi_rates_sig_data_rate_r = 8'hAA;
    reg_xspi_status_sig_wip_r = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkConfigCSR_SCCR_Reg

