//
// Generated by Bluespec Compiler, version 2025.07-40-g5dccc4ba (build 5dccc4ba)
//
//
// Ports:
// Name                         I/O  size props
// axis_awready                   O     1 reg
// axis_wready                    O     1 reg
// axis_bvalid                    O     1 reg
// axis_bid                       O     9 reg
// axis_bresp                     O     2 reg
// axis_arready                   O     1 reg
// axis_rvalid                    O     1 reg
// axis_rid                       O     9 reg
// axis_rdata                     O    64 reg
// axis_rresp                     O     2 reg
// axis_rlast                     O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// axis_awvalid                   I     1
// axis_awid                      I     9 reg
// axis_awaddr                    I    32 reg
// axis_awlen                     I     8 reg
// axis_awsize                    I     3 reg
// axis_awburst                   I     2 reg
// axis_awlock                    I     1 reg
// axis_awcache                   I     4 reg
// axis_awprot                    I     3 reg
// axis_awqos                     I     4 reg
// axis_awregion                  I     4 reg
// axis_wvalid                    I     1
// axis_wdata                     I    64 reg
// axis_wstrb                     I     8 reg
// axis_wlast                     I     1 reg
// axis_bready                    I     1
// axis_arvalid                   I     1
// axis_arid                      I     9 reg
// axis_araddr                    I    32 reg
// axis_arlen                     I     8 reg
// axis_arsize                    I     3 reg
// axis_arburst                   I     2 reg
// axis_arlock                    I     1 reg
// axis_arcache                   I     4 reg
// axis_arprot                    I     3 reg
// axis_arqos                     I     4 reg
// axis_arregion                  I     4 reg
// axis_rready                    I     1
// rom_dsleep                     I     1
// ram_dsleep                     I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkRomRam(CLK,
		RST_N,

		rom_dsleep,

		ram_dsleep,

		axis_awvalid,
		axis_awid,
		axis_awaddr,
		axis_awlen,
		axis_awsize,
		axis_awburst,
		axis_awlock,
		axis_awcache,
		axis_awprot,
		axis_awqos,
		axis_awregion,

		axis_awready,

		axis_wvalid,
		axis_wdata,
		axis_wstrb,
		axis_wlast,

		axis_wready,

		axis_bvalid,

		axis_bid,

		axis_bresp,

		axis_bready,

		axis_arvalid,
		axis_arid,
		axis_araddr,
		axis_arlen,
		axis_arsize,
		axis_arburst,
		axis_arlock,
		axis_arcache,
		axis_arprot,
		axis_arqos,
		axis_arregion,

		axis_arready,

		axis_rvalid,

		axis_rid,

		axis_rdata,

		axis_rresp,

		axis_rlast,

		axis_rready);
  input  CLK;
  input  RST_N;

  // action method rom_sleep
  input  rom_dsleep;

  // action method ram_sleep
  input  ram_dsleep;

  // action method axis_m_awvalid
  input  axis_awvalid;
  input  [8 : 0] axis_awid;
  input  [31 : 0] axis_awaddr;
  input  [7 : 0] axis_awlen;
  input  [2 : 0] axis_awsize;
  input  [1 : 0] axis_awburst;
  input  axis_awlock;
  input  [3 : 0] axis_awcache;
  input  [2 : 0] axis_awprot;
  input  [3 : 0] axis_awqos;
  input  [3 : 0] axis_awregion;

  // value method axis_m_awready
  output axis_awready;

  // action method axis_m_wvalid
  input  axis_wvalid;
  input  [63 : 0] axis_wdata;
  input  [7 : 0] axis_wstrb;
  input  axis_wlast;

  // value method axis_m_wready
  output axis_wready;

  // value method axis_m_bvalid
  output axis_bvalid;

  // value method axis_m_bid
  output [8 : 0] axis_bid;

  // value method axis_m_bresp
  output [1 : 0] axis_bresp;

  // value method axis_m_buser

  // action method axis_m_bready
  input  axis_bready;

  // action method axis_m_arvalid
  input  axis_arvalid;
  input  [8 : 0] axis_arid;
  input  [31 : 0] axis_araddr;
  input  [7 : 0] axis_arlen;
  input  [2 : 0] axis_arsize;
  input  [1 : 0] axis_arburst;
  input  axis_arlock;
  input  [3 : 0] axis_arcache;
  input  [2 : 0] axis_arprot;
  input  [3 : 0] axis_arqos;
  input  [3 : 0] axis_arregion;

  // value method axis_m_arready
  output axis_arready;

  // value method axis_m_rvalid
  output axis_rvalid;

  // value method axis_m_rid
  output [8 : 0] axis_rid;

  // value method axis_m_rdata
  output [63 : 0] axis_rdata;

  // value method axis_m_rresp
  output [1 : 0] axis_rresp;

  // value method axis_m_rlast
  output axis_rlast;

  // value method axis_m_ruser

  // action method axis_m_rready
  input  axis_rready;

  // signals for module outputs
  wire [63 : 0] axis_rdata;
  wire [8 : 0] axis_bid, axis_rid;
  wire [1 : 0] axis_bresp, axis_rresp;
  wire axis_arready,
       axis_awready,
       axis_bvalid,
       axis_rlast,
       axis_rvalid,
       axis_wready;

  // inlined wires
  wire axi_f_rfifo_r_clr_whas, axi_f_rfifo_r_deq_whas, axi_f_rfifo_r_enq_whas;

  // register axi_f_rfifo_countReg
  reg [1 : 0] axi_f_rfifo_countReg;
  wire [1 : 0] axi_f_rfifo_countReg_D_IN;
  wire axi_f_rfifo_countReg_EN;

  // register delayedRespEmpty
  reg delayedRespEmpty;
  wire delayedRespEmpty_D_IN, delayedRespEmpty_EN;

  // register rdoffset
  reg [7 : 0] rdoffset;
  wire [7 : 0] rdoffset_D_IN;
  wire rdoffset_EN;

  // register wroffset
  reg [11 : 0] wroffset;
  wire [11 : 0] wroffset_D_IN;
  wire wroffset_EN;

  // ports of submodule axi_f_arfifo
  wire [69 : 0] axi_f_arfifo_D_IN, axi_f_arfifo_D_OUT;
  wire axi_f_arfifo_CLR,
       axi_f_arfifo_DEQ,
       axi_f_arfifo_EMPTY_N,
       axi_f_arfifo_ENQ,
       axi_f_arfifo_FULL_N;

  // ports of submodule axi_f_awfifo
  wire [69 : 0] axi_f_awfifo_D_IN, axi_f_awfifo_D_OUT;
  wire axi_f_awfifo_CLR,
       axi_f_awfifo_DEQ,
       axi_f_awfifo_EMPTY_N,
       axi_f_awfifo_ENQ,
       axi_f_awfifo_FULL_N;

  // ports of submodule axi_f_bfifo
  wire [10 : 0] axi_f_bfifo_D_IN, axi_f_bfifo_D_OUT;
  wire axi_f_bfifo_CLR,
       axi_f_bfifo_DEQ,
       axi_f_bfifo_EMPTY_N,
       axi_f_bfifo_ENQ,
       axi_f_bfifo_FULL_N;

  // ports of submodule axi_f_rfifo
  wire [75 : 0] axi_f_rfifo_D_IN, axi_f_rfifo_D_OUT;
  wire axi_f_rfifo_CLR,
       axi_f_rfifo_DEQ,
       axi_f_rfifo_EMPTY_N,
       axi_f_rfifo_ENQ,
       axi_f_rfifo_FULL_N;

  // ports of submodule axi_f_wfifo
  wire [72 : 0] axi_f_wfifo_D_IN, axi_f_wfifo_D_OUT;
  wire axi_f_wfifo_CLR,
       axi_f_wfifo_DEQ,
       axi_f_wfifo_EMPTY_N,
       axi_f_wfifo_ENQ,
       axi_f_wfifo_FULL_N;

  // ports of submodule ram
  wire [63 : 0] ram_bit_enable, ram_din, ram_dout;
  wire [8 : 0] ram_address;
  wire ram_deep_sleep, ram_enable, ram_isRead;

  // ports of submodule rd_inProgress
  wire [11 : 0] rd_inProgress_D_IN, rd_inProgress_D_OUT;
  wire rd_inProgress_CLR,
       rd_inProgress_DEQ,
       rd_inProgress_EMPTY_N,
       rd_inProgress_ENQ,
       rd_inProgress_FULL_N;

  // ports of submodule rom
  wire [63 : 0] rom_dout;
  wire [9 : 0] rom_address;
  wire rom_deep_sleep, rom_enable;

  // rule scheduling signals
  wire CAN_FIRE_RL_axi_f_rfifo__updateLevelCounter,
       CAN_FIRE_RL_read,
       CAN_FIRE_RL_read_response,
       CAN_FIRE_RL_write,
       CAN_FIRE_axis_m_arvalid,
       CAN_FIRE_axis_m_awvalid,
       CAN_FIRE_axis_m_bready,
       CAN_FIRE_axis_m_rready,
       CAN_FIRE_axis_m_wvalid,
       CAN_FIRE_ram_sleep,
       CAN_FIRE_rom_sleep,
       WILL_FIRE_RL_axi_f_rfifo__updateLevelCounter,
       WILL_FIRE_RL_read,
       WILL_FIRE_RL_read_response,
       WILL_FIRE_RL_write,
       WILL_FIRE_axis_m_arvalid,
       WILL_FIRE_axis_m_awvalid,
       WILL_FIRE_axis_m_bready,
       WILL_FIRE_axis_m_rready,
       WILL_FIRE_axis_m_wvalid,
       WILL_FIRE_ram_sleep,
       WILL_FIRE_rom_sleep;

  // inputs to muxes for submodule ports
  wire [63 : 0] MUX_ram_request_3__VAL_1;
  wire MUX_ram_request_1__SEL_1;

  // remaining internal signals
  reg [63 : 0] x_rdata__h11727;
  reg [1 : 0] x_rresp__h11728;
  wire [31 : 0] _0_CONCAT_axi_f_arfifo_first__7_BITS_60_TO_32_8_ETC___d92,
		_0_CONCAT_axi_f_awfifo_first__7_BITS_60_TO_32_8_ETC___d22;
  wire [11 : 0] wro__h11175;
  wire [7 : 0] rro__h11552;
  wire rdoffset_0_EQ_axi_f_arfifo_first__7_BITS_28_TO_ETC___d102;

  // action method rom_sleep
  assign CAN_FIRE_rom_sleep = 1'd1 ;
  assign WILL_FIRE_rom_sleep = rom_dsleep ;

  // action method ram_sleep
  assign CAN_FIRE_ram_sleep = 1'd1 ;
  assign WILL_FIRE_ram_sleep = ram_dsleep ;

  // action method axis_m_awvalid
  assign CAN_FIRE_axis_m_awvalid = 1'd1 ;
  assign WILL_FIRE_axis_m_awvalid = 1'd1 ;

  // value method axis_m_awready
  assign axis_awready = axi_f_awfifo_FULL_N ;

  // action method axis_m_wvalid
  assign CAN_FIRE_axis_m_wvalid = 1'd1 ;
  assign WILL_FIRE_axis_m_wvalid = 1'd1 ;

  // value method axis_m_wready
  assign axis_wready = axi_f_wfifo_FULL_N ;

  // value method axis_m_bvalid
  assign axis_bvalid = axi_f_bfifo_EMPTY_N ;

  // value method axis_m_bid
  assign axis_bid = axi_f_bfifo_D_OUT[10:2] ;

  // value method axis_m_bresp
  assign axis_bresp = axi_f_bfifo_D_OUT[1:0] ;

  // action method axis_m_bready
  assign CAN_FIRE_axis_m_bready = 1'd1 ;
  assign WILL_FIRE_axis_m_bready = 1'd1 ;

  // action method axis_m_arvalid
  assign CAN_FIRE_axis_m_arvalid = 1'd1 ;
  assign WILL_FIRE_axis_m_arvalid = 1'd1 ;

  // value method axis_m_arready
  assign axis_arready = axi_f_arfifo_FULL_N ;

  // value method axis_m_rvalid
  assign axis_rvalid = axi_f_rfifo_EMPTY_N ;

  // value method axis_m_rid
  assign axis_rid = axi_f_rfifo_D_OUT[75:67] ;

  // value method axis_m_rdata
  assign axis_rdata = axi_f_rfifo_D_OUT[66:3] ;

  // value method axis_m_rresp
  assign axis_rresp = axi_f_rfifo_D_OUT[2:1] ;

  // value method axis_m_rlast
  assign axis_rlast = axi_f_rfifo_D_OUT[0] ;

  // action method axis_m_rready
  assign CAN_FIRE_axis_m_rready = 1'd1 ;
  assign WILL_FIRE_axis_m_rready = 1'd1 ;

  // submodule axi_f_arfifo
  FIFO2 #(.width(32'd70), .guarded(1'd1)) axi_f_arfifo(.RST(RST_N),
						       .CLK(CLK),
						       .D_IN(axi_f_arfifo_D_IN),
						       .ENQ(axi_f_arfifo_ENQ),
						       .DEQ(axi_f_arfifo_DEQ),
						       .CLR(axi_f_arfifo_CLR),
						       .D_OUT(axi_f_arfifo_D_OUT),
						       .FULL_N(axi_f_arfifo_FULL_N),
						       .EMPTY_N(axi_f_arfifo_EMPTY_N));

  // submodule axi_f_awfifo
  FIFO2 #(.width(32'd70), .guarded(1'd1)) axi_f_awfifo(.RST(RST_N),
						       .CLK(CLK),
						       .D_IN(axi_f_awfifo_D_IN),
						       .ENQ(axi_f_awfifo_ENQ),
						       .DEQ(axi_f_awfifo_DEQ),
						       .CLR(axi_f_awfifo_CLR),
						       .D_OUT(axi_f_awfifo_D_OUT),
						       .FULL_N(axi_f_awfifo_FULL_N),
						       .EMPTY_N(axi_f_awfifo_EMPTY_N));

  // submodule axi_f_bfifo
  FIFO2 #(.width(32'd11), .guarded(1'd1)) axi_f_bfifo(.RST(RST_N),
						      .CLK(CLK),
						      .D_IN(axi_f_bfifo_D_IN),
						      .ENQ(axi_f_bfifo_ENQ),
						      .DEQ(axi_f_bfifo_DEQ),
						      .CLR(axi_f_bfifo_CLR),
						      .D_OUT(axi_f_bfifo_D_OUT),
						      .FULL_N(axi_f_bfifo_FULL_N),
						      .EMPTY_N(axi_f_bfifo_EMPTY_N));

  // submodule axi_f_rfifo
  SizedFIFO #(.p1width(32'd76),
	      .p2depth(32'd3),
	      .p3cntr_width(32'd1),
	      .guarded(1'd1)) axi_f_rfifo(.RST(RST_N),
					  .CLK(CLK),
					  .D_IN(axi_f_rfifo_D_IN),
					  .ENQ(axi_f_rfifo_ENQ),
					  .DEQ(axi_f_rfifo_DEQ),
					  .CLR(axi_f_rfifo_CLR),
					  .D_OUT(axi_f_rfifo_D_OUT),
					  .FULL_N(axi_f_rfifo_FULL_N),
					  .EMPTY_N(axi_f_rfifo_EMPTY_N));

  // submodule axi_f_wfifo
  FIFO2 #(.width(32'd73), .guarded(1'd1)) axi_f_wfifo(.RST(RST_N),
						      .CLK(CLK),
						      .D_IN(axi_f_wfifo_D_IN),
						      .ENQ(axi_f_wfifo_ENQ),
						      .DEQ(axi_f_wfifo_DEQ),
						      .CLR(axi_f_wfifo_CLR),
						      .D_OUT(axi_f_wfifo_D_OUT),
						      .FULL_N(axi_f_wfifo_FULL_N),
						      .EMPTY_N(axi_f_wfifo_EMPTY_N));

  // submodule ram
  ram #(.ADDRESS_WIDTH(32'd9), .DATA_WIDTH(32'd64)) ram(.clk(CLK),
							.address(ram_address),
							.bit_enable(ram_bit_enable),
							.din(ram_din),
							.isRead(ram_isRead),
							.enable(ram_enable),
							.deep_sleep(ram_deep_sleep),
							.dout(ram_dout));

  // submodule rd_inProgress
  FIFO2 #(.width(32'd12), .guarded(1'd1)) rd_inProgress(.RST(RST_N),
							.CLK(CLK),
							.D_IN(rd_inProgress_D_IN),
							.ENQ(rd_inProgress_ENQ),
							.DEQ(rd_inProgress_DEQ),
							.CLR(rd_inProgress_CLR),
							.D_OUT(rd_inProgress_D_OUT),
							.FULL_N(rd_inProgress_FULL_N),
							.EMPTY_N(rd_inProgress_EMPTY_N));

  // submodule rom
  rom #(.ADDRESS_WIDTH(32'd10), .DATA_WIDTH(32'd64)) rom(.clk(CLK),
							 .rst_n(RST_N),
							 .address(rom_address),
							 .enable(rom_enable),
							 .deep_sleep(rom_deep_sleep),
							 .dout(rom_dout));

  // rule RL_read_response
  assign CAN_FIRE_RL_read_response =
	     axi_f_rfifo_FULL_N && rd_inProgress_EMPTY_N ;
  assign WILL_FIRE_RL_read_response = CAN_FIRE_RL_read_response ;

  // rule RL_write
  assign CAN_FIRE_RL_write =
	     axi_f_wfifo_EMPTY_N && axi_f_awfifo_EMPTY_N &&
	     axi_f_bfifo_FULL_N ;
  assign WILL_FIRE_RL_write = CAN_FIRE_RL_write ;

  // rule RL_read
  assign CAN_FIRE_RL_read =
	     axi_f_arfifo_EMPTY_N && rd_inProgress_FULL_N &&
	     axi_f_rfifo_countReg < 2'd2 ;
  assign WILL_FIRE_RL_read = CAN_FIRE_RL_read && !WILL_FIRE_RL_write ;

  // rule RL_axi_f_rfifo__updateLevelCounter
  assign CAN_FIRE_RL_axi_f_rfifo__updateLevelCounter =
	     CAN_FIRE_RL_read_response != axi_f_rfifo_r_deq_whas ;
  assign WILL_FIRE_RL_axi_f_rfifo__updateLevelCounter =
	     CAN_FIRE_RL_axi_f_rfifo__updateLevelCounter ;

  // inputs to muxes for submodule ports
  assign MUX_ram_request_1__SEL_1 =
	     WILL_FIRE_RL_write &&
	     _0_CONCAT_axi_f_awfifo_first__7_BITS_60_TO_32_8_ETC___d22[12:9] ==
	     4'b1100 ;
  assign MUX_ram_request_3__VAL_1 =
	     { axi_f_wfifo_D_OUT[8],
	       axi_f_wfifo_D_OUT[8],
	       axi_f_wfifo_D_OUT[8],
	       axi_f_wfifo_D_OUT[8],
	       axi_f_wfifo_D_OUT[8],
	       axi_f_wfifo_D_OUT[8],
	       axi_f_wfifo_D_OUT[8],
	       axi_f_wfifo_D_OUT[8:7],
	       axi_f_wfifo_D_OUT[7],
	       axi_f_wfifo_D_OUT[7],
	       axi_f_wfifo_D_OUT[7],
	       axi_f_wfifo_D_OUT[7],
	       axi_f_wfifo_D_OUT[7],
	       axi_f_wfifo_D_OUT[7],
	       axi_f_wfifo_D_OUT[7:6],
	       axi_f_wfifo_D_OUT[6],
	       axi_f_wfifo_D_OUT[6],
	       axi_f_wfifo_D_OUT[6],
	       axi_f_wfifo_D_OUT[6],
	       axi_f_wfifo_D_OUT[6],
	       axi_f_wfifo_D_OUT[6],
	       axi_f_wfifo_D_OUT[6:5],
	       axi_f_wfifo_D_OUT[5],
	       axi_f_wfifo_D_OUT[5],
	       axi_f_wfifo_D_OUT[5],
	       axi_f_wfifo_D_OUT[5],
	       axi_f_wfifo_D_OUT[5],
	       axi_f_wfifo_D_OUT[5],
	       axi_f_wfifo_D_OUT[5:4],
	       axi_f_wfifo_D_OUT[4],
	       axi_f_wfifo_D_OUT[4],
	       axi_f_wfifo_D_OUT[4],
	       axi_f_wfifo_D_OUT[4],
	       axi_f_wfifo_D_OUT[4],
	       axi_f_wfifo_D_OUT[4],
	       axi_f_wfifo_D_OUT[4:3],
	       axi_f_wfifo_D_OUT[3],
	       axi_f_wfifo_D_OUT[3],
	       axi_f_wfifo_D_OUT[3],
	       axi_f_wfifo_D_OUT[3],
	       axi_f_wfifo_D_OUT[3],
	       axi_f_wfifo_D_OUT[3],
	       axi_f_wfifo_D_OUT[3:2],
	       axi_f_wfifo_D_OUT[2],
	       axi_f_wfifo_D_OUT[2],
	       axi_f_wfifo_D_OUT[2],
	       axi_f_wfifo_D_OUT[2],
	       axi_f_wfifo_D_OUT[2],
	       axi_f_wfifo_D_OUT[2],
	       axi_f_wfifo_D_OUT[2:1],
	       axi_f_wfifo_D_OUT[1],
	       axi_f_wfifo_D_OUT[1],
	       axi_f_wfifo_D_OUT[1],
	       axi_f_wfifo_D_OUT[1],
	       axi_f_wfifo_D_OUT[1],
	       axi_f_wfifo_D_OUT[1],
	       axi_f_wfifo_D_OUT[1] } ;

  // inlined wires
  assign axi_f_rfifo_r_enq_whas = CAN_FIRE_RL_read_response ;
  assign axi_f_rfifo_r_deq_whas = axis_rready && axi_f_rfifo_EMPTY_N ;
  assign axi_f_rfifo_r_clr_whas = 1'b0 ;

  // register axi_f_rfifo_countReg
  assign axi_f_rfifo_countReg_D_IN =
	     CAN_FIRE_RL_read_response ?
	       axi_f_rfifo_countReg + 2'd1 :
	       axi_f_rfifo_countReg - 2'd1 ;
  assign axi_f_rfifo_countReg_EN =
	     CAN_FIRE_RL_axi_f_rfifo__updateLevelCounter ;

  // register delayedRespEmpty
  assign delayedRespEmpty_D_IN = 1'b0 ;
  assign delayedRespEmpty_EN = 1'b0 ;

  // register rdoffset
  assign rdoffset_D_IN =
	     rdoffset_0_EQ_axi_f_arfifo_first__7_BITS_28_TO_ETC___d102 ?
	       8'd0 :
	       rro__h11552 ;
  assign rdoffset_EN = WILL_FIRE_RL_read ;

  // register wroffset
  assign wroffset_D_IN = axi_f_wfifo_D_OUT[0] ? 12'd0 : wro__h11175 ;
  assign wroffset_EN = CAN_FIRE_RL_write ;

  // submodule axi_f_arfifo
  assign axi_f_arfifo_D_IN =
	     { axis_arid,
	       axis_araddr,
	       axis_arlen,
	       axis_arsize,
	       axis_arburst,
	       axis_arlock,
	       axis_arcache,
	       axis_arprot,
	       axis_arqos,
	       axis_arregion } ;
  assign axi_f_arfifo_ENQ = axis_arvalid && axi_f_arfifo_FULL_N ;
  assign axi_f_arfifo_DEQ =
	     WILL_FIRE_RL_read &&
	     rdoffset_0_EQ_axi_f_arfifo_first__7_BITS_28_TO_ETC___d102 ;
  assign axi_f_arfifo_CLR = 1'b0 ;

  // submodule axi_f_awfifo
  assign axi_f_awfifo_D_IN =
	     { axis_awid,
	       axis_awaddr,
	       axis_awlen,
	       axis_awsize,
	       axis_awburst,
	       axis_awlock,
	       axis_awcache,
	       axis_awprot,
	       axis_awqos,
	       axis_awregion } ;
  assign axi_f_awfifo_ENQ = axis_awvalid && axi_f_awfifo_FULL_N ;
  assign axi_f_awfifo_DEQ = WILL_FIRE_RL_write && axi_f_wfifo_D_OUT[0] ;
  assign axi_f_awfifo_CLR = 1'b0 ;

  // submodule axi_f_bfifo
  assign axi_f_bfifo_D_IN =
	     { axi_f_awfifo_D_OUT[69:61],
	       (_0_CONCAT_axi_f_awfifo_first__7_BITS_60_TO_32_8_ETC___d22[12:9] ==
		4'b1100) ?
		 2'b0 :
		 ((_0_CONCAT_axi_f_awfifo_first__7_BITS_60_TO_32_8_ETC___d22[12:10] ==
		   3'b100) ?
		    2'b10 :
		    2'b11) } ;
  assign axi_f_bfifo_ENQ = CAN_FIRE_RL_write ;
  assign axi_f_bfifo_DEQ = axis_bready && axi_f_bfifo_EMPTY_N ;
  assign axi_f_bfifo_CLR = 1'b0 ;

  // submodule axi_f_rfifo
  assign axi_f_rfifo_D_IN =
	     { rd_inProgress_D_OUT[9:1],
	       x_rdata__h11727,
	       x_rresp__h11728,
	       rd_inProgress_D_OUT[0] } ;
  assign axi_f_rfifo_ENQ = CAN_FIRE_RL_read_response ;
  assign axi_f_rfifo_DEQ = axi_f_rfifo_r_deq_whas ;
  assign axi_f_rfifo_CLR = 1'b0 ;

  // submodule axi_f_wfifo
  assign axi_f_wfifo_D_IN = { axis_wdata, axis_wstrb, axis_wlast } ;
  assign axi_f_wfifo_ENQ = axis_wvalid && axi_f_wfifo_FULL_N ;
  assign axi_f_wfifo_DEQ = CAN_FIRE_RL_write ;
  assign axi_f_wfifo_CLR = 1'b0 ;

  // submodule ram
  assign ram_address =
	     MUX_ram_request_1__SEL_1 ?
	       _0_CONCAT_axi_f_awfifo_first__7_BITS_60_TO_32_8_ETC___d22[8:0] :
	       _0_CONCAT_axi_f_arfifo_first__7_BITS_60_TO_32_8_ETC___d92[8:0] ;
  assign ram_bit_enable =
	     MUX_ram_request_1__SEL_1 ? MUX_ram_request_3__VAL_1 : 64'd0 ;
  assign ram_din =
	     MUX_ram_request_1__SEL_1 ? axi_f_wfifo_D_OUT[72:9] : 64'd0 ;
  assign ram_isRead = !MUX_ram_request_1__SEL_1 ;
  assign ram_enable =
	     WILL_FIRE_RL_write &&
	     _0_CONCAT_axi_f_awfifo_first__7_BITS_60_TO_32_8_ETC___d22[12:9] ==
	     4'b1100 ||
	     WILL_FIRE_RL_read &&
	     _0_CONCAT_axi_f_arfifo_first__7_BITS_60_TO_32_8_ETC___d92[12:9] ==
	     4'b1100 ;
  assign ram_deep_sleep = ram_dsleep ;

  // submodule rd_inProgress
  assign rd_inProgress_D_IN =
	     { (_0_CONCAT_axi_f_arfifo_first__7_BITS_60_TO_32_8_ETC___d92[12:10] ==
		3'b100) ?
		 2'd0 :
		 ((_0_CONCAT_axi_f_arfifo_first__7_BITS_60_TO_32_8_ETC___d92[12:9] ==
		   4'b1100) ?
		    2'd1 :
		    2'd2),
	       axi_f_arfifo_D_OUT[69:61],
	       rdoffset_0_EQ_axi_f_arfifo_first__7_BITS_28_TO_ETC___d102 } ;
  assign rd_inProgress_ENQ = WILL_FIRE_RL_read ;
  assign rd_inProgress_DEQ = CAN_FIRE_RL_read_response ;
  assign rd_inProgress_CLR = 1'b0 ;

  // submodule rom
  assign rom_address =
	     _0_CONCAT_axi_f_arfifo_first__7_BITS_60_TO_32_8_ETC___d92[9:0] ;
  assign rom_enable =
	     WILL_FIRE_RL_read &&
	     _0_CONCAT_axi_f_arfifo_first__7_BITS_60_TO_32_8_ETC___d92[12:10] ==
	     3'b100 ;
  assign rom_deep_sleep = rom_dsleep ;

  // remaining internal signals
  assign _0_CONCAT_axi_f_arfifo_first__7_BITS_60_TO_32_8_ETC___d92 =
	     { 3'd0, axi_f_arfifo_D_OUT[60:32] } + { 24'd0, rdoffset } ;
  assign _0_CONCAT_axi_f_awfifo_first__7_BITS_60_TO_32_8_ETC___d22 =
	     { 3'd0, axi_f_awfifo_D_OUT[60:32] } + { 20'd0, wroffset } ;
  assign rdoffset_0_EQ_axi_f_arfifo_first__7_BITS_28_TO_ETC___d102 =
	     rdoffset == axi_f_arfifo_D_OUT[28:21] ;
  assign rro__h11552 = rdoffset + 8'd1 ;
  assign wro__h11175 = wroffset + 12'd1 ;
  always@(rd_inProgress_D_OUT or rom_dout or ram_dout)
  begin
    case (rd_inProgress_D_OUT[11:10])
      2'd0: x_rdata__h11727 = rom_dout;
      2'd1: x_rdata__h11727 = ram_dout;
      default: x_rdata__h11727 = 64'd0;
    endcase
  end
  always@(rd_inProgress_D_OUT)
  begin
    case (rd_inProgress_D_OUT[11:10])
      2'd0, 2'd1: x_rresp__h11728 = 2'b0;
      default: x_rresp__h11728 = 2'b11;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        axi_f_rfifo_countReg <= `BSV_ASSIGNMENT_DELAY 2'd0;
      end
    else
      begin
        if (axi_f_rfifo_countReg_EN)
	  axi_f_rfifo_countReg <= `BSV_ASSIGNMENT_DELAY
	      axi_f_rfifo_countReg_D_IN;
      end
  end

  always@(posedge CLK or `BSV_RESET_EDGE RST_N)
  if (RST_N == `BSV_RESET_VALUE)
    begin
      delayedRespEmpty <= `BSV_ASSIGNMENT_DELAY 1'd0;
      rdoffset <= `BSV_ASSIGNMENT_DELAY 8'd0;
      wroffset <= `BSV_ASSIGNMENT_DELAY 12'd0;
    end
  else
    begin
      if (delayedRespEmpty_EN)
	delayedRespEmpty <= `BSV_ASSIGNMENT_DELAY delayedRespEmpty_D_IN;
      if (rdoffset_EN) rdoffset <= `BSV_ASSIGNMENT_DELAY rdoffset_D_IN;
      if (wroffset_EN) wroffset <= `BSV_ASSIGNMENT_DELAY wroffset_D_IN;
    end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    axi_f_rfifo_countReg = 2'h2;
    delayedRespEmpty = 1'h0;
    rdoffset = 8'hAA;
    wroffset = 12'hAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkRomRam

