////////////////////////////////////////////////////////////////
// Netlist generated by	: Custom Designer (TM) db::generateVerilog
// Date			: Wed Feb 18 16:17:03 MST 2026
////////////////////////////////////////////////////////////////
// Library Name	:	 erbium
// Cell Name	:	 anachip
// View Name	:	 verilog
////////////////////////////////////////////////////////////////

module anachip (en, en_b, h1_mnvdd09_g, sah_en_b, vdd, vdd18, vss);
       input en;
       input en_b;
       output h1_mnvdd09_g;
       reg h1_mnvdd09_g;
       input sah_en_b;
       inout vdd;
       inout vdd18;
       inout vss;

    wire [2:0] mode;

    assign mode = {en, en_b, sah_en_b};
    always @(mode) begin
        case (mode)
            3'b010 : h1_mnvdd09_g = 1'b0; // Power down / Deep sleep mode
            3'b011 : h1_mnvdd09_g = 1'b0; // Power down / Deep sleep mode
            3'b100 : h1_mnvdd09_g = 1'b1; // Normal SAH Operation
            3'b101 : h1_mnvdd09_g = 1'b1; // Test Mode Operation (high power)
            default: h1_mnvdd09_g = 1'bx;
        endcase
    end
endmodule