////////////////////////////////////////////////////////////////
// Netlist generated by	: Custom Designer (TM) db::generateVerilog
// Date			: Thu Feb 19 15:50:52 MST 2026
////////////////////////////////////////////////////////////////
// Library Name	:	 erbium
// Cell Name	:	 rochip
// View Name	:	 verilog
////////////////////////////////////////////////////////////////
`timescale 1ps/1ps

module rochip (
  output logic       clk,
  input  logic       divby2_sel,
  input  logic       en,
  input  logic       en_b,
  input  logic       h1_mnvdd09_g,
  input  logic [4:0] trm,
  inout              vdd,
  inout              vdd18,
  inout              vss
);

  // ----------------------------
  // Debug signals (hierarchical access from TB)
  // ----------------------------
  logic dbg_enabled, dbg_disabled, dbg_invalid;
  real  dbg_freq_hz;
  realtime dbg_tper, dbg_thi, dbg_tlo;

  // ----------------------------
  // Deterministic PRNG (xorshift32)
  // ----------------------------
  int unsigned s = 32'h1234_5678;

  function automatic int unsigned xorshift32(input int unsigned x);
    x ^= (x << 13);
    x ^= (x >> 17);
    x ^= (x << 5);
    return x;
  endfunction

  function automatic real urand01();
    int unsigned tmp;
    int unsigned frac;
    s = xorshift32(s);
    tmp  = s >> 8;
    frac = tmp & 32'h00FF_FFFF;
    urand01 = real'(frac) / 16777216.0;  // 2^24
  endfunction

  // ----------------------------
  // Frequency + duty helpers
  // ----------------------------
  function automatic real freq_hz(input logic div2, input logic [4:0] trim);
    real f_fast, f_slow;
    real a;

    if (div2 == 1'b0) begin
      f_fast = 1.608e9;
      f_slow = 0.899e9;
    end else begin
      f_fast = 0.794e9;
      f_slow = 0.449e9;
    end

    // trm=0 fastest, trm=31 slowest
    a = real'(trim) / 31.0;
    freq_hz = f_fast - a * (f_fast - f_slow);
  endfunction

  function automatic void duty_range(input logic div2, output real dmin, output real dmax);
    if (div2 == 1'b0) begin
      dmin = 0.467;
      dmax = 0.524;
    end else begin
      dmin = 0.478;
      dmax = 0.497;
    end
  endfunction

  // ----------------------------
  // Enable/validity
  // ----------------------------
  function automatic bit f_invalid();
    // invalid if en/en_b not complementary OR either is X/Z
    if ((en === 1'b1 && en_b === 1'b0) || (en === 1'b0 && en_b === 1'b1)) begin
      return 0;
    end
    return 1;
  endfunction

  function automatic bit f_enabled();
    // analog pin acts like extra enable
    return (h1_mnvdd09_g === 1'b1) && (en === 1'b1) && (en_b === 1'b0);
  endfunction

  function automatic bit f_disabled();
    return (h1_mnvdd09_g === 1'b0) || ((en === 1'b0) && (en_b === 1'b1));
  endfunction

  // Drive debug signals continuously
  always_comb begin
    dbg_invalid  = f_invalid();
    dbg_enabled  = (!dbg_invalid) && f_enabled();
    dbg_disabled = (!dbg_invalid) && f_disabled();
    dbg_freq_hz  = freq_hz(divby2_sel, trm);
  end

  // Print state when any control changes
  //always @(en or en_b or h1_mnvdd09_g or divby2_sel or trm) begin
  //  $display("[%0t] rochip ctrl: h1=%b en=%b en_b=%b div2=%b trm=%0d | invalid=%b enabled=%b disabled=%b | f=%0.3f MHz",
  //           $realtime, h1_mnvdd09_g, en, en_b, divby2_sel, trm,
  //           dbg_invalid, dbg_enabled, dbg_disabled, dbg_freq_hz/1e6);
  //end

  // ----------------------------
  // Oscillator process (Pattern B)
  // ----------------------------
  realtime t_hi, t_lo, t_per;
  real     f, dmin, dmax, duty;

  initial begin
    clk = 1'b0;
    $display("[%0t] rochip: starting model (NOTE: Verilator needs --timing for #delays)", $realtime);

    forever begin
      // wait for a potential state change
      @(en or en_b or h1_mnvdd09_g or divby2_sel or trm);

      if (dbg_invalid) begin
        clk = 1'bx;
        //$display("[%0t] rochip: INVALID en/en_b -> clk=X", $realtime);
        continue;
      end

      if (dbg_disabled) begin
        clk = 1'b0;
        //$display("[%0t] rochip: DISABLED -> clk=0", $realtime);
        continue;
      end

      if (dbg_enabled) begin
        if (clk === 1'bx) clk = 1'b0;
        //$display("[%0t] rochip: ENABLED -> starting oscillation", $realtime);

        while (1) begin
          // re-check state
          if (f_invalid()) begin
            clk = 1'bx;
            //$display("[%0t] rochip: became INVALID -> clk=X", $realtime);
            break;
          end
          if (f_disabled()) begin
            clk = 1'b0;
            //$display("[%0t] rochip: became DISABLED -> clk=0", $realtime);
            break;
          end
          if (!f_enabled()) begin
            // complementary but not "enabled" (e.g., h1 unknown)
            //$display("[%0t] rochip: complementary but not enabled (h1=%b en=%b en_b=%b)", $realtime,
            //         h1_mnvdd09_g, en, en_b);
            break;
          end

          // compute timing
          f = freq_hz(divby2_sel, trm);
          t_per = 1.0s / f;

          duty_range(divby2_sel, dmin, dmax);
          duty = dmin + (dmax - dmin) * urand01();

          t_hi = t_per * duty;
          t_lo = t_per - t_hi;

          // publish debug timing values
          dbg_tper = t_per;
          dbg_thi  = t_hi;
          dbg_tlo  = t_lo;

          //$display("[%0t] rochip: cycle params: f=%0.3f MHz duty=%0.4f t_per=%0t t_lo=%0t t_hi=%0t",
          //         $realtime, f/1e6, duty, t_per, t_lo, t_hi);

          // low phase then rising edge
          #(t_lo);
          if (!f_enabled()) continue;
          clk = 1'b1;
          //$display("[%0t] rochip: clk=%0b (rising)", $realtime, clk);

          // high phase then falling edge
          #(t_hi);
          if (!f_enabled()) continue;
          clk = 1'b0;
          //$display("[%0t] rochip: clk=%0b (falling)", $realtime, clk);
        end
      end
    end
  end

endmodule