// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package external_test_regs_pkg;

    localparam EXTERNAL_TEST_REGS_DATA_WIDTH = 64;
    localparam EXTERNAL_TEST_REGS_MIN_ADDR_WIDTH = 16;
    localparam EXTERNAL_TEST_REGS_SIZE = 'hfff8;

    typedef struct {
        logic rd_ack;
        logic [63:0] rd_data;
        logic wr_ack;
    } MRAM_Controller_Test_Regs__external__in_t;

    typedef struct {
        MRAM_Controller_Test_Regs__external__in_t test_regs;
    } external_test_regs__in_t;

    typedef struct {
        logic req;
        logic [7:0] addr;
        logic req_is_wr;
        logic [63:0] wr_data;
        logic [63:0] wr_biten;
    } MRAM_Controller_Test_Regs__external__out_t;

    typedef struct {
        MRAM_Controller_Test_Regs__external__out_t test_regs;
    } external_test_regs__out_t;
endpackage
