// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module axi2mram_bridge_registers (
        input wire clk,
        input wire arst_n,

        output logic s_axil_awready,
        input wire s_axil_awvalid,
        input wire [10:0] s_axil_awaddr,
        input wire [2:0] s_axil_awprot,
        output logic s_axil_wready,
        input wire s_axil_wvalid,
        input wire [63:0] s_axil_wdata,
        input wire [7:0]s_axil_wstrb,
        input wire s_axil_bready,
        output logic s_axil_bvalid,
        output logic [1:0] s_axil_bresp,
        output logic s_axil_arready,
        input wire s_axil_arvalid,
        input wire [10:0] s_axil_araddr,
        input wire [2:0] s_axil_arprot,
        input wire s_axil_rready,
        output logic s_axil_rvalid,
        output logic [63:0] s_axil_rdata,
        output logic [1:0] s_axil_rresp,

        input axi2mram_bridge_registers_pkg::axi2mram_bridge_registers__in_t hwif_in,
        output axi2mram_bridge_registers_pkg::axi2mram_bridge_registers__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [10:0] cpuif_addr;
    logic [63:0] cpuif_wr_data;
    logic [63:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [63:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Max Outstanding Transactions: 2
    logic [1:0] axil_n_in_flight;
    logic axil_prev_was_rd;
    logic axil_arvalid;
    logic [10:0] axil_araddr;
    logic axil_ar_accept;
    logic axil_awvalid;
    logic [10:0] axil_awaddr;
    logic axil_wvalid;
    logic [63:0] axil_wdata;
    logic [7:0] axil_wstrb;
    logic axil_aw_accept;
    logic axil_resp_acked;

    // Transaction request acceptance
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            axil_prev_was_rd <= '0;
            axil_arvalid <= '0;
            axil_araddr <= '0;
            axil_awvalid <= '0;
            axil_awaddr <= '0;
            axil_wvalid <= '0;
            axil_wdata <= '0;
            axil_wstrb <= '0;
            axil_n_in_flight <= '0;
        end else begin
            // AR* acceptance register
            if(axil_ar_accept) begin
                axil_prev_was_rd <= '1;
                axil_arvalid <= '0;
            end
            if(s_axil_arvalid && s_axil_arready) begin
                axil_arvalid <= '1;
                axil_araddr <= s_axil_araddr;
            end

            // AW* & W* acceptance registers
            if(axil_aw_accept) begin
                axil_prev_was_rd <= '0;
                axil_awvalid <= '0;
                axil_wvalid <= '0;
            end
            if(s_axil_awvalid && s_axil_awready) begin
                axil_awvalid <= '1;
                axil_awaddr <= s_axil_awaddr;
            end
            if(s_axil_wvalid && s_axil_wready) begin
                axil_wvalid <= '1;
                axil_wdata <= s_axil_wdata;
                axil_wstrb <= s_axil_wstrb;
            end

            // Keep track of in-flight transactions
            if((axil_ar_accept || axil_aw_accept) && !axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight + 1'b1;
            end else if(!(axil_ar_accept || axil_aw_accept) && axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight - 1'b1;
            end
        end
    end

    always_comb begin
        s_axil_arready = (!axil_arvalid || axil_ar_accept);
        s_axil_awready = (!axil_awvalid || axil_aw_accept);
        s_axil_wready = (!axil_wvalid || axil_aw_accept);
    end

    // Request dispatch
    always_comb begin
        cpuif_wr_data = axil_wdata;
        for(int i=0; i<8; i++) begin
            cpuif_wr_biten[i*8 +: 8] = {8{axil_wstrb[i]}};
        end
        cpuif_req = '0;
        cpuif_req_is_wr = '0;
        cpuif_addr = '0;
        axil_ar_accept = '0;
        axil_aw_accept = '0;

        if(axil_n_in_flight < 2'd2) begin
            // Can safely issue more transactions without overwhelming response buffer
            if(axil_arvalid && !axil_prev_was_rd) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = {axil_araddr[10:3], 3'b0};
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end else if(axil_awvalid && axil_wvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '1;
                cpuif_addr = {axil_awaddr[10:3], 3'b0};
                if(!cpuif_req_stall_wr) axil_aw_accept = '1;
            end else if(axil_arvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = {axil_araddr[10:3], 3'b0};
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end
        end
    end


    // AXI4-Lite Response Logic
    struct {
        logic is_wr;
        logic err;
        logic [63:0] rdata;
    } axil_resp_buffer[2];

    logic [1:0] axil_resp_wptr;
    logic [1:0] axil_resp_rptr;

    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            for(int i=0; i<2; i++) begin
                axil_resp_buffer[i].is_wr <= '0;
                axil_resp_buffer[i].err <= '0;
                axil_resp_buffer[i].rdata <= '0;
            end
            axil_resp_wptr <= '0;
            axil_resp_rptr <= '0;
        end else begin
            // Store responses in buffer until AXI response channel accepts them
            if(cpuif_rd_ack || cpuif_wr_ack) begin
                if(cpuif_rd_ack) begin
                    axil_resp_buffer[axil_resp_wptr[0:0]].is_wr <= '0;
                    axil_resp_buffer[axil_resp_wptr[0:0]].err <= cpuif_rd_err;
                    axil_resp_buffer[axil_resp_wptr[0:0]].rdata <= cpuif_rd_data;

                end else if(cpuif_wr_ack) begin
                    axil_resp_buffer[axil_resp_wptr[0:0]].is_wr <= '1;
                    axil_resp_buffer[axil_resp_wptr[0:0]].err <= cpuif_wr_err;
                end
                axil_resp_wptr <= axil_resp_wptr + 1'b1;
            end

            // Advance read pointer when acknowledged
            if(axil_resp_acked) begin
                axil_resp_rptr <= axil_resp_rptr + 1'b1;
            end
        end
    end

    always_comb begin
        axil_resp_acked = '0;
        s_axil_bvalid = '0;
        s_axil_rvalid = '0;
        if(axil_resp_rptr != axil_resp_wptr) begin
            if(axil_resp_buffer[axil_resp_rptr[0:0]].is_wr) begin
                s_axil_bvalid = '1;
                if(s_axil_bready) axil_resp_acked = '1;
            end else begin
                s_axil_rvalid = '1;
                if(s_axil_rready) axil_resp_acked = '1;
            end
        end

        s_axil_rdata = axil_resp_buffer[axil_resp_rptr[0:0]].rdata;
        if(axil_resp_buffer[axil_resp_rptr[0:0]].err) begin
            s_axil_bresp = 2'b10;
            s_axil_rresp = 2'b10;
        end else begin
            s_axil_bresp = 2'b00;
            s_axil_rresp = 2'b00;
        end
    end

    logic cpuif_req_masked;
    logic external_req;
    logic external_pending;
    logic external_wr_ack;
    logic external_rd_ack;
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            external_pending <= '0;
        end else begin
            if(external_req & ~external_wr_ack & ~external_rd_ack) external_pending <= '1;
            else if(external_wr_ack | external_rd_ack) external_pending <= '0;
            `ifndef SYNTHESIS
                assert_bad_ext_wr_ack: assert(!external_wr_ack || (external_pending | external_req))
                    else $error("An external wr_ack strobe was asserted when no external request was active");
                assert_bad_ext_rd_ack: assert(!external_rd_ack || (external_pending | external_req))
                    else $error("An external rd_ack strobe was asserted when no external request was active");
            `endif
        end
    end

    // Read & write latencies are balanced. Stalls not required
    // except if external
    assign cpuif_req_stall_rd = external_pending;
    assign cpuif_req_stall_wr = external_pending;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            logic arbiter_mode_reg;
            logic bridge_status_reg;
            logic slverr_status_reg;
            logic control_reg;
            logic ecc_1bit_error_count_reg;
            logic ecc_2bit_error_count_reg;
            logic ecc_3bit_error_count_reg;
        } bridge_regs;
        logic bank0_tregs;
        logic bank1_tregs;
        logic bank2_tregs;
        logic bank3_tregs;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic decoded_strb_is_external;

    logic [10:0] decoded_addr;

    logic decoded_req;
    logic decoded_req_is_wr;
    logic [63:0] decoded_wr_data;
    logic [63:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_invalid_rw;
        automatic logic is_external;
        is_external = '0;
        is_valid_addr = '1; // No error checking on valid address access
        is_invalid_rw = '0;
        decoded_reg_strb.bridge_regs.arbiter_mode_reg = cpuif_req_masked & (cpuif_addr == 11'h0);
        decoded_reg_strb.bridge_regs.bridge_status_reg = cpuif_req_masked & (cpuif_addr == 11'h8) & !cpuif_req_is_wr;
        decoded_reg_strb.bridge_regs.slverr_status_reg = cpuif_req_masked & (cpuif_addr == 11'h10) & !cpuif_req_is_wr;
        decoded_reg_strb.bridge_regs.control_reg = cpuif_req_masked & (cpuif_addr == 11'h18);
        decoded_reg_strb.bridge_regs.ecc_1bit_error_count_reg = cpuif_req_masked & (cpuif_addr == 11'h20) & !cpuif_req_is_wr;
        decoded_reg_strb.bridge_regs.ecc_2bit_error_count_reg = cpuif_req_masked & (cpuif_addr == 11'h28) & !cpuif_req_is_wr;
        decoded_reg_strb.bridge_regs.ecc_3bit_error_count_reg = cpuif_req_masked & (cpuif_addr == 11'h30) & !cpuif_req_is_wr;
        decoded_reg_strb.bank0_tregs = cpuif_req_masked & (cpuif_addr >= 11'h100) & (cpuif_addr <= 11'h100 + 11'h9f);
        is_external |= cpuif_req_masked & (cpuif_addr >= 11'h100) & (cpuif_addr <= 11'h100 + 11'h9f);
        decoded_reg_strb.bank1_tregs = cpuif_req_masked & (cpuif_addr >= 11'h200) & (cpuif_addr <= 11'h200 + 11'h9f);
        is_external |= cpuif_req_masked & (cpuif_addr >= 11'h200) & (cpuif_addr <= 11'h200 + 11'h9f);
        decoded_reg_strb.bank2_tregs = cpuif_req_masked & (cpuif_addr >= 11'h300) & (cpuif_addr <= 11'h300 + 11'h9f);
        is_external |= cpuif_req_masked & (cpuif_addr >= 11'h300) & (cpuif_addr <= 11'h300 + 11'h9f);
        decoded_reg_strb.bank3_tregs = cpuif_req_masked & (cpuif_addr >= 11'h400) & (cpuif_addr <= 11'h400 + 11'h9f);
        is_external |= cpuif_req_masked & (cpuif_addr >= 11'h400) & (cpuif_addr <= 11'h400 + 11'h9f);
        decoded_err = (~is_valid_addr | is_invalid_rw) & decoded_req;
        decoded_strb_is_external = is_external;
        external_req = is_external;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;

    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                struct {
                    logic [1:0] next;
                    logic load_next;
                } arbiter_mode;
            } arbiter_mode_reg;
            struct {
                struct {
                    logic next;
                    logic load_next;
                } oor_read;
                struct {
                    logic next;
                    logic load_next;
                } oor_write;
                struct {
                    logic next;
                    logic load_next;
                } mram_not_ready;
                struct {
                    logic next;
                    logic load_next;
                } mram_unpowered;
                struct {
                    logic next;
                    logic load_next;
                } maintenance;
                struct {
                    logic next;
                    logic load_next;
                } unrecoverable_error;
            } slverr_status_reg;
            struct {
                struct {
                    logic [3:0] next;
                    logic load_next;
                } disable_clock_gate;
                struct {
                    logic next;
                    logic load_next;
                } ecc_1bit_intr_mask;
                struct {
                    logic next;
                    logic load_next;
                } ecc_2bit_intr_mask;
                struct {
                    logic next;
                    logic load_next;
                } ecc_3bit_intr_mask;
            } control_reg;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                    logic incrthreshold;
                    logic incrsaturate;
                } count;
            } ecc_1bit_error_count_reg;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                    logic incrthreshold;
                    logic incrsaturate;
                } count;
            } ecc_2bit_error_count_reg;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                    logic incrthreshold;
                    logic incrsaturate;
                } count;
            } ecc_3bit_error_count_reg;
        } bridge_regs;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                struct {
                    logic [1:0] value;
                } arbiter_mode;
            } arbiter_mode_reg;
            struct {
                struct {
                    logic value;
                } oor_read;
                struct {
                    logic value;
                } oor_write;
                struct {
                    logic value;
                } mram_not_ready;
                struct {
                    logic value;
                } mram_unpowered;
                struct {
                    logic value;
                } maintenance;
                struct {
                    logic value;
                } unrecoverable_error;
            } slverr_status_reg;
            struct {
                struct {
                    logic [3:0] value;
                } disable_clock_gate;
                struct {
                    logic value;
                } ecc_1bit_intr_mask;
                struct {
                    logic value;
                } ecc_2bit_intr_mask;
                struct {
                    logic value;
                } ecc_3bit_intr_mask;
            } control_reg;
            struct {
                struct {
                    logic [31:0] value;
                } count;
            } ecc_1bit_error_count_reg;
            struct {
                struct {
                    logic [31:0] value;
                } count;
            } ecc_2bit_error_count_reg;
            struct {
                struct {
                    logic [31:0] value;
                } count;
            } ecc_3bit_error_count_reg;
        } bridge_regs;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: axi2mram_bridge_registers.bridge_regs.arbiter_mode_reg.arbiter_mode
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.bridge_regs.arbiter_mode_reg.arbiter_mode.value;
        load_next_c = '0;
        if(decoded_reg_strb.bridge_regs.arbiter_mode_reg && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.bridge_regs.arbiter_mode_reg.arbiter_mode.value & ~decoded_wr_biten[1:0]) | (decoded_wr_data[1:0] & decoded_wr_biten[1:0]);
            load_next_c = '1;
        end
        field_combo.bridge_regs.arbiter_mode_reg.arbiter_mode.next = next_c;
        field_combo.bridge_regs.arbiter_mode_reg.arbiter_mode.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.bridge_regs.arbiter_mode_reg.arbiter_mode.value <= 2'h2;
        end else begin
            if(field_combo.bridge_regs.arbiter_mode_reg.arbiter_mode.load_next) begin
                field_storage.bridge_regs.arbiter_mode_reg.arbiter_mode.value <= field_combo.bridge_regs.arbiter_mode_reg.arbiter_mode.next;
            end
        end
    end
    assign hwif_out.bridge_regs.arbiter_mode_reg.arbiter_mode.value = field_storage.bridge_regs.arbiter_mode_reg.arbiter_mode.value;
    // Field: axi2mram_bridge_registers.bridge_regs.slverr_status_reg.oor_read
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.bridge_regs.slverr_status_reg.oor_read.value;
        load_next_c = '0;
        if(decoded_reg_strb.bridge_regs.slverr_status_reg && !decoded_req_is_wr) begin // SW clear on read
            next_c = '0;
            load_next_c = '1;
        end else if(hwif_in.bridge_regs.slverr_status_reg.oor_read.hwset) begin // HW Set
            next_c = '1;
            load_next_c = '1;
        end
        field_combo.bridge_regs.slverr_status_reg.oor_read.next = next_c;
        field_combo.bridge_regs.slverr_status_reg.oor_read.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.bridge_regs.slverr_status_reg.oor_read.value <= 1'h0;
        end else begin
            if(field_combo.bridge_regs.slverr_status_reg.oor_read.load_next) begin
                field_storage.bridge_regs.slverr_status_reg.oor_read.value <= field_combo.bridge_regs.slverr_status_reg.oor_read.next;
            end
        end
    end
    assign hwif_out.bridge_regs.slverr_status_reg.oor_read.value = field_storage.bridge_regs.slverr_status_reg.oor_read.value;
    // Field: axi2mram_bridge_registers.bridge_regs.slverr_status_reg.oor_write
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.bridge_regs.slverr_status_reg.oor_write.value;
        load_next_c = '0;
        if(decoded_reg_strb.bridge_regs.slverr_status_reg && !decoded_req_is_wr) begin // SW clear on read
            next_c = '0;
            load_next_c = '1;
        end else if(hwif_in.bridge_regs.slverr_status_reg.oor_write.hwset) begin // HW Set
            next_c = '1;
            load_next_c = '1;
        end
        field_combo.bridge_regs.slverr_status_reg.oor_write.next = next_c;
        field_combo.bridge_regs.slverr_status_reg.oor_write.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.bridge_regs.slverr_status_reg.oor_write.value <= 1'h0;
        end else begin
            if(field_combo.bridge_regs.slverr_status_reg.oor_write.load_next) begin
                field_storage.bridge_regs.slverr_status_reg.oor_write.value <= field_combo.bridge_regs.slverr_status_reg.oor_write.next;
            end
        end
    end
    assign hwif_out.bridge_regs.slverr_status_reg.oor_write.value = field_storage.bridge_regs.slverr_status_reg.oor_write.value;
    // Field: axi2mram_bridge_registers.bridge_regs.slverr_status_reg.mram_not_ready
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.bridge_regs.slverr_status_reg.mram_not_ready.value;
        load_next_c = '0;
        if(decoded_reg_strb.bridge_regs.slverr_status_reg && !decoded_req_is_wr) begin // SW clear on read
            next_c = '0;
            load_next_c = '1;
        end else if(hwif_in.bridge_regs.slverr_status_reg.mram_not_ready.hwset) begin // HW Set
            next_c = '1;
            load_next_c = '1;
        end
        field_combo.bridge_regs.slverr_status_reg.mram_not_ready.next = next_c;
        field_combo.bridge_regs.slverr_status_reg.mram_not_ready.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.bridge_regs.slverr_status_reg.mram_not_ready.value <= 1'h0;
        end else begin
            if(field_combo.bridge_regs.slverr_status_reg.mram_not_ready.load_next) begin
                field_storage.bridge_regs.slverr_status_reg.mram_not_ready.value <= field_combo.bridge_regs.slverr_status_reg.mram_not_ready.next;
            end
        end
    end
    assign hwif_out.bridge_regs.slverr_status_reg.mram_not_ready.value = field_storage.bridge_regs.slverr_status_reg.mram_not_ready.value;
    // Field: axi2mram_bridge_registers.bridge_regs.slverr_status_reg.mram_unpowered
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.bridge_regs.slverr_status_reg.mram_unpowered.value;
        load_next_c = '0;
        if(decoded_reg_strb.bridge_regs.slverr_status_reg && !decoded_req_is_wr) begin // SW clear on read
            next_c = '0;
            load_next_c = '1;
        end else if(hwif_in.bridge_regs.slverr_status_reg.mram_unpowered.hwset) begin // HW Set
            next_c = '1;
            load_next_c = '1;
        end
        field_combo.bridge_regs.slverr_status_reg.mram_unpowered.next = next_c;
        field_combo.bridge_regs.slverr_status_reg.mram_unpowered.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.bridge_regs.slverr_status_reg.mram_unpowered.value <= 1'h0;
        end else begin
            if(field_combo.bridge_regs.slverr_status_reg.mram_unpowered.load_next) begin
                field_storage.bridge_regs.slverr_status_reg.mram_unpowered.value <= field_combo.bridge_regs.slverr_status_reg.mram_unpowered.next;
            end
        end
    end
    assign hwif_out.bridge_regs.slverr_status_reg.mram_unpowered.value = field_storage.bridge_regs.slverr_status_reg.mram_unpowered.value;
    // Field: axi2mram_bridge_registers.bridge_regs.slverr_status_reg.maintenance
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.bridge_regs.slverr_status_reg.maintenance.value;
        load_next_c = '0;
        if(decoded_reg_strb.bridge_regs.slverr_status_reg && !decoded_req_is_wr) begin // SW clear on read
            next_c = '0;
            load_next_c = '1;
        end else if(hwif_in.bridge_regs.slverr_status_reg.maintenance.hwset) begin // HW Set
            next_c = '1;
            load_next_c = '1;
        end
        field_combo.bridge_regs.slverr_status_reg.maintenance.next = next_c;
        field_combo.bridge_regs.slverr_status_reg.maintenance.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.bridge_regs.slverr_status_reg.maintenance.value <= 1'h0;
        end else begin
            if(field_combo.bridge_regs.slverr_status_reg.maintenance.load_next) begin
                field_storage.bridge_regs.slverr_status_reg.maintenance.value <= field_combo.bridge_regs.slverr_status_reg.maintenance.next;
            end
        end
    end
    assign hwif_out.bridge_regs.slverr_status_reg.maintenance.value = field_storage.bridge_regs.slverr_status_reg.maintenance.value;
    // Field: axi2mram_bridge_registers.bridge_regs.slverr_status_reg.unrecoverable_error
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.bridge_regs.slverr_status_reg.unrecoverable_error.value;
        load_next_c = '0;
        if(decoded_reg_strb.bridge_regs.slverr_status_reg && !decoded_req_is_wr) begin // SW clear on read
            next_c = '0;
            load_next_c = '1;
        end else if(hwif_in.bridge_regs.slverr_status_reg.unrecoverable_error.hwset) begin // HW Set
            next_c = '1;
            load_next_c = '1;
        end
        field_combo.bridge_regs.slverr_status_reg.unrecoverable_error.next = next_c;
        field_combo.bridge_regs.slverr_status_reg.unrecoverable_error.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.bridge_regs.slverr_status_reg.unrecoverable_error.value <= 1'h0;
        end else begin
            if(field_combo.bridge_regs.slverr_status_reg.unrecoverable_error.load_next) begin
                field_storage.bridge_regs.slverr_status_reg.unrecoverable_error.value <= field_combo.bridge_regs.slverr_status_reg.unrecoverable_error.next;
            end
        end
    end
    assign hwif_out.bridge_regs.slverr_status_reg.unrecoverable_error.value = field_storage.bridge_regs.slverr_status_reg.unrecoverable_error.value;
    // Field: axi2mram_bridge_registers.bridge_regs.control_reg.disable_clock_gate
    always_comb begin
        automatic logic [3:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.bridge_regs.control_reg.disable_clock_gate.value;
        load_next_c = '0;
        if(decoded_reg_strb.bridge_regs.control_reg && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.bridge_regs.control_reg.disable_clock_gate.value & ~decoded_wr_biten[3:0]) | (decoded_wr_data[3:0] & decoded_wr_biten[3:0]);
            load_next_c = '1;
        end
        field_combo.bridge_regs.control_reg.disable_clock_gate.next = next_c;
        field_combo.bridge_regs.control_reg.disable_clock_gate.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.bridge_regs.control_reg.disable_clock_gate.value <= 4'h0;
        end else begin
            if(field_combo.bridge_regs.control_reg.disable_clock_gate.load_next) begin
                field_storage.bridge_regs.control_reg.disable_clock_gate.value <= field_combo.bridge_regs.control_reg.disable_clock_gate.next;
            end
        end
    end
    assign hwif_out.bridge_regs.control_reg.disable_clock_gate.value = field_storage.bridge_regs.control_reg.disable_clock_gate.value;
    // Field: axi2mram_bridge_registers.bridge_regs.control_reg.ecc_1bit_intr_mask
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.bridge_regs.control_reg.ecc_1bit_intr_mask.value;
        load_next_c = '0;
        if(decoded_reg_strb.bridge_regs.control_reg && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.bridge_regs.control_reg.ecc_1bit_intr_mask.value & ~decoded_wr_biten[4:4]) | (decoded_wr_data[4:4] & decoded_wr_biten[4:4]);
            load_next_c = '1;
        end
        field_combo.bridge_regs.control_reg.ecc_1bit_intr_mask.next = next_c;
        field_combo.bridge_regs.control_reg.ecc_1bit_intr_mask.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.bridge_regs.control_reg.ecc_1bit_intr_mask.value <= 1'h1;
        end else begin
            if(field_combo.bridge_regs.control_reg.ecc_1bit_intr_mask.load_next) begin
                field_storage.bridge_regs.control_reg.ecc_1bit_intr_mask.value <= field_combo.bridge_regs.control_reg.ecc_1bit_intr_mask.next;
            end
        end
    end
    assign hwif_out.bridge_regs.control_reg.ecc_1bit_intr_mask.value = field_storage.bridge_regs.control_reg.ecc_1bit_intr_mask.value;
    // Field: axi2mram_bridge_registers.bridge_regs.control_reg.ecc_2bit_intr_mask
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.bridge_regs.control_reg.ecc_2bit_intr_mask.value;
        load_next_c = '0;
        if(decoded_reg_strb.bridge_regs.control_reg && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.bridge_regs.control_reg.ecc_2bit_intr_mask.value & ~decoded_wr_biten[5:5]) | (decoded_wr_data[5:5] & decoded_wr_biten[5:5]);
            load_next_c = '1;
        end
        field_combo.bridge_regs.control_reg.ecc_2bit_intr_mask.next = next_c;
        field_combo.bridge_regs.control_reg.ecc_2bit_intr_mask.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.bridge_regs.control_reg.ecc_2bit_intr_mask.value <= 1'h0;
        end else begin
            if(field_combo.bridge_regs.control_reg.ecc_2bit_intr_mask.load_next) begin
                field_storage.bridge_regs.control_reg.ecc_2bit_intr_mask.value <= field_combo.bridge_regs.control_reg.ecc_2bit_intr_mask.next;
            end
        end
    end
    assign hwif_out.bridge_regs.control_reg.ecc_2bit_intr_mask.value = field_storage.bridge_regs.control_reg.ecc_2bit_intr_mask.value;
    // Field: axi2mram_bridge_registers.bridge_regs.control_reg.ecc_3bit_intr_mask
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.bridge_regs.control_reg.ecc_3bit_intr_mask.value;
        load_next_c = '0;
        if(decoded_reg_strb.bridge_regs.control_reg && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.bridge_regs.control_reg.ecc_3bit_intr_mask.value & ~decoded_wr_biten[6:6]) | (decoded_wr_data[6:6] & decoded_wr_biten[6:6]);
            load_next_c = '1;
        end
        field_combo.bridge_regs.control_reg.ecc_3bit_intr_mask.next = next_c;
        field_combo.bridge_regs.control_reg.ecc_3bit_intr_mask.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.bridge_regs.control_reg.ecc_3bit_intr_mask.value <= 1'h0;
        end else begin
            if(field_combo.bridge_regs.control_reg.ecc_3bit_intr_mask.load_next) begin
                field_storage.bridge_regs.control_reg.ecc_3bit_intr_mask.value <= field_combo.bridge_regs.control_reg.ecc_3bit_intr_mask.next;
            end
        end
    end
    assign hwif_out.bridge_regs.control_reg.ecc_3bit_intr_mask.value = field_storage.bridge_regs.control_reg.ecc_3bit_intr_mask.value;
    // Field: axi2mram_bridge_registers.bridge_regs.ecc_1bit_error_count_reg.count
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.bridge_regs.ecc_1bit_error_count_reg.count.value;
        load_next_c = '0;
        
        // HW Write
        next_c = hwif_in.bridge_regs.ecc_1bit_error_count_reg.count.next;
        load_next_c = '1;
        if(hwif_in.bridge_regs.ecc_1bit_error_count_reg.count.incr) begin // increment
            if(((33)'(next_c) + hwif_in.bridge_regs.ecc_1bit_error_count_reg.count.incrvalue) > 32'hffffffff) begin // up-counter saturated
                next_c = 32'hffffffff;
            end else begin
                next_c = next_c + hwif_in.bridge_regs.ecc_1bit_error_count_reg.count.incrvalue;
            end
            load_next_c = '1;
        end
        field_combo.bridge_regs.ecc_1bit_error_count_reg.count.incrthreshold = (field_storage.bridge_regs.ecc_1bit_error_count_reg.count.value >= 32'hffffffff);
        field_combo.bridge_regs.ecc_1bit_error_count_reg.count.incrsaturate = (field_storage.bridge_regs.ecc_1bit_error_count_reg.count.value >= 32'hffffffff);
        field_combo.bridge_regs.ecc_1bit_error_count_reg.count.next = next_c;
        field_combo.bridge_regs.ecc_1bit_error_count_reg.count.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.bridge_regs.ecc_1bit_error_count_reg.count.value <= 32'h0;
        end else begin
            if(field_combo.bridge_regs.ecc_1bit_error_count_reg.count.load_next) begin
                field_storage.bridge_regs.ecc_1bit_error_count_reg.count.value <= field_combo.bridge_regs.ecc_1bit_error_count_reg.count.next;
            end
        end
    end
    assign hwif_out.bridge_regs.ecc_1bit_error_count_reg.count.value = field_storage.bridge_regs.ecc_1bit_error_count_reg.count.value;
    // Field: axi2mram_bridge_registers.bridge_regs.ecc_2bit_error_count_reg.count
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.bridge_regs.ecc_2bit_error_count_reg.count.value;
        load_next_c = '0;
        
        // HW Write
        next_c = hwif_in.bridge_regs.ecc_2bit_error_count_reg.count.next;
        load_next_c = '1;
        if(hwif_in.bridge_regs.ecc_2bit_error_count_reg.count.incr) begin // increment
            if(((33)'(next_c) + hwif_in.bridge_regs.ecc_2bit_error_count_reg.count.incrvalue) > 32'hffffffff) begin // up-counter saturated
                next_c = 32'hffffffff;
            end else begin
                next_c = next_c + hwif_in.bridge_regs.ecc_2bit_error_count_reg.count.incrvalue;
            end
            load_next_c = '1;
        end
        field_combo.bridge_regs.ecc_2bit_error_count_reg.count.incrthreshold = (field_storage.bridge_regs.ecc_2bit_error_count_reg.count.value >= 32'hffffffff);
        field_combo.bridge_regs.ecc_2bit_error_count_reg.count.incrsaturate = (field_storage.bridge_regs.ecc_2bit_error_count_reg.count.value >= 32'hffffffff);
        field_combo.bridge_regs.ecc_2bit_error_count_reg.count.next = next_c;
        field_combo.bridge_regs.ecc_2bit_error_count_reg.count.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.bridge_regs.ecc_2bit_error_count_reg.count.value <= 32'h0;
        end else begin
            if(field_combo.bridge_regs.ecc_2bit_error_count_reg.count.load_next) begin
                field_storage.bridge_regs.ecc_2bit_error_count_reg.count.value <= field_combo.bridge_regs.ecc_2bit_error_count_reg.count.next;
            end
        end
    end
    assign hwif_out.bridge_regs.ecc_2bit_error_count_reg.count.value = field_storage.bridge_regs.ecc_2bit_error_count_reg.count.value;
    // Field: axi2mram_bridge_registers.bridge_regs.ecc_3bit_error_count_reg.count
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.bridge_regs.ecc_3bit_error_count_reg.count.value;
        load_next_c = '0;
        
        // HW Write
        next_c = hwif_in.bridge_regs.ecc_3bit_error_count_reg.count.next;
        load_next_c = '1;
        if(hwif_in.bridge_regs.ecc_3bit_error_count_reg.count.incr) begin // increment
            if(((33)'(next_c) + hwif_in.bridge_regs.ecc_3bit_error_count_reg.count.incrvalue) > 32'hffffffff) begin // up-counter saturated
                next_c = 32'hffffffff;
            end else begin
                next_c = next_c + hwif_in.bridge_regs.ecc_3bit_error_count_reg.count.incrvalue;
            end
            load_next_c = '1;
        end
        field_combo.bridge_regs.ecc_3bit_error_count_reg.count.incrthreshold = (field_storage.bridge_regs.ecc_3bit_error_count_reg.count.value >= 32'hffffffff);
        field_combo.bridge_regs.ecc_3bit_error_count_reg.count.incrsaturate = (field_storage.bridge_regs.ecc_3bit_error_count_reg.count.value >= 32'hffffffff);
        field_combo.bridge_regs.ecc_3bit_error_count_reg.count.next = next_c;
        field_combo.bridge_regs.ecc_3bit_error_count_reg.count.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.bridge_regs.ecc_3bit_error_count_reg.count.value <= 32'h0;
        end else begin
            if(field_combo.bridge_regs.ecc_3bit_error_count_reg.count.load_next) begin
                field_storage.bridge_regs.ecc_3bit_error_count_reg.count.value <= field_combo.bridge_regs.ecc_3bit_error_count_reg.count.next;
            end
        end
    end
    assign hwif_out.bridge_regs.ecc_3bit_error_count_reg.count.value = field_storage.bridge_regs.ecc_3bit_error_count_reg.count.value;
    // External region: axi2mram_bridge_registers.bank0_tregs
    assign hwif_out.bank0_tregs.req = decoded_reg_strb.bank0_tregs;
    assign hwif_out.bank0_tregs.addr = decoded_addr[7:0];
    assign hwif_out.bank0_tregs.req_is_wr = decoded_req_is_wr;
    assign hwif_out.bank0_tregs.wr_data = decoded_wr_data;
    assign hwif_out.bank0_tregs.wr_biten = decoded_wr_biten;
    // External region: axi2mram_bridge_registers.bank1_tregs
    assign hwif_out.bank1_tregs.req = decoded_reg_strb.bank1_tregs;
    assign hwif_out.bank1_tregs.addr = decoded_addr[7:0];
    assign hwif_out.bank1_tregs.req_is_wr = decoded_req_is_wr;
    assign hwif_out.bank1_tregs.wr_data = decoded_wr_data;
    assign hwif_out.bank1_tregs.wr_biten = decoded_wr_biten;
    // External region: axi2mram_bridge_registers.bank2_tregs
    assign hwif_out.bank2_tregs.req = decoded_reg_strb.bank2_tregs;
    assign hwif_out.bank2_tregs.addr = decoded_addr[7:0];
    assign hwif_out.bank2_tregs.req_is_wr = decoded_req_is_wr;
    assign hwif_out.bank2_tregs.wr_data = decoded_wr_data;
    assign hwif_out.bank2_tregs.wr_biten = decoded_wr_biten;
    // External region: axi2mram_bridge_registers.bank3_tregs
    assign hwif_out.bank3_tregs.req = decoded_reg_strb.bank3_tregs;
    assign hwif_out.bank3_tregs.addr = decoded_addr[7:0];
    assign hwif_out.bank3_tregs.req_is_wr = decoded_req_is_wr;
    assign hwif_out.bank3_tregs.wr_data = decoded_wr_data;
    assign hwif_out.bank3_tregs.wr_biten = decoded_wr_biten;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    always_comb begin
        automatic logic wr_ack;
        wr_ack = '0;
        wr_ack |= hwif_in.bank0_tregs.wr_ack;
        wr_ack |= hwif_in.bank1_tregs.wr_ack;
        wr_ack |= hwif_in.bank2_tregs.wr_ack;
        wr_ack |= hwif_in.bank3_tregs.wr_ack;
        external_wr_ack = wr_ack;
    end
    assign cpuif_wr_ack = external_wr_ack | (decoded_req & decoded_req_is_wr & ~decoded_strb_is_external);
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------
    logic readback_external_rd_ack_c;
    always_comb begin
        automatic logic rd_ack;
        rd_ack = '0;
        rd_ack |= hwif_in.bank0_tregs.rd_ack;
        rd_ack |= hwif_in.bank1_tregs.rd_ack;
        rd_ack |= hwif_in.bank2_tregs.rd_ack;
        rd_ack |= hwif_in.bank3_tregs.rd_ack;
        readback_external_rd_ack_c = rd_ack;
    end

    logic readback_external_rd_ack;

    assign readback_external_rd_ack = readback_external_rd_ack_c;

    logic readback_err;
    logic readback_done;
    logic [63:0] readback_data;

    // Assign readback values to a flattened array
    logic [63:0] readback_array[11];
    assign readback_array[0][1:0] = (decoded_reg_strb.bridge_regs.arbiter_mode_reg && !decoded_req_is_wr) ? field_storage.bridge_regs.arbiter_mode_reg.arbiter_mode.value : '0;
    assign readback_array[0][63:2] = '0;
    assign readback_array[1][0:0] = (decoded_reg_strb.bridge_regs.bridge_status_reg && !decoded_req_is_wr) ? hwif_in.bridge_regs.bridge_status_reg.axi_busy.next : '0;
    assign readback_array[1][3:1] = '0;
    assign readback_array[1][7:4] = (decoded_reg_strb.bridge_regs.bridge_status_reg && !decoded_req_is_wr) ? hwif_in.bridge_regs.bridge_status_reg.cmd_queue_active.next : '0;
    assign readback_array[1][11:8] = (decoded_reg_strb.bridge_regs.bridge_status_reg && !decoded_req_is_wr) ? hwif_in.bridge_regs.bridge_status_reg.mram_ready.next : '0;
    assign readback_array[1][63:12] = '0;
    assign readback_array[2][0:0] = (decoded_reg_strb.bridge_regs.slverr_status_reg && !decoded_req_is_wr) ? field_storage.bridge_regs.slverr_status_reg.oor_read.value : '0;
    assign readback_array[2][1:1] = (decoded_reg_strb.bridge_regs.slverr_status_reg && !decoded_req_is_wr) ? field_storage.bridge_regs.slverr_status_reg.oor_write.value : '0;
    assign readback_array[2][2:2] = (decoded_reg_strb.bridge_regs.slverr_status_reg && !decoded_req_is_wr) ? field_storage.bridge_regs.slverr_status_reg.mram_not_ready.value : '0;
    assign readback_array[2][3:3] = (decoded_reg_strb.bridge_regs.slverr_status_reg && !decoded_req_is_wr) ? field_storage.bridge_regs.slverr_status_reg.mram_unpowered.value : '0;
    assign readback_array[2][4:4] = (decoded_reg_strb.bridge_regs.slverr_status_reg && !decoded_req_is_wr) ? field_storage.bridge_regs.slverr_status_reg.maintenance.value : '0;
    assign readback_array[2][5:5] = (decoded_reg_strb.bridge_regs.slverr_status_reg && !decoded_req_is_wr) ? field_storage.bridge_regs.slverr_status_reg.unrecoverable_error.value : '0;
    assign readback_array[2][63:6] = '0;
    assign readback_array[3][3:0] = (decoded_reg_strb.bridge_regs.control_reg && !decoded_req_is_wr) ? field_storage.bridge_regs.control_reg.disable_clock_gate.value : '0;
    assign readback_array[3][4:4] = (decoded_reg_strb.bridge_regs.control_reg && !decoded_req_is_wr) ? field_storage.bridge_regs.control_reg.ecc_1bit_intr_mask.value : '0;
    assign readback_array[3][5:5] = (decoded_reg_strb.bridge_regs.control_reg && !decoded_req_is_wr) ? field_storage.bridge_regs.control_reg.ecc_2bit_intr_mask.value : '0;
    assign readback_array[3][6:6] = (decoded_reg_strb.bridge_regs.control_reg && !decoded_req_is_wr) ? field_storage.bridge_regs.control_reg.ecc_3bit_intr_mask.value : '0;
    assign readback_array[3][63:7] = '0;
    assign readback_array[4][31:0] = (decoded_reg_strb.bridge_regs.ecc_1bit_error_count_reg && !decoded_req_is_wr) ? field_storage.bridge_regs.ecc_1bit_error_count_reg.count.value : '0;
    assign readback_array[4][63:32] = '0;
    assign readback_array[5][31:0] = (decoded_reg_strb.bridge_regs.ecc_2bit_error_count_reg && !decoded_req_is_wr) ? field_storage.bridge_regs.ecc_2bit_error_count_reg.count.value : '0;
    assign readback_array[5][63:32] = '0;
    assign readback_array[6][31:0] = (decoded_reg_strb.bridge_regs.ecc_3bit_error_count_reg && !decoded_req_is_wr) ? field_storage.bridge_regs.ecc_3bit_error_count_reg.count.value : '0;
    assign readback_array[6][63:32] = '0;
    assign readback_array[7] = hwif_in.bank0_tregs.rd_ack ? hwif_in.bank0_tregs.rd_data : '0;
    assign readback_array[8] = hwif_in.bank1_tregs.rd_ack ? hwif_in.bank1_tregs.rd_data : '0;
    assign readback_array[9] = hwif_in.bank2_tregs.rd_ack ? hwif_in.bank2_tregs.rd_data : '0;
    assign readback_array[10] = hwif_in.bank3_tregs.rd_ack ? hwif_in.bank3_tregs.rd_data : '0;

    // Reduce the array
    always_comb begin
        automatic logic [63:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr & ~decoded_strb_is_external;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<11; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign external_rd_ack = readback_external_rd_ack;
    assign cpuif_rd_ack = readback_done | readback_external_rd_ack;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
