// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package axi2mram_bridge_registers_pkg;

    localparam AXI2MRAM_BRIDGE_REGISTERS_DATA_WIDTH = 64;
    localparam AXI2MRAM_BRIDGE_REGISTERS_MIN_ADDR_WIDTH = 11;
    localparam AXI2MRAM_BRIDGE_REGISTERS_SIZE = 'h4a0;

    typedef struct {
        logic next;
    } Axi2Mram_Regs__bridge_status_reg__axi_busy__in_t;

    typedef struct {
        logic [3:0] next;
    } Axi2Mram_Regs__bridge_status_reg__cmd_queue_active__in_t;

    typedef struct {
        logic [3:0] next;
    } Axi2Mram_Regs__bridge_status_reg__mram_ready__in_t;

    typedef struct {
        Axi2Mram_Regs__bridge_status_reg__axi_busy__in_t axi_busy;
        Axi2Mram_Regs__bridge_status_reg__cmd_queue_active__in_t cmd_queue_active;
        Axi2Mram_Regs__bridge_status_reg__mram_ready__in_t mram_ready;
    } Axi2Mram_Regs__bridge_status_reg__in_t;

    typedef struct {
        logic hwset;
    } Axi2Mram_Regs__slverr_status_reg__oor_read__in_t;

    typedef struct {
        logic hwset;
    } Axi2Mram_Regs__slverr_status_reg__oor_write__in_t;

    typedef struct {
        logic hwset;
    } Axi2Mram_Regs__slverr_status_reg__mram_not_ready__in_t;

    typedef struct {
        logic hwset;
    } Axi2Mram_Regs__slverr_status_reg__mram_unpowered__in_t;

    typedef struct {
        logic hwset;
    } Axi2Mram_Regs__slverr_status_reg__maintenance__in_t;

    typedef struct {
        logic hwset;
    } Axi2Mram_Regs__slverr_status_reg__unrecoverable_error__in_t;

    typedef struct {
        Axi2Mram_Regs__slverr_status_reg__oor_read__in_t oor_read;
        Axi2Mram_Regs__slverr_status_reg__oor_write__in_t oor_write;
        Axi2Mram_Regs__slverr_status_reg__mram_not_ready__in_t mram_not_ready;
        Axi2Mram_Regs__slverr_status_reg__mram_unpowered__in_t mram_unpowered;
        Axi2Mram_Regs__slverr_status_reg__maintenance__in_t maintenance;
        Axi2Mram_Regs__slverr_status_reg__unrecoverable_error__in_t unrecoverable_error;
    } Axi2Mram_Regs__slverr_status_reg__in_t;

    typedef struct {
        logic [31:0] next;
        logic incr;
        logic [3:0] incrvalue;
    } Axi2Mram_Regs__ecc_1bit_error_count_reg__count__in_t;

    typedef struct {
        Axi2Mram_Regs__ecc_1bit_error_count_reg__count__in_t count;
    } Axi2Mram_Regs__ecc_1bit_error_count_reg__in_t;

    typedef struct {
        logic [31:0] next;
        logic incr;
        logic [3:0] incrvalue;
    } Axi2Mram_Regs__ecc_2bit_error_count_reg__count__in_t;

    typedef struct {
        Axi2Mram_Regs__ecc_2bit_error_count_reg__count__in_t count;
    } Axi2Mram_Regs__ecc_2bit_error_count_reg__in_t;

    typedef struct {
        logic [31:0] next;
        logic incr;
        logic [3:0] incrvalue;
    } Axi2Mram_Regs__ecc_3bit_error_count_reg__count__in_t;

    typedef struct {
        Axi2Mram_Regs__ecc_3bit_error_count_reg__count__in_t count;
    } Axi2Mram_Regs__ecc_3bit_error_count_reg__in_t;

    typedef struct {
        Axi2Mram_Regs__bridge_status_reg__in_t bridge_status_reg;
        Axi2Mram_Regs__slverr_status_reg__in_t slverr_status_reg;
        Axi2Mram_Regs__ecc_1bit_error_count_reg__in_t ecc_1bit_error_count_reg;
        Axi2Mram_Regs__ecc_2bit_error_count_reg__in_t ecc_2bit_error_count_reg;
        Axi2Mram_Regs__ecc_3bit_error_count_reg__in_t ecc_3bit_error_count_reg;
    } Axi2Mram_Regs__in_t;

    typedef struct {
        logic rd_ack;
        logic [63:0] rd_data;
        logic wr_ack;
    } MRAM_Controller_Test_Regs__external__in_t;

    typedef struct {
        Axi2Mram_Regs__in_t bridge_regs;
        MRAM_Controller_Test_Regs__external__in_t bank0_tregs;
        MRAM_Controller_Test_Regs__external__in_t bank1_tregs;
        MRAM_Controller_Test_Regs__external__in_t bank2_tregs;
        MRAM_Controller_Test_Regs__external__in_t bank3_tregs;
    } axi2mram_bridge_registers__in_t;

    typedef struct {
        logic [1:0] value;
    } Axi2Mram_Regs__arbiter_mode_reg__arbiter_mode__out_t;

    typedef struct {
        Axi2Mram_Regs__arbiter_mode_reg__arbiter_mode__out_t arbiter_mode;
    } Axi2Mram_Regs__arbiter_mode_reg__out_t;

    typedef struct {
        logic value;
    } Axi2Mram_Regs__slverr_status_reg__oor_read__out_t;

    typedef struct {
        logic value;
    } Axi2Mram_Regs__slverr_status_reg__oor_write__out_t;

    typedef struct {
        logic value;
    } Axi2Mram_Regs__slverr_status_reg__mram_not_ready__out_t;

    typedef struct {
        logic value;
    } Axi2Mram_Regs__slverr_status_reg__mram_unpowered__out_t;

    typedef struct {
        logic value;
    } Axi2Mram_Regs__slverr_status_reg__maintenance__out_t;

    typedef struct {
        logic value;
    } Axi2Mram_Regs__slverr_status_reg__unrecoverable_error__out_t;

    typedef struct {
        Axi2Mram_Regs__slverr_status_reg__oor_read__out_t oor_read;
        Axi2Mram_Regs__slverr_status_reg__oor_write__out_t oor_write;
        Axi2Mram_Regs__slverr_status_reg__mram_not_ready__out_t mram_not_ready;
        Axi2Mram_Regs__slverr_status_reg__mram_unpowered__out_t mram_unpowered;
        Axi2Mram_Regs__slverr_status_reg__maintenance__out_t maintenance;
        Axi2Mram_Regs__slverr_status_reg__unrecoverable_error__out_t unrecoverable_error;
    } Axi2Mram_Regs__slverr_status_reg__out_t;

    typedef struct {
        logic [3:0] value;
    } Axi2Mram_Regs__control_reg__disable_clock_gate__out_t;

    typedef struct {
        logic value;
    } Axi2Mram_Regs__control_reg__ecc_1bit_intr_mask__out_t;

    typedef struct {
        logic value;
    } Axi2Mram_Regs__control_reg__ecc_2bit_intr_mask__out_t;

    typedef struct {
        logic value;
    } Axi2Mram_Regs__control_reg__ecc_3bit_intr_mask__out_t;

    typedef struct {
        Axi2Mram_Regs__control_reg__disable_clock_gate__out_t disable_clock_gate;
        Axi2Mram_Regs__control_reg__ecc_1bit_intr_mask__out_t ecc_1bit_intr_mask;
        Axi2Mram_Regs__control_reg__ecc_2bit_intr_mask__out_t ecc_2bit_intr_mask;
        Axi2Mram_Regs__control_reg__ecc_3bit_intr_mask__out_t ecc_3bit_intr_mask;
    } Axi2Mram_Regs__control_reg__out_t;

    typedef struct {
        logic [31:0] value;
    } Axi2Mram_Regs__ecc_1bit_error_count_reg__count__out_t;

    typedef struct {
        Axi2Mram_Regs__ecc_1bit_error_count_reg__count__out_t count;
    } Axi2Mram_Regs__ecc_1bit_error_count_reg__out_t;

    typedef struct {
        logic [31:0] value;
    } Axi2Mram_Regs__ecc_2bit_error_count_reg__count__out_t;

    typedef struct {
        Axi2Mram_Regs__ecc_2bit_error_count_reg__count__out_t count;
    } Axi2Mram_Regs__ecc_2bit_error_count_reg__out_t;

    typedef struct {
        logic [31:0] value;
    } Axi2Mram_Regs__ecc_3bit_error_count_reg__count__out_t;

    typedef struct {
        Axi2Mram_Regs__ecc_3bit_error_count_reg__count__out_t count;
    } Axi2Mram_Regs__ecc_3bit_error_count_reg__out_t;

    typedef struct {
        Axi2Mram_Regs__arbiter_mode_reg__out_t arbiter_mode_reg;
        Axi2Mram_Regs__slverr_status_reg__out_t slverr_status_reg;
        Axi2Mram_Regs__control_reg__out_t control_reg;
        Axi2Mram_Regs__ecc_1bit_error_count_reg__out_t ecc_1bit_error_count_reg;
        Axi2Mram_Regs__ecc_2bit_error_count_reg__out_t ecc_2bit_error_count_reg;
        Axi2Mram_Regs__ecc_3bit_error_count_reg__out_t ecc_3bit_error_count_reg;
    } Axi2Mram_Regs__out_t;

    typedef struct {
        logic req;
        logic [7:0] addr;
        logic req_is_wr;
        logic [63:0] wr_data;
        logic [63:0] wr_biten;
    } MRAM_Controller_Test_Regs__external__out_t;

    typedef struct {
        Axi2Mram_Regs__out_t bridge_regs;
        MRAM_Controller_Test_Regs__external__out_t bank0_tregs;
        MRAM_Controller_Test_Regs__external__out_t bank1_tregs;
        MRAM_Controller_Test_Regs__external__out_t bank2_tregs;
        MRAM_Controller_Test_Regs__external__out_t bank3_tregs;
    } axi2mram_bridge_registers__out_t;
endpackage
