// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package HB_Reg_pkg;

    localparam HB_REG_DATA_WIDTH = 32;
    localparam HB_REG_MIN_ADDR_WIDTH = 3;

    typedef struct {
        logic next;
    } HB_Reg__HB_STATUS__busy__in_t;

    typedef struct {
        HB_Reg__HB_STATUS__busy__in_t busy;
    } HB_Reg__HB_STATUS__in_t;

    typedef struct {
        HB_Reg__HB_STATUS__in_t HB_STATUS;
    } HB_Reg__in_t;

    typedef struct {
        logic [3:0] value;
    } HB_Reg__HB_CTRL__initial_latency__out_t;

    typedef struct {
        logic [5:0] value;
    } HB_Reg__HB_CTRL__burst_length__out_t;

    typedef struct {
        logic value;
    } HB_Reg__HB_CTRL__burst_type__out_t;

    typedef struct {
        logic value;
    } HB_Reg__HB_CTRL__txn_32_64__out_t;

    typedef struct {
        logic value;
    } HB_Reg__HB_CTRL__reg_access__out_t;

    typedef struct {
        HB_Reg__HB_CTRL__initial_latency__out_t initial_latency;
        HB_Reg__HB_CTRL__burst_length__out_t burst_length;
        HB_Reg__HB_CTRL__burst_type__out_t burst_type;
        HB_Reg__HB_CTRL__txn_32_64__out_t txn_32_64;
        HB_Reg__HB_CTRL__reg_access__out_t reg_access;
    } HB_Reg__HB_CTRL__out_t;

    typedef struct {
        logic value;
    } HB_Reg__HB_STATUS__busy__out_t;

    typedef struct {
        HB_Reg__HB_STATUS__busy__out_t busy;
    } HB_Reg__HB_STATUS__out_t;

    typedef struct {
        HB_Reg__HB_CTRL__out_t HB_CTRL;
        HB_Reg__HB_STATUS__out_t HB_STATUS;
    } HB_Reg__out_t;
endpackage