"""
Copyright: Copyright (c) 2026 Ainekko, Co. All rights reserved.
Author: Vijayvithal <jvs@nekko.ai>

Comprehensive RWDS / DQ output-enable and byte-enable verification.

Register address map (sccr.rdl: regwidth=64, alignment=64 → 8 bytes/reg):
  0x00  ID0
  0x08  ID1
  0x10  CFG              InitialLatency[7:4]   (used by setLatency)
  0x18  xspi_status      wip[0]                (used by _wait_wip)
  0x20  xspi_control     interrupt_enable[1]
  0x28  xspi_rates       cmd_rate / addr_rate / data_rate
  0x30  interrupt_status axi_resp[1:0], read_underflow[2], write_overflow[3]  (rclr)

OE verification strategy
─────────────────────────
The driver has a built-in checker activated by ``env.cmd.check_enables = True``.
At every byte clock edge ``_check_oe(rwds_ena, dq_ena)`` asserts:

    bus.rwds_out_ena == rwds_ena
    bus.dq_out_ena   == dq_ena

The driver calls it with:
  Phase       rwds_ena  dq_ena   Meaning
  ──────────  ────────  ──────   ──────────────────────────────────────
  CMD / EXT      1        0      DUT drives RWDS=0 (idle), host drives DQ
  ADDR           0        0      Host drives both DQ and RWDS
  WRITE DATA     0        0      Host drives DQ; host drives RWDS as byte-enable
  READ DATA      1        1      DUT drives DQ (data) and RWDS (DS strobe)

Setting ``check_enables = True`` makes each byte-clock edge an inline assertion.
No custom monitor class is needed for OE — the driver handles it.

RWDS_IN waveform verification
──────────────────────────────
``RwdsInSampler`` captures ``xspi_rwds_in`` at every clock edge while CS# is low.
Because ``_write_byte`` sets ``rwds_in`` once per byte (before the byte's clocks),
the captured sequence can be sliced using mode-dependent edge counts to extract
the data-phase values and compare them against the supplied mask.

Edge counts per byte write call:
  Mode.S1 → 16  (8 iterations × rising+falling)
  Mode.D1 →  8  (4 iterations × rising+falling)
  Mode.S4 →  4  (2 iterations × rising+falling)
  Mode.D4 →  2  (1 rising + 1 falling)
  Mode.S8 →  2  (1 rising + 1 falling)
  Mode.D8 →  1  (1 Edge(any))

Functional correctness
───────────────────────
After a masked write, memory must satisfy for each byte i:
  mask[i] = False  →  memory[i] == new_val[i]    (byte WAS written)
  mask[i] = True   →  memory[i] == orig_val[i]   (byte was MASKED)
"""

import cocotb
from cocotb.triggers import RisingEdge, FallingEdge, Edge, Timer
from env import Env
from cocotbext.xspi.types import Mode, Format, Cmd, command_table, format_table
import random

random.seed(0xBEEF0001)

# ── Register addresses (sccr.rdl regwidth=64, alignment=64) ──────────────────
REG_CFG              = 0x10   # InitialLatency[7:4]
REG_XSPI_STATUS      = 0x18   # wip[0]
REG_XSPI_CONTROL     = 0x20   # interrupt_enable[1]
REG_XSPI_RATES       = 0x28
REG_INTERRUPT_STATUS = 0x30   # axi_resp[1:0], read_underflow, write_overflow

# ── Constants ─────────────────────────────────────────────────────────────────
MEM_BYTES  = 8          # one xSPI memory word = 64 bits
WRITE      = False      # rwds_in = 0  →  byte IS written
MASK_BYTE  = True       # rwds_in = 1  →  byte is NOT written

# Modes that support write-with-mask (DDR/SDR modes with RWDS)
WRITE_MODES = [
    (Mode.S1, Mode.S1, Mode.S1),
    (Mode.S4, Mode.D4, Mode.D4),
    (Mode.D4, Mode.D4, Mode.D4),
    (Mode.S8, Mode.S8, Mode.S8),
    (Mode.D8, Mode.D8, Mode.D8),
]

CORNER_DATA = [
    0xAABBCCDDEEFF0011,
    0x0000000000000000,
    0xFFFFFFFFFFFFFFFF,
    0xAA55AA55AA55AA55,
    0x5555555555555555,
    0x0102030405060708,
    0xFEDCBA9876543210,
    0xF0F0F0F0F0F0F0F0,
]

random.seed(0xBEEF0001)
ADDRS = [random.randint(0, 2**28) & 0xfffffff8 for _ in range(60)]


# ── Helpers ───────────────────────────────────────────────────────────────────

async def _boot(dut, default_mode_pin: int) -> Env:
    """Standard boot sequence matching test_default.py pattern."""
    dut.cfg_default_mode_m.value = default_mode_pin
    env = Env(dut)
    env.cmd.set_Default_Mode(default_mode_pin)
    await env.boot()
    return env


def _expected_bytes(orig: int, new: int, mask: list) -> bytes:
    """Return expected 8-byte memory content after a masked write.

    mask[i] = WRITE (False) → byte i = new_val byte i
    mask[i] = MASK  (True)  → byte i = orig_val byte i  (unchanged)
    Byte 0 = least-significant byte.
    """
    ob = list(orig.to_bytes(MEM_BYTES, "little"))
    nb = list(new.to_bytes(MEM_BYTES, "little"))
    return bytes(nb[i] if not mask[i] else ob[i] for i in range(MEM_BYTES))


def _clocks_per_byte_write(mode: Mode) -> int:
    """Total clock edges generated by _write_byte() for one byte in given mode.

    Derived from master_driver._write_byte() implementation:
      S1: 8 × (RisingEdge + FallingEdge) = 16
      D1: 4 × (RisingEdge + FallingEdge) =  8
      S4: 2 × (RisingEdge + FallingEdge) =  4
      D4: 1 × (RisingEdge + FallingEdge) =  2
      S8: 1 × (RisingEdge + FallingEdge) =  2
      D8: 1 × Edge(any)                  =  1
    """
    return {
        Mode.S1: 16,
        Mode.D1:  8,
        Mode.S4:  4,
        Mode.D4:  2,
        Mode.S8:  2,
        Mode.D8:  1,
    }[mode]


def _write_mem_preamble_edges(cmd_mode: Mode, addr_mode: Mode,
                               has_ext: bool, n_addr: int) -> int:
    """Number of clock edges before the first data byte for write_Mem.

    WriteMEM format (D1 for non-S1, K0 for S1):
      D1: extension=True,  address=4 bytes
      K0: extension=False, address=4 bytes
    """
    cpb_cmd  = _clocks_per_byte_write(cmd_mode)
    cpb_addr = _clocks_per_byte_write(addr_mode)
    ext_edges = cpb_cmd if has_ext else 0
    return cpb_cmd + ext_edges + n_addr * cpb_addr


# ── RwdsInSampler ─────────────────────────────────────────────────────────────

class RwdsInSampler:
    """Captures xspi_rwds_in at every clock edge while CS# is asserted.

    Usage:
        sam = RwdsInSampler(dut)
        sam.start()
        await env.cmd.write_Mem(addr, data, mask=mask)
        sam.stop()
        data_vals = sam.data_phase_values(cmd_mode, addr_mode, data_mode, has_ext=True)
        assert data_vals == [int(m) for m in mask]
    """

    def __init__(self, dut):
        self.dut = dut
        self._raw: list = []    # [(time_ns, rwds_in_val)] sampled while csn=0
        self._task = None

    def start(self):
        self._raw = []
        self._task = cocotb.start_soon(self._run())

    def stop(self):
        if self._task is not None:
            self._task.cancel()
            self._task = None

    async def _run(self):
        while True:
            await Edge(self.dut.xspi_clk)
            if int(self.dut.xspi_csn.value) == 0:
                t = cocotb.utils.get_sim_time("ns")
                v = int(self.dut.xspi_rwds_in.value)
                self._raw.append((t, v))

    def all_values(self) -> list:
        """All captured (time_ns, rwds_in) pairs while CS# was low."""
        return list(self._raw)

    def data_phase_values(self, cmd_mode: Mode, addr_mode: Mode,
                          data_mode: Mode, has_ext: bool,
                          n_addr: int, n_data_bytes: int) -> list:
        """Extract one rwds_in value per data byte from the captured sequence.

        Uses the first edge of each data byte (all edges within a byte carry
        the same rwds_in value since _write_byte sets it once per byte call).

        Returns a list of int (0 or 1), one per data byte.
        """
        preamble = _write_mem_preamble_edges(
            cmd_mode, addr_mode, has_ext, n_addr
        )
        cpb_data = _clocks_per_byte_write(data_mode)
        raw_vals = [v for _, v in self._raw]

        result = []
        for byte_idx in range(n_data_bytes):
            edge_idx = preamble + byte_idx * cpb_data
            if edge_idx < len(raw_vals):
                result.append(raw_vals[edge_idx])
            else:
                cocotb.log.warning(
                    f"RwdsInSampler: insufficient samples for byte {byte_idx} "
                    f"(edge_idx={edge_idx}, total={len(raw_vals)})"
                )
                result.append(None)
        return result

    def assert_all_zero_preamble(self, cmd_mode: Mode, addr_mode: Mode,
                                  has_ext: bool, n_addr: int, tag: str = ""):
        """Assert that every preamble (CMD/EXT/ADDR) edge has rwds_in=0."""
        preamble = _write_mem_preamble_edges(
            cmd_mode, addr_mode, has_ext, n_addr
        )
        raw_vals = [v for _, v in self._raw]
        for idx in range(min(preamble, len(raw_vals))):
            assert raw_vals[idx] == 0, (
                f"{tag} rwds_in={raw_vals[idx]} at preamble edge {idx} "
                f"(expected 0: CMD/EXT/ADDR must not assert byte-enable)"
            )

    def log_sequence(self, tag: str = ""):
        vals = [v for _, v in self._raw]
        cocotb.log.info(
            f"  {tag} rwds_in sequence ({len(vals)} edges): "
            + "".join(str(v) for v in vals)
        )


# ═══════════════════════════════════════════════════════════════════════════════
# GROUP 1 – OE inline checks (check_enables=True)
#
# Setting check_enables=True activates _check_oe() at every byte clock edge.
# Any OE protocol violation raises an AssertionError inside the driver.
# ═══════════════════════════════════════════════════════════════════════════════

@cocotb.test(timeout_time=40000, timeout_unit="ns")
@cocotb.parametrize(
    mode=WRITE_MODES,
    latency=[8, 17],
    default_mode_pin=[1, 2, 3],
)
async def test_oe_write_transaction(dut, mode, latency, default_mode_pin):
    """OE-W: dq_out_ena=0 and rwds_out_ena=0 throughout write DATA phase.

    CMD/EXT phases: rwds_out_ena=1, dq_out_ena=0  (DUT drives RWDS idle-low)
    ADDR phase:     rwds_out_ena=0, dq_out_ena=0  (host drives both)
    WRITE DATA:     rwds_out_ena=0, dq_out_ena=0  (host drives DQ + RWDS mask)

    check_enables=True activates _check_oe() at every byte clock.
    Any violation raises AssertionError inside the driver.
    """
    cocotb.log.info(
        f"OE-W write {mode[0].name}-{mode[1].name}-{mode[2].name} "
        f"latency={latency} pin={default_mode_pin}"
    )
    env = await _boot(dut, default_mode_pin)
    await env.cmd.setLatency(latency)
    assert int(dut.dut.latency_count.value) == latency
    await env.cmd.setRate(*mode)

    # Activate built-in OE checker
    env.cmd.check_enables = True

    for i in range(3):
        addr = ADDRS[i]
        val  = CORNER_DATA[i]
        cocotb.log.info(
            f"  write {i} addr=0x{addr:08x} data=0x{val:016x}"
        )
        # driver will assert OE correctness inline at every byte clock
        await env.cmd.write_Mem(addr, val.to_bytes(MEM_BYTES, "little"))

    env.cmd.check_enables = False
    await env.assert_no_xspi_errors(msg=f"OE-W mode={mode[0].name}")


@cocotb.test(timeout_time=40000, timeout_unit="ns")
@cocotb.parametrize(
    mode=WRITE_MODES,
    latency=[8, 17],
    default_mode_pin=[1, 2, 3],
)
async def test_oe_masked_write_transaction(dut, mode, latency, default_mode_pin):
    """OE-WM: OE behaviour must be identical for masked writes.

    Even with all bytes masked (rwds_in=1), the DUT must keep
    dq_out_ena=0 and rwds_out_ena=0 during the write DATA phase.
    """
    cocotb.log.info(
        f"OE-WM masked write OE {mode[0].name} latency={latency} pin={default_mode_pin}"
    )
    env = await _boot(dut, default_mode_pin)
    await env.cmd.setLatency(latency)
    assert int(dut.dut.latency_count.value) == latency
    await env.cmd.setRate(*mode)

    env.cmd.check_enables = True

    masks = [
        [MASK_BYTE] * MEM_BYTES,                                        # all masked
        [WRITE, MASK_BYTE] * (MEM_BYTES // 2),                         # alternating
        [WRITE]*4 + [MASK_BYTE]*4,                                      # lower half
    ]
    for i, mask in enumerate(masks):
        addr = ADDRS[3 + i]
        val  = CORNER_DATA[i]
        cocotb.log.info(
            f"  masked-write {i}: mask={[int(m) for m in mask]}"
        )
        await env.cmd.write_Mem(addr, val.to_bytes(MEM_BYTES, "little"), mask=mask)

    env.cmd.check_enables = False
    await env.assert_no_xspi_errors(msg=f"OE-WM mode={mode[0].name}")


@cocotb.test(timeout_time=40000, timeout_unit="ns")
@cocotb.parametrize(
    mode=WRITE_MODES,
    latency=[8, 17],
    default_mode_pin=[1, 2, 3],
)
async def test_oe_read_transaction(dut, mode, latency, default_mode_pin):
    """OE-R: dq_out_ena=1 AND rwds_out_ena=1 throughout read DATA phase.

    CMD/EXT/ADDR/LATENCY: rwds_out_ena=1, dq_out_ena=0
    READ DATA:            rwds_out_ena=1, dq_out_ena=1  (DUT drives DS + data)

    _read_byte_ds calls _check_oe(1,1) at every data byte edge.
    _write_byte (cmd/ext/addr phases) calls _check_oe(1,0) or _check_oe(0,0).
    """
    cocotb.log.info(
        f"OE-R read {mode[0].name}-{mode[1].name}-{mode[2].name} "
        f"latency={latency} pin={default_mode_pin}"
    )
    env = await _boot(dut, default_mode_pin)
    await env.cmd.setLatency(latency)
    assert int(dut.dut.latency_count.value) == latency
    await env.cmd.setRate(*mode)

    env.cmd.check_enables = True

    for i in range(3):
        addr = ADDRS[6 + i]
        val  = CORNER_DATA[i]
        env.axi_ram.write(addr, list(val.to_bytes(MEM_BYTES, "little")))
        rdata = await env.cmd.read_Mem(addr)
        assert hex(int.from_bytes(rdata, "little")) == hex(val), (
            f"OE-R read mismatch i={i} addr=0x{addr:08x} "
            f"expected=0x{val:016x} got=0x{int.from_bytes(rdata,'little'):016x}"
        )

    env.cmd.check_enables = False
    await env.assert_no_xspi_errors(msg=f"OE-R mode={mode[0].name}")


@cocotb.test(timeout_time=40000, timeout_unit="ns")
@cocotb.parametrize(
    mode=WRITE_MODES,
    latency=[8, 17],
    default_mode_pin=[1, 2, 3],
)
async def test_oe_write_then_read(dut, mode, latency, default_mode_pin):
    """OE-WR: Write immediately followed by read — OE must be correct for both.

    Verifies OE state machine resets properly between transactions
    (write: rwds_oe=0 in data phase → read: rwds_oe=1 in data phase).
    """
    cocotb.log.info(
        f"OE-WR write→read {mode[0].name} latency={latency} pin={default_mode_pin}"
    )
    env = await _boot(dut, default_mode_pin)
    await env.cmd.setLatency(latency)
    assert int(dut.dut.latency_count.value) == latency
    await env.cmd.setRate(*mode)

    env.cmd.check_enables = True

    addr = ADDRS[9]
    val  = CORNER_DATA[4]

    # Write (OE check: rwds_oe=0 in data, rwds_oe=1 in cmd/ext)
    await env.cmd.write_Mem(addr, val.to_bytes(MEM_BYTES, "little"))

    # Read immediately (OE check: rwds_oe=1 in cmd/ext AND data)
    rdata = await env.cmd.read_Mem(addr)
    assert hex(int.from_bytes(rdata, "little")) == hex(val), (
        f"OE-WR read-back mismatch: expected=0x{val:016x} "
        f"got=0x{int.from_bytes(rdata,'little'):016x}"
    )

    env.cmd.check_enables = False
    await env.assert_no_xspi_errors(msg=f"OE-WR mode={mode[0].name}")


# ═══════════════════════════════════════════════════════════════════════════════
# GROUP 2 – RWDS_IN waveform: value matches mask per byte
# ═══════════════════════════════════════════════════════════════════════════════

@cocotb.test(timeout_time=40000, timeout_unit="ns")
@cocotb.parametrize(
    mode=WRITE_MODES,
    default_mode_pin=[1, 2, 3],
)
async def test_rwds_in_all_zero_unmasked_write(dut, mode, default_mode_pin):
    """RWDS-W2: write_Mem(mask=None) → rwds_in=0 at every data-phase clock edge.

    BUG-9 in the old driver: masked=None was assigned directly to a LogicArray,
    producing undefined behaviour. The fix is ``msk = False`` when mask is None
    (line 133 of the updated master_driver.py). This test confirms the fix.
    """
    cocotb.log.info(
        f"RWDS-W2 rwds_in=0 unmasked {mode[0].name} pin={default_mode_pin}"
    )
    env = await _boot(dut, default_mode_pin)
    await env.cmd.setLatency(17)
    assert int(dut.dut.latency_count.value) == 17
    await env.cmd.setRate(*mode)
    env.cmd.check_enables = False   # functional focus, OE checked separately

    # Determine format for WriteMEM
    if env.cmd.cmd_mode in [Mode.S1, Mode.D1]:
        fmt = command_table[Cmd.WriteMEM]["fmt_1s"]   # K0: no extension, 4B addr
    else:
        fmt = command_table[Cmd.WriteMEM]["fmt_8s"]   # D1: extension, 4B addr
    has_ext = format_table[fmt]["extension"]
    n_addr  = format_table[fmt]["address"]

    sam = RwdsInSampler(dut)
    sam.start()

    addr = ADDRS[10]
    val  = 0x0102030405060708
    await env.cmd.write_Mem(addr, val.to_bytes(MEM_BYTES, "little"))
    # mask=None → every byte written → rwds_in must be 0

    for _ in range(4):
        await RisingEdge(dut.xspi_clk)
    sam.stop()
    sam.log_sequence(tag=f"RWDS-W2 {mode[0].name}")

    data_vals = sam.data_phase_values(
        mode[0], mode[1], mode[2], has_ext, n_addr, MEM_BYTES
    )
    cocotb.log.info(f"  data-phase rwds_in per byte: {data_vals}")

    for i, v in enumerate(data_vals):
        assert v == 0, (
            f"RWDS-W2 BUG: byte[{i}] rwds_in={v} (expected 0). "
            f"masked=None must map to rwds_in=0, not undefined. "
            f"mode={mode[0].name}"
        )

    rv = await env.cmd.read_Mem(addr)
    assert hex(int.from_bytes(rv, "little")) == hex(val), (
        f"RWDS-W2 write-back mismatch: expected=0x{val:016x} "
        f"got=0x{int.from_bytes(rv,'little'):016x}"
    )
    await env.assert_no_xspi_errors(msg="RWDS-W2")


@cocotb.test(timeout_time=40000, timeout_unit="ns")
@cocotb.parametrize(
    mode=WRITE_MODES,
    default_mode_pin=[1, 2, 3],
)
async def test_rwds_in_all_one_all_masked(dut, mode, default_mode_pin):
    """RWDS-W3: All bytes masked → rwds_in=1 at every data-phase clock edge."""
    cocotb.log.info(
        f"RWDS-W3 rwds_in=1 all-masked {mode[0].name} pin={default_mode_pin}"
    )
    env = await _boot(dut, default_mode_pin)
    await env.cmd.setLatency(17)
    assert int(dut.dut.latency_count.value) == 17
    await env.cmd.setRate(*mode)
    env.cmd.check_enables = False

    if env.cmd.cmd_mode in [Mode.S1, Mode.D1]:
        fmt = command_table[Cmd.WriteMEM]["fmt_1s"]
    else:
        fmt = command_table[Cmd.WriteMEM]["fmt_8s"]
    has_ext = format_table[fmt]["extension"]
    n_addr  = format_table[fmt]["address"]

    sam = RwdsInSampler(dut)
    sam.start()

    mask = [MASK_BYTE] * MEM_BYTES
    addr = ADDRS[11]
    val  = 0xAABBCCDDEEFF0011
    await env.cmd.write_Mem(addr, val.to_bytes(MEM_BYTES, "little"), mask=mask)

    for _ in range(4):
        await RisingEdge(dut.xspi_clk)
    sam.stop()
    sam.log_sequence(tag=f"RWDS-W3 {mode[0].name}")

    data_vals = sam.data_phase_values(
        mode[0], mode[1], mode[2], has_ext, n_addr, MEM_BYTES
    )
    cocotb.log.info(f"  data-phase rwds_in per byte: {data_vals}")

    for i, v in enumerate(data_vals):
        assert v == 1, (
            f"RWDS-W3 byte[{i}] rwds_in={v} (expected 1 for all-masked write) "
            f"mode={mode[0].name}"
        )

    await env.assert_no_xspi_errors(msg="RWDS-W3")


@cocotb.test(timeout_time=40000, timeout_unit="ns")
@cocotb.parametrize(
    mode=WRITE_MODES,
    default_mode_pin=[1, 2, 3],
)
async def test_rwds_in_alternating_mask(dut, mode, default_mode_pin):
    """RWDS-W4: Alternating mask → rwds_in sequence = 0,1,0,1,0,1,0,1.

    Verifies that rwds_in changes correctly from byte to byte — the driver
    must update rwds_in before each byte's first clock, not just once.
    """
    cocotb.log.info(
        f"RWDS-W4 alternating mask {mode[0].name} pin={default_mode_pin}"
    )
    env = await _boot(dut, default_mode_pin)
    await env.cmd.setLatency(17)
    assert int(dut.dut.latency_count.value) == 17
    await env.cmd.setRate(*mode)
    env.cmd.check_enables = False

    if env.cmd.cmd_mode in [Mode.S1, Mode.D1]:
        fmt = command_table[Cmd.WriteMEM]["fmt_1s"]
    else:
        fmt = command_table[Cmd.WriteMEM]["fmt_8s"]
    has_ext = format_table[fmt]["extension"]
    n_addr  = format_table[fmt]["address"]

    # Also check preamble (CMD/EXT/ADDR) stays 0
    sam = RwdsInSampler(dut)
    sam.start()

    mask = [WRITE, MASK_BYTE] * 4   # [F,T,F,T,F,T,F,T]
    addr = ADDRS[12]
    val  = 0x0102030405060708
    await env.cmd.write_Mem(addr, val.to_bytes(MEM_BYTES, "little"), mask=mask)

    for _ in range(4):
        await RisingEdge(dut.xspi_clk)
    sam.stop()
    sam.log_sequence(tag=f"RWDS-W4 {mode[0].name}")

    # Preamble edges must all be 0
    sam.assert_all_zero_preamble(
        mode[0], mode[1], has_ext, n_addr,
        tag=f"RWDS-W4 {mode[0].name} preamble"
    )

    # Data-phase edges must match mask
    expected_seq = [int(m) for m in mask]
    data_vals = sam.data_phase_values(
        mode[0], mode[1], mode[2], has_ext, n_addr, MEM_BYTES
    )
    cocotb.log.info(
        f"  expected: {expected_seq}\n"
        f"  got:      {data_vals}"
    )
    for i, (exp, got) in enumerate(zip(expected_seq, data_vals)):
        assert got == exp, (
            f"RWDS-W4 byte[{i}] rwds_in={got} expected={exp} "
            f"(alternating mask pattern mismatch) mode={mode[0].name}"
        )

    await env.assert_no_xspi_errors(msg="RWDS-W4")


@cocotb.test(timeout_time=40000, timeout_unit="ns")
@cocotb.parametrize(
    mode=WRITE_MODES,
    default_mode_pin=[1, 2, 3],
)
async def test_rwds_in_preamble_always_zero(dut, mode, default_mode_pin):
    """RWDS-P1: rwds_in=0 during CMD, EXT, ADDR phases (even with all-masked data).

    The byte-enable RWDS is only meaningful during write DATA bytes.
    Even when all data bytes are masked (rwds_in=1 during data), the
    preamble bytes must see rwds_in=0.
    """
    cocotb.log.info(
        f"RWDS-P1 preamble=0 {mode[0].name} pin={default_mode_pin}"
    )
    env = await _boot(dut, default_mode_pin)
    await env.cmd.setLatency(17)
    assert int(dut.dut.latency_count.value) == 17
    await env.cmd.setRate(*mode)
    env.cmd.check_enables = False

    if env.cmd.cmd_mode in [Mode.S1, Mode.D1]:
        fmt = command_table[Cmd.WriteMEM]["fmt_1s"]
    else:
        fmt = command_table[Cmd.WriteMEM]["fmt_8s"]
    has_ext = format_table[fmt]["extension"]
    n_addr  = format_table[fmt]["address"]

    sam = RwdsInSampler(dut)
    sam.start()

    mask = [MASK_BYTE] * MEM_BYTES
    addr = ADDRS[13]
    val  = 0xDEADBEEFCAFEBABE
    await env.cmd.write_Mem(addr, val.to_bytes(MEM_BYTES, "little"), mask=mask)

    for _ in range(4):
        await RisingEdge(dut.xspi_clk)
    sam.stop()
    sam.log_sequence(tag=f"RWDS-P1 {mode[0].name}")

    sam.assert_all_zero_preamble(
        mode[0], mode[1], has_ext, n_addr,
        tag=f"RWDS-P1 {mode[0].name}"
    )
    await env.assert_no_xspi_errors(msg="RWDS-P1")


@cocotb.test(timeout_time=40000, timeout_unit="ns")
@cocotb.parametrize(
    mode=WRITE_MODES,
    default_mode_pin=[1, 2, 3],
)
async def test_rwds_in_custom_mask_sequence(dut, mode, default_mode_pin):
    """RWDS-W5: Verify arbitrary mask sequence is faithfully driven on rwds_in.

    Tests 4 different mask patterns; for each one verifies:
    - preamble edges have rwds_in=0
    - data-phase edges match the mask exactly
    """
    cocotb.log.info(
        f"RWDS-W5 custom mask sequence {mode[0].name} pin={default_mode_pin}"
    )
    env = await _boot(dut, default_mode_pin)
    await env.cmd.setLatency(17)
    assert int(dut.dut.latency_count.value) == 17
    await env.cmd.setRate(*mode)
    env.cmd.check_enables = False

    if env.cmd.cmd_mode in [Mode.S1, Mode.D1]:
        fmt = command_table[Cmd.WriteMEM]["fmt_1s"]
    else:
        fmt = command_table[Cmd.WriteMEM]["fmt_8s"]
    has_ext = format_table[fmt]["extension"]
    n_addr  = format_table[fmt]["address"]

    test_masks = [
        [WRITE]*4 + [MASK_BYTE]*4,
        [MASK_BYTE]*4 + [WRITE]*4,
        [WRITE, WRITE, MASK_BYTE, MASK_BYTE, WRITE, WRITE, MASK_BYTE, MASK_BYTE],
        [MASK_BYTE, WRITE, WRITE, MASK_BYTE, MASK_BYTE, WRITE, WRITE, MASK_BYTE],
    ]

    for mi, mask in enumerate(test_masks):
        sam = RwdsInSampler(dut)
        sam.start()

        addr = ADDRS[14 + mi]
        val  = CORNER_DATA[mi]
        await env.cmd.write_Mem(addr, val.to_bytes(MEM_BYTES, "little"), mask=mask)

        for _ in range(4):
            await RisingEdge(dut.xspi_clk)
        sam.stop()
        sam.log_sequence(tag=f"RWDS-W5 mask#{mi} {mode[0].name}")

        sam.assert_all_zero_preamble(
            mode[0], mode[1], has_ext, n_addr,
            tag=f"RWDS-W5 mask#{mi} preamble"
        )

        expected_seq = [int(m) for m in mask]
        data_vals = sam.data_phase_values(
            mode[0], mode[1], mode[2], has_ext, n_addr, MEM_BYTES
        )
        for i, (exp, got) in enumerate(zip(expected_seq, data_vals)):
            assert got == exp, (
                f"RWDS-W5 mask#{mi} byte[{i}] rwds_in={got} expected={exp} "
                f"mode={mode[0].name} mask={[int(m) for m in mask]}"
            )

    await env.assert_no_xspi_errors(msg="RWDS-W5")


# ═══════════════════════════════════════════════════════════════════════════════
# GROUP 3 – Functional mask correctness: memory content after masked write
# ═══════════════════════════════════════════════════════════════════════════════

_MASK_PATTERNS = {
    "all_write":   [WRITE]     * 8,
    "all_mask":    [MASK_BYTE] * 8,
    "alt_WM":      [WRITE, MASK_BYTE] * 4,
    "alt_MW":      [MASK_BYTE, WRITE] * 4,
    "first_4_W":   [WRITE]*4 + [MASK_BYTE]*4,
    "last_4_W":    [MASK_BYTE]*4 + [WRITE]*4,
    "byte0_only":  [WRITE] + [MASK_BYTE]*7,
    "byte7_only":  [MASK_BYTE]*7 + [WRITE],
    "bytes_0_7":   [WRITE] + [MASK_BYTE]*6 + [WRITE],
    "middle_4_W":  [MASK_BYTE]*2 + [WRITE]*4 + [MASK_BYTE]*2,
    "odd_bytes_W": [MASK_BYTE, WRITE, MASK_BYTE, WRITE, MASK_BYTE, WRITE, MASK_BYTE, WRITE],
    "even_bytes_W":[WRITE, MASK_BYTE, WRITE, MASK_BYTE, WRITE, MASK_BYTE, WRITE, MASK_BYTE],
}

_ORIG = 0xAABBCCDDEEFF0011
_NEW  = 0x0102030405060708


@cocotb.test(timeout_time=50000, timeout_unit="ns")
@cocotb.parametrize(
    mask_name=list(_MASK_PATTERNS.keys()),
    mode=WRITE_MODES,
    latency=[8, 17],
    default_mode_pin=[1, 2, 3],
)
async def test_mask_functional(dut, mask_name, mode, latency, default_mode_pin):
    """RWDS-F1: Memory must reflect mask semantics byte-by-byte after a masked write.

    For each byte i:
      mask[i] = WRITE     → memory[i] == new_val[i]
      mask[i] = MASK_BYTE → memory[i] == orig_val[i]  (unchanged)
    """
    mask = _MASK_PATTERNS[mask_name]
    cocotb.log.info(
        f"RWDS-F1 mask={mask_name} {mode[0].name} latency={latency} pin={default_mode_pin}"
    )
    env = await _boot(dut, default_mode_pin)
    await env.cmd.setLatency(latency)
    assert int(dut.dut.latency_count.value) == latency
    await env.cmd.setRate(*mode)
    env.cmd.check_enables = False

    addr = ADDRS[18]
    orig = _ORIG
    new  = _NEW

    # Preload via AXI backdoor
    env.axi_ram.write(addr, list(orig.to_bytes(MEM_BYTES, "little")))

    # Verify preload via xSPI
    pre = await env.cmd.read_Mem(addr)
    assert hex(int.from_bytes(pre, "little")) == hex(orig), (
        f"RWDS-F1 preload failed: expected=0x{orig:016x} "
        f"got=0x{int.from_bytes(pre,'little'):016x}"
    )

    # Masked write
    await env.cmd.write_Mem(addr, new.to_bytes(MEM_BYTES, "little"), mask=mask)

    # Read back
    post = await env.cmd.read_Mem(addr)

    expected     = _expected_bytes(orig, new, mask)
    expected_int = int.from_bytes(expected, "little")
    got_int      = int.from_bytes(post, "little")

    # Per-byte detail for diagnosis
    orig_b = list(orig.to_bytes(MEM_BYTES, "little"))
    new_b  = list(new.to_bytes(MEM_BYTES, "little"))
    got_b  = list(post)
    exp_b  = list(expected)

    byte_lines = []
    for i in range(MEM_BYTES):
        op      = "WRITE" if not mask[i] else "MASK "
        correct = got_b[i] == exp_b[i]
        byte_lines.append(
            f"    byte[{i}] {op} "
            f"orig=0x{orig_b[i]:02x} new=0x{new_b[i]:02x} "
            f"exp=0x{exp_b[i]:02x} got=0x{got_b[i]:02x} "
            f"{'OK' if correct else '*** FAIL ***'}"
        )

    assert hex(got_int) == hex(expected_int), (
        f"RWDS-F1 mask={mask_name} mode={mode[0].name} latency={latency}:\n"
        f"  expected=0x{expected_int:016x}\n"
        f"  got     =0x{got_int:016x}\n"
        + "\n".join(byte_lines)
    )
    cocotb.log.info(
        f"  PASS expected=0x{expected_int:016x} got=0x{got_int:016x}"
    )
    await env.assert_no_xspi_errors(msg=f"RWDS-F1 {mask_name}")


@cocotb.test(timeout_time=60000, timeout_unit="ns")
@cocotb.parametrize(
    mode=WRITE_MODES,
    latency=[8, 17],
    default_mode_pin=[1, 2, 3],
)
async def test_mask_each_byte_individually(dut, mode, latency, default_mode_pin):
    """RWDS-F2: Mask exactly one byte at a time across all 8 byte positions.

    Isolates each byte lane: when byte i is masked, ONLY byte i must
    be unchanged; all other bytes must reflect the new value.
    """
    cocotb.log.info(
        f"RWDS-F2 single-byte isolation {mode[0].name} latency={latency} pin={default_mode_pin}"
    )
    env = await _boot(dut, default_mode_pin)
    await env.cmd.setLatency(latency)
    assert int(dut.dut.latency_count.value) == latency
    await env.cmd.setRate(*mode)
    env.cmd.check_enables = False

    addr = ADDRS[19]
    orig = _ORIG
    new  = _NEW

    for byte_idx in range(MEM_BYTES):
        mask = [WRITE] * MEM_BYTES
        mask[byte_idx] = MASK_BYTE

        env.axi_ram.write(addr, list(orig.to_bytes(MEM_BYTES, "little")))
        await env.cmd.write_Mem(addr, new.to_bytes(MEM_BYTES, "little"), mask=mask)
        post = await env.cmd.read_Mem(addr)

        expected     = _expected_bytes(orig, new, mask)
        expected_int = int.from_bytes(expected, "little")
        got_int      = int.from_bytes(post, "little")
        got_b        = list(post)
        exp_b        = list(expected)

        cocotb.log.info(
            f"  byte_idx={byte_idx} masked: "
            f"expected=0x{expected_int:016x} got=0x{got_int:016x}"
        )

        for i in range(MEM_BYTES):
            assert got_b[i] == exp_b[i], (
                f"RWDS-F2 byte[{i}] mismatch when masking byte[{byte_idx}]:\n"
                f"  expected=0x{exp_b[i]:02x} got=0x{got_b[i]:02x}\n"
                f"  full expected=0x{expected_int:016x}\n"
                f"  full got     =0x{got_int:016x}\n"
                f"  mask={[int(m) for m in mask]}\n"
                f"  mode={mode[0].name}"
            )

    await env.assert_no_xspi_errors(msg="RWDS-F2")


@cocotb.test(timeout_time=60000, timeout_unit="ns")
@cocotb.parametrize(
    mode=WRITE_MODES,
    latency=[8, 17],
    default_mode_pin=[1, 2, 3],
)
async def test_mask_write_only_one_byte(dut, mode, latency, default_mode_pin):
    """RWDS-F3: Write exactly one byte at a time — all others must be masked.

    Complement of F2: mask[i]=MASK_BYTE for all except one, verifying
    that a single written byte does not corrupt adjacent byte lanes.
    """
    cocotb.log.info(
        f"RWDS-F3 single-byte write {mode[0].name} latency={latency} pin={default_mode_pin}"
    )
    env = await _boot(dut, default_mode_pin)
    await env.cmd.setLatency(latency)
    assert int(dut.dut.latency_count.value) == latency
    await env.cmd.setRate(*mode)
    env.cmd.check_enables = False

    addr = ADDRS[20]
    orig = _ORIG
    new  = _NEW

    for byte_idx in range(MEM_BYTES):
        mask = [MASK_BYTE] * MEM_BYTES
        mask[byte_idx] = WRITE

        env.axi_ram.write(addr, list(orig.to_bytes(MEM_BYTES, "little")))
        await env.cmd.write_Mem(addr, new.to_bytes(MEM_BYTES, "little"), mask=mask)
        post = await env.cmd.read_Mem(addr)

        expected     = _expected_bytes(orig, new, mask)
        expected_int = int.from_bytes(expected, "little")
        got_int      = int.from_bytes(post, "little")
        got_b        = list(post)
        exp_b        = list(expected)

        cocotb.log.info(
            f"  byte_idx={byte_idx} written: "
            f"expected=0x{expected_int:016x} got=0x{got_int:016x}"
        )

        for i in range(MEM_BYTES):
            assert got_b[i] == exp_b[i], (
                f"RWDS-F3 byte[{i}] mismatch when writing only byte[{byte_idx}]:\n"
                f"  expected=0x{exp_b[i]:02x} got=0x{got_b[i]:02x}\n"
                f"  full expected=0x{expected_int:016x}\n"
                f"  full got     =0x{got_int:016x}\n"
                f"  mode={mode[0].name}"
            )

    await env.assert_no_xspi_errors(msg="RWDS-F3")


# ═══════════════════════════════════════════════════════════════════════════════
# GROUP 4 – Combined OE + waveform + functional
# ═══════════════════════════════════════════════════════════════════════════════

@cocotb.test(timeout_time=50000, timeout_unit="ns")
@cocotb.parametrize(
    mode=WRITE_MODES,
    latency=[8, 17],
    default_mode_pin=[1, 2, 3],
)
async def test_combined_oe_waveform_functional(dut, mode, latency, default_mode_pin):
    """RWDS-C1: All three layers checked in one transaction.

    1. OE check via check_enables=True (inline assertions per byte clock)
    2. RWDS_IN waveform capture (preamble=0, data=mask)
    3. Functional correctness (memory byte-by-byte matches expected)
    """
    cocotb.log.info(
        f"RWDS-C1 combined {mode[0].name} latency={latency} pin={default_mode_pin}"
    )
    env = await _boot(dut, default_mode_pin)
    await env.cmd.setLatency(latency)
    assert int(dut.dut.latency_count.value) == latency
    await env.cmd.setRate(*mode)

    if env.cmd.cmd_mode in [Mode.S1, Mode.D1]:
        fmt = command_table[Cmd.WriteMEM]["fmt_1s"]
    else:
        fmt = command_table[Cmd.WriteMEM]["fmt_8s"]
    has_ext = format_table[fmt]["extension"]
    n_addr  = format_table[fmt]["address"]

    mask = [WRITE, MASK_BYTE, WRITE, MASK_BYTE, WRITE, MASK_BYTE, WRITE, MASK_BYTE]
    addr = ADDRS[21]
    orig = _ORIG
    new  = _NEW

    env.axi_ram.write(addr, list(orig.to_bytes(MEM_BYTES, "little")))

    # Activate inline OE checker
    env.cmd.check_enables = True

    # Capture RWDS_IN waveform
    sam = RwdsInSampler(dut)
    sam.start()

    await env.cmd.write_Mem(addr, new.to_bytes(MEM_BYTES, "little"), mask=mask)

    for _ in range(4):
        await RisingEdge(dut.xspi_clk)
    sam.stop()
    env.cmd.check_enables = False

    sam.log_sequence(tag=f"RWDS-C1 {mode[0].name}")

    # Layer 2: waveform check
    sam.assert_all_zero_preamble(
        mode[0], mode[1], has_ext, n_addr,
        tag=f"RWDS-C1 preamble {mode[0].name}"
    )
    expected_seq = [int(m) for m in mask]
    data_vals = sam.data_phase_values(
        mode[0], mode[1], mode[2], has_ext, n_addr, MEM_BYTES
    )
    for i, (exp, got) in enumerate(zip(expected_seq, data_vals)):
        assert got == exp, (
            f"RWDS-C1 waveform byte[{i}] rwds_in={got} expected={exp} "
            f"mode={mode[0].name}"
        )

    # Layer 3: functional check
    post = await env.cmd.read_Mem(addr)
    expected     = _expected_bytes(orig, new, mask)
    expected_int = int.from_bytes(expected, "little")
    got_int      = int.from_bytes(post, "little")
    assert hex(got_int) == hex(expected_int), (
        f"RWDS-C1 functional: expected=0x{expected_int:016x} got=0x{got_int:016x} "
        f"mode={mode[0].name}"
    )

    await env.assert_no_xspi_errors(msg=f"RWDS-C1 {mode[0].name}")


# ═══════════════════════════════════════════════════════════════════════════════
# GROUP 5 – Back-to-back masked writes: OE correct between transactions
# ═══════════════════════════════════════════════════════════════════════════════

@cocotb.test(timeout_time=60000, timeout_unit="ns")
@cocotb.parametrize(
    mode=WRITE_MODES,
    default_mode_pin=[1, 2, 3],
)
async def test_back_to_back_masked_writes(dut, mode, default_mode_pin):
    """RWDS-B1: Two masked writes in sequence; OE clean across the CS# gap.

    Write 1: writes bytes 0-3 (bytes 4-7 masked).
    Write 2: writes bytes 4-7 (bytes 0-3 masked).
    Final readback must equal byte-by-byte composition of both writes.
    """
    cocotb.log.info(
        f"RWDS-B1 back-to-back {mode[0].name} pin={default_mode_pin}"
    )
    env = await _boot(dut, default_mode_pin)
    await env.cmd.setLatency(17)
    assert int(dut.dut.latency_count.value) == 17
    await env.cmd.setRate(*mode)

    env.cmd.check_enables = True  # OE checked on every byte

    addr = ADDRS[22]
    orig = 0x0000000000000000
    env.axi_ram.write(addr, list(orig.to_bytes(MEM_BYTES, "little")))

    val1  = 0xAABBCCDDEEFF0011
    mask1 = [WRITE]*4 + [MASK_BYTE]*4

    val2  = 0x1122334455667788
    mask2 = [MASK_BYTE]*4 + [WRITE]*4

    cocotb.log.info(
        f"  write1=0x{val1:016x} mask={[int(m) for m in mask1]}"
    )
    await env.cmd.write_Mem(addr, val1.to_bytes(MEM_BYTES, "little"), mask=mask1)

    cocotb.log.info(
        f"  write2=0x{val2:016x} mask={[int(m) for m in mask2]}"
    )
    await env.cmd.write_Mem(addr, val2.to_bytes(MEM_BYTES, "little"), mask=mask2)

    env.cmd.check_enables = False

    post = await env.cmd.read_Mem(addr)

    stage1 = _expected_bytes(orig, val1, mask1)
    stage2 = _expected_bytes(int.from_bytes(stage1, "little"), val2, mask2)
    expected_int = int.from_bytes(stage2, "little")
    got_int      = int.from_bytes(post, "little")

    assert hex(got_int) == hex(expected_int), (
        f"RWDS-B1 sequential masked writes:\n"
        f"  expected=0x{expected_int:016x}\n"
        f"  got     =0x{got_int:016x}"
    )
    await env.assert_no_xspi_errors(msg="RWDS-B1")


# ═══════════════════════════════════════════════════════════════════════════════
# GROUP 6 – Latency sweep: byte-enable independent of latency
# ═══════════════════════════════════════════════════════════════════════════════

_SWEEP_MASKS = [
    [WRITE]     * 8,
    [MASK_BYTE] * 8,
    [WRITE, MASK_BYTE] * 4,
    [MASK_BYTE, WRITE] * 4,
    [WRITE]*4 + [MASK_BYTE]*4,
    [MASK_BYTE]*4 + [WRITE]*4,
]

_SWEEP_ORIG_VALS = [
    0xAAAAAAAAAAAAAAAA,
    0x5555555555555555,
    0xFF00FF00FF00FF00,
    0x00FF00FF00FF00FF,
    0xF0F0F0F0F0F0F0F0,
    0x0F0F0F0F0F0F0F0F,
]

_SWEEP_NEW_VALS = [v ^ 0xFFFFFFFFFFFFFFFF for v in _SWEEP_ORIG_VALS]


@cocotb.test(timeout_time=80000, timeout_unit="ns")
@cocotb.parametrize(
    latency=list(range(8, 21, 3)),
    default_mode_pin=[1, 2, 3],
)
async def test_rwds_latency_sweep(dut, latency, default_mode_pin):
    """RWDS-L1: Mask correctness across full latency range in SPI and Octal DDR.

    Byte-enable behaviour must be independent of the latency count setting.
    Tests both SPI (Format K0) and Octal DDR (Format D1) at each latency.
    """
    cocotb.log.info(
        f"RWDS-L1 latency_sweep latency={latency} pin={default_mode_pin}"
    )
    for mode in [(Mode.S1, Mode.S1, Mode.S1), (Mode.D8, Mode.D8, Mode.D8)]:
        env = await _boot(dut, default_mode_pin)
        await env.cmd.setLatency(latency)
        assert int(dut.dut.latency_count.value) == latency, (
            f"latency_count mismatch: expected={latency} "
            f"got={int(dut.dut.latency_count.value)}"
        )
        await env.cmd.setRate(*mode)
        env.cmd.check_enables = False

        for mi, mask in enumerate(_SWEEP_MASKS):
            orig = _SWEEP_ORIG_VALS[mi]
            new  = _SWEEP_NEW_VALS[mi]
            addr = ADDRS[(mi + latency + 23) % len(ADDRS)]

            env.axi_ram.write(addr, list(orig.to_bytes(MEM_BYTES, "little")))
            await env.cmd.write_Mem(addr, new.to_bytes(MEM_BYTES, "little"), mask=mask)
            post = await env.cmd.read_Mem(addr)

            expected     = _expected_bytes(orig, new, mask)
            expected_int = int.from_bytes(expected, "little")
            got_int      = int.from_bytes(post, "little")

            assert hex(got_int) == hex(expected_int), (
                f"RWDS-L1 latency={latency} mode={mode[0].name} mask#{mi}:\n"
                f"  orig=0x{orig:016x} new=0x{new:016x}\n"
                f"  expected=0x{expected_int:016x}\n"
                f"  got     =0x{got_int:016x}"
            )

        await env.cmd.Reset()
        for _ in range(10):
            await RisingEdge(dut.xspi_clk)

    await env.assert_no_xspi_errors(msg=f"RWDS-L1 latency={latency}")


# ═══════════════════════════════════════════════════════════════════════════════
# GROUP 7 – Corner data × corner mask exhaustive sweep
# ═══════════════════════════════════════════════════════════════════════════════

@cocotb.test(timeout_time=80000, timeout_unit="ns")
@cocotb.parametrize(
    mode=WRITE_MODES,
    default_mode_pin=[1, 2, 3],
)
async def test_corner_data_corner_mask(dut, mode, default_mode_pin):
    """RWDS-X1: Exhaustive corner data × corner mask product in each write mode.

    8 corner data values × 12 mask patterns = 96 combinations per mode.
    Uses AXI backdoor preload to set known initial state.
    """
    cocotb.log.info(
        f"RWDS-X1 corner data×mask {mode[0].name} pin={default_mode_pin}"
    )
    env = await _boot(dut, default_mode_pin)
    await env.cmd.setLatency(17)
    assert int(dut.dut.latency_count.value) == 17
    await env.cmd.setRate(*mode)
    env.cmd.check_enables = False

    addr = ADDRS[40]

    for di, orig in enumerate(CORNER_DATA):
        new = CORNER_DATA[(di + 4) % len(CORNER_DATA)]

        for mi, (mask_name, mask) in enumerate(_MASK_PATTERNS.items()):
            env.axi_ram.write(addr, list(orig.to_bytes(MEM_BYTES, "little")))
            await env.cmd.write_Mem(addr, new.to_bytes(MEM_BYTES, "little"), mask=mask)
            post = await env.cmd.read_Mem(addr)

            expected     = _expected_bytes(orig, new, mask)
            expected_int = int.from_bytes(expected, "little")
            got_int      = int.from_bytes(post, "little")

            assert hex(got_int) == hex(expected_int), (
                f"RWDS-X1 di={di} mi={mi} mask={mask_name} "
                f"mode={mode[0].name}:\n"
                f"  orig=0x{orig:016x} new=0x{new:016x}\n"
                f"  expected=0x{expected_int:016x}\n"
                f"  got     =0x{got_int:016x}"
            )

    await env.assert_no_xspi_errors(msg=f"RWDS-X1 {mode[0].name}")
