module et_ctrl_wrapper(
    // REMOVED — now driven directly by hwif_out in erbium_et_bank_wrapper:
    //   output         wr_en_ovr,
    //   output         vblslx_gain_mode_ovr,
    //   output         sah_en,
    //   output         ref_prg_en,
    //   output         rd_pulse_meas_en,
    //   output         rd_en_ovr,
    //   output         rca_ovr_en,
    //   output [6:0]   rca_ovr,
    //   output         prg_rd1_byp,
    //   output         otp_wr_en,
    //   output [3:0]   odd_man_wr,
    //   output [3:0]   odd_man_stripe_sel,
    //   output [3:0]   even_man_wr,
    //   output [3:0]   even_man_stripe_sel,
    //   output         dma_en,
    //   output         test_cal_en,
    //   output         gbl_cfg_ovr_en,
    //   output [2:0]   anatest1_sel,
    //   output [2:0]   anatest0_sel,
    //   output         scc_otp_en,
    //   output         reg_logic_sup_sleep,
    //
    // REMOVED — now read directly by hwif_in in erbium_et_bank_wrapper:
    //   input  [1:0]   temp,
    //
    // REMOVED — was input to boot_sequencer in et_ctrl_top;
    //   needs re-routing from hwif_in or bank wrapper:
    //   input          pwr_ok,
    //
    input          rst_b,
    input          pwr_ok,
    output         pwr_up_sel,
    output         reg_logic_sup_sleep,
    output         ref_prg_en,
    output         mram_ready,
    input          nvsram_startup_bypass,
    output         mram_we,
    output [7:0]   mram_ce,
    output [7:0]   mram_dout_en,
    output         mram_dsleep,
    input  [157:0] mram_dout,
    output [78:0]  mram_din,
    output [3:0]   mram_clk,
    output [78:0]  mram_bwe,
    output [16:0]  mram_add,
    inout  [42:0]  gbl_cfg,
    input          dsleep,
    input  [2:0]   ecc_disable_bit,
    output [1:0]   ecc_single_error,
    output [1:0]   ecc_double_error,
    output [1:0]   ecc_triple_error,
    output [1:0]   cpu_intr_flag,
    input          clk,
    input  [7:0]   mram_busy,
    output [7:0]   axi_busy,
    input          axi_we,
    input  [7:0]   axi_dout_en,
    input  [7:0]   axi_ce,
    output [127:0] axi_dout,
    input  [63:0]  axi_din,
    input  [63:0]  axi_bwe,
    input  [16:0]  axi_add,
    output controller_regs_pkg::controller_regs__in_t  hwif_in,
    input  controller_regs_pkg::controller_regs__out_t hwif_out,
    output         mram_rst_b
  );
  //
  wire     [78:0]  cmx_axi_din;
  wire             ecc_bypass_en;
  wire             ecc_disable_ted;
  wire             ref_ecc_sel;
  wire    [7:0]    mram_op_busy;
  assign  mram_op_busy = {8{~pwr_ok}} | mram_busy;
  //
  et_ctrl_top  et_ctrl_top_u(
    .axi_add(axi_add),
    .axi_bwe(axi_bwe),
    .axi_din(cmx_axi_din),
    .axi_ce(axi_ce),
    .axi_dout_en(axi_dout_en),
    .axi_we(axi_we),
    .mram_busy(mram_op_busy),
    .axi_busy(axi_busy),
    .clk(clk),
    .ecc_disable_bit(ecc_disable_bit),
    .cpu_intr_flag(cpu_intr_flag),
    .dsleep(dsleep),
    .ecc_1bit(ecc_single_error),
    .ecc_2bit(ecc_double_error),
    .ecc_3bit(ecc_triple_error),
    .gbl_cfg(gbl_cfg),
    .hwif_in(hwif_in),
    .hwif_out(hwif_out),
    .mram_add(mram_add),
    .mram_bwe(mram_bwe),
    .mram_clk(mram_clk),
    .mram_din(mram_din),
    .mram_dout(mram_dout),
    .mram_dsleep(mram_dsleep),
    .mram_rst_b(mram_rst_b),
    .mram_ce(mram_ce),
    .mram_dout_en(mram_dout_en),
    .mram_we(mram_we),
    .nvsram_startup_bypass(nvsram_startup_bypass),
    .pwr_ok(pwr_ok),
    .pwr_up_sel(pwr_up_sel),
    .reg_logic_sup_sleep(reg_logic_sup_sleep),
    .ref_prg_en(ref_prg_en),
    .mram_ready(mram_ready),
    .rst_b(rst_b),

    // REMOVED — treg pass-throughs now handled by hwif_out/hwif_in:
    //   .test_cal_en(test_cal_en),
    //   .pwr_ok(pwr_ok),
    //   .rca_ovr(rca_ovr),
    //   .rca_ovr_en(rca_ovr_en),
    //   .ref_prg_en(ref_prg_en),
    //   .reg_logic_sup_sleep(reg_logic_sup_sleep),
    //   .treg_anatest0_sel(anatest0_sel),
    //   .treg_anatest1_sel(anatest1_sel),
    //   .treg_dma_en(dma_en),
    //   .treg_even_man_stripe_sel(even_man_stripe_sel),
    //   .treg_even_man_wr(even_man_wr),
    //   .treg_gbl_cfg_ovr_en(gbl_cfg_ovr_en),
    //   .treg_odd_man_stripe_sel(odd_man_stripe_sel),
    //   .treg_odd_man_wr(odd_man_wr),
    //   .treg_otp_wr_en(otp_wr_en),
    //   .treg_prg_rd1_byp(prg_rd1_byp),
    //   .treg_rd_en_ovr(rd_en_ovr),
    //   .treg_rd_pulse_meas_en(rd_pulse_meas_en),
    //   .treg_sah_en(sah_en),
    //   .treg_scc_otp_en(scc_otp_en),
    //   .treg_temp(temp),
    //   .treg_vblslx_gain_mode_ovr(vblslx_gain_mode_ovr),
    //   .treg_wr_en_ovr(wr_en_ovr),

    // Still connected — internal to et_ctrl_wrapper (feed et_ecc_wrapper):
    .treg_disable_ted(ecc_disable_ted),
    .treg_ecc_bypass_en(ecc_bypass_en),
    .treg_ref_ecc_sel(ref_ecc_sel)
  );
  //
  et_ecc_wrapper  et_ecc_wrapper_u(
    .clk(clk),
    .rst_b(rst_b),
    .data_to_encode_i(axi_din),
    .ecc_encoded_data_o(cmx_axi_din),
    .uncorrected_data_i(mram_dout),
    .corrected_data_o(axi_dout),
    .ecc_bypass_en_i(ecc_bypass_en),
    .ref_ecc_sel_i(ref_ecc_sel),
    .single_error_o(ecc_single_error),
    .double_error_o(ecc_double_error),
    .triple_error_o(ecc_triple_error),
    .disable_ted_i(ecc_disable_ted)
  );
endmodule : et_ctrl_wrapper
