//
// Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
//
//
// Ports:
// Name                         I/O  size props
// command_ready                  O     1 reg
// RDY_command_ready              O     1 const
// response_valid                 O     1 reg
// RDY_response_valid             O     1 const
// op_inflight                    O     1
// RDY_op_inflight                O     1 const
// RDY_read_word                  O     1 reg
// RDY_read_ref_word              O     1 reg
// RDY_write_word                 O     1 reg
// RDY_write_ref_word             O     1 reg
// response                       O    83
// RDY_response                   O     1 const
// response_blocking              O    81 reg
// RDY_response_blocking          O     1 reg
// mram_addr_o                    O    17 reg
// mram_ce_o                      O     8
// mram_dout_en_o                 O     8
// mram_we_o                      O     1
// mram_din_o                     O    79 reg
// mram_bwe_o                     O    79
// mram_ref_prg_en_o              O     1 reg
// mram_clk_en_o                  O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// read_word_target_addr          I    20
// read_ref_word_target_addr      I    20
// write_word_target_addr         I    20
// write_word_din                 I    79
// write_ref_word_target_addr     I    20
// write_ref_word_din             I    79
// mram_rdata_i                   I   158 reg
// mram_busy_i                    I     8 reg
// EN_read_word                   I     1
// EN_read_ref_word               I     1
// EN_write_word                  I     1
// EN_write_ref_word              I     1
// EN_mram_mram_dout              I     1
// EN_mram_mram_busy              I     1
// EN_response                    I     1
// EN_response_blocking           I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkBistEtMramTranslator(CLK,
			      RST_N,

			      command_ready,
			      RDY_command_ready,

			      response_valid,
			      RDY_response_valid,

			      op_inflight,
			      RDY_op_inflight,

			      read_word_target_addr,
			      EN_read_word,
			      RDY_read_word,

			      read_ref_word_target_addr,
			      EN_read_ref_word,
			      RDY_read_ref_word,

			      write_word_target_addr,
			      write_word_din,
			      EN_write_word,
			      RDY_write_word,

			      write_ref_word_target_addr,
			      write_ref_word_din,
			      EN_write_ref_word,
			      RDY_write_ref_word,

			      EN_response,
			      response,
			      RDY_response,

			      EN_response_blocking,
			      response_blocking,
			      RDY_response_blocking,

			      mram_rdata_i,
			      EN_mram_mram_dout,

			      mram_busy_i,
			      EN_mram_mram_busy,

			      mram_addr_o,

			      mram_ce_o,

			      mram_dout_en_o,

			      mram_we_o,

			      mram_din_o,

			      mram_bwe_o,

			      mram_ref_prg_en_o,

			      mram_clk_en_o);
  input  CLK;
  input  RST_N;

  // value method command_ready
  output command_ready;
  output RDY_command_ready;

  // value method response_valid
  output response_valid;
  output RDY_response_valid;

  // value method op_inflight
  output op_inflight;
  output RDY_op_inflight;

  // action method read_word
  input  [19 : 0] read_word_target_addr;
  input  EN_read_word;
  output RDY_read_word;

  // action method read_ref_word
  input  [19 : 0] read_ref_word_target_addr;
  input  EN_read_ref_word;
  output RDY_read_ref_word;

  // action method write_word
  input  [19 : 0] write_word_target_addr;
  input  [78 : 0] write_word_din;
  input  EN_write_word;
  output RDY_write_word;

  // action method write_ref_word
  input  [19 : 0] write_ref_word_target_addr;
  input  [78 : 0] write_ref_word_din;
  input  EN_write_ref_word;
  output RDY_write_ref_word;

  // actionvalue method response
  input  EN_response;
  output [82 : 0] response;
  output RDY_response;

  // actionvalue method response_blocking
  input  EN_response_blocking;
  output [80 : 0] response_blocking;
  output RDY_response_blocking;

  // action method mram_mram_dout
  input  [157 : 0] mram_rdata_i;
  input  EN_mram_mram_dout;

  // action method mram_mram_busy
  input  [7 : 0] mram_busy_i;
  input  EN_mram_mram_busy;

  // value method mram_addr_o
  output [16 : 0] mram_addr_o;

  // value method mram_ce_o
  output [7 : 0] mram_ce_o;

  // value method mram_dout_en_o
  output [7 : 0] mram_dout_en_o;

  // value method mram_we_o
  output mram_we_o;

  // value method mram_din_o
  output [78 : 0] mram_din_o;

  // value method mram_bwe_o
  output [78 : 0] mram_bwe_o;

  // value method mram_ref_prg_en_o
  output mram_ref_prg_en_o;

  // value method mram_clk_en_o
  output mram_clk_en_o;

  // signals for module outputs
  wire [82 : 0] response;
  wire [80 : 0] response_blocking;
  wire [78 : 0] mram_bwe_o, mram_din_o;
  wire [16 : 0] mram_addr_o;
  wire [7 : 0] mram_ce_o, mram_dout_en_o;
  wire RDY_command_ready,
       RDY_op_inflight,
       RDY_read_ref_word,
       RDY_read_word,
       RDY_response,
       RDY_response_blocking,
       RDY_response_valid,
       RDY_write_ref_word,
       RDY_write_word,
       command_ready,
       mram_clk_en_o,
       mram_ref_prg_en_o,
       mram_we_o,
       op_inflight,
       response_valid;

  // inlined wires
  wire read_word_fsm_start_wire_whas,
       read_word_fsm_state_set_pw_whas,
       write_word_fsm_start_wire_whas,
       write_word_fsm_state_set_pw_whas;

  // register get_dout
  reg get_dout;
  reg get_dout_D_IN;
  wire get_dout_EN;

  // register issue_cmd
  reg issue_cmd;
  reg issue_cmd_D_IN;
  wire issue_cmd_EN;

  // register mram_busy_q
  reg [7 : 0] mram_busy_q;
  wire [7 : 0] mram_busy_q_D_IN;
  wire mram_busy_q_EN;

  // register mram_dout_q
  reg [157 : 0] mram_dout_q;
  wire [157 : 0] mram_dout_q_D_IN;
  wire mram_dout_q_EN;

  // register op_active
  reg op_active;
  reg op_active_D_IN;
  wire op_active_EN;

  // register pending_addr
  reg [19 : 0] pending_addr;
  wire [19 : 0] pending_addr_D_IN;
  wire pending_addr_EN;

  // register pending_din
  reg [78 : 0] pending_din;
  wire [78 : 0] pending_din_D_IN;
  wire pending_din_EN;

  // register pending_ref_prg
  reg pending_ref_prg;
  wire pending_ref_prg_D_IN, pending_ref_prg_EN;

  // register pending_write
  reg pending_write;
  wire pending_write_D_IN, pending_write_EN;

  // register read_word_fsm_jj_repeat_count
  reg [3 : 0] read_word_fsm_jj_repeat_count;
  wire [3 : 0] read_word_fsm_jj_repeat_count_D_IN;
  wire read_word_fsm_jj_repeat_count_EN;

  // register read_word_fsm_start_reg
  reg read_word_fsm_start_reg;
  wire read_word_fsm_start_reg_D_IN, read_word_fsm_start_reg_EN;

  // register read_word_fsm_start_reg_1
  reg read_word_fsm_start_reg_1;
  wire read_word_fsm_start_reg_1_D_IN, read_word_fsm_start_reg_1_EN;

  // register read_word_fsm_state_can_overlap
  reg read_word_fsm_state_can_overlap;
  wire read_word_fsm_state_can_overlap_D_IN,
       read_word_fsm_state_can_overlap_EN;

  // register read_word_fsm_state_fired
  reg read_word_fsm_state_fired;
  wire read_word_fsm_state_fired_D_IN, read_word_fsm_state_fired_EN;

  // register read_word_fsm_state_mkFSMstate
  reg [3 : 0] read_word_fsm_state_mkFSMstate;
  reg [3 : 0] read_word_fsm_state_mkFSMstate_D_IN;
  wire read_word_fsm_state_mkFSMstate_EN;

  // register write_word_fsm_jj_repeat_count
  reg [3 : 0] write_word_fsm_jj_repeat_count;
  wire [3 : 0] write_word_fsm_jj_repeat_count_D_IN;
  wire write_word_fsm_jj_repeat_count_EN;

  // register write_word_fsm_start_reg
  reg write_word_fsm_start_reg;
  wire write_word_fsm_start_reg_D_IN, write_word_fsm_start_reg_EN;

  // register write_word_fsm_start_reg_1
  reg write_word_fsm_start_reg_1;
  wire write_word_fsm_start_reg_1_D_IN, write_word_fsm_start_reg_1_EN;

  // register write_word_fsm_state_can_overlap
  reg write_word_fsm_state_can_overlap;
  wire write_word_fsm_state_can_overlap_D_IN,
       write_word_fsm_state_can_overlap_EN;

  // register write_word_fsm_state_fired
  reg write_word_fsm_state_fired;
  wire write_word_fsm_state_fired_D_IN, write_word_fsm_state_fired_EN;

  // register write_word_fsm_state_mkFSMstate
  reg [3 : 0] write_word_fsm_state_mkFSMstate;
  reg [3 : 0] write_word_fsm_state_mkFSMstate_D_IN;
  wire write_word_fsm_state_mkFSMstate_EN;

  // ports of submodule cmd_in_flight_q
  wire [100 : 0] cmd_in_flight_q_D_IN, cmd_in_flight_q_D_OUT;
  wire cmd_in_flight_q_CLR,
       cmd_in_flight_q_DEQ,
       cmd_in_flight_q_EMPTY_N,
       cmd_in_flight_q_ENQ,
       cmd_in_flight_q_FULL_N;

  // ports of submodule cmd_q
  reg [100 : 0] cmd_q_D_IN;
  wire [100 : 0] cmd_q_D_OUT;
  wire cmd_q_CLR, cmd_q_DEQ, cmd_q_EMPTY_N, cmd_q_ENQ, cmd_q_FULL_N;

  // ports of submodule resp_q
  wire [80 : 0] resp_q_D_IN, resp_q_D_OUT;
  wire resp_q_CLR, resp_q_DEQ, resp_q_EMPTY_N, resp_q_ENQ, resp_q_FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_launch_read_word,
       CAN_FIRE_RL_launch_write_word,
       WILL_FIRE_RL_launch_read_word,
       WILL_FIRE_RL_launch_write_word,
       WILL_FIRE_RL_read_word_fsm_action_l108c13,
       WILL_FIRE_RL_read_word_fsm_action_l117c22,
       WILL_FIRE_RL_read_word_fsm_action_l119c35,
       WILL_FIRE_RL_read_word_fsm_action_l120c26,
       WILL_FIRE_RL_read_word_fsm_action_l130c9,
       WILL_FIRE_RL_read_word_fsm_action_ovlp_r_update_l119c17,
       WILL_FIRE_RL_read_word_fsm_action_r_init_l119c17,
       WILL_FIRE_RL_read_word_fsm_fsm_start,
       WILL_FIRE_RL_read_word_fsm_idle_l128c25,
       WILL_FIRE_RL_write_word_fsm_action_l108c13,
       WILL_FIRE_RL_write_word_fsm_action_l117c22,
       WILL_FIRE_RL_write_word_fsm_action_l119c35,
       WILL_FIRE_RL_write_word_fsm_action_l120c26,
       WILL_FIRE_RL_write_word_fsm_action_l143c9,
       WILL_FIRE_RL_write_word_fsm_action_ovlp_r_update_l119c17,
       WILL_FIRE_RL_write_word_fsm_action_r_init_l119c17,
       WILL_FIRE_RL_write_word_fsm_fsm_start,
       WILL_FIRE_RL_write_word_fsm_idle_l141c26;

  // inputs to muxes for submodule ports
  wire [100 : 0] MUX_cmd_q_enq_1__VAL_1,
		 MUX_cmd_q_enq_1__VAL_2,
		 MUX_cmd_q_enq_1__VAL_3,
		 MUX_cmd_q_enq_1__VAL_4;
  wire [80 : 0] MUX_resp_q_enq_1__VAL_1;
  wire [3 : 0] MUX_read_word_fsm_jj_repeat_count_write_1__VAL_1,
	       MUX_write_word_fsm_jj_repeat_count_write_1__VAL_1;
  wire MUX_pending_ref_prg_write_1__VAL_2;

  // remaining internal signals
  wire [78 : 0] x_data__h36748;
  wire [7 : 0] _0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44;
  wire [3 : 0] x__h37011, x__h71641;
  wire NOT_cmd_in_flight_q_first__4_BIT_100_5_00_AND__ETC___d113,
       NOT_cmd_in_flight_q_first__4_BIT_100_5_00_AND__ETC___d212,
       NOT_read_word_fsm_abort_whas_6_OR_NOT_read_wor_ETC___d288,
       NOT_read_word_fsm_jj_repeat_count_read__01_BIT_ETC___d118,
       NOT_write_word_fsm_abort_whas__59_81_OR_NOT_wr_ETC___d295,
       NOT_write_word_fsm_jj_repeat_count_read__00_BI_ETC___d217,
       cmd_in_flight_q_i_notEmpty__1_AND_NOT_0b1_SL_p_ETC___d93,
       cmd_q_notEmpty__53_OR_op_active_58_03_OR_NOT_r_ETC___d305,
       read_word_fsm_abort_whas_AND_read_word_fsm_abo_ETC___d153,
       write_word_fsm_abort_whas__59_AND_write_word_f_ETC___d244;

  // value method command_ready
  assign command_ready = cmd_q_FULL_N ;
  assign RDY_command_ready = 1'd1 ;

  // value method response_valid
  assign response_valid = resp_q_EMPTY_N ;
  assign RDY_response_valid = 1'd1 ;

  // value method op_inflight
  assign op_inflight =
	     op_active ||
	     NOT_read_word_fsm_abort_whas_6_OR_NOT_read_wor_ETC___d288 ||
	     read_word_fsm_start_reg ||
	     NOT_write_word_fsm_abort_whas__59_81_OR_NOT_wr_ETC___d295 ||
	     write_word_fsm_start_reg ;
  assign RDY_op_inflight = 1'd1 ;

  // action method read_word
  assign RDY_read_word = cmd_q_FULL_N ;

  // action method read_ref_word
  assign RDY_read_ref_word = cmd_q_FULL_N ;

  // action method write_word
  assign RDY_write_word = cmd_q_FULL_N ;

  // action method write_ref_word
  assign RDY_write_ref_word = cmd_q_FULL_N ;

  // actionvalue method response
  assign response =
	     { resp_q_EMPTY_N ?
		 2'd2 :
		 (cmd_q_notEmpty__53_OR_op_active_58_03_OR_NOT_r_ETC___d305 ?
		    2'd1 :
		    2'd0),
	       resp_q_EMPTY_N && resp_q_D_OUT[80],
	       resp_q_EMPTY_N && resp_q_D_OUT[79],
	       resp_q_EMPTY_N ? resp_q_D_OUT[78:0] : 79'd0 } ;
  assign RDY_response = 1'b1 ;

  // actionvalue method response_blocking
  assign response_blocking = resp_q_D_OUT ;
  assign RDY_response_blocking = resp_q_EMPTY_N ;

  // value method mram_addr_o
  assign mram_addr_o = { pending_addr[19], pending_addr[15:0] } ;

  // value method mram_ce_o
  assign mram_ce_o =
	     { issue_cmd && _0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[7],
	       issue_cmd && _0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[6],
	       issue_cmd && _0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[5],
	       issue_cmd && _0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[4],
	       issue_cmd && _0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[3],
	       issue_cmd && _0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[2],
	       issue_cmd && _0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[1],
	       issue_cmd &&
	       _0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[0] } ;

  // value method mram_dout_en_o
  assign mram_dout_en_o =
	     { get_dout && !pending_write &&
	       _0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[7],
	       get_dout && !pending_write &&
	       _0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[6],
	       get_dout && !pending_write &&
	       _0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[5],
	       get_dout && !pending_write &&
	       _0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[4],
	       get_dout && !pending_write &&
	       _0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[3],
	       get_dout && !pending_write &&
	       _0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[2],
	       get_dout && !pending_write &&
	       _0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[1],
	       get_dout && !pending_write &&
	       _0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[0] } ;

  // value method mram_we_o
  assign mram_we_o = issue_cmd && pending_write ;

  // value method mram_din_o
  assign mram_din_o = pending_din ;

  // value method mram_bwe_o
  assign mram_bwe_o = pending_write ? 79'h7FFFFFFFFFFFFFFFFFFF : 79'd0 ;

  // value method mram_ref_prg_en_o
  assign mram_ref_prg_en_o = pending_ref_prg ;

  // value method mram_clk_en_o
  assign mram_clk_en_o = issue_cmd || op_active ;

  // submodule cmd_in_flight_q
  FIFO2 #(.width(32'd101), .guarded(1'd1)) cmd_in_flight_q(.RST(RST_N),
							   .CLK(CLK),
							   .D_IN(cmd_in_flight_q_D_IN),
							   .ENQ(cmd_in_flight_q_ENQ),
							   .DEQ(cmd_in_flight_q_DEQ),
							   .CLR(cmd_in_flight_q_CLR),
							   .D_OUT(cmd_in_flight_q_D_OUT),
							   .FULL_N(cmd_in_flight_q_FULL_N),
							   .EMPTY_N(cmd_in_flight_q_EMPTY_N));

  // submodule cmd_q
  FIFO2 #(.width(32'd101), .guarded(1'd1)) cmd_q(.RST(RST_N),
						 .CLK(CLK),
						 .D_IN(cmd_q_D_IN),
						 .ENQ(cmd_q_ENQ),
						 .DEQ(cmd_q_DEQ),
						 .CLR(cmd_q_CLR),
						 .D_OUT(cmd_q_D_OUT),
						 .FULL_N(cmd_q_FULL_N),
						 .EMPTY_N(cmd_q_EMPTY_N));

  // submodule resp_q
  FIFO2 #(.width(32'd81), .guarded(1'd1)) resp_q(.RST(RST_N),
						 .CLK(CLK),
						 .D_IN(resp_q_D_IN),
						 .ENQ(resp_q_ENQ),
						 .DEQ(resp_q_DEQ),
						 .CLR(resp_q_CLR),
						 .D_OUT(resp_q_D_OUT),
						 .FULL_N(resp_q_FULL_N),
						 .EMPTY_N(resp_q_EMPTY_N));

  // rule RL_launch_read_word
  assign CAN_FIRE_RL_launch_read_word =
	     cmd_q_EMPTY_N &&
	     read_word_fsm_abort_whas_AND_read_word_fsm_abo_ETC___d153 &&
	     !read_word_fsm_start_reg &&
	     cmd_in_flight_q_FULL_N &&
	     cmd_q_EMPTY_N &&
	     !cmd_q_D_OUT[100] &&
	     !op_active &&
	     resp_q_FULL_N &&
	     write_word_fsm_abort_whas__59_AND_write_word_f_ETC___d244 &&
	     !write_word_fsm_start_reg ;
  assign WILL_FIRE_RL_launch_read_word =
	     CAN_FIRE_RL_launch_read_word && !EN_response &&
	     !EN_write_ref_word &&
	     !EN_write_word &&
	     !EN_read_ref_word &&
	     !EN_read_word ;

  // rule RL_launch_write_word
  assign CAN_FIRE_RL_launch_write_word =
	     cmd_q_EMPTY_N &&
	     write_word_fsm_abort_whas__59_AND_write_word_f_ETC___d244 &&
	     !write_word_fsm_start_reg &&
	     cmd_in_flight_q_FULL_N &&
	     cmd_q_EMPTY_N &&
	     cmd_q_D_OUT[100] &&
	     !op_active &&
	     resp_q_FULL_N &&
	     read_word_fsm_abort_whas_AND_read_word_fsm_abo_ETC___d153 &&
	     !read_word_fsm_start_reg ;
  assign WILL_FIRE_RL_launch_write_word =
	     CAN_FIRE_RL_launch_write_word && !EN_response &&
	     !EN_write_ref_word &&
	     !EN_write_word &&
	     !EN_read_ref_word &&
	     !EN_read_word ;

  // rule RL_read_word_fsm_action_l117c22
  assign WILL_FIRE_RL_read_word_fsm_action_l117c22 =
	     cmd_in_flight_q_i_notEmpty__1_AND_NOT_0b1_SL_p_ETC___d93 &&
	     cmd_in_flight_q_D_OUT[100] &&
	     read_word_fsm_state_mkFSMstate == 4'd3 ;

  // rule RL_read_word_fsm_action_r_init_l119c17
  assign WILL_FIRE_RL_read_word_fsm_action_r_init_l119c17 =
	     cmd_in_flight_q_EMPTY_N && !cmd_in_flight_q_D_OUT[100] &&
	     !read_word_fsm_jj_repeat_count[0] &&
	     read_word_fsm_state_mkFSMstate == 4'd3 ;

  // rule RL_read_word_fsm_action_l120c26
  assign WILL_FIRE_RL_read_word_fsm_action_l120c26 =
	     read_word_fsm_jj_repeat_count[0] &&
	     read_word_fsm_state_mkFSMstate == 4'd7 ;

  // rule RL_read_word_fsm_action_ovlp_r_update_l119c17
  assign WILL_FIRE_RL_read_word_fsm_action_ovlp_r_update_l119c17 =
	     cmd_in_flight_q_EMPTY_N && read_word_fsm_state_can_overlap &&
	     (NOT_cmd_in_flight_q_first__4_BIT_100_5_00_AND__ETC___d113 ||
	      NOT_read_word_fsm_jj_repeat_count_read__01_BIT_ETC___d118) ;

  // rule RL_read_word_fsm_fsm_start
  assign WILL_FIRE_RL_read_word_fsm_fsm_start =
	     read_word_fsm_abort_whas_AND_read_word_fsm_abo_ETC___d153 &&
	     read_word_fsm_start_reg ;

  // rule RL_read_word_fsm_action_l108c13
  assign WILL_FIRE_RL_read_word_fsm_action_l108c13 =
	     read_word_fsm_start_wire_whas &&
	     (read_word_fsm_state_mkFSMstate == 4'd0 ||
	      read_word_fsm_state_mkFSMstate == 4'd13) ;

  // rule RL_read_word_fsm_action_l119c35
  assign WILL_FIRE_RL_read_word_fsm_action_l119c35 =
	     cmd_in_flight_q_EMPTY_N &&
	     (NOT_cmd_in_flight_q_first__4_BIT_100_5_00_AND__ETC___d113 ||
	      read_word_fsm_state_mkFSMstate == 4'd6 ||
	      NOT_read_word_fsm_jj_repeat_count_read__01_BIT_ETC___d118) ;

  // rule RL_read_word_fsm_idle_l128c25
  assign WILL_FIRE_RL_read_word_fsm_idle_l128c25 =
	     !read_word_fsm_start_wire_whas &&
	     read_word_fsm_state_mkFSMstate == 4'd13 ;

  // rule RL_write_word_fsm_action_l117c22
  assign WILL_FIRE_RL_write_word_fsm_action_l117c22 =
	     cmd_in_flight_q_i_notEmpty__1_AND_NOT_0b1_SL_p_ETC___d93 &&
	     cmd_in_flight_q_D_OUT[100] &&
	     write_word_fsm_state_mkFSMstate == 4'd3 ;

  // rule RL_write_word_fsm_action_r_init_l119c17
  assign WILL_FIRE_RL_write_word_fsm_action_r_init_l119c17 =
	     cmd_in_flight_q_EMPTY_N && !cmd_in_flight_q_D_OUT[100] &&
	     !write_word_fsm_jj_repeat_count[0] &&
	     write_word_fsm_state_mkFSMstate == 4'd3 ;

  // rule RL_write_word_fsm_action_l120c26
  assign WILL_FIRE_RL_write_word_fsm_action_l120c26 =
	     write_word_fsm_jj_repeat_count[0] &&
	     write_word_fsm_state_mkFSMstate == 4'd7 ;

  // rule RL_write_word_fsm_action_l143c9
  assign WILL_FIRE_RL_write_word_fsm_action_l143c9 =
	     cmd_in_flight_q_EMPTY_N && resp_q_FULL_N &&
	     (write_word_fsm_state_mkFSMstate == 4'd4 ||
	      write_word_fsm_state_mkFSMstate == 4'd12) &&
	     !WILL_FIRE_RL_read_word_fsm_action_l130c9 ;

  // rule RL_write_word_fsm_action_ovlp_r_update_l119c17
  assign WILL_FIRE_RL_write_word_fsm_action_ovlp_r_update_l119c17 =
	     cmd_in_flight_q_EMPTY_N && write_word_fsm_state_can_overlap &&
	     (NOT_cmd_in_flight_q_first__4_BIT_100_5_00_AND__ETC___d212 ||
	      NOT_write_word_fsm_jj_repeat_count_read__00_BI_ETC___d217) ;

  // rule RL_write_word_fsm_fsm_start
  assign WILL_FIRE_RL_write_word_fsm_fsm_start =
	     write_word_fsm_abort_whas__59_AND_write_word_f_ETC___d244 &&
	     write_word_fsm_start_reg ;

  // rule RL_write_word_fsm_action_l108c13
  assign WILL_FIRE_RL_write_word_fsm_action_l108c13 =
	     write_word_fsm_start_wire_whas &&
	     (write_word_fsm_state_mkFSMstate == 4'd0 ||
	      write_word_fsm_state_mkFSMstate == 4'd13) ;

  // rule RL_write_word_fsm_action_l119c35
  assign WILL_FIRE_RL_write_word_fsm_action_l119c35 =
	     cmd_in_flight_q_EMPTY_N &&
	     (NOT_cmd_in_flight_q_first__4_BIT_100_5_00_AND__ETC___d212 ||
	      write_word_fsm_state_mkFSMstate == 4'd6 ||
	      NOT_write_word_fsm_jj_repeat_count_read__00_BI_ETC___d217) ;

  // rule RL_read_word_fsm_action_l130c9
  assign WILL_FIRE_RL_read_word_fsm_action_l130c9 =
	     cmd_in_flight_q_EMPTY_N && resp_q_FULL_N &&
	     (read_word_fsm_state_mkFSMstate == 4'd4 ||
	      read_word_fsm_state_mkFSMstate == 4'd12) ;

  // rule RL_write_word_fsm_idle_l141c26
  assign WILL_FIRE_RL_write_word_fsm_idle_l141c26 =
	     !write_word_fsm_start_wire_whas &&
	     write_word_fsm_state_mkFSMstate == 4'd13 ;

  // inputs to muxes for submodule ports
  assign MUX_cmd_q_enq_1__VAL_1 = { 2'd0, read_word_target_addr, 79'd0 } ;
  assign MUX_cmd_q_enq_1__VAL_2 = { 2'd1, read_ref_word_target_addr, 79'd0 } ;
  assign MUX_cmd_q_enq_1__VAL_3 =
	     { 2'd2, write_word_target_addr, write_word_din } ;
  assign MUX_cmd_q_enq_1__VAL_4 =
	     { 2'd3, write_ref_word_target_addr, write_ref_word_din } ;
  assign MUX_pending_ref_prg_write_1__VAL_2 =
	     cmd_in_flight_q_EMPTY_N && cmd_in_flight_q_D_OUT[99] ;
  assign MUX_read_word_fsm_jj_repeat_count_write_1__VAL_1 =
	     read_word_fsm_jj_repeat_count[3] ? 4'd1 : x__h37011 ;
  assign MUX_resp_q_enq_1__VAL_1 = { 2'd1, x_data__h36748 } ;
  assign MUX_write_word_fsm_jj_repeat_count_write_1__VAL_1 =
	     write_word_fsm_jj_repeat_count[3] ? 4'd1 : x__h71641 ;

  // inlined wires
  assign read_word_fsm_start_wire_whas =
	     WILL_FIRE_RL_read_word_fsm_fsm_start ||
	     read_word_fsm_start_reg_1 && !read_word_fsm_state_fired ;
  assign write_word_fsm_start_wire_whas =
	     WILL_FIRE_RL_write_word_fsm_fsm_start ||
	     write_word_fsm_start_reg_1 && !write_word_fsm_state_fired ;
  assign read_word_fsm_state_set_pw_whas =
	     WILL_FIRE_RL_read_word_fsm_idle_l128c25 ||
	     WILL_FIRE_RL_read_word_fsm_action_l130c9 ||
	     read_word_fsm_state_mkFSMstate == 4'd11 ||
	     read_word_fsm_state_mkFSMstate == 4'd10 ||
	     read_word_fsm_state_mkFSMstate == 4'd9 ||
	     WILL_FIRE_RL_read_word_fsm_action_l120c26 ||
	     WILL_FIRE_RL_read_word_fsm_action_l119c35 ||
	     WILL_FIRE_RL_read_word_fsm_action_r_init_l119c17 ||
	     WILL_FIRE_RL_read_word_fsm_action_l117c22 ||
	     read_word_fsm_state_mkFSMstate == 4'd2 ||
	     read_word_fsm_state_mkFSMstate == 4'd1 ||
	     WILL_FIRE_RL_read_word_fsm_action_l108c13 ;
  assign write_word_fsm_state_set_pw_whas =
	     WILL_FIRE_RL_write_word_fsm_idle_l141c26 ||
	     WILL_FIRE_RL_write_word_fsm_action_l143c9 ||
	     write_word_fsm_state_mkFSMstate == 4'd11 ||
	     write_word_fsm_state_mkFSMstate == 4'd10 ||
	     write_word_fsm_state_mkFSMstate == 4'd9 ||
	     WILL_FIRE_RL_write_word_fsm_action_l120c26 ||
	     WILL_FIRE_RL_write_word_fsm_action_l119c35 ||
	     WILL_FIRE_RL_write_word_fsm_action_r_init_l119c17 ||
	     WILL_FIRE_RL_write_word_fsm_action_l117c22 ||
	     write_word_fsm_state_mkFSMstate == 4'd2 ||
	     write_word_fsm_state_mkFSMstate == 4'd1 ||
	     WILL_FIRE_RL_write_word_fsm_action_l108c13 ;

  // register get_dout
  always@(write_word_fsm_state_mkFSMstate or
	  WILL_FIRE_RL_write_word_fsm_action_l120c26 or
	  read_word_fsm_state_mkFSMstate or
	  WILL_FIRE_RL_read_word_fsm_action_l120c26)
  case (1'b1)
    write_word_fsm_state_mkFSMstate == 4'd9: get_dout_D_IN = 1'd0;
    WILL_FIRE_RL_write_word_fsm_action_l120c26: get_dout_D_IN = 1'd1;
    read_word_fsm_state_mkFSMstate == 4'd9: get_dout_D_IN = 1'd0;
    WILL_FIRE_RL_read_word_fsm_action_l120c26: get_dout_D_IN = 1'd1;
    default: get_dout_D_IN = 1'b0 /* unspecified value */ ;
  endcase
  assign get_dout_EN =
	     write_word_fsm_state_mkFSMstate == 4'd9 ||
	     read_word_fsm_state_mkFSMstate == 4'd9 ||
	     WILL_FIRE_RL_write_word_fsm_action_l120c26 ||
	     WILL_FIRE_RL_read_word_fsm_action_l120c26 ;

  // register issue_cmd
  always@(WILL_FIRE_RL_write_word_fsm_action_l108c13 or
	  write_word_fsm_state_mkFSMstate or
	  WILL_FIRE_RL_read_word_fsm_action_l108c13 or
	  read_word_fsm_state_mkFSMstate)
  case (1'b1)
    WILL_FIRE_RL_write_word_fsm_action_l108c13: issue_cmd_D_IN = 1'd1;
    write_word_fsm_state_mkFSMstate == 4'd2: issue_cmd_D_IN = 1'd0;
    WILL_FIRE_RL_read_word_fsm_action_l108c13: issue_cmd_D_IN = 1'd1;
    read_word_fsm_state_mkFSMstate == 4'd2: issue_cmd_D_IN = 1'd0;
    default: issue_cmd_D_IN = 1'b0 /* unspecified value */ ;
  endcase
  assign issue_cmd_EN =
	     write_word_fsm_state_mkFSMstate == 4'd2 ||
	     read_word_fsm_state_mkFSMstate == 4'd2 ||
	     WILL_FIRE_RL_write_word_fsm_action_l108c13 ||
	     WILL_FIRE_RL_read_word_fsm_action_l108c13 ;

  // register mram_busy_q
  assign mram_busy_q_D_IN = mram_busy_i ;
  assign mram_busy_q_EN = EN_mram_mram_busy ;

  // register mram_dout_q
  assign mram_dout_q_D_IN = mram_rdata_i ;
  assign mram_dout_q_EN = EN_mram_mram_dout ;

  // register op_active
  always@(WILL_FIRE_RL_read_word_fsm_action_l130c9 or
	  WILL_FIRE_RL_write_word_fsm_action_l108c13 or
	  WILL_FIRE_RL_write_word_fsm_action_l143c9 or
	  WILL_FIRE_RL_read_word_fsm_action_l108c13)
  case (1'b1)
    WILL_FIRE_RL_read_word_fsm_action_l130c9: op_active_D_IN = 1'd0;
    WILL_FIRE_RL_write_word_fsm_action_l108c13: op_active_D_IN = 1'd1;
    WILL_FIRE_RL_write_word_fsm_action_l143c9: op_active_D_IN = 1'd0;
    WILL_FIRE_RL_read_word_fsm_action_l108c13: op_active_D_IN = 1'd1;
    default: op_active_D_IN = 1'b0 /* unspecified value */ ;
  endcase
  assign op_active_EN =
	     WILL_FIRE_RL_write_word_fsm_action_l143c9 ||
	     WILL_FIRE_RL_read_word_fsm_action_l130c9 ||
	     WILL_FIRE_RL_write_word_fsm_action_l108c13 ||
	     WILL_FIRE_RL_read_word_fsm_action_l108c13 ;

  // register pending_addr
  assign pending_addr_D_IN = cmd_q_D_OUT[98:79] ;
  assign pending_addr_EN =
	     WILL_FIRE_RL_launch_write_word || WILL_FIRE_RL_launch_read_word ;

  // register pending_din
  assign pending_din_D_IN =
	     WILL_FIRE_RL_launch_write_word ? cmd_q_D_OUT[78:0] : 79'd0 ;
  assign pending_din_EN =
	     WILL_FIRE_RL_launch_write_word || WILL_FIRE_RL_launch_read_word ;

  // register pending_ref_prg
  assign pending_ref_prg_D_IN =
	     WILL_FIRE_RL_launch_read_word ?
	       cmd_q_D_OUT[99] :
	       MUX_pending_ref_prg_write_1__VAL_2 ;
  assign pending_ref_prg_EN = 1'b1 ;

  // register pending_write
  assign pending_write_D_IN = !WILL_FIRE_RL_launch_read_word ;
  assign pending_write_EN =
	     WILL_FIRE_RL_launch_read_word || WILL_FIRE_RL_launch_write_word ;

  // register read_word_fsm_jj_repeat_count
  assign read_word_fsm_jj_repeat_count_D_IN =
	     WILL_FIRE_RL_read_word_fsm_action_ovlp_r_update_l119c17 ?
	       MUX_read_word_fsm_jj_repeat_count_write_1__VAL_1 :
	       4'd1 ;
  assign read_word_fsm_jj_repeat_count_EN =
	     WILL_FIRE_RL_read_word_fsm_action_ovlp_r_update_l119c17 ||
	     WILL_FIRE_RL_read_word_fsm_action_r_init_l119c17 ;

  // register read_word_fsm_start_reg
  assign read_word_fsm_start_reg_D_IN =
	     !WILL_FIRE_RL_read_word_fsm_fsm_start ;
  assign read_word_fsm_start_reg_EN =
	     WILL_FIRE_RL_read_word_fsm_fsm_start ||
	     WILL_FIRE_RL_launch_read_word ;

  // register read_word_fsm_start_reg_1
  assign read_word_fsm_start_reg_1_D_IN = read_word_fsm_start_wire_whas ;
  assign read_word_fsm_start_reg_1_EN = 1'd1 ;

  // register read_word_fsm_state_can_overlap
  assign read_word_fsm_state_can_overlap_D_IN =
	     read_word_fsm_state_set_pw_whas ||
	     !WILL_FIRE_RL_read_word_fsm_action_ovlp_r_update_l119c17 &&
	     read_word_fsm_state_can_overlap ;
  assign read_word_fsm_state_can_overlap_EN = 1'd1 ;

  // register read_word_fsm_state_fired
  assign read_word_fsm_state_fired_D_IN = read_word_fsm_state_set_pw_whas ;
  assign read_word_fsm_state_fired_EN = 1'd1 ;

  // register read_word_fsm_state_mkFSMstate
  always@(WILL_FIRE_RL_read_word_fsm_idle_l128c25 or
	  WILL_FIRE_RL_read_word_fsm_action_l108c13 or
	  read_word_fsm_state_mkFSMstate or
	  WILL_FIRE_RL_read_word_fsm_action_l117c22 or
	  WILL_FIRE_RL_read_word_fsm_action_r_init_l119c17 or
	  WILL_FIRE_RL_read_word_fsm_action_l119c35 or
	  WILL_FIRE_RL_read_word_fsm_action_l120c26 or
	  WILL_FIRE_RL_read_word_fsm_action_l130c9)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_read_word_fsm_idle_l128c25:
	  read_word_fsm_state_mkFSMstate_D_IN = 4'd0;
      WILL_FIRE_RL_read_word_fsm_action_l108c13:
	  read_word_fsm_state_mkFSMstate_D_IN = 4'd1;
      read_word_fsm_state_mkFSMstate == 4'd1:
	  read_word_fsm_state_mkFSMstate_D_IN = 4'd2;
      read_word_fsm_state_mkFSMstate == 4'd2:
	  read_word_fsm_state_mkFSMstate_D_IN = 4'd3;
      WILL_FIRE_RL_read_word_fsm_action_l117c22:
	  read_word_fsm_state_mkFSMstate_D_IN = 4'd4;
      WILL_FIRE_RL_read_word_fsm_action_r_init_l119c17:
	  read_word_fsm_state_mkFSMstate_D_IN = 4'd5;
      WILL_FIRE_RL_read_word_fsm_action_l119c35:
	  read_word_fsm_state_mkFSMstate_D_IN = 4'd7;
      WILL_FIRE_RL_read_word_fsm_action_l120c26:
	  read_word_fsm_state_mkFSMstate_D_IN = 4'd9;
      read_word_fsm_state_mkFSMstate == 4'd9:
	  read_word_fsm_state_mkFSMstate_D_IN = 4'd10;
      read_word_fsm_state_mkFSMstate == 4'd10:
	  read_word_fsm_state_mkFSMstate_D_IN = 4'd11;
      read_word_fsm_state_mkFSMstate == 4'd11:
	  read_word_fsm_state_mkFSMstate_D_IN = 4'd12;
      WILL_FIRE_RL_read_word_fsm_action_l130c9:
	  read_word_fsm_state_mkFSMstate_D_IN = 4'd13;
      default: read_word_fsm_state_mkFSMstate_D_IN =
		   4'b1010 /* unspecified value */ ;
    endcase
  end
  assign read_word_fsm_state_mkFSMstate_EN =
	     WILL_FIRE_RL_read_word_fsm_idle_l128c25 ||
	     WILL_FIRE_RL_read_word_fsm_action_l108c13 ||
	     read_word_fsm_state_mkFSMstate == 4'd1 ||
	     read_word_fsm_state_mkFSMstate == 4'd2 ||
	     WILL_FIRE_RL_read_word_fsm_action_l117c22 ||
	     WILL_FIRE_RL_read_word_fsm_action_r_init_l119c17 ||
	     WILL_FIRE_RL_read_word_fsm_action_l119c35 ||
	     WILL_FIRE_RL_read_word_fsm_action_l120c26 ||
	     read_word_fsm_state_mkFSMstate == 4'd9 ||
	     read_word_fsm_state_mkFSMstate == 4'd10 ||
	     read_word_fsm_state_mkFSMstate == 4'd11 ||
	     WILL_FIRE_RL_read_word_fsm_action_l130c9 ;

  // register write_word_fsm_jj_repeat_count
  assign write_word_fsm_jj_repeat_count_D_IN =
	     WILL_FIRE_RL_write_word_fsm_action_ovlp_r_update_l119c17 ?
	       MUX_write_word_fsm_jj_repeat_count_write_1__VAL_1 :
	       4'd1 ;
  assign write_word_fsm_jj_repeat_count_EN =
	     WILL_FIRE_RL_write_word_fsm_action_ovlp_r_update_l119c17 ||
	     WILL_FIRE_RL_write_word_fsm_action_r_init_l119c17 ;

  // register write_word_fsm_start_reg
  assign write_word_fsm_start_reg_D_IN =
	     !WILL_FIRE_RL_write_word_fsm_fsm_start ;
  assign write_word_fsm_start_reg_EN =
	     WILL_FIRE_RL_write_word_fsm_fsm_start ||
	     WILL_FIRE_RL_launch_write_word ;

  // register write_word_fsm_start_reg_1
  assign write_word_fsm_start_reg_1_D_IN = write_word_fsm_start_wire_whas ;
  assign write_word_fsm_start_reg_1_EN = 1'd1 ;

  // register write_word_fsm_state_can_overlap
  assign write_word_fsm_state_can_overlap_D_IN =
	     write_word_fsm_state_set_pw_whas ||
	     !WILL_FIRE_RL_write_word_fsm_action_ovlp_r_update_l119c17 &&
	     write_word_fsm_state_can_overlap ;
  assign write_word_fsm_state_can_overlap_EN = 1'd1 ;

  // register write_word_fsm_state_fired
  assign write_word_fsm_state_fired_D_IN = write_word_fsm_state_set_pw_whas ;
  assign write_word_fsm_state_fired_EN = 1'd1 ;

  // register write_word_fsm_state_mkFSMstate
  always@(WILL_FIRE_RL_write_word_fsm_idle_l141c26 or
	  WILL_FIRE_RL_write_word_fsm_action_l108c13 or
	  write_word_fsm_state_mkFSMstate or
	  WILL_FIRE_RL_write_word_fsm_action_l117c22 or
	  WILL_FIRE_RL_write_word_fsm_action_r_init_l119c17 or
	  WILL_FIRE_RL_write_word_fsm_action_l119c35 or
	  WILL_FIRE_RL_write_word_fsm_action_l120c26 or
	  WILL_FIRE_RL_write_word_fsm_action_l143c9)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_write_word_fsm_idle_l141c26:
	  write_word_fsm_state_mkFSMstate_D_IN = 4'd0;
      WILL_FIRE_RL_write_word_fsm_action_l108c13:
	  write_word_fsm_state_mkFSMstate_D_IN = 4'd1;
      write_word_fsm_state_mkFSMstate == 4'd1:
	  write_word_fsm_state_mkFSMstate_D_IN = 4'd2;
      write_word_fsm_state_mkFSMstate == 4'd2:
	  write_word_fsm_state_mkFSMstate_D_IN = 4'd3;
      WILL_FIRE_RL_write_word_fsm_action_l117c22:
	  write_word_fsm_state_mkFSMstate_D_IN = 4'd4;
      WILL_FIRE_RL_write_word_fsm_action_r_init_l119c17:
	  write_word_fsm_state_mkFSMstate_D_IN = 4'd5;
      WILL_FIRE_RL_write_word_fsm_action_l119c35:
	  write_word_fsm_state_mkFSMstate_D_IN = 4'd7;
      WILL_FIRE_RL_write_word_fsm_action_l120c26:
	  write_word_fsm_state_mkFSMstate_D_IN = 4'd9;
      write_word_fsm_state_mkFSMstate == 4'd9:
	  write_word_fsm_state_mkFSMstate_D_IN = 4'd10;
      write_word_fsm_state_mkFSMstate == 4'd10:
	  write_word_fsm_state_mkFSMstate_D_IN = 4'd11;
      write_word_fsm_state_mkFSMstate == 4'd11:
	  write_word_fsm_state_mkFSMstate_D_IN = 4'd12;
      WILL_FIRE_RL_write_word_fsm_action_l143c9:
	  write_word_fsm_state_mkFSMstate_D_IN = 4'd13;
      default: write_word_fsm_state_mkFSMstate_D_IN =
		   4'b1010 /* unspecified value */ ;
    endcase
  end
  assign write_word_fsm_state_mkFSMstate_EN =
	     WILL_FIRE_RL_write_word_fsm_idle_l141c26 ||
	     WILL_FIRE_RL_write_word_fsm_action_l108c13 ||
	     write_word_fsm_state_mkFSMstate == 4'd1 ||
	     write_word_fsm_state_mkFSMstate == 4'd2 ||
	     WILL_FIRE_RL_write_word_fsm_action_l117c22 ||
	     WILL_FIRE_RL_write_word_fsm_action_r_init_l119c17 ||
	     WILL_FIRE_RL_write_word_fsm_action_l119c35 ||
	     WILL_FIRE_RL_write_word_fsm_action_l120c26 ||
	     write_word_fsm_state_mkFSMstate == 4'd9 ||
	     write_word_fsm_state_mkFSMstate == 4'd10 ||
	     write_word_fsm_state_mkFSMstate == 4'd11 ||
	     WILL_FIRE_RL_write_word_fsm_action_l143c9 ;

  // submodule cmd_in_flight_q
  assign cmd_in_flight_q_D_IN = cmd_q_D_OUT ;
  assign cmd_in_flight_q_ENQ =
	     WILL_FIRE_RL_launch_write_word || WILL_FIRE_RL_launch_read_word ;
  assign cmd_in_flight_q_DEQ =
	     WILL_FIRE_RL_write_word_fsm_action_l143c9 ||
	     WILL_FIRE_RL_read_word_fsm_action_l130c9 ;
  assign cmd_in_flight_q_CLR = 1'b0 ;

  // submodule cmd_q
  always@(EN_read_word or
	  MUX_cmd_q_enq_1__VAL_1 or
	  EN_read_ref_word or
	  MUX_cmd_q_enq_1__VAL_2 or
	  EN_write_word or
	  MUX_cmd_q_enq_1__VAL_3 or
	  EN_write_ref_word or MUX_cmd_q_enq_1__VAL_4)
  begin
    case (1'b1) // synopsys parallel_case
      EN_read_word: cmd_q_D_IN = MUX_cmd_q_enq_1__VAL_1;
      EN_read_ref_word: cmd_q_D_IN = MUX_cmd_q_enq_1__VAL_2;
      EN_write_word: cmd_q_D_IN = MUX_cmd_q_enq_1__VAL_3;
      EN_write_ref_word: cmd_q_D_IN = MUX_cmd_q_enq_1__VAL_4;
      default: cmd_q_D_IN =
		   101'h0AAAAAAAAAAAAAAAAAAAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign cmd_q_ENQ =
	     EN_read_word || EN_read_ref_word || EN_write_word ||
	     EN_write_ref_word ;
  assign cmd_q_DEQ =
	     WILL_FIRE_RL_launch_write_word || WILL_FIRE_RL_launch_read_word ;
  assign cmd_q_CLR = 1'b0 ;

  // submodule resp_q
  assign resp_q_D_IN =
	     WILL_FIRE_RL_read_word_fsm_action_l130c9 ?
	       MUX_resp_q_enq_1__VAL_1 :
	       81'h100000000000000000000 ;
  assign resp_q_ENQ =
	     WILL_FIRE_RL_read_word_fsm_action_l130c9 ||
	     WILL_FIRE_RL_write_word_fsm_action_l143c9 ;
  assign resp_q_DEQ = EN_response && resp_q_EMPTY_N || EN_response_blocking ;
  assign resp_q_CLR = 1'b0 ;

  // remaining internal signals
  assign NOT_cmd_in_flight_q_first__4_BIT_100_5_00_AND__ETC___d113 =
	     !cmd_in_flight_q_D_OUT[100] &&
	     read_word_fsm_jj_repeat_count[0] &&
	     read_word_fsm_state_mkFSMstate == 4'd3 ||
	     read_word_fsm_state_mkFSMstate == 4'd5 ;
  assign NOT_cmd_in_flight_q_first__4_BIT_100_5_00_AND__ETC___d212 =
	     !cmd_in_flight_q_D_OUT[100] &&
	     write_word_fsm_jj_repeat_count[0] &&
	     write_word_fsm_state_mkFSMstate == 4'd3 ||
	     write_word_fsm_state_mkFSMstate == 4'd5 ;
  assign NOT_read_word_fsm_abort_whas_6_OR_NOT_read_wor_ETC___d288 =
	     read_word_fsm_state_mkFSMstate != 4'd0 &&
	     read_word_fsm_state_mkFSMstate != 4'd13 ||
	     read_word_fsm_start_reg_1 && !read_word_fsm_state_fired ;
  assign NOT_read_word_fsm_jj_repeat_count_read__01_BIT_ETC___d118 =
	     !read_word_fsm_jj_repeat_count[0] &&
	     read_word_fsm_state_mkFSMstate == 4'd7 ;
  assign NOT_write_word_fsm_abort_whas__59_81_OR_NOT_wr_ETC___d295 =
	     write_word_fsm_state_mkFSMstate != 4'd0 &&
	     write_word_fsm_state_mkFSMstate != 4'd13 ||
	     write_word_fsm_start_reg_1 && !write_word_fsm_state_fired ;
  assign NOT_write_word_fsm_jj_repeat_count_read__00_BI_ETC___d217 =
	     !write_word_fsm_jj_repeat_count[0] &&
	     write_word_fsm_state_mkFSMstate == 4'd7 ;
  assign _0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44 =
	     8'b00000001 << pending_addr[18:16] ;
  assign cmd_in_flight_q_i_notEmpty__1_AND_NOT_0b1_SL_p_ETC___d93 =
	     cmd_in_flight_q_EMPTY_N &&
	     (!_0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[0] ||
	      !mram_busy_q[0]) &&
	     (!_0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[1] ||
	      !mram_busy_q[1]) &&
	     (!_0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[2] ||
	      !mram_busy_q[2]) &&
	     (!_0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[3] ||
	      !mram_busy_q[3]) &&
	     (!_0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[4] ||
	      !mram_busy_q[4]) &&
	     (!_0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[5] ||
	      !mram_busy_q[5]) &&
	     (!_0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[6] ||
	      !mram_busy_q[6]) &&
	     (!_0b1_SL_pending_addr_2_BITS_18_TO_16_3___d44[7] ||
	      !mram_busy_q[7]) ;
  assign cmd_q_notEmpty__53_OR_op_active_58_03_OR_NOT_r_ETC___d305 =
	     cmd_q_EMPTY_N || op_active ||
	     NOT_read_word_fsm_abort_whas_6_OR_NOT_read_wor_ETC___d288 ||
	     read_word_fsm_start_reg ||
	     NOT_write_word_fsm_abort_whas__59_81_OR_NOT_wr_ETC___d295 ||
	     write_word_fsm_start_reg ;
  assign read_word_fsm_abort_whas_AND_read_word_fsm_abo_ETC___d153 =
	     (read_word_fsm_state_mkFSMstate == 4'd0 ||
	      read_word_fsm_state_mkFSMstate == 4'd13) &&
	     (!read_word_fsm_start_reg_1 || read_word_fsm_state_fired) ;
  assign write_word_fsm_abort_whas__59_AND_write_word_f_ETC___d244 =
	     (write_word_fsm_state_mkFSMstate == 4'd0 ||
	      write_word_fsm_state_mkFSMstate == 4'd13) &&
	     (!write_word_fsm_start_reg_1 || write_word_fsm_state_fired) ;
  assign x__h37011 = { read_word_fsm_jj_repeat_count[2:0], 1'd0 } ;
  assign x__h71641 = { write_word_fsm_jj_repeat_count[2:0], 1'd0 } ;
  assign x_data__h36748 =
	     pending_addr[16] ? mram_dout_q[157:79] : mram_dout_q[78:0] ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        get_dout <= `BSV_ASSIGNMENT_DELAY 1'd0;
	issue_cmd <= `BSV_ASSIGNMENT_DELAY 1'd0;
	mram_busy_q <= `BSV_ASSIGNMENT_DELAY 8'd0;
	mram_dout_q <= `BSV_ASSIGNMENT_DELAY 158'd0;
	op_active <= `BSV_ASSIGNMENT_DELAY 1'd0;
	pending_addr <= `BSV_ASSIGNMENT_DELAY 20'd0;
	pending_din <= `BSV_ASSIGNMENT_DELAY 79'd0;
	pending_ref_prg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	pending_write <= `BSV_ASSIGNMENT_DELAY 1'd0;
	read_word_fsm_jj_repeat_count <= `BSV_ASSIGNMENT_DELAY 4'd1;
	read_word_fsm_start_reg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	read_word_fsm_start_reg_1 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	read_word_fsm_state_can_overlap <= `BSV_ASSIGNMENT_DELAY 1'd1;
	read_word_fsm_state_fired <= `BSV_ASSIGNMENT_DELAY 1'd0;
	read_word_fsm_state_mkFSMstate <= `BSV_ASSIGNMENT_DELAY 4'd0;
	write_word_fsm_jj_repeat_count <= `BSV_ASSIGNMENT_DELAY 4'd1;
	write_word_fsm_start_reg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	write_word_fsm_start_reg_1 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	write_word_fsm_state_can_overlap <= `BSV_ASSIGNMENT_DELAY 1'd1;
	write_word_fsm_state_fired <= `BSV_ASSIGNMENT_DELAY 1'd0;
	write_word_fsm_state_mkFSMstate <= `BSV_ASSIGNMENT_DELAY 4'd0;
      end
    else
      begin
        if (get_dout_EN) get_dout <= `BSV_ASSIGNMENT_DELAY get_dout_D_IN;
	if (issue_cmd_EN) issue_cmd <= `BSV_ASSIGNMENT_DELAY issue_cmd_D_IN;
	if (mram_busy_q_EN)
	  mram_busy_q <= `BSV_ASSIGNMENT_DELAY mram_busy_q_D_IN;
	if (mram_dout_q_EN)
	  mram_dout_q <= `BSV_ASSIGNMENT_DELAY mram_dout_q_D_IN;
	if (op_active_EN) op_active <= `BSV_ASSIGNMENT_DELAY op_active_D_IN;
	if (pending_addr_EN)
	  pending_addr <= `BSV_ASSIGNMENT_DELAY pending_addr_D_IN;
	if (pending_din_EN)
	  pending_din <= `BSV_ASSIGNMENT_DELAY pending_din_D_IN;
	if (pending_ref_prg_EN)
	  pending_ref_prg <= `BSV_ASSIGNMENT_DELAY pending_ref_prg_D_IN;
	if (pending_write_EN)
	  pending_write <= `BSV_ASSIGNMENT_DELAY pending_write_D_IN;
	if (read_word_fsm_jj_repeat_count_EN)
	  read_word_fsm_jj_repeat_count <= `BSV_ASSIGNMENT_DELAY
	      read_word_fsm_jj_repeat_count_D_IN;
	if (read_word_fsm_start_reg_EN)
	  read_word_fsm_start_reg <= `BSV_ASSIGNMENT_DELAY
	      read_word_fsm_start_reg_D_IN;
	if (read_word_fsm_start_reg_1_EN)
	  read_word_fsm_start_reg_1 <= `BSV_ASSIGNMENT_DELAY
	      read_word_fsm_start_reg_1_D_IN;
	if (read_word_fsm_state_can_overlap_EN)
	  read_word_fsm_state_can_overlap <= `BSV_ASSIGNMENT_DELAY
	      read_word_fsm_state_can_overlap_D_IN;
	if (read_word_fsm_state_fired_EN)
	  read_word_fsm_state_fired <= `BSV_ASSIGNMENT_DELAY
	      read_word_fsm_state_fired_D_IN;
	if (read_word_fsm_state_mkFSMstate_EN)
	  read_word_fsm_state_mkFSMstate <= `BSV_ASSIGNMENT_DELAY
	      read_word_fsm_state_mkFSMstate_D_IN;
	if (write_word_fsm_jj_repeat_count_EN)
	  write_word_fsm_jj_repeat_count <= `BSV_ASSIGNMENT_DELAY
	      write_word_fsm_jj_repeat_count_D_IN;
	if (write_word_fsm_start_reg_EN)
	  write_word_fsm_start_reg <= `BSV_ASSIGNMENT_DELAY
	      write_word_fsm_start_reg_D_IN;
	if (write_word_fsm_start_reg_1_EN)
	  write_word_fsm_start_reg_1 <= `BSV_ASSIGNMENT_DELAY
	      write_word_fsm_start_reg_1_D_IN;
	if (write_word_fsm_state_can_overlap_EN)
	  write_word_fsm_state_can_overlap <= `BSV_ASSIGNMENT_DELAY
	      write_word_fsm_state_can_overlap_D_IN;
	if (write_word_fsm_state_fired_EN)
	  write_word_fsm_state_fired <= `BSV_ASSIGNMENT_DELAY
	      write_word_fsm_state_fired_D_IN;
	if (write_word_fsm_state_mkFSMstate_EN)
	  write_word_fsm_state_mkFSMstate <= `BSV_ASSIGNMENT_DELAY
	      write_word_fsm_state_mkFSMstate_D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    get_dout = 1'h0;
    issue_cmd = 1'h0;
    mram_busy_q = 8'hAA;
    mram_dout_q = 158'h2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    op_active = 1'h0;
    pending_addr = 20'hAAAAA;
    pending_din = 79'h2AAAAAAAAAAAAAAAAAAA;
    pending_ref_prg = 1'h0;
    pending_write = 1'h0;
    read_word_fsm_jj_repeat_count = 4'hA;
    read_word_fsm_start_reg = 1'h0;
    read_word_fsm_start_reg_1 = 1'h0;
    read_word_fsm_state_can_overlap = 1'h0;
    read_word_fsm_state_fired = 1'h0;
    read_word_fsm_state_mkFSMstate = 4'hA;
    write_word_fsm_jj_repeat_count = 4'hA;
    write_word_fsm_start_reg = 1'h0;
    write_word_fsm_start_reg_1 = 1'h0;
    write_word_fsm_state_can_overlap = 1'h0;
    write_word_fsm_state_fired = 1'h0;
    write_word_fsm_state_mkFSMstate = 4'hA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_write_word_fsm_action_l120c26 &&
	  (write_word_fsm_state_mkFSMstate == 4'd9 ||
	   write_word_fsm_state_mkFSMstate == 4'd10 ||
	   write_word_fsm_state_mkFSMstate == 4'd11 ||
	   WILL_FIRE_RL_write_word_fsm_action_l143c9))
	$display("Error: \"BistEtMramTranslator.bsv\", line 120, column 26: (R0001)\n  Mutually exclusive rules (from the ME sets\n  [RL_write_word_fsm_action_l120c26] and [RL_write_word_fsm_action_l121c26,\n  RL_write_word_fsm_action_l122c25, RL_write_word_fsm_action_l123c25,\n  RL_write_word_fsm_action_l143c9] ) fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (write_word_fsm_state_mkFSMstate == 4'd9 &&
	  (write_word_fsm_state_mkFSMstate == 4'd10 ||
	   write_word_fsm_state_mkFSMstate == 4'd11 ||
	   WILL_FIRE_RL_write_word_fsm_action_l143c9))
	$display("Error: \"BistEtMramTranslator.bsv\", line 121, column 26: (R0001)\n  Mutually exclusive rules (from the ME sets\n  [RL_write_word_fsm_action_l121c26] and [RL_write_word_fsm_action_l122c25,\n  RL_write_word_fsm_action_l123c25, RL_write_word_fsm_action_l143c9] ) fired\n  in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (write_word_fsm_state_mkFSMstate == 4'd10 &&
	  (write_word_fsm_state_mkFSMstate == 4'd11 ||
	   WILL_FIRE_RL_write_word_fsm_action_l143c9))
	$display("Error: \"BistEtMramTranslator.bsv\", line 122, column 25: (R0001)\n  Mutually exclusive rules (from the ME sets\n  [RL_write_word_fsm_action_l122c25] and [RL_write_word_fsm_action_l123c25,\n  RL_write_word_fsm_action_l143c9] ) fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (write_word_fsm_state_mkFSMstate == 4'd11 &&
	  WILL_FIRE_RL_write_word_fsm_action_l143c9)
	$display("Error: \"BistEtMramTranslator.bsv\", line 123, column 25: (R0001)\n  Mutually exclusive rules (from the ME sets\n  [RL_write_word_fsm_action_l123c25] and [RL_write_word_fsm_action_l143c9] )\n  fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_write_word_fsm_action_l108c13 &&
	  (write_word_fsm_state_mkFSMstate == 4'd1 ||
	   write_word_fsm_state_mkFSMstate == 4'd2 ||
	   WILL_FIRE_RL_write_word_fsm_action_l117c22 ||
	   WILL_FIRE_RL_write_word_fsm_action_r_init_l119c17 ||
	   WILL_FIRE_RL_write_word_fsm_action_l119c35 ||
	   WILL_FIRE_RL_write_word_fsm_action_l120c26 ||
	   write_word_fsm_state_mkFSMstate == 4'd9 ||
	   write_word_fsm_state_mkFSMstate == 4'd10 ||
	   write_word_fsm_state_mkFSMstate == 4'd11 ||
	   WILL_FIRE_RL_write_word_fsm_action_l143c9))
	$display("Error: \"BistEtMramTranslator.bsv\", line 108, column 13: (R0001)\n  Mutually exclusive rules (from the ME sets\n  [RL_write_word_fsm_action_l108c13] and [RL_write_word_fsm_action_l112c21,\n  RL_write_word_fsm_action_l113c13, RL_write_word_fsm_action_l117c22,\n  RL_write_word_fsm_action_r_init_l119c17, RL_write_word_fsm_action_l119c35,\n  RL_write_word_fsm_action_l120c26, RL_write_word_fsm_action_l121c26,\n  RL_write_word_fsm_action_l122c25, RL_write_word_fsm_action_l123c25,\n  RL_write_word_fsm_action_l143c9] ) fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (write_word_fsm_state_mkFSMstate == 4'd1 &&
	  (write_word_fsm_state_mkFSMstate == 4'd2 ||
	   WILL_FIRE_RL_write_word_fsm_action_l117c22 ||
	   WILL_FIRE_RL_write_word_fsm_action_r_init_l119c17 ||
	   WILL_FIRE_RL_write_word_fsm_action_l119c35 ||
	   WILL_FIRE_RL_write_word_fsm_action_l120c26 ||
	   write_word_fsm_state_mkFSMstate == 4'd9 ||
	   write_word_fsm_state_mkFSMstate == 4'd10 ||
	   write_word_fsm_state_mkFSMstate == 4'd11 ||
	   WILL_FIRE_RL_write_word_fsm_action_l143c9))
	$display("Error: \"BistEtMramTranslator.bsv\", line 112, column 21: (R0001)\n  Mutually exclusive rules (from the ME sets\n  [RL_write_word_fsm_action_l112c21] and [RL_write_word_fsm_action_l113c13,\n  RL_write_word_fsm_action_l117c22, RL_write_word_fsm_action_r_init_l119c17,\n  RL_write_word_fsm_action_l119c35, RL_write_word_fsm_action_l120c26,\n  RL_write_word_fsm_action_l121c26, RL_write_word_fsm_action_l122c25,\n  RL_write_word_fsm_action_l123c25, RL_write_word_fsm_action_l143c9] ) fired\n  in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (write_word_fsm_state_mkFSMstate == 4'd2 &&
	  (WILL_FIRE_RL_write_word_fsm_action_l117c22 ||
	   WILL_FIRE_RL_write_word_fsm_action_r_init_l119c17 ||
	   WILL_FIRE_RL_write_word_fsm_action_l119c35 ||
	   WILL_FIRE_RL_write_word_fsm_action_l120c26 ||
	   write_word_fsm_state_mkFSMstate == 4'd9 ||
	   write_word_fsm_state_mkFSMstate == 4'd10 ||
	   write_word_fsm_state_mkFSMstate == 4'd11 ||
	   WILL_FIRE_RL_write_word_fsm_action_l143c9))
	$display("Error: \"BistEtMramTranslator.bsv\", line 113, column 13: (R0001)\n  Mutually exclusive rules (from the ME sets\n  [RL_write_word_fsm_action_l113c13] and [RL_write_word_fsm_action_l117c22,\n  RL_write_word_fsm_action_r_init_l119c17, RL_write_word_fsm_action_l119c35,\n  RL_write_word_fsm_action_l120c26, RL_write_word_fsm_action_l121c26,\n  RL_write_word_fsm_action_l122c25, RL_write_word_fsm_action_l123c25,\n  RL_write_word_fsm_action_l143c9] ) fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_write_word_fsm_action_l117c22 &&
	  (WILL_FIRE_RL_write_word_fsm_action_r_init_l119c17 ||
	   WILL_FIRE_RL_write_word_fsm_action_l119c35 ||
	   WILL_FIRE_RL_write_word_fsm_action_l120c26 ||
	   write_word_fsm_state_mkFSMstate == 4'd9 ||
	   write_word_fsm_state_mkFSMstate == 4'd10 ||
	   write_word_fsm_state_mkFSMstate == 4'd11 ||
	   WILL_FIRE_RL_write_word_fsm_action_l143c9))
	$display("Error: \"BistEtMramTranslator.bsv\", line 117, column 22: (R0001)\n  Mutually exclusive rules (from the ME sets\n  [RL_write_word_fsm_action_l117c22] and\n  [RL_write_word_fsm_action_r_init_l119c17, RL_write_word_fsm_action_l119c35,\n  RL_write_word_fsm_action_l120c26, RL_write_word_fsm_action_l121c26,\n  RL_write_word_fsm_action_l122c25, RL_write_word_fsm_action_l123c25,\n  RL_write_word_fsm_action_l143c9] ) fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_write_word_fsm_action_l119c35 &&
	  (WILL_FIRE_RL_write_word_fsm_action_l120c26 ||
	   write_word_fsm_state_mkFSMstate == 4'd9 ||
	   write_word_fsm_state_mkFSMstate == 4'd10 ||
	   write_word_fsm_state_mkFSMstate == 4'd11 ||
	   WILL_FIRE_RL_write_word_fsm_action_l143c9))
	$display("Error: \"BistEtMramTranslator.bsv\", line 119, column 35: (R0001)\n  Mutually exclusive rules (from the ME sets\n  [RL_write_word_fsm_action_l119c35] and [RL_write_word_fsm_action_l120c26,\n  RL_write_word_fsm_action_l121c26, RL_write_word_fsm_action_l122c25,\n  RL_write_word_fsm_action_l123c25, RL_write_word_fsm_action_l143c9] ) fired\n  in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_write_word_fsm_action_r_init_l119c17 &&
	  (WILL_FIRE_RL_write_word_fsm_action_l119c35 ||
	   WILL_FIRE_RL_write_word_fsm_action_l120c26 ||
	   write_word_fsm_state_mkFSMstate == 4'd9 ||
	   write_word_fsm_state_mkFSMstate == 4'd10 ||
	   write_word_fsm_state_mkFSMstate == 4'd11 ||
	   WILL_FIRE_RL_write_word_fsm_action_l143c9))
	$display("Error: \"BistEtMramTranslator.bsv\", line 119, column 17: (R0001)\n  Mutually exclusive rules (from the ME sets\n  [RL_write_word_fsm_action_r_init_l119c17] and\n  [RL_write_word_fsm_action_l119c35, RL_write_word_fsm_action_l120c26,\n  RL_write_word_fsm_action_l121c26, RL_write_word_fsm_action_l122c25,\n  RL_write_word_fsm_action_l123c25, RL_write_word_fsm_action_l143c9] ) fired\n  in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_read_word_fsm_action_l108c13 &&
	  (read_word_fsm_state_mkFSMstate == 4'd1 ||
	   read_word_fsm_state_mkFSMstate == 4'd2 ||
	   WILL_FIRE_RL_read_word_fsm_action_l117c22 ||
	   WILL_FIRE_RL_read_word_fsm_action_r_init_l119c17 ||
	   WILL_FIRE_RL_read_word_fsm_action_l119c35 ||
	   WILL_FIRE_RL_read_word_fsm_action_l120c26 ||
	   read_word_fsm_state_mkFSMstate == 4'd9 ||
	   read_word_fsm_state_mkFSMstate == 4'd10 ||
	   read_word_fsm_state_mkFSMstate == 4'd11 ||
	   WILL_FIRE_RL_read_word_fsm_action_l130c9))
	$display("Error: \"BistEtMramTranslator.bsv\", line 108, column 13: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_read_word_fsm_action_l108c13]\n  and [RL_read_word_fsm_action_l112c21, RL_read_word_fsm_action_l113c13,\n  RL_read_word_fsm_action_l117c22, RL_read_word_fsm_action_r_init_l119c17,\n  RL_read_word_fsm_action_l119c35, RL_read_word_fsm_action_l120c26,\n  RL_read_word_fsm_action_l121c26, RL_read_word_fsm_action_l122c25,\n  RL_read_word_fsm_action_l123c25, RL_read_word_fsm_action_l130c9] ) fired in\n  the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (read_word_fsm_state_mkFSMstate == 4'd1 &&
	  (read_word_fsm_state_mkFSMstate == 4'd2 ||
	   WILL_FIRE_RL_read_word_fsm_action_l117c22 ||
	   WILL_FIRE_RL_read_word_fsm_action_r_init_l119c17 ||
	   WILL_FIRE_RL_read_word_fsm_action_l119c35 ||
	   WILL_FIRE_RL_read_word_fsm_action_l120c26 ||
	   read_word_fsm_state_mkFSMstate == 4'd9 ||
	   read_word_fsm_state_mkFSMstate == 4'd10 ||
	   read_word_fsm_state_mkFSMstate == 4'd11 ||
	   WILL_FIRE_RL_read_word_fsm_action_l130c9))
	$display("Error: \"BistEtMramTranslator.bsv\", line 112, column 21: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_read_word_fsm_action_l112c21]\n  and [RL_read_word_fsm_action_l113c13, RL_read_word_fsm_action_l117c22,\n  RL_read_word_fsm_action_r_init_l119c17, RL_read_word_fsm_action_l119c35,\n  RL_read_word_fsm_action_l120c26, RL_read_word_fsm_action_l121c26,\n  RL_read_word_fsm_action_l122c25, RL_read_word_fsm_action_l123c25,\n  RL_read_word_fsm_action_l130c9] ) fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (read_word_fsm_state_mkFSMstate == 4'd2 &&
	  (WILL_FIRE_RL_read_word_fsm_action_l117c22 ||
	   WILL_FIRE_RL_read_word_fsm_action_r_init_l119c17 ||
	   WILL_FIRE_RL_read_word_fsm_action_l119c35 ||
	   WILL_FIRE_RL_read_word_fsm_action_l120c26 ||
	   read_word_fsm_state_mkFSMstate == 4'd9 ||
	   read_word_fsm_state_mkFSMstate == 4'd10 ||
	   read_word_fsm_state_mkFSMstate == 4'd11 ||
	   WILL_FIRE_RL_read_word_fsm_action_l130c9))
	$display("Error: \"BistEtMramTranslator.bsv\", line 113, column 13: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_read_word_fsm_action_l113c13]\n  and [RL_read_word_fsm_action_l117c22,\n  RL_read_word_fsm_action_r_init_l119c17, RL_read_word_fsm_action_l119c35,\n  RL_read_word_fsm_action_l120c26, RL_read_word_fsm_action_l121c26,\n  RL_read_word_fsm_action_l122c25, RL_read_word_fsm_action_l123c25,\n  RL_read_word_fsm_action_l130c9] ) fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_read_word_fsm_action_r_init_l119c17 &&
	  (WILL_FIRE_RL_read_word_fsm_action_l119c35 ||
	   WILL_FIRE_RL_read_word_fsm_action_l120c26 ||
	   read_word_fsm_state_mkFSMstate == 4'd9 ||
	   read_word_fsm_state_mkFSMstate == 4'd10 ||
	   read_word_fsm_state_mkFSMstate == 4'd11 ||
	   WILL_FIRE_RL_read_word_fsm_action_l130c9))
	$display("Error: \"BistEtMramTranslator.bsv\", line 119, column 17: (R0001)\n  Mutually exclusive rules (from the ME sets\n  [RL_read_word_fsm_action_r_init_l119c17] and\n  [RL_read_word_fsm_action_l119c35, RL_read_word_fsm_action_l120c26,\n  RL_read_word_fsm_action_l121c26, RL_read_word_fsm_action_l122c25,\n  RL_read_word_fsm_action_l123c25, RL_read_word_fsm_action_l130c9] ) fired in\n  the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_read_word_fsm_action_l117c22 &&
	  (WILL_FIRE_RL_read_word_fsm_action_r_init_l119c17 ||
	   WILL_FIRE_RL_read_word_fsm_action_l119c35 ||
	   WILL_FIRE_RL_read_word_fsm_action_l120c26 ||
	   read_word_fsm_state_mkFSMstate == 4'd9 ||
	   read_word_fsm_state_mkFSMstate == 4'd10 ||
	   read_word_fsm_state_mkFSMstate == 4'd11 ||
	   WILL_FIRE_RL_read_word_fsm_action_l130c9))
	$display("Error: \"BistEtMramTranslator.bsv\", line 117, column 22: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_read_word_fsm_action_l117c22]\n  and [RL_read_word_fsm_action_r_init_l119c17,\n  RL_read_word_fsm_action_l119c35, RL_read_word_fsm_action_l120c26,\n  RL_read_word_fsm_action_l121c26, RL_read_word_fsm_action_l122c25,\n  RL_read_word_fsm_action_l123c25, RL_read_word_fsm_action_l130c9] ) fired in\n  the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_read_word_fsm_action_l119c35 &&
	  (WILL_FIRE_RL_read_word_fsm_action_l120c26 ||
	   read_word_fsm_state_mkFSMstate == 4'd9 ||
	   read_word_fsm_state_mkFSMstate == 4'd10 ||
	   read_word_fsm_state_mkFSMstate == 4'd11 ||
	   WILL_FIRE_RL_read_word_fsm_action_l130c9))
	$display("Error: \"BistEtMramTranslator.bsv\", line 119, column 35: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_read_word_fsm_action_l119c35]\n  and [RL_read_word_fsm_action_l120c26, RL_read_word_fsm_action_l121c26,\n  RL_read_word_fsm_action_l122c25, RL_read_word_fsm_action_l123c25,\n  RL_read_word_fsm_action_l130c9] ) fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_read_word_fsm_action_l120c26 &&
	  (read_word_fsm_state_mkFSMstate == 4'd9 ||
	   read_word_fsm_state_mkFSMstate == 4'd10 ||
	   read_word_fsm_state_mkFSMstate == 4'd11 ||
	   WILL_FIRE_RL_read_word_fsm_action_l130c9))
	$display("Error: \"BistEtMramTranslator.bsv\", line 120, column 26: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_read_word_fsm_action_l120c26]\n  and [RL_read_word_fsm_action_l121c26, RL_read_word_fsm_action_l122c25,\n  RL_read_word_fsm_action_l123c25, RL_read_word_fsm_action_l130c9] ) fired in\n  the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (read_word_fsm_state_mkFSMstate == 4'd9 &&
	  (read_word_fsm_state_mkFSMstate == 4'd10 ||
	   read_word_fsm_state_mkFSMstate == 4'd11 ||
	   WILL_FIRE_RL_read_word_fsm_action_l130c9))
	$display("Error: \"BistEtMramTranslator.bsv\", line 121, column 26: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_read_word_fsm_action_l121c26]\n  and [RL_read_word_fsm_action_l122c25, RL_read_word_fsm_action_l123c25,\n  RL_read_word_fsm_action_l130c9] ) fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (read_word_fsm_state_mkFSMstate == 4'd10 &&
	  (read_word_fsm_state_mkFSMstate == 4'd11 ||
	   WILL_FIRE_RL_read_word_fsm_action_l130c9))
	$display("Error: \"BistEtMramTranslator.bsv\", line 122, column 25: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_read_word_fsm_action_l122c25]\n  and [RL_read_word_fsm_action_l123c25, RL_read_word_fsm_action_l130c9] )\n  fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (read_word_fsm_state_mkFSMstate == 4'd11 &&
	  WILL_FIRE_RL_read_word_fsm_action_l130c9)
	$display("Error: \"BistEtMramTranslator.bsv\", line 123, column 25: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_read_word_fsm_action_l123c25]\n  and [RL_read_word_fsm_action_l130c9] ) fired in the same clock cycle.\n");
  end
  // synopsys translate_on
endmodule  // mkBistEtMramTranslator

