//
// Generated by Bluespec Compiler, version 2025.07-40-g5dccc4ba (build 5dccc4ba)
//
// On Tue Mar 17 12:18:36 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// AXI4_AWREADY                   O     1 reg
// AXI4_WREADY                    O     1 reg
// AXI4_BVALID                    O     1 reg
// AXI4_BRESP                     O     2 reg
// AXI4_BID                       O     9 reg
// AXI4_ARREADY                   O     1 reg
// AXI4_RVALID                    O     1 reg
// AXI4_RRESP                     O     2 reg
// AXI4_RDATA                     O    64 reg
// AXI4_RLAST                     O     1 reg
// AXI4_RID                       O     9 reg
// AXI4L_awvalid                  O     1 reg
// AXI4L_awaddr                   O    32 reg
// AXI4L_awprot                   O     3 reg
// AXI4L_awsize                   O     2 reg
// AXI4L_wvalid                   O     1 reg
// AXI4L_wdata                    O    64 reg
// AXI4L_wstrb                    O     8 reg
// AXI4L_bready                   O     1 reg
// AXI4L_arvalid                  O     1 reg
// AXI4L_araddr                   O    32 reg
// AXI4L_arprot                   O     3 reg
// AXI4L_arsize                   O     2 reg
// AXI4L_rready                   O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// AXI4_AWVALID                   I     1
// AXI4_AWADDR                    I    32 reg
// AXI4_AWSIZE                    I     3 reg
// AXI4_AWPROT                    I     3 reg
// AXI4_AWLEN                     I     8 reg
// AXI4_AWBURST                   I     2 reg
// AXI4_AWID                      I     9 reg
// AXI4_WVALID                    I     1
// AXI4_WDATA                     I    64 reg
// AXI4_WSTRB                     I     8 reg
// AXI4_WLAST                     I     1 reg
// AXI4_WID                       I     9 reg
// AXI4_BREADY                    I     1
// AXI4_ARVALID                   I     1
// AXI4_ARADDR                    I    32 reg
// AXI4_ARSIZE                    I     3 reg
// AXI4_ARPROT                    I     3 reg
// AXI4_ARLEN                     I     8 reg
// AXI4_ARBURST                   I     2 reg
// AXI4_ARID                      I     9 reg
// AXI4_RREADY                    I     1
// AXI4L_m_awready_awready        I     1
// AXI4L_m_wready_wready          I     1
// AXI4L_m_bvalid_bvalid          I     1
// AXI4L_m_bvalid_bresp           I     2 reg
// AXI4L_m_arready_arready        I     1
// AXI4L_m_rvalid_rvalid          I     1
// AXI4L_m_rvalid_rresp           I     2 reg
// AXI4L_m_rvalid_rdata           I    64 reg
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module axi2axil_64(CLK,
		   RST_N,

		   AXI4_AWVALID,
		   AXI4_AWADDR,
		   AXI4_AWSIZE,
		   AXI4_AWPROT,
		   AXI4_AWLEN,
		   AXI4_AWBURST,
		   AXI4_AWID,

		   AXI4_AWREADY,

		   AXI4_WVALID,
		   AXI4_WDATA,
		   AXI4_WSTRB,
		   AXI4_WLAST,
		   AXI4_WID,

		   AXI4_WREADY,

		   AXI4_BVALID,

		   AXI4_BRESP,

		   AXI4_BID,

		   AXI4_BREADY,

		   AXI4_ARVALID,
		   AXI4_ARADDR,
		   AXI4_ARSIZE,
		   AXI4_ARPROT,
		   AXI4_ARLEN,
		   AXI4_ARBURST,
		   AXI4_ARID,

		   AXI4_ARREADY,

		   AXI4_RVALID,

		   AXI4_RRESP,

		   AXI4_RDATA,

		   AXI4_RLAST,

		   AXI4_RID,

		   AXI4_RREADY,

		   AXI4L_awvalid,

		   AXI4L_awaddr,

		   AXI4L_awprot,

		   AXI4L_awsize,

		   AXI4L_m_awready_awready,

		   AXI4L_wvalid,

		   AXI4L_wdata,

		   AXI4L_wstrb,

		   AXI4L_m_wready_wready,

		   AXI4L_m_bvalid_bvalid,
		   AXI4L_m_bvalid_bresp,

		   AXI4L_bready,

		   AXI4L_arvalid,

		   AXI4L_araddr,

		   AXI4L_arprot,

		   AXI4L_arsize,

		   AXI4L_m_arready_arready,

		   AXI4L_m_rvalid_rvalid,
		   AXI4L_m_rvalid_rresp,
		   AXI4L_m_rvalid_rdata,

		   AXI4L_rready);
  input  CLK;
  input  RST_N;

  // action method axi4_side_m_awvalid
  input  AXI4_AWVALID;
  input  [31 : 0] AXI4_AWADDR;
  input  [2 : 0] AXI4_AWSIZE;
  input  [2 : 0] AXI4_AWPROT;
  input  [7 : 0] AXI4_AWLEN;
  input  [1 : 0] AXI4_AWBURST;
  input  [8 : 0] AXI4_AWID;

  // value method axi4_side_m_awready
  output AXI4_AWREADY;

  // action method axi4_side_m_wvalid
  input  AXI4_WVALID;
  input  [63 : 0] AXI4_WDATA;
  input  [7 : 0] AXI4_WSTRB;
  input  AXI4_WLAST;
  input  [8 : 0] AXI4_WID;

  // value method axi4_side_m_wready
  output AXI4_WREADY;

  // value method axi4_side_m_bvalid
  output AXI4_BVALID;

  // value method axi4_side_m_bresp
  output [1 : 0] AXI4_BRESP;

  // value method axi4_side_m_buser

  // value method axi4_side_m_bid
  output [8 : 0] AXI4_BID;

  // action method axi4_side_m_bready
  input  AXI4_BREADY;

  // action method axi4_side_m_arvalid
  input  AXI4_ARVALID;
  input  [31 : 0] AXI4_ARADDR;
  input  [2 : 0] AXI4_ARSIZE;
  input  [2 : 0] AXI4_ARPROT;
  input  [7 : 0] AXI4_ARLEN;
  input  [1 : 0] AXI4_ARBURST;
  input  [8 : 0] AXI4_ARID;

  // value method axi4_side_m_arready
  output AXI4_ARREADY;

  // value method axi4_side_m_rvalid
  output AXI4_RVALID;

  // value method axi4_side_m_rresp
  output [1 : 0] AXI4_RRESP;

  // value method axi4_side_m_rdata
  output [63 : 0] AXI4_RDATA;

  // value method axi4_side_m_rlast
  output AXI4_RLAST;

  // value method axi4_side_m_ruser

  // value method axi4_side_m_rid
  output [8 : 0] AXI4_RID;

  // action method axi4_side_m_rready
  input  AXI4_RREADY;

  // value method axi4l_side_m_awvalid
  output AXI4L_awvalid;

  // value method axi4l_side_m_awaddr
  output [31 : 0] AXI4L_awaddr;

  // value method axi4l_side_m_awuser

  // value method axi4l_side_m_awprot
  output [2 : 0] AXI4L_awprot;

  // value method axi4l_side_m_awsize
  output [1 : 0] AXI4L_awsize;

  // action method axi4l_side_m_awready
  input  AXI4L_m_awready_awready;

  // value method axi4l_side_m_wvalid
  output AXI4L_wvalid;

  // value method axi4l_side_m_wdata
  output [63 : 0] AXI4L_wdata;

  // value method axi4l_side_m_wstrb
  output [7 : 0] AXI4L_wstrb;

  // action method axi4l_side_m_wready
  input  AXI4L_m_wready_wready;

  // action method axi4l_side_m_bvalid
  input  AXI4L_m_bvalid_bvalid;
  input  [1 : 0] AXI4L_m_bvalid_bresp;

  // value method axi4l_side_m_bready
  output AXI4L_bready;

  // value method axi4l_side_m_arvalid
  output AXI4L_arvalid;

  // value method axi4l_side_m_araddr
  output [31 : 0] AXI4L_araddr;

  // value method axi4l_side_m_aruser

  // value method axi4l_side_m_arprot
  output [2 : 0] AXI4L_arprot;

  // value method axi4l_side_m_arsize
  output [1 : 0] AXI4L_arsize;

  // action method axi4l_side_m_arready
  input  AXI4L_m_arready_arready;

  // action method axi4l_side_m_rvalid
  input  AXI4L_m_rvalid_rvalid;
  input  [1 : 0] AXI4L_m_rvalid_rresp;
  input  [63 : 0] AXI4L_m_rvalid_rdata;

  // value method axi4l_side_m_rready
  output AXI4L_rready;

  // signals for module outputs
  wire [63 : 0] AXI4L_wdata, AXI4_RDATA;
  wire [31 : 0] AXI4L_araddr, AXI4L_awaddr;
  wire [8 : 0] AXI4_BID, AXI4_RID;
  wire [7 : 0] AXI4L_wstrb;
  wire [2 : 0] AXI4L_arprot, AXI4L_awprot;
  wire [1 : 0] AXI4L_arsize, AXI4L_awsize, AXI4_BRESP, AXI4_RRESP;
  wire AXI4L_arvalid,
       AXI4L_awvalid,
       AXI4L_bready,
       AXI4L_rready,
       AXI4L_wvalid,
       AXI4_ARREADY,
       AXI4_AWREADY,
       AXI4_BVALID,
       AXI4_RLAST,
       AXI4_RVALID,
       AXI4_WREADY;

  // register t_rg_accum_data
  reg [63 : 0] t_rg_accum_data;
  wire [63 : 0] t_rg_accum_data_D_IN;
  wire t_rg_accum_data_EN;

  // register t_rg_accum_err
  reg [1 : 0] t_rg_accum_err;
  wire [1 : 0] t_rg_accum_err_D_IN;
  wire t_rg_accum_err_EN;

  // register t_rg_accum_mask
  reg [7 : 0] t_rg_accum_mask;
  wire [7 : 0] t_rg_accum_mask_D_IN;
  wire t_rg_accum_mask_EN;

  // register t_rg_child_rd_burst
  reg [7 : 0] t_rg_child_rd_burst;
  wire [7 : 0] t_rg_child_rd_burst_D_IN;
  wire t_rg_child_rd_burst_EN;

  // register t_rg_child_rd_req_count
  reg [7 : 0] t_rg_child_rd_req_count;
  wire [7 : 0] t_rg_child_rd_req_count_D_IN;
  wire t_rg_child_rd_req_count_EN;

  // register t_rg_child_rd_res_count
  reg [7 : 0] t_rg_child_rd_res_count;
  wire [7 : 0] t_rg_child_rd_res_count_D_IN;
  wire t_rg_child_rd_res_count_EN;

  // register t_rg_child_wr_burst
  reg [7 : 0] t_rg_child_wr_burst;
  wire [7 : 0] t_rg_child_wr_burst_D_IN;
  wire t_rg_child_wr_burst_EN;

  // register t_rg_child_wr_req_count
  reg [7 : 0] t_rg_child_wr_req_count;
  wire [7 : 0] t_rg_child_wr_req_count_D_IN;
  wire t_rg_child_wr_req_count_EN;

  // register t_rg_child_wr_res_count
  reg [7 : 0] t_rg_child_wr_res_count;
  wire [7 : 0] t_rg_child_wr_res_count_D_IN;
  wire t_rg_child_wr_res_count_EN;

  // register t_rg_rd_req_beat
  reg [7 : 0] t_rg_rd_req_beat;
  wire [7 : 0] t_rg_rd_req_beat_D_IN;
  wire t_rg_rd_req_beat_EN;

  // register t_rg_rd_request
  reg [56 : 0] t_rg_rd_request;
  wire [56 : 0] t_rg_rd_request_D_IN;
  wire t_rg_rd_request_EN;

  // register t_rg_rd_resp_beat
  reg [7 : 0] t_rg_rd_resp_beat;
  wire [7 : 0] t_rg_rd_resp_beat_D_IN;
  wire t_rg_rd_resp_beat_EN;

  // register t_rg_rd_state
  reg t_rg_rd_state;
  wire t_rg_rd_state_D_IN, t_rg_rd_state_EN;

  // register t_rg_wd_request
  reg [81 : 0] t_rg_wd_request;
  wire [81 : 0] t_rg_wd_request_D_IN;
  wire t_rg_wd_request_EN;

  // register t_rg_wr_req_beat
  reg [7 : 0] t_rg_wr_req_beat;
  wire [7 : 0] t_rg_wr_req_beat_D_IN;
  wire t_rg_wr_req_beat_EN;

  // register t_rg_wr_request
  reg [56 : 0] t_rg_wr_request;
  wire [56 : 0] t_rg_wr_request_D_IN;
  wire t_rg_wr_request_EN;

  // register t_rg_wr_resp_beat
  reg [7 : 0] t_rg_wr_resp_beat;
  wire [7 : 0] t_rg_wr_resp_beat_D_IN;
  wire t_rg_wr_resp_beat_EN;

  // register t_rg_wr_state
  reg t_rg_wr_state;
  wire t_rg_wr_state_D_IN, t_rg_wr_state_EN;

  // ports of submodule t_axi_xactor_f_rd_addr
  wire [56 : 0] t_axi_xactor_f_rd_addr_D_IN, t_axi_xactor_f_rd_addr_D_OUT;
  wire t_axi_xactor_f_rd_addr_CLR,
       t_axi_xactor_f_rd_addr_DEQ,
       t_axi_xactor_f_rd_addr_EMPTY_N,
       t_axi_xactor_f_rd_addr_ENQ,
       t_axi_xactor_f_rd_addr_FULL_N;

  // ports of submodule t_axi_xactor_f_rd_data
  wire [75 : 0] t_axi_xactor_f_rd_data_D_IN, t_axi_xactor_f_rd_data_D_OUT;
  wire t_axi_xactor_f_rd_data_CLR,
       t_axi_xactor_f_rd_data_DEQ,
       t_axi_xactor_f_rd_data_EMPTY_N,
       t_axi_xactor_f_rd_data_ENQ,
       t_axi_xactor_f_rd_data_FULL_N;

  // ports of submodule t_axi_xactor_f_wr_addr
  wire [56 : 0] t_axi_xactor_f_wr_addr_D_IN, t_axi_xactor_f_wr_addr_D_OUT;
  wire t_axi_xactor_f_wr_addr_CLR,
       t_axi_xactor_f_wr_addr_DEQ,
       t_axi_xactor_f_wr_addr_EMPTY_N,
       t_axi_xactor_f_wr_addr_ENQ,
       t_axi_xactor_f_wr_addr_FULL_N;

  // ports of submodule t_axi_xactor_f_wr_data
  wire [81 : 0] t_axi_xactor_f_wr_data_D_IN, t_axi_xactor_f_wr_data_D_OUT;
  wire t_axi_xactor_f_wr_data_CLR,
       t_axi_xactor_f_wr_data_DEQ,
       t_axi_xactor_f_wr_data_EMPTY_N,
       t_axi_xactor_f_wr_data_ENQ,
       t_axi_xactor_f_wr_data_FULL_N;

  // ports of submodule t_axi_xactor_f_wr_resp
  wire [10 : 0] t_axi_xactor_f_wr_resp_D_IN, t_axi_xactor_f_wr_resp_D_OUT;
  wire t_axi_xactor_f_wr_resp_CLR,
       t_axi_xactor_f_wr_resp_DEQ,
       t_axi_xactor_f_wr_resp_EMPTY_N,
       t_axi_xactor_f_wr_resp_ENQ,
       t_axi_xactor_f_wr_resp_FULL_N;

  // ports of submodule t_axil_xactor_f_rd_addr
  wire [36 : 0] t_axil_xactor_f_rd_addr_D_IN, t_axil_xactor_f_rd_addr_D_OUT;
  wire t_axil_xactor_f_rd_addr_CLR,
       t_axil_xactor_f_rd_addr_DEQ,
       t_axil_xactor_f_rd_addr_EMPTY_N,
       t_axil_xactor_f_rd_addr_ENQ,
       t_axil_xactor_f_rd_addr_FULL_N;

  // ports of submodule t_axil_xactor_f_rd_data
  wire [65 : 0] t_axil_xactor_f_rd_data_D_IN, t_axil_xactor_f_rd_data_D_OUT;
  wire t_axil_xactor_f_rd_data_CLR,
       t_axil_xactor_f_rd_data_DEQ,
       t_axil_xactor_f_rd_data_EMPTY_N,
       t_axil_xactor_f_rd_data_ENQ,
       t_axil_xactor_f_rd_data_FULL_N;

  // ports of submodule t_axil_xactor_f_wr_addr
  wire [36 : 0] t_axil_xactor_f_wr_addr_D_IN, t_axil_xactor_f_wr_addr_D_OUT;
  wire t_axil_xactor_f_wr_addr_CLR,
       t_axil_xactor_f_wr_addr_DEQ,
       t_axil_xactor_f_wr_addr_EMPTY_N,
       t_axil_xactor_f_wr_addr_ENQ,
       t_axil_xactor_f_wr_addr_FULL_N;

  // ports of submodule t_axil_xactor_f_wr_data
  wire [71 : 0] t_axil_xactor_f_wr_data_D_IN, t_axil_xactor_f_wr_data_D_OUT;
  wire t_axil_xactor_f_wr_data_CLR,
       t_axil_xactor_f_wr_data_DEQ,
       t_axil_xactor_f_wr_data_EMPTY_N,
       t_axil_xactor_f_wr_data_ENQ,
       t_axil_xactor_f_wr_data_FULL_N;

  // ports of submodule t_axil_xactor_f_wr_resp
  wire [1 : 0] t_axil_xactor_f_wr_resp_D_IN, t_axil_xactor_f_wr_resp_D_OUT;
  wire t_axil_xactor_f_wr_resp_CLR,
       t_axil_xactor_f_wr_resp_DEQ,
       t_axil_xactor_f_wr_resp_EMPTY_N,
       t_axil_xactor_f_wr_resp_ENQ,
       t_axil_xactor_f_wr_resp_FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_t_rl_read_frm_axi,
       CAN_FIRE_RL_t_rl_read_response_to_axi,
       CAN_FIRE_RL_t_rl_send_rd_burst_req,
       CAN_FIRE_RL_t_rl_send_wr_burst_req,
       CAN_FIRE_RL_t_rl_write_frm_axi,
       CAN_FIRE_RL_t_rl_write_response_to_axi,
       CAN_FIRE_axi4_side_m_arvalid,
       CAN_FIRE_axi4_side_m_awvalid,
       CAN_FIRE_axi4_side_m_bready,
       CAN_FIRE_axi4_side_m_rready,
       CAN_FIRE_axi4_side_m_wvalid,
       CAN_FIRE_axi4l_side_m_arready,
       CAN_FIRE_axi4l_side_m_awready,
       CAN_FIRE_axi4l_side_m_bvalid,
       CAN_FIRE_axi4l_side_m_rvalid,
       CAN_FIRE_axi4l_side_m_wready,
       WILL_FIRE_RL_t_rl_read_frm_axi,
       WILL_FIRE_RL_t_rl_read_response_to_axi,
       WILL_FIRE_RL_t_rl_send_rd_burst_req,
       WILL_FIRE_RL_t_rl_send_wr_burst_req,
       WILL_FIRE_RL_t_rl_write_frm_axi,
       WILL_FIRE_RL_t_rl_write_response_to_axi,
       WILL_FIRE_axi4_side_m_arvalid,
       WILL_FIRE_axi4_side_m_awvalid,
       WILL_FIRE_axi4_side_m_bready,
       WILL_FIRE_axi4_side_m_rready,
       WILL_FIRE_axi4_side_m_wvalid,
       WILL_FIRE_axi4l_side_m_arready,
       WILL_FIRE_axi4l_side_m_awready,
       WILL_FIRE_axi4l_side_m_bvalid,
       WILL_FIRE_axi4l_side_m_rvalid,
       WILL_FIRE_axi4l_side_m_wready;

  // inputs to muxes for submodule ports
  reg [1 : 0] MUX_t_rg_accum_err_write_1__VAL_1;
  wire [71 : 0] MUX_t_axil_xactor_f_wr_data_enq_1__VAL_1;
  wire [56 : 0] MUX_t_rg_rd_request_write_1__VAL_2,
		MUX_t_rg_wr_request_write_1__VAL_2;
  wire [36 : 0] MUX_t_axil_xactor_f_rd_addr_enq_1__VAL_1,
		MUX_t_axil_xactor_f_rd_addr_enq_1__VAL_2,
		MUX_t_axil_xactor_f_wr_addr_enq_1__VAL_1,
		MUX_t_axil_xactor_f_wr_addr_enq_1__VAL_2;
  wire [7 : 0] MUX_t_rg_rd_req_beat_write_1__VAL_1,
	       MUX_t_rg_rd_resp_beat_write_1__VAL_1,
	       MUX_t_rg_rd_resp_beat_write_1__VAL_2,
	       MUX_t_rg_wr_req_beat_write_1__VAL_1,
	       MUX_t_rg_wr_resp_beat_write_1__VAL_1,
	       MUX_t_rg_wr_resp_beat_write_1__VAL_2;
  wire MUX_t_rg_rd_state_write_1__SEL_1, MUX_t_rg_wr_state_write_1__SEL_1;

  // declarations used by system tasks
  // synopsys translate_off
  reg TASK_testplusargs___d14;
  reg TASK_testplusargs___d15;
  reg TASK_testplusargs___d16;
  reg [63 : 0] v__h2005;
  reg TASK_testplusargs___d25;
  reg TASK_testplusargs___d26;
  reg TASK_testplusargs___d27;
  reg [63 : 0] v__h2166;
  reg TASK_testplusargs___d101;
  reg TASK_testplusargs___d102;
  reg TASK_testplusargs___d103;
  reg [63 : 0] v__h3485;
  reg TASK_testplusargs___d129;
  reg TASK_testplusargs___d130;
  reg TASK_testplusargs___d131;
  reg [63 : 0] v__h3767;
  reg TASK_testplusargs___d139;
  reg TASK_testplusargs___d140;
  reg TASK_testplusargs___d141;
  reg [63 : 0] v__h3922;
  reg TASK_testplusargs___d68;
  reg TASK_testplusargs___d69;
  reg TASK_testplusargs___d70;
  reg [63 : 0] v__h2738;
  reg TASK_testplusargs___d74;
  reg TASK_testplusargs___d75;
  reg TASK_testplusargs___d76;
  reg [63 : 0] v__h2882;
  reg TASK_testplusargs___d80;
  reg TASK_testplusargs___d81;
  reg TASK_testplusargs___d82;
  reg [63 : 0] v__h3019;
  reg TASK_testplusargs___d174;
  reg TASK_testplusargs___d175;
  reg TASK_testplusargs___d176;
  reg [63 : 0] v__h4529;
  reg TASK_testplusargs___d184;
  reg TASK_testplusargs___d185;
  reg TASK_testplusargs___d186;
  reg [63 : 0] v__h4678;
  reg TASK_testplusargs___d289;
  reg TASK_testplusargs___d290;
  reg TASK_testplusargs___d291;
  reg [63 : 0] v__h6060;
  reg TASK_testplusargs___d221;
  reg TASK_testplusargs___d222;
  reg TASK_testplusargs___d223;
  reg [63 : 0] v__h5106;
  reg TASK_testplusargs___d238;
  reg TASK_testplusargs___d239;
  reg TASK_testplusargs___d240;
  reg [63 : 0] v__h5336;
  reg TASK_testplusargs___d246;
  reg TASK_testplusargs___d247;
  reg TASK_testplusargs___d248;
  reg [63 : 0] v__h5499;
  reg TASK_testplusargs___d252;
  reg TASK_testplusargs___d253;
  reg TASK_testplusargs___d254;
  reg [63 : 0] v__h5636;
  reg TASK_testplusargs_01_OR_TASK_testplusargs_02_A_ETC___d109;
  reg TASK_testplusargs_01_OR_TASK_testplusargs_02_A_ETC___d111;
  reg TASK_testplusargs_01_OR_TASK_testplusargs_02_A_ETC___d113;
  reg TASK_testplusargs_01_OR_TASK_testplusargs_02_A_ETC___d119;
  reg TASK_testplusargs_01_OR_TASK_testplusargs_02_A_ETC___d121;
  reg TASK_testplusargs_01_OR_TASK_testplusargs_02_A_ETC___d123;
  reg TASK_testplusargs_29_OR_TASK_testplusargs_30_A_ETC___d135;
  reg TASK_testplusargs_29_OR_TASK_testplusargs_30_A_ETC___d136;
  reg TASK_testplusargs_29_OR_TASK_testplusargs_30_A_ETC___d137;
  reg TASK_testplusargs_29_OR_TASK_testplusargs_30_A_ETC___d138;
  reg TASK_testplusargs_21_OR_TASK_testplusargs_22_A_ETC___d229;
  reg TASK_testplusargs_21_OR_TASK_testplusargs_22_A_ETC___d231;
  reg TASK_testplusargs_38_OR_TASK_testplusargs_39_A_ETC___d244;
  reg TASK_testplusargs_38_OR_TASK_testplusargs_39_A_ETC___d245;
  reg TASK_testplusargs_89_OR_TASK_testplusargs_90_A_ETC___d296;
  reg TASK_testplusargs_89_OR_TASK_testplusargs_90_A_ETC___d298;
  reg TASK_testplusargs_89_OR_TASK_testplusargs_90_A_ETC___d299;
  reg TASK_testplusargs_89_OR_TASK_testplusargs_90_A_ETC___d305;
  // synopsys translate_on

  // remaining internal signals
  reg [31 : 0] axil_req_awaddr__h5224, axil_request_araddr__h2652;
  reg [2 : 0] CASE_t_rg_rd_request_BITS_18_TO_11_3_2_7_3_15_4_1__q1,
	      CASE_t_rg_wr_request_BITS_21_TO_14_3_2_7_3_15_4_1__q2;
  wire [63 : 0] axil_data___h4029;
  wire [31 : 0] mask__h2418,
		mask__h4791,
		new_address__h2416,
		new_address__h4789,
		temp1__h2419,
		temp1__h4792,
		temp2__h2420,
		temp2__h4793,
		y__h2539,
		y__h4912;
  wire [7 : 0] axil_wstrb__h4028;
  wire [5 : 0] x__h4138;
  wire [2 : 0] x__h2483, x__h4856;
  wire [1 : 0] IF_t_axil_xactor_f_wr_resp_first__72_EQ_2_74_T_ETC___d275,
	       axil_req_awsize__h4060,
	       axil_req_awsize__h5227,
	       axil_request_arsize__h1827,
	       axil_request_arsize__h2655;

  // action method axi4_side_m_awvalid
  assign CAN_FIRE_axi4_side_m_awvalid = 1'd1 ;
  assign WILL_FIRE_axi4_side_m_awvalid = 1'd1 ;

  // value method axi4_side_m_awready
  assign AXI4_AWREADY = t_axi_xactor_f_wr_addr_FULL_N ;

  // action method axi4_side_m_wvalid
  assign CAN_FIRE_axi4_side_m_wvalid = 1'd1 ;
  assign WILL_FIRE_axi4_side_m_wvalid = 1'd1 ;

  // value method axi4_side_m_wready
  assign AXI4_WREADY = t_axi_xactor_f_wr_data_FULL_N ;

  // value method axi4_side_m_bvalid
  assign AXI4_BVALID = t_axi_xactor_f_wr_resp_EMPTY_N ;

  // value method axi4_side_m_bresp
  assign AXI4_BRESP = t_axi_xactor_f_wr_resp_D_OUT[10:9] ;

  // value method axi4_side_m_bid
  assign AXI4_BID = t_axi_xactor_f_wr_resp_D_OUT[8:0] ;

  // action method axi4_side_m_bready
  assign CAN_FIRE_axi4_side_m_bready = 1'd1 ;
  assign WILL_FIRE_axi4_side_m_bready = 1'd1 ;

  // action method axi4_side_m_arvalid
  assign CAN_FIRE_axi4_side_m_arvalid = 1'd1 ;
  assign WILL_FIRE_axi4_side_m_arvalid = 1'd1 ;

  // value method axi4_side_m_arready
  assign AXI4_ARREADY = t_axi_xactor_f_rd_addr_FULL_N ;

  // value method axi4_side_m_rvalid
  assign AXI4_RVALID = t_axi_xactor_f_rd_data_EMPTY_N ;

  // value method axi4_side_m_rresp
  assign AXI4_RRESP = t_axi_xactor_f_rd_data_D_OUT[75:74] ;

  // value method axi4_side_m_rdata
  assign AXI4_RDATA = t_axi_xactor_f_rd_data_D_OUT[73:10] ;

  // value method axi4_side_m_rlast
  assign AXI4_RLAST = t_axi_xactor_f_rd_data_D_OUT[9] ;

  // value method axi4_side_m_rid
  assign AXI4_RID = t_axi_xactor_f_rd_data_D_OUT[8:0] ;

  // action method axi4_side_m_rready
  assign CAN_FIRE_axi4_side_m_rready = 1'd1 ;
  assign WILL_FIRE_axi4_side_m_rready = 1'd1 ;

  // value method axi4l_side_m_awvalid
  assign AXI4L_awvalid = t_axil_xactor_f_wr_addr_EMPTY_N ;

  // value method axi4l_side_m_awaddr
  assign AXI4L_awaddr = t_axil_xactor_f_wr_addr_D_OUT[36:5] ;

  // value method axi4l_side_m_awprot
  assign AXI4L_awprot = t_axil_xactor_f_wr_addr_D_OUT[4:2] ;

  // value method axi4l_side_m_awsize
  assign AXI4L_awsize = t_axil_xactor_f_wr_addr_D_OUT[1:0] ;

  // action method axi4l_side_m_awready
  assign CAN_FIRE_axi4l_side_m_awready = 1'd1 ;
  assign WILL_FIRE_axi4l_side_m_awready = 1'd1 ;

  // value method axi4l_side_m_wvalid
  assign AXI4L_wvalid = t_axil_xactor_f_wr_data_EMPTY_N ;

  // value method axi4l_side_m_wdata
  assign AXI4L_wdata = t_axil_xactor_f_wr_data_D_OUT[71:8] ;

  // value method axi4l_side_m_wstrb
  assign AXI4L_wstrb = t_axil_xactor_f_wr_data_D_OUT[7:0] ;

  // action method axi4l_side_m_wready
  assign CAN_FIRE_axi4l_side_m_wready = 1'd1 ;
  assign WILL_FIRE_axi4l_side_m_wready = 1'd1 ;

  // action method axi4l_side_m_bvalid
  assign CAN_FIRE_axi4l_side_m_bvalid = 1'd1 ;
  assign WILL_FIRE_axi4l_side_m_bvalid = 1'd1 ;

  // value method axi4l_side_m_bready
  assign AXI4L_bready = t_axil_xactor_f_wr_resp_FULL_N ;

  // value method axi4l_side_m_arvalid
  assign AXI4L_arvalid = t_axil_xactor_f_rd_addr_EMPTY_N ;

  // value method axi4l_side_m_araddr
  assign AXI4L_araddr = t_axil_xactor_f_rd_addr_D_OUT[36:5] ;

  // value method axi4l_side_m_arprot
  assign AXI4L_arprot = t_axil_xactor_f_rd_addr_D_OUT[4:2] ;

  // value method axi4l_side_m_arsize
  assign AXI4L_arsize = t_axil_xactor_f_rd_addr_D_OUT[1:0] ;

  // action method axi4l_side_m_arready
  assign CAN_FIRE_axi4l_side_m_arready = 1'd1 ;
  assign WILL_FIRE_axi4l_side_m_arready = 1'd1 ;

  // action method axi4l_side_m_rvalid
  assign CAN_FIRE_axi4l_side_m_rvalid = 1'd1 ;
  assign WILL_FIRE_axi4l_side_m_rvalid = 1'd1 ;

  // value method axi4l_side_m_rready
  assign AXI4L_rready = t_axil_xactor_f_rd_data_FULL_N ;

  // submodule t_axi_xactor_f_rd_addr
  FIFO1 #(.width(32'd57), .guarded(1'd1)) t_axi_xactor_f_rd_addr(.RST(RST_N),
								 .CLK(CLK),
								 .D_IN(t_axi_xactor_f_rd_addr_D_IN),
								 .ENQ(t_axi_xactor_f_rd_addr_ENQ),
								 .DEQ(t_axi_xactor_f_rd_addr_DEQ),
								 .CLR(t_axi_xactor_f_rd_addr_CLR),
								 .D_OUT(t_axi_xactor_f_rd_addr_D_OUT),
								 .FULL_N(t_axi_xactor_f_rd_addr_FULL_N),
								 .EMPTY_N(t_axi_xactor_f_rd_addr_EMPTY_N));

  // submodule t_axi_xactor_f_rd_data
  FIFO1 #(.width(32'd76), .guarded(1'd1)) t_axi_xactor_f_rd_data(.RST(RST_N),
								 .CLK(CLK),
								 .D_IN(t_axi_xactor_f_rd_data_D_IN),
								 .ENQ(t_axi_xactor_f_rd_data_ENQ),
								 .DEQ(t_axi_xactor_f_rd_data_DEQ),
								 .CLR(t_axi_xactor_f_rd_data_CLR),
								 .D_OUT(t_axi_xactor_f_rd_data_D_OUT),
								 .FULL_N(t_axi_xactor_f_rd_data_FULL_N),
								 .EMPTY_N(t_axi_xactor_f_rd_data_EMPTY_N));

  // submodule t_axi_xactor_f_wr_addr
  FIFO1 #(.width(32'd57), .guarded(1'd1)) t_axi_xactor_f_wr_addr(.RST(RST_N),
								 .CLK(CLK),
								 .D_IN(t_axi_xactor_f_wr_addr_D_IN),
								 .ENQ(t_axi_xactor_f_wr_addr_ENQ),
								 .DEQ(t_axi_xactor_f_wr_addr_DEQ),
								 .CLR(t_axi_xactor_f_wr_addr_CLR),
								 .D_OUT(t_axi_xactor_f_wr_addr_D_OUT),
								 .FULL_N(t_axi_xactor_f_wr_addr_FULL_N),
								 .EMPTY_N(t_axi_xactor_f_wr_addr_EMPTY_N));

  // submodule t_axi_xactor_f_wr_data
  FIFO1 #(.width(32'd82), .guarded(1'd1)) t_axi_xactor_f_wr_data(.RST(RST_N),
								 .CLK(CLK),
								 .D_IN(t_axi_xactor_f_wr_data_D_IN),
								 .ENQ(t_axi_xactor_f_wr_data_ENQ),
								 .DEQ(t_axi_xactor_f_wr_data_DEQ),
								 .CLR(t_axi_xactor_f_wr_data_CLR),
								 .D_OUT(t_axi_xactor_f_wr_data_D_OUT),
								 .FULL_N(t_axi_xactor_f_wr_data_FULL_N),
								 .EMPTY_N(t_axi_xactor_f_wr_data_EMPTY_N));

  // submodule t_axi_xactor_f_wr_resp
  FIFO1 #(.width(32'd11), .guarded(1'd1)) t_axi_xactor_f_wr_resp(.RST(RST_N),
								 .CLK(CLK),
								 .D_IN(t_axi_xactor_f_wr_resp_D_IN),
								 .ENQ(t_axi_xactor_f_wr_resp_ENQ),
								 .DEQ(t_axi_xactor_f_wr_resp_DEQ),
								 .CLR(t_axi_xactor_f_wr_resp_CLR),
								 .D_OUT(t_axi_xactor_f_wr_resp_D_OUT),
								 .FULL_N(t_axi_xactor_f_wr_resp_FULL_N),
								 .EMPTY_N(t_axi_xactor_f_wr_resp_EMPTY_N));

  // submodule t_axil_xactor_f_rd_addr
  FIFO1 #(.width(32'd37), .guarded(1'd1)) t_axil_xactor_f_rd_addr(.RST(RST_N),
								  .CLK(CLK),
								  .D_IN(t_axil_xactor_f_rd_addr_D_IN),
								  .ENQ(t_axil_xactor_f_rd_addr_ENQ),
								  .DEQ(t_axil_xactor_f_rd_addr_DEQ),
								  .CLR(t_axil_xactor_f_rd_addr_CLR),
								  .D_OUT(t_axil_xactor_f_rd_addr_D_OUT),
								  .FULL_N(t_axil_xactor_f_rd_addr_FULL_N),
								  .EMPTY_N(t_axil_xactor_f_rd_addr_EMPTY_N));

  // submodule t_axil_xactor_f_rd_data
  FIFO1 #(.width(32'd66), .guarded(1'd1)) t_axil_xactor_f_rd_data(.RST(RST_N),
								  .CLK(CLK),
								  .D_IN(t_axil_xactor_f_rd_data_D_IN),
								  .ENQ(t_axil_xactor_f_rd_data_ENQ),
								  .DEQ(t_axil_xactor_f_rd_data_DEQ),
								  .CLR(t_axil_xactor_f_rd_data_CLR),
								  .D_OUT(t_axil_xactor_f_rd_data_D_OUT),
								  .FULL_N(t_axil_xactor_f_rd_data_FULL_N),
								  .EMPTY_N(t_axil_xactor_f_rd_data_EMPTY_N));

  // submodule t_axil_xactor_f_wr_addr
  FIFO1 #(.width(32'd37), .guarded(1'd1)) t_axil_xactor_f_wr_addr(.RST(RST_N),
								  .CLK(CLK),
								  .D_IN(t_axil_xactor_f_wr_addr_D_IN),
								  .ENQ(t_axil_xactor_f_wr_addr_ENQ),
								  .DEQ(t_axil_xactor_f_wr_addr_DEQ),
								  .CLR(t_axil_xactor_f_wr_addr_CLR),
								  .D_OUT(t_axil_xactor_f_wr_addr_D_OUT),
								  .FULL_N(t_axil_xactor_f_wr_addr_FULL_N),
								  .EMPTY_N(t_axil_xactor_f_wr_addr_EMPTY_N));

  // submodule t_axil_xactor_f_wr_data
  FIFO1 #(.width(32'd72), .guarded(1'd1)) t_axil_xactor_f_wr_data(.RST(RST_N),
								  .CLK(CLK),
								  .D_IN(t_axil_xactor_f_wr_data_D_IN),
								  .ENQ(t_axil_xactor_f_wr_data_ENQ),
								  .DEQ(t_axil_xactor_f_wr_data_DEQ),
								  .CLR(t_axil_xactor_f_wr_data_CLR),
								  .D_OUT(t_axil_xactor_f_wr_data_D_OUT),
								  .FULL_N(t_axil_xactor_f_wr_data_FULL_N),
								  .EMPTY_N(t_axil_xactor_f_wr_data_EMPTY_N));

  // submodule t_axil_xactor_f_wr_resp
  FIFO1 #(.width(32'd2), .guarded(1'd1)) t_axil_xactor_f_wr_resp(.RST(RST_N),
								 .CLK(CLK),
								 .D_IN(t_axil_xactor_f_wr_resp_D_IN),
								 .ENQ(t_axil_xactor_f_wr_resp_ENQ),
								 .DEQ(t_axil_xactor_f_wr_resp_DEQ),
								 .CLR(t_axil_xactor_f_wr_resp_CLR),
								 .D_OUT(t_axil_xactor_f_wr_resp_D_OUT),
								 .FULL_N(t_axil_xactor_f_wr_resp_FULL_N),
								 .EMPTY_N(t_axil_xactor_f_wr_resp_EMPTY_N));

  // rule RL_t_rl_read_frm_axi
  assign CAN_FIRE_RL_t_rl_read_frm_axi =
	     t_axi_xactor_f_rd_addr_EMPTY_N &&
	     t_axil_xactor_f_rd_addr_FULL_N &&
	     !t_rg_rd_state ;
  assign WILL_FIRE_RL_t_rl_read_frm_axi = CAN_FIRE_RL_t_rl_read_frm_axi ;

  // rule RL_t_rl_read_response_to_axi
  assign CAN_FIRE_RL_t_rl_read_response_to_axi =
	     t_axil_xactor_f_rd_data_EMPTY_N &&
	     t_axi_xactor_f_rd_data_FULL_N &&
	     t_rg_rd_state &&
	     t_rg_rd_resp_beat != 8'd0 ;
  assign WILL_FIRE_RL_t_rl_read_response_to_axi =
	     CAN_FIRE_RL_t_rl_read_response_to_axi ;

  // rule RL_t_rl_send_rd_burst_req
  assign CAN_FIRE_RL_t_rl_send_rd_burst_req =
	     t_axil_xactor_f_rd_addr_FULL_N && t_rg_rd_state &&
	     t_rg_rd_req_beat != 8'd0 ;
  assign WILL_FIRE_RL_t_rl_send_rd_burst_req =
	     CAN_FIRE_RL_t_rl_send_rd_burst_req ;

  // rule RL_t_rl_write_frm_axi
  assign CAN_FIRE_RL_t_rl_write_frm_axi =
	     t_axi_xactor_f_wr_addr_EMPTY_N &&
	     t_axil_xactor_f_wr_addr_FULL_N &&
	     t_axil_xactor_f_wr_data_FULL_N &&
	     t_axi_xactor_f_wr_data_EMPTY_N &&
	     !t_rg_wr_state ;
  assign WILL_FIRE_RL_t_rl_write_frm_axi = CAN_FIRE_RL_t_rl_write_frm_axi ;

  // rule RL_t_rl_write_response_to_axi
  assign CAN_FIRE_RL_t_rl_write_response_to_axi =
	     t_axil_xactor_f_wr_resp_EMPTY_N &&
	     t_axi_xactor_f_wr_resp_FULL_N &&
	     t_rg_wr_state &&
	     t_rg_wr_resp_beat != 8'd0 ;
  assign WILL_FIRE_RL_t_rl_write_response_to_axi =
	     CAN_FIRE_RL_t_rl_write_response_to_axi ;

  // rule RL_t_rl_send_wr_burst_req
  assign CAN_FIRE_RL_t_rl_send_wr_burst_req =
	     t_axil_xactor_f_wr_addr_FULL_N &&
	     t_axil_xactor_f_wr_data_FULL_N &&
	     t_axi_xactor_f_wr_data_EMPTY_N &&
	     t_rg_wr_state &&
	     t_rg_wr_req_beat != 8'd0 ;
  assign WILL_FIRE_RL_t_rl_send_wr_burst_req =
	     CAN_FIRE_RL_t_rl_send_wr_burst_req ;

  // inputs to muxes for submodule ports
  assign MUX_t_rg_rd_state_write_1__SEL_1 =
	     WILL_FIRE_RL_t_rl_read_response_to_axi &&
	     t_rg_rd_resp_beat == 8'd1 &&
	     (t_rg_child_rd_res_count == t_rg_child_rd_burst ||
	      t_rg_child_rd_burst == 8'd0) ;
  assign MUX_t_rg_wr_state_write_1__SEL_1 =
	     WILL_FIRE_RL_t_rl_write_response_to_axi &&
	     t_rg_wr_resp_beat == 8'd1 &&
	     (t_rg_child_wr_res_count == t_rg_child_wr_burst ||
	      t_rg_child_wr_burst == 8'd0) ;
  assign MUX_t_axil_xactor_f_rd_addr_enq_1__VAL_1 =
	     { t_axi_xactor_f_rd_addr_D_OUT[56:22],
	       axil_request_arsize__h1827 } ;
  assign MUX_t_axil_xactor_f_rd_addr_enq_1__VAL_2 =
	     { axil_request_araddr__h2652,
	       t_rg_rd_request[24:22],
	       axil_request_arsize__h2655 } ;
  assign MUX_t_axil_xactor_f_wr_addr_enq_1__VAL_1 =
	     { t_axi_xactor_f_wr_addr_D_OUT[56:22], axil_req_awsize__h4060 } ;
  assign MUX_t_axil_xactor_f_wr_addr_enq_1__VAL_2 =
	     { axil_req_awaddr__h5224,
	       t_rg_wr_request[24:22],
	       axil_req_awsize__h5227 } ;
  assign MUX_t_axil_xactor_f_wr_data_enq_1__VAL_1 =
	     { axil_data___h4029, axil_wstrb__h4028 } ;
  always@(t_rg_accum_err or
	  t_axil_xactor_f_wr_resp_D_OUT or
	  IF_t_axil_xactor_f_wr_resp_first__72_EQ_2_74_T_ETC___d275)
  begin
    case (t_rg_accum_err)
      2'd0, 2'd1:
	  MUX_t_rg_accum_err_write_1__VAL_1 = t_axil_xactor_f_wr_resp_D_OUT;
      2'd2: MUX_t_rg_accum_err_write_1__VAL_1 = t_rg_accum_err;
      2'd3:
	  MUX_t_rg_accum_err_write_1__VAL_1 =
	      IF_t_axil_xactor_f_wr_resp_first__72_EQ_2_74_T_ETC___d275;
    endcase
  end
  assign MUX_t_rg_rd_req_beat_write_1__VAL_1 = t_rg_rd_req_beat - 8'd1 ;
  assign MUX_t_rg_rd_request_write_1__VAL_2 =
	     { axil_request_araddr__h2652, t_rg_rd_request[24:0] } ;
  assign MUX_t_rg_rd_resp_beat_write_1__VAL_1 =
	     t_axi_xactor_f_rd_addr_D_OUT[18:11] + 8'd1 ;
  assign MUX_t_rg_rd_resp_beat_write_1__VAL_2 = t_rg_rd_resp_beat - 8'd1 ;
  assign MUX_t_rg_wr_req_beat_write_1__VAL_1 = t_rg_wr_req_beat - 8'd1 ;
  assign MUX_t_rg_wr_request_write_1__VAL_2 =
	     { axil_req_awaddr__h5224, t_rg_wr_request[24:0] } ;
  assign MUX_t_rg_wr_resp_beat_write_1__VAL_1 =
	     t_axi_xactor_f_wr_addr_D_OUT[21:14] + 8'd1 ;
  assign MUX_t_rg_wr_resp_beat_write_1__VAL_2 = t_rg_wr_resp_beat - 8'd1 ;

  // register t_rg_accum_data
  assign t_rg_accum_data_D_IN = 64'h0 ;
  assign t_rg_accum_data_EN = 1'b0 ;

  // register t_rg_accum_err
  assign t_rg_accum_err_D_IN =
	     WILL_FIRE_RL_t_rl_write_response_to_axi ?
	       MUX_t_rg_accum_err_write_1__VAL_1 :
	       2'd0 ;
  assign t_rg_accum_err_EN =
	     WILL_FIRE_RL_t_rl_write_response_to_axi ||
	     WILL_FIRE_RL_t_rl_write_frm_axi ;

  // register t_rg_accum_mask
  assign t_rg_accum_mask_D_IN = 8'd255 ;
  assign t_rg_accum_mask_EN = CAN_FIRE_RL_t_rl_read_frm_axi ;

  // register t_rg_child_rd_burst
  assign t_rg_child_rd_burst_D_IN = 8'h0 ;
  assign t_rg_child_rd_burst_EN = 1'b0 ;

  // register t_rg_child_rd_req_count
  assign t_rg_child_rd_req_count_D_IN = 8'h0 ;
  assign t_rg_child_rd_req_count_EN = 1'b0 ;

  // register t_rg_child_rd_res_count
  assign t_rg_child_rd_res_count_D_IN = 8'h0 ;
  assign t_rg_child_rd_res_count_EN = 1'b0 ;

  // register t_rg_child_wr_burst
  assign t_rg_child_wr_burst_D_IN = 8'h0 ;
  assign t_rg_child_wr_burst_EN = 1'b0 ;

  // register t_rg_child_wr_req_count
  assign t_rg_child_wr_req_count_D_IN = 8'h0 ;
  assign t_rg_child_wr_req_count_EN = 1'b0 ;

  // register t_rg_child_wr_res_count
  assign t_rg_child_wr_res_count_D_IN = 8'h0 ;
  assign t_rg_child_wr_res_count_EN = 1'b0 ;

  // register t_rg_rd_req_beat
  assign t_rg_rd_req_beat_D_IN =
	     WILL_FIRE_RL_t_rl_send_rd_burst_req ?
	       MUX_t_rg_rd_req_beat_write_1__VAL_1 :
	       t_axi_xactor_f_rd_addr_D_OUT[18:11] ;
  assign t_rg_rd_req_beat_EN =
	     WILL_FIRE_RL_t_rl_send_rd_burst_req ||
	     WILL_FIRE_RL_t_rl_read_frm_axi ;

  // register t_rg_rd_request
  assign t_rg_rd_request_D_IN =
	     WILL_FIRE_RL_t_rl_read_frm_axi ?
	       t_axi_xactor_f_rd_addr_D_OUT :
	       MUX_t_rg_rd_request_write_1__VAL_2 ;
  assign t_rg_rd_request_EN =
	     WILL_FIRE_RL_t_rl_read_frm_axi ||
	     WILL_FIRE_RL_t_rl_send_rd_burst_req ;

  // register t_rg_rd_resp_beat
  assign t_rg_rd_resp_beat_D_IN =
	     WILL_FIRE_RL_t_rl_read_frm_axi ?
	       MUX_t_rg_rd_resp_beat_write_1__VAL_1 :
	       MUX_t_rg_rd_resp_beat_write_1__VAL_2 ;
  assign t_rg_rd_resp_beat_EN =
	     WILL_FIRE_RL_t_rl_read_frm_axi ||
	     WILL_FIRE_RL_t_rl_read_response_to_axi ;

  // register t_rg_rd_state
  assign t_rg_rd_state_D_IN = !MUX_t_rg_rd_state_write_1__SEL_1 ;
  assign t_rg_rd_state_EN =
	     MUX_t_rg_rd_state_write_1__SEL_1 ||
	     WILL_FIRE_RL_t_rl_read_frm_axi ;

  // register t_rg_wd_request
  assign t_rg_wd_request_D_IN = t_axi_xactor_f_wr_data_D_OUT ;
  assign t_rg_wd_request_EN = CAN_FIRE_RL_t_rl_write_frm_axi ;

  // register t_rg_wr_req_beat
  assign t_rg_wr_req_beat_D_IN =
	     WILL_FIRE_RL_t_rl_send_wr_burst_req ?
	       MUX_t_rg_wr_req_beat_write_1__VAL_1 :
	       t_axi_xactor_f_wr_addr_D_OUT[21:14] ;
  assign t_rg_wr_req_beat_EN =
	     WILL_FIRE_RL_t_rl_send_wr_burst_req ||
	     WILL_FIRE_RL_t_rl_write_frm_axi ;

  // register t_rg_wr_request
  assign t_rg_wr_request_D_IN =
	     WILL_FIRE_RL_t_rl_write_frm_axi ?
	       t_axi_xactor_f_wr_addr_D_OUT :
	       MUX_t_rg_wr_request_write_1__VAL_2 ;
  assign t_rg_wr_request_EN =
	     WILL_FIRE_RL_t_rl_write_frm_axi ||
	     WILL_FIRE_RL_t_rl_send_wr_burst_req ;

  // register t_rg_wr_resp_beat
  assign t_rg_wr_resp_beat_D_IN =
	     WILL_FIRE_RL_t_rl_write_frm_axi ?
	       MUX_t_rg_wr_resp_beat_write_1__VAL_1 :
	       MUX_t_rg_wr_resp_beat_write_1__VAL_2 ;
  assign t_rg_wr_resp_beat_EN =
	     WILL_FIRE_RL_t_rl_write_frm_axi ||
	     WILL_FIRE_RL_t_rl_write_response_to_axi ;

  // register t_rg_wr_state
  assign t_rg_wr_state_D_IN = !MUX_t_rg_wr_state_write_1__SEL_1 ;
  assign t_rg_wr_state_EN =
	     MUX_t_rg_wr_state_write_1__SEL_1 ||
	     WILL_FIRE_RL_t_rl_write_frm_axi ;

  // submodule t_axi_xactor_f_rd_addr
  assign t_axi_xactor_f_rd_addr_D_IN =
	     { AXI4_ARADDR,
	       AXI4_ARPROT,
	       AXI4_ARSIZE,
	       AXI4_ARLEN,
	       AXI4_ARBURST,
	       AXI4_ARID } ;
  assign t_axi_xactor_f_rd_addr_ENQ =
	     AXI4_ARVALID && t_axi_xactor_f_rd_addr_FULL_N ;
  assign t_axi_xactor_f_rd_addr_DEQ = CAN_FIRE_RL_t_rl_read_frm_axi ;
  assign t_axi_xactor_f_rd_addr_CLR = 1'b0 ;

  // submodule t_axi_xactor_f_rd_data
  assign t_axi_xactor_f_rd_data_D_IN =
	     { t_axil_xactor_f_rd_data_D_OUT,
	       t_rg_rd_resp_beat == 8'd1,
	       t_rg_rd_request[8:0] } ;
  assign t_axi_xactor_f_rd_data_ENQ = CAN_FIRE_RL_t_rl_read_response_to_axi ;
  assign t_axi_xactor_f_rd_data_DEQ =
	     AXI4_RREADY && t_axi_xactor_f_rd_data_EMPTY_N ;
  assign t_axi_xactor_f_rd_data_CLR = 1'b0 ;

  // submodule t_axi_xactor_f_wr_addr
  assign t_axi_xactor_f_wr_addr_D_IN =
	     { AXI4_AWADDR,
	       AXI4_AWPROT,
	       AXI4_AWLEN,
	       AXI4_AWSIZE,
	       AXI4_AWBURST,
	       AXI4_AWID } ;
  assign t_axi_xactor_f_wr_addr_ENQ =
	     AXI4_AWVALID && t_axi_xactor_f_wr_addr_FULL_N ;
  assign t_axi_xactor_f_wr_addr_DEQ = CAN_FIRE_RL_t_rl_write_frm_axi ;
  assign t_axi_xactor_f_wr_addr_CLR = 1'b0 ;

  // submodule t_axi_xactor_f_wr_data
  assign t_axi_xactor_f_wr_data_D_IN =
	     { AXI4_WDATA, AXI4_WSTRB, AXI4_WID, AXI4_WLAST } ;
  assign t_axi_xactor_f_wr_data_ENQ =
	     AXI4_WVALID && t_axi_xactor_f_wr_data_FULL_N ;
  assign t_axi_xactor_f_wr_data_DEQ =
	     WILL_FIRE_RL_t_rl_send_wr_burst_req ||
	     WILL_FIRE_RL_t_rl_write_frm_axi ;
  assign t_axi_xactor_f_wr_data_CLR = 1'b0 ;

  // submodule t_axi_xactor_f_wr_resp
  assign t_axi_xactor_f_wr_resp_D_IN =
	     { MUX_t_rg_accum_err_write_1__VAL_1, t_rg_wr_request[8:0] } ;
  assign t_axi_xactor_f_wr_resp_ENQ = MUX_t_rg_wr_state_write_1__SEL_1 ;
  assign t_axi_xactor_f_wr_resp_DEQ =
	     AXI4_BREADY && t_axi_xactor_f_wr_resp_EMPTY_N ;
  assign t_axi_xactor_f_wr_resp_CLR = 1'b0 ;

  // submodule t_axil_xactor_f_rd_addr
  assign t_axil_xactor_f_rd_addr_D_IN =
	     WILL_FIRE_RL_t_rl_read_frm_axi ?
	       MUX_t_axil_xactor_f_rd_addr_enq_1__VAL_1 :
	       MUX_t_axil_xactor_f_rd_addr_enq_1__VAL_2 ;
  assign t_axil_xactor_f_rd_addr_ENQ =
	     WILL_FIRE_RL_t_rl_read_frm_axi ||
	     WILL_FIRE_RL_t_rl_send_rd_burst_req ;
  assign t_axil_xactor_f_rd_addr_DEQ =
	     t_axil_xactor_f_rd_addr_EMPTY_N && AXI4L_m_arready_arready ;
  assign t_axil_xactor_f_rd_addr_CLR = 1'b0 ;

  // submodule t_axil_xactor_f_rd_data
  assign t_axil_xactor_f_rd_data_D_IN =
	     { AXI4L_m_rvalid_rresp, AXI4L_m_rvalid_rdata } ;
  assign t_axil_xactor_f_rd_data_ENQ =
	     AXI4L_m_rvalid_rvalid && t_axil_xactor_f_rd_data_FULL_N ;
  assign t_axil_xactor_f_rd_data_DEQ = CAN_FIRE_RL_t_rl_read_response_to_axi ;
  assign t_axil_xactor_f_rd_data_CLR = 1'b0 ;

  // submodule t_axil_xactor_f_wr_addr
  assign t_axil_xactor_f_wr_addr_D_IN =
	     WILL_FIRE_RL_t_rl_write_frm_axi ?
	       MUX_t_axil_xactor_f_wr_addr_enq_1__VAL_1 :
	       MUX_t_axil_xactor_f_wr_addr_enq_1__VAL_2 ;
  assign t_axil_xactor_f_wr_addr_ENQ =
	     WILL_FIRE_RL_t_rl_write_frm_axi ||
	     WILL_FIRE_RL_t_rl_send_wr_burst_req ;
  assign t_axil_xactor_f_wr_addr_DEQ =
	     t_axil_xactor_f_wr_addr_EMPTY_N && AXI4L_m_awready_awready ;
  assign t_axil_xactor_f_wr_addr_CLR = 1'b0 ;

  // submodule t_axil_xactor_f_wr_data
  assign t_axil_xactor_f_wr_data_D_IN =
	     WILL_FIRE_RL_t_rl_write_frm_axi ?
	       MUX_t_axil_xactor_f_wr_data_enq_1__VAL_1 :
	       t_axi_xactor_f_wr_data_D_OUT[81:10] ;
  assign t_axil_xactor_f_wr_data_ENQ =
	     WILL_FIRE_RL_t_rl_write_frm_axi ||
	     WILL_FIRE_RL_t_rl_send_wr_burst_req ;
  assign t_axil_xactor_f_wr_data_DEQ =
	     t_axil_xactor_f_wr_data_EMPTY_N && AXI4L_m_wready_wready ;
  assign t_axil_xactor_f_wr_data_CLR = 1'b0 ;

  // submodule t_axil_xactor_f_wr_resp
  assign t_axil_xactor_f_wr_resp_D_IN = AXI4L_m_bvalid_bresp ;
  assign t_axil_xactor_f_wr_resp_ENQ =
	     AXI4L_m_bvalid_bvalid && t_axil_xactor_f_wr_resp_FULL_N ;
  assign t_axil_xactor_f_wr_resp_DEQ =
	     CAN_FIRE_RL_t_rl_write_response_to_axi ;
  assign t_axil_xactor_f_wr_resp_CLR = 1'b0 ;

  // remaining internal signals
  assign IF_t_axil_xactor_f_wr_resp_first__72_EQ_2_74_T_ETC___d275 =
	     (t_axil_xactor_f_wr_resp_D_OUT == 2'd2) ?
	       t_axil_xactor_f_wr_resp_D_OUT :
	       2'd3 ;
  assign axil_data___h4029 = t_axi_xactor_f_wr_data_D_OUT[81:18] >> x__h4138 ;
  assign axil_req_awsize__h4060 =
	     (t_axi_xactor_f_wr_addr_D_OUT[13:11] <= 3'd3) ?
	       t_axi_xactor_f_wr_addr_D_OUT[12:11] :
	       2'd3 ;
  assign axil_req_awsize__h5227 =
	     (t_rg_wr_request[13:11] <= 3'd3) ?
	       t_rg_wr_request[12:11] :
	       2'd3 ;
  assign axil_request_arsize__h1827 =
	     (t_axi_xactor_f_rd_addr_D_OUT[21:19] <= 3'd3) ?
	       t_axi_xactor_f_rd_addr_D_OUT[20:19] :
	       2'd3 ;
  assign axil_request_arsize__h2655 =
	     (t_rg_rd_request[21:19] <= 3'd3) ?
	       t_rg_rd_request[20:19] :
	       2'd3 ;
  assign axil_wstrb__h4028 =
	     t_axi_xactor_f_wr_data_D_OUT[17:10] >>
	     t_axi_xactor_f_wr_addr_D_OUT[27:25] ;
  assign mask__h2418 = 32'hFFFFFFFF << x__h2483 ;
  assign mask__h4791 = 32'hFFFFFFFF << x__h4856 ;
  assign new_address__h2416 =
	     t_rg_rd_request[56:25] +
	     (32'b00000000000000000000000000000001 <<
	      t_rg_rd_request[21:19]) ;
  assign new_address__h4789 =
	     t_rg_wr_request[56:25] +
	     (32'b00000000000000000000000000000001 <<
	      t_rg_wr_request[13:11]) ;
  assign temp1__h2419 = t_rg_rd_request[56:25] & mask__h2418 ;
  assign temp1__h4792 = t_rg_wr_request[56:25] & mask__h4791 ;
  assign temp2__h2420 = new_address__h2416 & y__h2539 ;
  assign temp2__h4793 = new_address__h4789 & y__h4912 ;
  assign x__h2483 =
	     t_rg_rd_request[21:19] +
	     CASE_t_rg_rd_request_BITS_18_TO_11_3_2_7_3_15_4_1__q1 ;
  assign x__h4138 = { t_axi_xactor_f_wr_addr_D_OUT[27:25], 3'b0 } ;
  assign x__h4856 =
	     t_rg_wr_request[13:11] +
	     CASE_t_rg_wr_request_BITS_21_TO_14_3_2_7_3_15_4_1__q2 ;
  assign y__h2539 = ~mask__h2418 ;
  assign y__h4912 = ~mask__h4791 ;
  always@(t_rg_rd_request)
  begin
    case (t_rg_rd_request[18:11])
      8'd3: CASE_t_rg_rd_request_BITS_18_TO_11_3_2_7_3_15_4_1__q1 = 3'd2;
      8'd7: CASE_t_rg_rd_request_BITS_18_TO_11_3_2_7_3_15_4_1__q1 = 3'd3;
      8'd15: CASE_t_rg_rd_request_BITS_18_TO_11_3_2_7_3_15_4_1__q1 = 3'd4;
      default: CASE_t_rg_rd_request_BITS_18_TO_11_3_2_7_3_15_4_1__q1 = 3'd1;
    endcase
  end
  always@(t_rg_wr_request)
  begin
    case (t_rg_wr_request[21:14])
      8'd3: CASE_t_rg_wr_request_BITS_21_TO_14_3_2_7_3_15_4_1__q2 = 3'd2;
      8'd7: CASE_t_rg_wr_request_BITS_21_TO_14_3_2_7_3_15_4_1__q2 = 3'd3;
      8'd15: CASE_t_rg_wr_request_BITS_21_TO_14_3_2_7_3_15_4_1__q2 = 3'd4;
      default: CASE_t_rg_wr_request_BITS_21_TO_14_3_2_7_3_15_4_1__q2 = 3'd1;
    endcase
  end
  always@(t_rg_rd_request or
	  temp1__h2419 or temp2__h2420 or new_address__h2416)
  begin
    case (t_rg_rd_request[10:9])
      2'd0: axil_request_araddr__h2652 = t_rg_rd_request[56:25];
      2'd1: axil_request_araddr__h2652 = new_address__h2416;
      default: axil_request_araddr__h2652 = temp1__h2419 | temp2__h2420;
    endcase
  end
  always@(t_rg_wr_request or
	  temp1__h4792 or temp2__h4793 or new_address__h4789)
  begin
    case (t_rg_wr_request[10:9])
      2'd0: axil_req_awaddr__h5224 = t_rg_wr_request[56:25];
      2'd1: axil_req_awaddr__h5224 = new_address__h4789;
      default: axil_req_awaddr__h5224 = temp1__h4792 | temp2__h4793;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        t_rg_rd_state <= `BSV_ASSIGNMENT_DELAY 1'd0;
	t_rg_wr_state <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (t_rg_rd_state_EN)
	  t_rg_rd_state <= `BSV_ASSIGNMENT_DELAY t_rg_rd_state_D_IN;
	if (t_rg_wr_state_EN)
	  t_rg_wr_state <= `BSV_ASSIGNMENT_DELAY t_rg_wr_state_D_IN;
      end
  end

  always@(posedge CLK or `BSV_RESET_EDGE RST_N)
  if (RST_N == `BSV_RESET_VALUE)
    begin
      t_rg_accum_data <= `BSV_ASSIGNMENT_DELAY 64'd0;
      t_rg_accum_err <= `BSV_ASSIGNMENT_DELAY 2'd0;
      t_rg_accum_mask <= `BSV_ASSIGNMENT_DELAY 8'd0;
      t_rg_child_rd_burst <= `BSV_ASSIGNMENT_DELAY 8'd0;
      t_rg_child_rd_req_count <= `BSV_ASSIGNMENT_DELAY 8'd0;
      t_rg_child_rd_res_count <= `BSV_ASSIGNMENT_DELAY 8'd0;
      t_rg_child_wr_burst <= `BSV_ASSIGNMENT_DELAY 8'd0;
      t_rg_child_wr_req_count <= `BSV_ASSIGNMENT_DELAY 8'd0;
      t_rg_child_wr_res_count <= `BSV_ASSIGNMENT_DELAY 8'd0;
      t_rg_rd_req_beat <= `BSV_ASSIGNMENT_DELAY 8'd0;
      t_rg_rd_request <= `BSV_ASSIGNMENT_DELAY 57'd0;
      t_rg_rd_resp_beat <= `BSV_ASSIGNMENT_DELAY 8'd0;
      t_rg_wd_request <= `BSV_ASSIGNMENT_DELAY 82'd0;
      t_rg_wr_req_beat <= `BSV_ASSIGNMENT_DELAY 8'd0;
      t_rg_wr_request <= `BSV_ASSIGNMENT_DELAY 57'd0;
      t_rg_wr_resp_beat <= `BSV_ASSIGNMENT_DELAY 8'd0;
    end
  else
    begin
      if (t_rg_accum_data_EN)
	t_rg_accum_data <= `BSV_ASSIGNMENT_DELAY t_rg_accum_data_D_IN;
      if (t_rg_accum_err_EN)
	t_rg_accum_err <= `BSV_ASSIGNMENT_DELAY t_rg_accum_err_D_IN;
      if (t_rg_accum_mask_EN)
	t_rg_accum_mask <= `BSV_ASSIGNMENT_DELAY t_rg_accum_mask_D_IN;
      if (t_rg_child_rd_burst_EN)
	t_rg_child_rd_burst <= `BSV_ASSIGNMENT_DELAY t_rg_child_rd_burst_D_IN;
      if (t_rg_child_rd_req_count_EN)
	t_rg_child_rd_req_count <= `BSV_ASSIGNMENT_DELAY
	    t_rg_child_rd_req_count_D_IN;
      if (t_rg_child_rd_res_count_EN)
	t_rg_child_rd_res_count <= `BSV_ASSIGNMENT_DELAY
	    t_rg_child_rd_res_count_D_IN;
      if (t_rg_child_wr_burst_EN)
	t_rg_child_wr_burst <= `BSV_ASSIGNMENT_DELAY t_rg_child_wr_burst_D_IN;
      if (t_rg_child_wr_req_count_EN)
	t_rg_child_wr_req_count <= `BSV_ASSIGNMENT_DELAY
	    t_rg_child_wr_req_count_D_IN;
      if (t_rg_child_wr_res_count_EN)
	t_rg_child_wr_res_count <= `BSV_ASSIGNMENT_DELAY
	    t_rg_child_wr_res_count_D_IN;
      if (t_rg_rd_req_beat_EN)
	t_rg_rd_req_beat <= `BSV_ASSIGNMENT_DELAY t_rg_rd_req_beat_D_IN;
      if (t_rg_rd_request_EN)
	t_rg_rd_request <= `BSV_ASSIGNMENT_DELAY t_rg_rd_request_D_IN;
      if (t_rg_rd_resp_beat_EN)
	t_rg_rd_resp_beat <= `BSV_ASSIGNMENT_DELAY t_rg_rd_resp_beat_D_IN;
      if (t_rg_wd_request_EN)
	t_rg_wd_request <= `BSV_ASSIGNMENT_DELAY t_rg_wd_request_D_IN;
      if (t_rg_wr_req_beat_EN)
	t_rg_wr_req_beat <= `BSV_ASSIGNMENT_DELAY t_rg_wr_req_beat_D_IN;
      if (t_rg_wr_request_EN)
	t_rg_wr_request <= `BSV_ASSIGNMENT_DELAY t_rg_wr_request_D_IN;
      if (t_rg_wr_resp_beat_EN)
	t_rg_wr_resp_beat <= `BSV_ASSIGNMENT_DELAY t_rg_wr_resp_beat_D_IN;
    end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    t_rg_accum_data = 64'hAAAAAAAAAAAAAAAA;
    t_rg_accum_err = 2'h2;
    t_rg_accum_mask = 8'hAA;
    t_rg_child_rd_burst = 8'hAA;
    t_rg_child_rd_req_count = 8'hAA;
    t_rg_child_rd_res_count = 8'hAA;
    t_rg_child_wr_burst = 8'hAA;
    t_rg_child_wr_req_count = 8'hAA;
    t_rg_child_wr_res_count = 8'hAA;
    t_rg_rd_req_beat = 8'hAA;
    t_rg_rd_request = 57'h0AAAAAAAAAAAAAA;
    t_rg_rd_resp_beat = 8'hAA;
    t_rg_rd_state = 1'h0;
    t_rg_wd_request = 82'h2AAAAAAAAAAAAAAAAAAAA;
    t_rg_wr_req_beat = 8'hAA;
    t_rg_wr_request = 57'h0AAAAAAAAAAAAAA;
    t_rg_wr_resp_beat = 8'hAA;
    t_rg_wr_state = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi)
	begin
	  TASK_testplusargs___d14 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi)
	begin
	  TASK_testplusargs___d15 = $test$plusargs("mbridge");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi)
	begin
	  TASK_testplusargs___d16 = $test$plusargs("l0");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi)
	begin
	  v__h2005 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write("[%10d", v__h2005, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write("Axi2AxiL: Axi4-Read:");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write("AXI4_Rd_Addr { ", "araddr: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write("'h%h", t_axi_xactor_f_rd_addr_D_OUT[56:25]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write(", ", "aruser: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write("'h%h", 1'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write(", ", "arprot: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write("'h%h", t_axi_xactor_f_rd_addr_D_OUT[24:22]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write(", ", "arsize: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write("'h%h", t_axi_xactor_f_rd_addr_D_OUT[21:19]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write(", ", "arlen: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write("'h%h", t_axi_xactor_f_rd_addr_D_OUT[18:11]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write(", ", "arburst: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write("'h%h", t_axi_xactor_f_rd_addr_D_OUT[10:9]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write(", ", "arid: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write("'h%h", t_axi_xactor_f_rd_addr_D_OUT[8:0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi)
	begin
	  TASK_testplusargs___d25 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi)
	begin
	  TASK_testplusargs___d26 = $test$plusargs("mbridge");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi)
	begin
	  TASK_testplusargs___d27 = $test$plusargs("l0");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi)
	begin
	  v__h2166 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d25 ||
	   TASK_testplusargs___d26 && TASK_testplusargs___d27))
	$write("[%10d", v__h2166, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d25 ||
	   TASK_testplusargs___d26 && TASK_testplusargs___d27))
	$write("Axi2AxiL: Axi4-Lite-Read  :");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d25 ||
	   TASK_testplusargs___d26 && TASK_testplusargs___d27))
	$write("AXI4_Lite_Rd_Addr { ", "araddr: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d25 ||
	   TASK_testplusargs___d26 && TASK_testplusargs___d27))
	$write("'h%h", t_axi_xactor_f_rd_addr_D_OUT[56:25]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d25 ||
	   TASK_testplusargs___d26 && TASK_testplusargs___d27))
	$write(", ", "aruser: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d25 ||
	   TASK_testplusargs___d26 && TASK_testplusargs___d27))
	$write("'h%h", 1'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d25 ||
	   TASK_testplusargs___d26 && TASK_testplusargs___d27))
	$write(", ", "arprot: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d25 ||
	   TASK_testplusargs___d26 && TASK_testplusargs___d27))
	$write("'h%h", t_axi_xactor_f_rd_addr_D_OUT[24:22]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d25 ||
	   TASK_testplusargs___d26 && TASK_testplusargs___d27))
	$write(", ", "arsize: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d25 ||
	   TASK_testplusargs___d26 && TASK_testplusargs___d27))
	$write("'h%h", axil_request_arsize__h1827, " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_frm_axi &&
	  (TASK_testplusargs___d25 ||
	   TASK_testplusargs___d26 && TASK_testplusargs___d27))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi)
	begin
	  TASK_testplusargs___d101 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi)
	begin
	  TASK_testplusargs___d102 = $test$plusargs("mbridge");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi)
	begin
	  TASK_testplusargs___d103 = $test$plusargs("l0");
	  #0;
	end
    TASK_testplusargs_01_OR_TASK_testplusargs_02_A_ETC___d109 =
	(TASK_testplusargs___d101 ||
	 TASK_testplusargs___d102 && TASK_testplusargs___d103) &&
	t_axil_xactor_f_rd_data_D_OUT[65:64] == 2'd0;
    TASK_testplusargs_01_OR_TASK_testplusargs_02_A_ETC___d111 =
	(TASK_testplusargs___d101 ||
	 TASK_testplusargs___d102 && TASK_testplusargs___d103) &&
	t_axil_xactor_f_rd_data_D_OUT[65:64] == 2'd1;
    TASK_testplusargs_01_OR_TASK_testplusargs_02_A_ETC___d113 =
	(TASK_testplusargs___d101 ||
	 TASK_testplusargs___d102 && TASK_testplusargs___d103) &&
	t_axil_xactor_f_rd_data_D_OUT[65:64] == 2'd2;
    TASK_testplusargs_01_OR_TASK_testplusargs_02_A_ETC___d119 =
	(TASK_testplusargs___d101 ||
	 TASK_testplusargs___d102 && TASK_testplusargs___d103) &&
	t_axil_xactor_f_rd_data_D_OUT[65:64] != 2'd0 &&
	t_axil_xactor_f_rd_data_D_OUT[65:64] != 2'd1 &&
	t_axil_xactor_f_rd_data_D_OUT[65:64] != 2'd2;
    TASK_testplusargs_01_OR_TASK_testplusargs_02_A_ETC___d121 =
	(TASK_testplusargs___d101 ||
	 TASK_testplusargs___d102 && TASK_testplusargs___d103) &&
	t_rg_rd_resp_beat == 8'd1;
    TASK_testplusargs_01_OR_TASK_testplusargs_02_A_ETC___d123 =
	(TASK_testplusargs___d101 ||
	 TASK_testplusargs___d102 && TASK_testplusargs___d103) &&
	t_rg_rd_resp_beat != 8'd1;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi)
	begin
	  v__h3485 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d101 ||
	   TASK_testplusargs___d102 && TASK_testplusargs___d103))
	$write("[%10d", v__h3485, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d101 ||
	   TASK_testplusargs___d102 && TASK_testplusargs___d103))
	$write("Axi2AxiL: AXI-RdResp:");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d101 ||
	   TASK_testplusargs___d102 && TASK_testplusargs___d103))
	$write("AXI4_Rd_Data { ", "rresp: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  TASK_testplusargs_01_OR_TASK_testplusargs_02_A_ETC___d109)
	$write("AXI4_OKAY");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  TASK_testplusargs_01_OR_TASK_testplusargs_02_A_ETC___d111)
	$write("AXI4_EXOKAY");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  TASK_testplusargs_01_OR_TASK_testplusargs_02_A_ETC___d113)
	$write("AXI4_SLVERR");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  TASK_testplusargs_01_OR_TASK_testplusargs_02_A_ETC___d119)
	$write("AXI4_DECERR");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d101 ||
	   TASK_testplusargs___d102 && TASK_testplusargs___d103))
	$write(", ", "rdata: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d101 ||
	   TASK_testplusargs___d102 && TASK_testplusargs___d103))
	$write("'h%h", t_axil_xactor_f_rd_data_D_OUT[63:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d101 ||
	   TASK_testplusargs___d102 && TASK_testplusargs___d103))
	$write(", ", "rlast: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  TASK_testplusargs_01_OR_TASK_testplusargs_02_A_ETC___d121)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  TASK_testplusargs_01_OR_TASK_testplusargs_02_A_ETC___d123)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d101 ||
	   TASK_testplusargs___d102 && TASK_testplusargs___d103))
	$write(", ", "ruser: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d101 ||
	   TASK_testplusargs___d102 && TASK_testplusargs___d103))
	$write("'h%h", 1'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d101 ||
	   TASK_testplusargs___d102 && TASK_testplusargs___d103))
	$write(", ", "rid: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d101 ||
	   TASK_testplusargs___d102 && TASK_testplusargs___d103))
	$write("'h%h", t_rg_rd_request[8:0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d101 ||
	   TASK_testplusargs___d102 && TASK_testplusargs___d103))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi)
	begin
	  TASK_testplusargs___d129 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi)
	begin
	  TASK_testplusargs___d130 = $test$plusargs("mbridge");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi)
	begin
	  TASK_testplusargs___d131 = $test$plusargs("l0");
	  #0;
	end
    TASK_testplusargs_29_OR_TASK_testplusargs_30_A_ETC___d135 =
	(TASK_testplusargs___d129 ||
	 TASK_testplusargs___d130 && TASK_testplusargs___d131) &&
	t_axil_xactor_f_rd_data_D_OUT[65:64] == 2'd0;
    TASK_testplusargs_29_OR_TASK_testplusargs_30_A_ETC___d136 =
	(TASK_testplusargs___d129 ||
	 TASK_testplusargs___d130 && TASK_testplusargs___d131) &&
	t_axil_xactor_f_rd_data_D_OUT[65:64] == 2'd1;
    TASK_testplusargs_29_OR_TASK_testplusargs_30_A_ETC___d137 =
	(TASK_testplusargs___d129 ||
	 TASK_testplusargs___d130 && TASK_testplusargs___d131) &&
	t_axil_xactor_f_rd_data_D_OUT[65:64] == 2'd2;
    TASK_testplusargs_29_OR_TASK_testplusargs_30_A_ETC___d138 =
	(TASK_testplusargs___d129 ||
	 TASK_testplusargs___d130 && TASK_testplusargs___d131) &&
	t_axil_xactor_f_rd_data_D_OUT[65:64] != 2'd0 &&
	t_axil_xactor_f_rd_data_D_OUT[65:64] != 2'd1 &&
	t_axil_xactor_f_rd_data_D_OUT[65:64] != 2'd2;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi)
	begin
	  v__h3767 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d129 ||
	   TASK_testplusargs___d130 && TASK_testplusargs___d131))
	$write("[%10d", v__h3767, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d129 ||
	   TASK_testplusargs___d130 && TASK_testplusargs___d131))
	$write("Axi2AxiL: AXI4L-Resp: Count:%2d", t_rg_rd_resp_beat);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d129 ||
	   TASK_testplusargs___d130 && TASK_testplusargs___d131))
	$write("AXI4_Lite_Rd_Data { ", "rresp: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  TASK_testplusargs_29_OR_TASK_testplusargs_30_A_ETC___d135)
	$write("AXI4_LITE_OKAY");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  TASK_testplusargs_29_OR_TASK_testplusargs_30_A_ETC___d136)
	$write("AXI4_LITE_EXOKAY");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  TASK_testplusargs_29_OR_TASK_testplusargs_30_A_ETC___d137)
	$write("AXI4_LITE_SLVERR");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  TASK_testplusargs_29_OR_TASK_testplusargs_30_A_ETC___d138)
	$write("AXI4_LITE_DECERR");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d129 ||
	   TASK_testplusargs___d130 && TASK_testplusargs___d131))
	$write(", ", "rdata: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d129 ||
	   TASK_testplusargs___d130 && TASK_testplusargs___d131))
	$write("'h%h", t_axil_xactor_f_rd_data_D_OUT[63:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d129 ||
	   TASK_testplusargs___d130 && TASK_testplusargs___d131))
	$write(", ", "ruser: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d129 ||
	   TASK_testplusargs___d130 && TASK_testplusargs___d131))
	$write("'h%h", 1'd0, " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d129 ||
	   TASK_testplusargs___d130 && TASK_testplusargs___d131))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi)
	begin
	  TASK_testplusargs___d139 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi)
	begin
	  TASK_testplusargs___d140 = $test$plusargs("mbridge");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi)
	begin
	  TASK_testplusargs___d141 = $test$plusargs("l0");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi)
	begin
	  v__h3922 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d139 ||
	   TASK_testplusargs___d140 && TASK_testplusargs___d141))
	$write("[%10d", v__h3922, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d139 ||
	   TASK_testplusargs___d140 && TASK_testplusargs___d141))
	$write("Axi2AxiL: Child:%d ChildRes:%d Mask:%b Accum:%h",
	       t_rg_child_rd_burst,
	       t_rg_child_rd_res_count,
	       t_rg_accum_mask,
	       t_rg_accum_data);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_read_response_to_axi &&
	  (TASK_testplusargs___d139 ||
	   TASK_testplusargs___d140 && TASK_testplusargs___d141))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req)
	begin
	  TASK_testplusargs___d68 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req)
	begin
	  TASK_testplusargs___d69 = $test$plusargs("mbridge");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req)
	begin
	  TASK_testplusargs___d70 = $test$plusargs("l0");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req)
	begin
	  v__h2738 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req &&
	  (TASK_testplusargs___d68 ||
	   TASK_testplusargs___d69 && TASK_testplusargs___d70))
	$write("[%10d", v__h2738, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req &&
	  (TASK_testplusargs___d68 ||
	   TASK_testplusargs___d69 && TASK_testplusargs___d70))
	$write("Axi2AxiL: Axi4-RdBurst Addr:%h Count:%d",
	       axil_request_araddr__h2652,
	       t_rg_rd_req_beat);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req &&
	  (TASK_testplusargs___d68 ||
	   TASK_testplusargs___d69 && TASK_testplusargs___d70))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req)
	begin
	  TASK_testplusargs___d74 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req)
	begin
	  TASK_testplusargs___d75 = $test$plusargs("mbridge");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req)
	begin
	  TASK_testplusargs___d76 = $test$plusargs("l0");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req)
	begin
	  v__h2882 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req &&
	  (TASK_testplusargs___d74 ||
	   TASK_testplusargs___d75 && TASK_testplusargs___d76))
	$write("[%10d", v__h2882, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req &&
	  (TASK_testplusargs___d74 ||
	   TASK_testplusargs___d75 && TASK_testplusargs___d76))
	$write("Axi2AxiL: New Axi4-Lite-Read  :");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req &&
	  (TASK_testplusargs___d74 ||
	   TASK_testplusargs___d75 && TASK_testplusargs___d76))
	$write("AXI4_Lite_Rd_Addr { ", "araddr: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req &&
	  (TASK_testplusargs___d74 ||
	   TASK_testplusargs___d75 && TASK_testplusargs___d76))
	$write("'h%h", axil_request_araddr__h2652);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req &&
	  (TASK_testplusargs___d74 ||
	   TASK_testplusargs___d75 && TASK_testplusargs___d76))
	$write(", ", "aruser: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req &&
	  (TASK_testplusargs___d74 ||
	   TASK_testplusargs___d75 && TASK_testplusargs___d76))
	$write("'h%h", 1'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req &&
	  (TASK_testplusargs___d74 ||
	   TASK_testplusargs___d75 && TASK_testplusargs___d76))
	$write(", ", "arprot: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req &&
	  (TASK_testplusargs___d74 ||
	   TASK_testplusargs___d75 && TASK_testplusargs___d76))
	$write("'h%h", t_rg_rd_request[24:22]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req &&
	  (TASK_testplusargs___d74 ||
	   TASK_testplusargs___d75 && TASK_testplusargs___d76))
	$write(", ", "arsize: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req &&
	  (TASK_testplusargs___d74 ||
	   TASK_testplusargs___d75 && TASK_testplusargs___d76))
	$write("'h%h", axil_request_arsize__h2655, " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req &&
	  (TASK_testplusargs___d74 ||
	   TASK_testplusargs___d75 && TASK_testplusargs___d76))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req)
	begin
	  TASK_testplusargs___d80 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req)
	begin
	  TASK_testplusargs___d81 = $test$plusargs("mbridge");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req)
	begin
	  TASK_testplusargs___d82 = $test$plusargs("l0");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req)
	begin
	  v__h3019 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req &&
	  (TASK_testplusargs___d80 ||
	   TASK_testplusargs___d81 && TASK_testplusargs___d82))
	$write("[%10d", v__h3019, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req &&
	  (TASK_testplusargs___d80 ||
	   TASK_testplusargs___d81 && TASK_testplusargs___d82))
	$write("Axi2AxiL: Child:%d ChildReq:%d",
	       t_rg_child_rd_burst,
	       t_rg_child_rd_req_count);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_rd_burst_req &&
	  (TASK_testplusargs___d80 ||
	   TASK_testplusargs___d81 && TASK_testplusargs___d82))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi)
	begin
	  TASK_testplusargs___d174 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi)
	begin
	  TASK_testplusargs___d175 = $test$plusargs("mbridge");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi)
	begin
	  TASK_testplusargs___d176 = $test$plusargs("l0");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi)
	begin
	  v__h4529 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d174 ||
	   TASK_testplusargs___d175 && TASK_testplusargs___d176))
	$write("[%10d", v__h4529, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d174 ||
	   TASK_testplusargs___d175 && TASK_testplusargs___d176))
	$write("Axi2AxiL: Axi4-Write:");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d174 ||
	   TASK_testplusargs___d175 && TASK_testplusargs___d176))
	$write("AXI4_Wr_Addr { ", "awaddr: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d174 ||
	   TASK_testplusargs___d175 && TASK_testplusargs___d176))
	$write("'h%h", t_axi_xactor_f_wr_addr_D_OUT[56:25]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d174 ||
	   TASK_testplusargs___d175 && TASK_testplusargs___d176))
	$write(", ", "awuser: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d174 ||
	   TASK_testplusargs___d175 && TASK_testplusargs___d176))
	$write("'h%h", 1'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d174 ||
	   TASK_testplusargs___d175 && TASK_testplusargs___d176))
	$write(", ", "awprot: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d174 ||
	   TASK_testplusargs___d175 && TASK_testplusargs___d176))
	$write("'h%h", t_axi_xactor_f_wr_addr_D_OUT[24:22]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d174 ||
	   TASK_testplusargs___d175 && TASK_testplusargs___d176))
	$write(", ", "awlen: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d174 ||
	   TASK_testplusargs___d175 && TASK_testplusargs___d176))
	$write("'h%h", t_axi_xactor_f_wr_addr_D_OUT[21:14]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d174 ||
	   TASK_testplusargs___d175 && TASK_testplusargs___d176))
	$write(", ", "awsize: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d174 ||
	   TASK_testplusargs___d175 && TASK_testplusargs___d176))
	$write("'h%h", t_axi_xactor_f_wr_addr_D_OUT[13:11]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d174 ||
	   TASK_testplusargs___d175 && TASK_testplusargs___d176))
	$write(", ", "awburst: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d174 ||
	   TASK_testplusargs___d175 && TASK_testplusargs___d176))
	$write("'h%h", t_axi_xactor_f_wr_addr_D_OUT[10:9]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d174 ||
	   TASK_testplusargs___d175 && TASK_testplusargs___d176))
	$write(", ", "awid: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d174 ||
	   TASK_testplusargs___d175 && TASK_testplusargs___d176))
	$write("'h%h", t_axi_xactor_f_wr_addr_D_OUT[8:0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d174 ||
	   TASK_testplusargs___d175 && TASK_testplusargs___d176))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi)
	begin
	  TASK_testplusargs___d184 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi)
	begin
	  TASK_testplusargs___d185 = $test$plusargs("mbridge");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi)
	begin
	  TASK_testplusargs___d186 = $test$plusargs("l0");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi)
	begin
	  v__h4678 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d184 ||
	   TASK_testplusargs___d185 && TASK_testplusargs___d186))
	$write("[%10d", v__h4678, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d184 ||
	   TASK_testplusargs___d185 && TASK_testplusargs___d186))
	$write("Axi2AxiL: Axi4-Lite-Write  :");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d184 ||
	   TASK_testplusargs___d185 && TASK_testplusargs___d186))
	$write("AXI4_Lite_Wr_Addr { ", "awaddr: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d184 ||
	   TASK_testplusargs___d185 && TASK_testplusargs___d186))
	$write("'h%h", t_axi_xactor_f_wr_addr_D_OUT[56:25]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d184 ||
	   TASK_testplusargs___d185 && TASK_testplusargs___d186))
	$write(", ", "awuser: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d184 ||
	   TASK_testplusargs___d185 && TASK_testplusargs___d186))
	$write("'h%h", 1'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d184 ||
	   TASK_testplusargs___d185 && TASK_testplusargs___d186))
	$write(", ", "awprot: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d184 ||
	   TASK_testplusargs___d185 && TASK_testplusargs___d186))
	$write("'h%h", t_axi_xactor_f_wr_addr_D_OUT[24:22]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d184 ||
	   TASK_testplusargs___d185 && TASK_testplusargs___d186))
	$write(", ", "awsize: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d184 ||
	   TASK_testplusargs___d185 && TASK_testplusargs___d186))
	$write("'h%h", axil_req_awsize__h4060, " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_frm_axi &&
	  (TASK_testplusargs___d184 ||
	   TASK_testplusargs___d185 && TASK_testplusargs___d186))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_response_to_axi)
	begin
	  TASK_testplusargs___d289 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_response_to_axi)
	begin
	  TASK_testplusargs___d290 = $test$plusargs("mbridge");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_response_to_axi)
	begin
	  TASK_testplusargs___d291 = $test$plusargs("l0");
	  #0;
	end
    TASK_testplusargs_89_OR_TASK_testplusargs_90_A_ETC___d296 =
	(TASK_testplusargs___d289 ||
	 TASK_testplusargs___d290 && TASK_testplusargs___d291) &&
	t_axil_xactor_f_wr_resp_D_OUT == 2'd0;
    TASK_testplusargs_89_OR_TASK_testplusargs_90_A_ETC___d298 =
	(TASK_testplusargs___d289 ||
	 TASK_testplusargs___d290 && TASK_testplusargs___d291) &&
	t_axil_xactor_f_wr_resp_D_OUT == 2'd1;
    TASK_testplusargs_89_OR_TASK_testplusargs_90_A_ETC___d299 =
	(TASK_testplusargs___d289 ||
	 TASK_testplusargs___d290 && TASK_testplusargs___d291) &&
	t_axil_xactor_f_wr_resp_D_OUT == 2'd2;
    TASK_testplusargs_89_OR_TASK_testplusargs_90_A_ETC___d305 =
	(TASK_testplusargs___d289 ||
	 TASK_testplusargs___d290 && TASK_testplusargs___d291) &&
	t_axil_xactor_f_wr_resp_D_OUT != 2'd0 &&
	t_axil_xactor_f_wr_resp_D_OUT != 2'd1 &&
	t_axil_xactor_f_wr_resp_D_OUT != 2'd2;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_response_to_axi)
	begin
	  v__h6060 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_response_to_axi &&
	  (TASK_testplusargs___d289 ||
	   TASK_testplusargs___d290 && TASK_testplusargs___d291))
	$write("[%10d", v__h6060, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_response_to_axi &&
	  (TASK_testplusargs___d289 ||
	   TASK_testplusargs___d290 && TASK_testplusargs___d291))
	$write("Axi2AxiL: AXI4L-Resp: Count:%2d", t_rg_wr_resp_beat);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_response_to_axi &&
	  (TASK_testplusargs___d289 ||
	   TASK_testplusargs___d290 && TASK_testplusargs___d291))
	$write("AXI4_Lite_Wr_Resp { ", "bresp: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_response_to_axi &&
	  TASK_testplusargs_89_OR_TASK_testplusargs_90_A_ETC___d296)
	$write("AXI4_LITE_OKAY");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_response_to_axi &&
	  TASK_testplusargs_89_OR_TASK_testplusargs_90_A_ETC___d298)
	$write("AXI4_LITE_EXOKAY");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_response_to_axi &&
	  TASK_testplusargs_89_OR_TASK_testplusargs_90_A_ETC___d299)
	$write("AXI4_LITE_SLVERR");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_response_to_axi &&
	  TASK_testplusargs_89_OR_TASK_testplusargs_90_A_ETC___d305)
	$write("AXI4_LITE_DECERR");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_response_to_axi &&
	  (TASK_testplusargs___d289 ||
	   TASK_testplusargs___d290 && TASK_testplusargs___d291))
	$write(", ", "buser: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_response_to_axi &&
	  (TASK_testplusargs___d289 ||
	   TASK_testplusargs___d290 && TASK_testplusargs___d291))
	$write("'h%h", 1'd0, " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_write_response_to_axi &&
	  (TASK_testplusargs___d289 ||
	   TASK_testplusargs___d290 && TASK_testplusargs___d291))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req)
	begin
	  TASK_testplusargs___d221 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req)
	begin
	  TASK_testplusargs___d222 = $test$plusargs("mbridge");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req)
	begin
	  TASK_testplusargs___d223 = $test$plusargs("l0");
	  #0;
	end
    TASK_testplusargs_21_OR_TASK_testplusargs_22_A_ETC___d229 =
	(TASK_testplusargs___d221 ||
	 TASK_testplusargs___d222 && TASK_testplusargs___d223) &&
	t_axi_xactor_f_wr_data_D_OUT[0];
    TASK_testplusargs_21_OR_TASK_testplusargs_22_A_ETC___d231 =
	(TASK_testplusargs___d221 ||
	 TASK_testplusargs___d222 && TASK_testplusargs___d223) &&
	!t_axi_xactor_f_wr_data_D_OUT[0];
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req)
	begin
	  v__h5106 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d221 ||
	   TASK_testplusargs___d222 && TASK_testplusargs___d223))
	$write("[%10d", v__h5106, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d221 ||
	   TASK_testplusargs___d222 && TASK_testplusargs___d223))
	$write("Axi2AxiL: Axi4-Wr Poping Wd Request:");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d221 ||
	   TASK_testplusargs___d222 && TASK_testplusargs___d223))
	$write("AXI4_Wr_Data { ", "wdata: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d221 ||
	   TASK_testplusargs___d222 && TASK_testplusargs___d223))
	$write("'h%h", t_axi_xactor_f_wr_data_D_OUT[81:18]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d221 ||
	   TASK_testplusargs___d222 && TASK_testplusargs___d223))
	$write(", ", "wstrb: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d221 ||
	   TASK_testplusargs___d222 && TASK_testplusargs___d223))
	$write("'h%h", t_axi_xactor_f_wr_data_D_OUT[17:10]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d221 ||
	   TASK_testplusargs___d222 && TASK_testplusargs___d223))
	$write(", ", "wid: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d221 ||
	   TASK_testplusargs___d222 && TASK_testplusargs___d223))
	$write("'h%h", t_axi_xactor_f_wr_data_D_OUT[9:1]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d221 ||
	   TASK_testplusargs___d222 && TASK_testplusargs___d223))
	$write(", ", "wlast: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  TASK_testplusargs_21_OR_TASK_testplusargs_22_A_ETC___d229)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  TASK_testplusargs_21_OR_TASK_testplusargs_22_A_ETC___d231)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d221 ||
	   TASK_testplusargs___d222 && TASK_testplusargs___d223))
	$write(" }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d221 ||
	   TASK_testplusargs___d222 && TASK_testplusargs___d223))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req)
	begin
	  TASK_testplusargs___d238 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req)
	begin
	  TASK_testplusargs___d239 = $test$plusargs("mbridge");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req)
	begin
	  TASK_testplusargs___d240 = $test$plusargs("l0");
	  #0;
	end
    TASK_testplusargs_38_OR_TASK_testplusargs_39_A_ETC___d244 =
	(TASK_testplusargs___d238 ||
	 TASK_testplusargs___d239 && TASK_testplusargs___d240) &&
	t_axi_xactor_f_wr_data_D_OUT[0];
    TASK_testplusargs_38_OR_TASK_testplusargs_39_A_ETC___d245 =
	(TASK_testplusargs___d238 ||
	 TASK_testplusargs___d239 && TASK_testplusargs___d240) &&
	!t_axi_xactor_f_wr_data_D_OUT[0];
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req)
	begin
	  v__h5336 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d238 ||
	   TASK_testplusargs___d239 && TASK_testplusargs___d240))
	$write("[%10d", v__h5336, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d238 ||
	   TASK_testplusargs___d239 && TASK_testplusargs___d240))
	$write("Axi2AxiL: New Axi4-Write Count:%d:", t_rg_wr_req_beat);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d238 ||
	   TASK_testplusargs___d239 && TASK_testplusargs___d240))
	$write("AXI4_Wr_Data { ", "wdata: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d238 ||
	   TASK_testplusargs___d239 && TASK_testplusargs___d240))
	$write("'h%h", t_axi_xactor_f_wr_data_D_OUT[81:18]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d238 ||
	   TASK_testplusargs___d239 && TASK_testplusargs___d240))
	$write(", ", "wstrb: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d238 ||
	   TASK_testplusargs___d239 && TASK_testplusargs___d240))
	$write("'h%h", t_axi_xactor_f_wr_data_D_OUT[17:10]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d238 ||
	   TASK_testplusargs___d239 && TASK_testplusargs___d240))
	$write(", ", "wid: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d238 ||
	   TASK_testplusargs___d239 && TASK_testplusargs___d240))
	$write("'h%h", t_axi_xactor_f_wr_data_D_OUT[9:1]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d238 ||
	   TASK_testplusargs___d239 && TASK_testplusargs___d240))
	$write(", ", "wlast: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  TASK_testplusargs_38_OR_TASK_testplusargs_39_A_ETC___d244)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  TASK_testplusargs_38_OR_TASK_testplusargs_39_A_ETC___d245)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d238 ||
	   TASK_testplusargs___d239 && TASK_testplusargs___d240))
	$write(" }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d238 ||
	   TASK_testplusargs___d239 && TASK_testplusargs___d240))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req)
	begin
	  TASK_testplusargs___d246 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req)
	begin
	  TASK_testplusargs___d247 = $test$plusargs("mbridge");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req)
	begin
	  TASK_testplusargs___d248 = $test$plusargs("l0");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req)
	begin
	  v__h5499 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d246 ||
	   TASK_testplusargs___d247 && TASK_testplusargs___d248))
	$write("[%10d", v__h5499, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d246 ||
	   TASK_testplusargs___d247 && TASK_testplusargs___d248))
	$write("Axi2AxiL: Axi4-Lite-Write  :");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d246 ||
	   TASK_testplusargs___d247 && TASK_testplusargs___d248))
	$write("AXI4_Lite_Wr_Addr { ", "awaddr: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d246 ||
	   TASK_testplusargs___d247 && TASK_testplusargs___d248))
	$write("'h%h", axil_req_awaddr__h5224);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d246 ||
	   TASK_testplusargs___d247 && TASK_testplusargs___d248))
	$write(", ", "awuser: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d246 ||
	   TASK_testplusargs___d247 && TASK_testplusargs___d248))
	$write("'h%h", 1'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d246 ||
	   TASK_testplusargs___d247 && TASK_testplusargs___d248))
	$write(", ", "awprot: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d246 ||
	   TASK_testplusargs___d247 && TASK_testplusargs___d248))
	$write("'h%h", t_rg_wr_request[24:22]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d246 ||
	   TASK_testplusargs___d247 && TASK_testplusargs___d248))
	$write(", ", "awsize: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d246 ||
	   TASK_testplusargs___d247 && TASK_testplusargs___d248))
	$write("'h%h", axil_req_awsize__h5227, " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d246 ||
	   TASK_testplusargs___d247 && TASK_testplusargs___d248))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req)
	begin
	  TASK_testplusargs___d252 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req)
	begin
	  TASK_testplusargs___d253 = $test$plusargs("mbridge");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req)
	begin
	  TASK_testplusargs___d254 = $test$plusargs("l0");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req)
	begin
	  v__h5636 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d252 ||
	   TASK_testplusargs___d253 && TASK_testplusargs___d254))
	$write("[%10d", v__h5636, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d252 ||
	   TASK_testplusargs___d253 && TASK_testplusargs___d254))
	$write("Axi2AxiL: Child:%d ChildReq:%d",
	       t_rg_child_wr_burst,
	       t_rg_child_wr_req_count);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_t_rl_send_wr_burst_req &&
	  (TASK_testplusargs___d252 ||
	   TASK_testplusargs___d253 && TASK_testplusargs___d254))
	$write("\n");
  end
  // synopsys translate_on
endmodule  // axi2axil_64

