//
// Generated by Bluespec Compiler, version 2025.01.1-9-g3ff99e1b (build 3ff99e1b)
//
// On Mon Mar  9 19:37:43 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// AXI4_awready                   O     1 reg
// AXI4_wready                    O     1 reg
// AXI4_bvalid                    O     1 reg
// AXI4_bid                       O     9 reg
// AXI4_bresp                     O     2 reg
// AXI4_arready                   O     1 reg
// AXI4_rvalid                    O     1 reg
// AXI4_rid                       O     9 reg
// AXI4_rdata                     O    64 reg
// AXI4_rresp                     O     2 reg
// AXI4_rlast                     O     1 reg
// APB_PADDR                      O    32 reg
// APB_PROT                       O     3 reg
// APB_PENABLE                    O     1 reg
// APB_PWRITE                     O     1 reg
// APB_PWDATA                     O    64 reg
// APB_PSTRB                      O     8 reg
// APB_PSEL                       O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// AXI4_awvalid                   I     1
// AXI4_awid                      I     9 reg
// AXI4_awaddr                    I    32 reg
// AXI4_awlen                     I     8 reg
// AXI4_awsize                    I     3 reg
// AXI4_awburst                   I     2 reg
// AXI4_awlock                    I     1 reg
// AXI4_awcache                   I     4 reg
// AXI4_awprot                    I     3 reg
// AXI4_awqos                     I     4 reg
// AXI4_awregion                  I     4 reg
// AXI4_wvalid                    I     1
// AXI4_wdata                     I    64 reg
// AXI4_wstrb                     I     8 reg
// AXI4_wlast                     I     1 reg
// AXI4_bready                    I     1
// AXI4_arvalid                   I     1
// AXI4_arid                      I     9 reg
// AXI4_araddr                    I    32 reg
// AXI4_arlen                     I     8 reg
// AXI4_arsize                    I     3 reg
// AXI4_arburst                   I     2 reg
// AXI4_arlock                    I     1 reg
// AXI4_arcache                   I     4 reg
// AXI4_arprot                    I     3 reg
// AXI4_arqos                     I     4 reg
// AXI4_arregion                  I     4 reg
// AXI4_rready                    I     1
// APB_PREADY                     I     1
// APB_PRDATA                     I    64 reg
// APB_PSLVERR                    I     1 reg
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module axi2apb_64(CLK,
		  RST_N,

		  AXI4_awvalid,
		  AXI4_awid,
		  AXI4_awaddr,
		  AXI4_awlen,
		  AXI4_awsize,
		  AXI4_awburst,
		  AXI4_awlock,
		  AXI4_awcache,
		  AXI4_awprot,
		  AXI4_awqos,
		  AXI4_awregion,

		  AXI4_awready,

		  AXI4_wvalid,
		  AXI4_wdata,
		  AXI4_wstrb,
		  AXI4_wlast,

		  AXI4_wready,

		  AXI4_bvalid,

		  AXI4_bid,

		  AXI4_bresp,

		  AXI4_bready,

		  AXI4_arvalid,
		  AXI4_arid,
		  AXI4_araddr,
		  AXI4_arlen,
		  AXI4_arsize,
		  AXI4_arburst,
		  AXI4_arlock,
		  AXI4_arcache,
		  AXI4_arprot,
		  AXI4_arqos,
		  AXI4_arregion,

		  AXI4_arready,

		  AXI4_rvalid,

		  AXI4_rid,

		  AXI4_rdata,

		  AXI4_rresp,

		  AXI4_rlast,

		  AXI4_rready,

		  APB_PADDR,

		  APB_PROT,

		  APB_PENABLE,

		  APB_PWRITE,

		  APB_PWDATA,

		  APB_PSTRB,

		  APB_PSEL,

		  APB_PREADY,
		  APB_PRDATA,
		  APB_PSLVERR);
  input  CLK;
  input  RST_N;

  // action method axi4_side_m_awvalid
  input  AXI4_awvalid;
  input  [8 : 0] AXI4_awid;
  input  [31 : 0] AXI4_awaddr;
  input  [7 : 0] AXI4_awlen;
  input  [2 : 0] AXI4_awsize;
  input  [1 : 0] AXI4_awburst;
  input  AXI4_awlock;
  input  [3 : 0] AXI4_awcache;
  input  [2 : 0] AXI4_awprot;
  input  [3 : 0] AXI4_awqos;
  input  [3 : 0] AXI4_awregion;

  // value method axi4_side_m_awready
  output AXI4_awready;

  // action method axi4_side_m_wvalid
  input  AXI4_wvalid;
  input  [63 : 0] AXI4_wdata;
  input  [7 : 0] AXI4_wstrb;
  input  AXI4_wlast;

  // value method axi4_side_m_wready
  output AXI4_wready;

  // value method axi4_side_m_bvalid
  output AXI4_bvalid;

  // value method axi4_side_m_bid
  output [8 : 0] AXI4_bid;

  // value method axi4_side_m_bresp
  output [1 : 0] AXI4_bresp;

  // value method axi4_side_m_buser

  // action method axi4_side_m_bready
  input  AXI4_bready;

  // action method axi4_side_m_arvalid
  input  AXI4_arvalid;
  input  [8 : 0] AXI4_arid;
  input  [31 : 0] AXI4_araddr;
  input  [7 : 0] AXI4_arlen;
  input  [2 : 0] AXI4_arsize;
  input  [1 : 0] AXI4_arburst;
  input  AXI4_arlock;
  input  [3 : 0] AXI4_arcache;
  input  [2 : 0] AXI4_arprot;
  input  [3 : 0] AXI4_arqos;
  input  [3 : 0] AXI4_arregion;

  // value method axi4_side_m_arready
  output AXI4_arready;

  // value method axi4_side_m_rvalid
  output AXI4_rvalid;

  // value method axi4_side_m_rid
  output [8 : 0] AXI4_rid;

  // value method axi4_side_m_rdata
  output [63 : 0] AXI4_rdata;

  // value method axi4_side_m_rresp
  output [1 : 0] AXI4_rresp;

  // value method axi4_side_m_rlast
  output AXI4_rlast;

  // value method axi4_side_m_ruser

  // action method axi4_side_m_rready
  input  AXI4_rready;

  // value method apb_side_m_paddr
  output [31 : 0] APB_PADDR;

  // value method apb_side_m_prot
  output [2 : 0] APB_PROT;

  // value method apb_side_m_penable
  output APB_PENABLE;

  // value method apb_side_m_pwrite
  output APB_PWRITE;

  // value method apb_side_m_pwdata
  output [63 : 0] APB_PWDATA;

  // value method apb_side_m_pstrb
  output [7 : 0] APB_PSTRB;

  // value method apb_side_m_psel
  output APB_PSEL;

  // value method apb_side_m_puser

  // action method apb_side_m_pready
  input  APB_PREADY;
  input  [63 : 0] APB_PRDATA;
  input  APB_PSLVERR;

  // signals for module outputs
  wire [63 : 0] APB_PWDATA, AXI4_rdata;
  wire [31 : 0] APB_PADDR;
  wire [8 : 0] AXI4_bid, AXI4_rid;
  wire [7 : 0] APB_PSTRB;
  wire [2 : 0] APB_PROT;
  wire [1 : 0] AXI4_bresp, AXI4_rresp;
  wire APB_PENABLE,
       APB_PSEL,
       APB_PWRITE,
       AXI4_arready,
       AXI4_awready,
       AXI4_bvalid,
       AXI4_rlast,
       AXI4_rvalid,
       AXI4_wready;

  // inlined wires
  reg [108 : 0] t_apb_xactor_ff_request_rv_port0__write_1;
  wire [108 : 0] t_apb_xactor_ff_request_rv_port1__read,
		 t_apb_xactor_ff_request_rv_port1__write_1,
		 t_apb_xactor_ff_request_rv_port2__read;
  wire t_apb_xactor_ff_request_rv_EN_port0__write;

  // register t_apb_xactor_ff_request_rv
  reg [108 : 0] t_apb_xactor_ff_request_rv;
  wire [108 : 0] t_apb_xactor_ff_request_rv_D_IN;
  wire t_apb_xactor_ff_request_rv_EN;

  // register t_apb_xactor_rg_enable
  reg t_apb_xactor_rg_enable;
  wire t_apb_xactor_rg_enable_D_IN, t_apb_xactor_rg_enable_EN;

  // register t_apb_xactor_rg_request
  reg [107 : 0] t_apb_xactor_rg_request;
  wire [107 : 0] t_apb_xactor_rg_request_D_IN;
  wire t_apb_xactor_rg_request_EN;

  // register t_apb_xactor_rg_sel
  reg t_apb_xactor_rg_sel;
  wire t_apb_xactor_rg_sel_D_IN, t_apb_xactor_rg_sel_EN;

  // register t_apb_xactor_rg_state
  reg [1 : 0] t_apb_xactor_rg_state;
  reg [1 : 0] t_apb_xactor_rg_state_D_IN;
  wire t_apb_xactor_rg_state_EN;

  // register t_rg_accum_data
  reg [63 : 0] t_rg_accum_data;
  wire [63 : 0] t_rg_accum_data_D_IN;
  wire t_rg_accum_data_EN;

  // register t_rg_accum_err
  reg t_rg_accum_err;
  wire t_rg_accum_err_D_IN, t_rg_accum_err_EN;

  // register t_rg_accum_mask
  reg [7 : 0] t_rg_accum_mask;
  wire [7 : 0] t_rg_accum_mask_D_IN;
  wire t_rg_accum_mask_EN;

  // register t_rg_child_burst
  reg [7 : 0] t_rg_child_burst;
  wire [7 : 0] t_rg_child_burst_D_IN;
  wire t_rg_child_burst_EN;

  // register t_rg_child_req_count
  reg [7 : 0] t_rg_child_req_count;
  wire [7 : 0] t_rg_child_req_count_D_IN;
  wire t_rg_child_req_count_EN;

  // register t_rg_child_res_count
  reg [7 : 0] t_rg_child_res_count;
  wire [7 : 0] t_rg_child_res_count_D_IN;
  wire t_rg_child_res_count_EN;

  // register t_rg_rd_request
  reg [69 : 0] t_rg_rd_request;
  wire [69 : 0] t_rg_rd_request_D_IN;
  wire t_rg_rd_request_EN;

  // register t_rg_req_beat
  reg [7 : 0] t_rg_req_beat;
  reg [7 : 0] t_rg_req_beat_D_IN;
  wire t_rg_req_beat_EN;

  // register t_rg_resp_beat
  reg [7 : 0] t_rg_resp_beat;
  reg [7 : 0] t_rg_resp_beat_D_IN;
  wire t_rg_resp_beat_EN;

  // register t_rg_state
  reg [1 : 0] t_rg_state;
  reg [1 : 0] t_rg_state_D_IN;
  wire t_rg_state_EN;

  // register t_rg_wd_request
  reg [72 : 0] t_rg_wd_request;
  wire [72 : 0] t_rg_wd_request_D_IN;
  wire t_rg_wd_request_EN;

  // register t_rg_wr_request
  reg [69 : 0] t_rg_wr_request;
  wire [69 : 0] t_rg_wr_request_D_IN;
  wire t_rg_wr_request_EN;

  // ports of submodule t_apb_xactor_ff_response
  wire [64 : 0] t_apb_xactor_ff_response_D_IN, t_apb_xactor_ff_response_D_OUT;
  wire t_apb_xactor_ff_response_CLR,
       t_apb_xactor_ff_response_DEQ,
       t_apb_xactor_ff_response_EMPTY_N,
       t_apb_xactor_ff_response_ENQ,
       t_apb_xactor_ff_response_FULL_N;

  // ports of submodule t_axi_xactor_f_arfifo
  wire [69 : 0] t_axi_xactor_f_arfifo_D_IN, t_axi_xactor_f_arfifo_D_OUT;
  wire t_axi_xactor_f_arfifo_CLR,
       t_axi_xactor_f_arfifo_DEQ,
       t_axi_xactor_f_arfifo_EMPTY_N,
       t_axi_xactor_f_arfifo_ENQ,
       t_axi_xactor_f_arfifo_FULL_N;

  // ports of submodule t_axi_xactor_f_awfifo
  wire [69 : 0] t_axi_xactor_f_awfifo_D_IN, t_axi_xactor_f_awfifo_D_OUT;
  wire t_axi_xactor_f_awfifo_CLR,
       t_axi_xactor_f_awfifo_DEQ,
       t_axi_xactor_f_awfifo_EMPTY_N,
       t_axi_xactor_f_awfifo_ENQ,
       t_axi_xactor_f_awfifo_FULL_N;

  // ports of submodule t_axi_xactor_f_bfifo
  wire [10 : 0] t_axi_xactor_f_bfifo_D_IN, t_axi_xactor_f_bfifo_D_OUT;
  wire t_axi_xactor_f_bfifo_CLR,
       t_axi_xactor_f_bfifo_DEQ,
       t_axi_xactor_f_bfifo_EMPTY_N,
       t_axi_xactor_f_bfifo_ENQ,
       t_axi_xactor_f_bfifo_FULL_N;

  // ports of submodule t_axi_xactor_f_rfifo
  wire [75 : 0] t_axi_xactor_f_rfifo_D_IN, t_axi_xactor_f_rfifo_D_OUT;
  wire t_axi_xactor_f_rfifo_CLR,
       t_axi_xactor_f_rfifo_DEQ,
       t_axi_xactor_f_rfifo_EMPTY_N,
       t_axi_xactor_f_rfifo_ENQ,
       t_axi_xactor_f_rfifo_FULL_N;

  // ports of submodule t_axi_xactor_f_wfifo
  wire [72 : 0] t_axi_xactor_f_wfifo_D_IN, t_axi_xactor_f_wfifo_D_OUT;
  wire t_axi_xactor_f_wfifo_CLR,
       t_axi_xactor_f_wfifo_DEQ,
       t_axi_xactor_f_wfifo_EMPTY_N,
       t_axi_xactor_f_wfifo_ENQ,
       t_axi_xactor_f_wfifo_FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_t_apb_xactor_rl_access_to_idle,
       CAN_FIRE_RL_t_apb_xactor_rl_access_to_setup,
       CAN_FIRE_RL_t_apb_xactor_rl_idle_to_setup,
       CAN_FIRE_RL_t_apb_xactor_rl_setup_state,
       CAN_FIRE_RL_t_rl_read_frm_axi,
       CAN_FIRE_RL_t_rl_read_response_to_axi,
       CAN_FIRE_RL_t_rl_send_rd_burst_req,
       CAN_FIRE_RL_t_rl_send_wr_burst_req,
       CAN_FIRE_RL_t_rl_write_frm_axi,
       CAN_FIRE_RL_t_rl_write_response_to_axi,
       CAN_FIRE_apb_side_m_pready,
       CAN_FIRE_axi4_side_m_arvalid,
       CAN_FIRE_axi4_side_m_awvalid,
       CAN_FIRE_axi4_side_m_bready,
       CAN_FIRE_axi4_side_m_rready,
       CAN_FIRE_axi4_side_m_wvalid,
       WILL_FIRE_RL_t_apb_xactor_rl_access_to_idle,
       WILL_FIRE_RL_t_apb_xactor_rl_access_to_setup,
       WILL_FIRE_RL_t_apb_xactor_rl_idle_to_setup,
       WILL_FIRE_RL_t_apb_xactor_rl_setup_state,
       WILL_FIRE_RL_t_rl_read_frm_axi,
       WILL_FIRE_RL_t_rl_read_response_to_axi,
       WILL_FIRE_RL_t_rl_send_rd_burst_req,
       WILL_FIRE_RL_t_rl_send_wr_burst_req,
       WILL_FIRE_RL_t_rl_write_frm_axi,
       WILL_FIRE_RL_t_rl_write_response_to_axi,
       WILL_FIRE_apb_side_m_pready,
       WILL_FIRE_axi4_side_m_arvalid,
       WILL_FIRE_axi4_side_m_awvalid,
       WILL_FIRE_axi4_side_m_bready,
       WILL_FIRE_axi4_side_m_rready,
       WILL_FIRE_axi4_side_m_wvalid;

  // inputs to muxes for submodule ports
  wire [108 : 0] MUX_t_apb_xactor_ff_request_rv_port0__write_1__VAL_1,
		 MUX_t_apb_xactor_ff_request_rv_port0__write_1__VAL_2,
		 MUX_t_apb_xactor_ff_request_rv_port0__write_1__VAL_3,
		 MUX_t_apb_xactor_ff_request_rv_port0__write_1__VAL_4;
  wire [69 : 0] MUX_t_rg_rd_request_write_1__VAL_2,
		MUX_t_rg_wr_request_write_1__VAL_2;
  wire [7 : 0] MUX_t_rg_req_beat_write_1__VAL_1,
	       MUX_t_rg_resp_beat_write_1__VAL_1,
	       MUX_t_rg_resp_beat_write_1__VAL_2,
	       MUX_t_rg_resp_beat_write_1__VAL_3;
  wire MUX_t_apb_xactor_rg_enable_write_1__SEL_1,
       MUX_t_apb_xactor_rg_sel_write_1__SEL_2,
       MUX_t_rg_accum_err_write_1__VAL_1,
       MUX_t_rg_req_beat_write_1__SEL_1,
       MUX_t_rg_state_write_1__PSEL_1,
       MUX_t_rg_state_write_1__SEL_1;

  // remaining internal signals
  reg [31 : 0] apb_request_paddr__h3261, apb_request_paddr__h4630;
  reg [2 : 0] CASE_t_rg_rd_request_BITS_28_TO_21_3_2_7_3_15_4_1__q1,
	      CASE_t_rg_wr_request_BITS_28_TO_21_3_2_7_3_15_4_1__q2;
  wire [31 : 0] mask__h3026,
		mask__h4361,
		new_address__h3024,
		new_address__h4359,
		temp1__h3027,
		temp1__h4362,
		temp2__h3028,
		temp2__h4363,
		y__h3128,
		y__h4463;
  wire [2 : 0] x__h3069, x__h4404;
  wire [1 : 0] axi_response_rresp__h3609;
  wire _dand1t_rg_state_EN_write;

  // action method axi4_side_m_awvalid
  assign CAN_FIRE_axi4_side_m_awvalid = 1'd1 ;
  assign WILL_FIRE_axi4_side_m_awvalid = 1'd1 ;

  // value method axi4_side_m_awready
  assign AXI4_awready = t_axi_xactor_f_awfifo_FULL_N ;

  // action method axi4_side_m_wvalid
  assign CAN_FIRE_axi4_side_m_wvalid = 1'd1 ;
  assign WILL_FIRE_axi4_side_m_wvalid = 1'd1 ;

  // value method axi4_side_m_wready
  assign AXI4_wready = t_axi_xactor_f_wfifo_FULL_N ;

  // value method axi4_side_m_bvalid
  assign AXI4_bvalid = t_axi_xactor_f_bfifo_EMPTY_N ;

  // value method axi4_side_m_bid
  assign AXI4_bid = t_axi_xactor_f_bfifo_D_OUT[10:2] ;

  // value method axi4_side_m_bresp
  assign AXI4_bresp = t_axi_xactor_f_bfifo_D_OUT[1:0] ;

  // action method axi4_side_m_bready
  assign CAN_FIRE_axi4_side_m_bready = 1'd1 ;
  assign WILL_FIRE_axi4_side_m_bready = 1'd1 ;

  // action method axi4_side_m_arvalid
  assign CAN_FIRE_axi4_side_m_arvalid = 1'd1 ;
  assign WILL_FIRE_axi4_side_m_arvalid = 1'd1 ;

  // value method axi4_side_m_arready
  assign AXI4_arready = t_axi_xactor_f_arfifo_FULL_N ;

  // value method axi4_side_m_rvalid
  assign AXI4_rvalid = t_axi_xactor_f_rfifo_EMPTY_N ;

  // value method axi4_side_m_rid
  assign AXI4_rid = t_axi_xactor_f_rfifo_D_OUT[75:67] ;

  // value method axi4_side_m_rdata
  assign AXI4_rdata = t_axi_xactor_f_rfifo_D_OUT[66:3] ;

  // value method axi4_side_m_rresp
  assign AXI4_rresp = t_axi_xactor_f_rfifo_D_OUT[2:1] ;

  // value method axi4_side_m_rlast
  assign AXI4_rlast = t_axi_xactor_f_rfifo_D_OUT[0] ;

  // action method axi4_side_m_rready
  assign CAN_FIRE_axi4_side_m_rready = 1'd1 ;
  assign WILL_FIRE_axi4_side_m_rready = 1'd1 ;

  // value method apb_side_m_paddr
  assign APB_PADDR = t_apb_xactor_rg_request[107:76] ;

  // value method apb_side_m_prot
  assign APB_PROT = t_apb_xactor_rg_request[75:73] ;

  // value method apb_side_m_penable
  assign APB_PENABLE = t_apb_xactor_rg_enable ;

  // value method apb_side_m_pwrite
  assign APB_PWRITE = t_apb_xactor_rg_request[72] ;

  // value method apb_side_m_pwdata
  assign APB_PWDATA = t_apb_xactor_rg_request[71:8] ;

  // value method apb_side_m_pstrb
  assign APB_PSTRB = t_apb_xactor_rg_request[7:0] ;

  // value method apb_side_m_psel
  assign APB_PSEL = t_apb_xactor_rg_sel ;

  // action method apb_side_m_pready
  assign CAN_FIRE_apb_side_m_pready = 1'd1 ;
  assign WILL_FIRE_apb_side_m_pready = 1'd1 ;

  // submodule t_apb_xactor_ff_response
  FIFOL1 #(.width(32'd65)) t_apb_xactor_ff_response(.RST(RST_N),
						    .CLK(CLK),
						    .D_IN(t_apb_xactor_ff_response_D_IN),
						    .ENQ(t_apb_xactor_ff_response_ENQ),
						    .DEQ(t_apb_xactor_ff_response_DEQ),
						    .CLR(t_apb_xactor_ff_response_CLR),
						    .D_OUT(t_apb_xactor_ff_response_D_OUT),
						    .FULL_N(t_apb_xactor_ff_response_FULL_N),
						    .EMPTY_N(t_apb_xactor_ff_response_EMPTY_N));

  // submodule t_axi_xactor_f_arfifo
  FIFO2 #(.width(32'd70), .guarded(1'd1)) t_axi_xactor_f_arfifo(.RST(RST_N),
								.CLK(CLK),
								.D_IN(t_axi_xactor_f_arfifo_D_IN),
								.ENQ(t_axi_xactor_f_arfifo_ENQ),
								.DEQ(t_axi_xactor_f_arfifo_DEQ),
								.CLR(t_axi_xactor_f_arfifo_CLR),
								.D_OUT(t_axi_xactor_f_arfifo_D_OUT),
								.FULL_N(t_axi_xactor_f_arfifo_FULL_N),
								.EMPTY_N(t_axi_xactor_f_arfifo_EMPTY_N));

  // submodule t_axi_xactor_f_awfifo
  FIFO2 #(.width(32'd70), .guarded(1'd1)) t_axi_xactor_f_awfifo(.RST(RST_N),
								.CLK(CLK),
								.D_IN(t_axi_xactor_f_awfifo_D_IN),
								.ENQ(t_axi_xactor_f_awfifo_ENQ),
								.DEQ(t_axi_xactor_f_awfifo_DEQ),
								.CLR(t_axi_xactor_f_awfifo_CLR),
								.D_OUT(t_axi_xactor_f_awfifo_D_OUT),
								.FULL_N(t_axi_xactor_f_awfifo_FULL_N),
								.EMPTY_N(t_axi_xactor_f_awfifo_EMPTY_N));

  // submodule t_axi_xactor_f_bfifo
  FIFO2 #(.width(32'd11), .guarded(1'd1)) t_axi_xactor_f_bfifo(.RST(RST_N),
							       .CLK(CLK),
							       .D_IN(t_axi_xactor_f_bfifo_D_IN),
							       .ENQ(t_axi_xactor_f_bfifo_ENQ),
							       .DEQ(t_axi_xactor_f_bfifo_DEQ),
							       .CLR(t_axi_xactor_f_bfifo_CLR),
							       .D_OUT(t_axi_xactor_f_bfifo_D_OUT),
							       .FULL_N(t_axi_xactor_f_bfifo_FULL_N),
							       .EMPTY_N(t_axi_xactor_f_bfifo_EMPTY_N));

  // submodule t_axi_xactor_f_rfifo
  FIFO2 #(.width(32'd76), .guarded(1'd1)) t_axi_xactor_f_rfifo(.RST(RST_N),
							       .CLK(CLK),
							       .D_IN(t_axi_xactor_f_rfifo_D_IN),
							       .ENQ(t_axi_xactor_f_rfifo_ENQ),
							       .DEQ(t_axi_xactor_f_rfifo_DEQ),
							       .CLR(t_axi_xactor_f_rfifo_CLR),
							       .D_OUT(t_axi_xactor_f_rfifo_D_OUT),
							       .FULL_N(t_axi_xactor_f_rfifo_FULL_N),
							       .EMPTY_N(t_axi_xactor_f_rfifo_EMPTY_N));

  // submodule t_axi_xactor_f_wfifo
  FIFO2 #(.width(32'd73), .guarded(1'd1)) t_axi_xactor_f_wfifo(.RST(RST_N),
							       .CLK(CLK),
							       .D_IN(t_axi_xactor_f_wfifo_D_IN),
							       .ENQ(t_axi_xactor_f_wfifo_ENQ),
							       .DEQ(t_axi_xactor_f_wfifo_DEQ),
							       .CLR(t_axi_xactor_f_wfifo_CLR),
							       .D_OUT(t_axi_xactor_f_wfifo_D_OUT),
							       .FULL_N(t_axi_xactor_f_wfifo_FULL_N),
							       .EMPTY_N(t_axi_xactor_f_wfifo_EMPTY_N));

  // rule RL_t_rl_read_frm_axi
  assign CAN_FIRE_RL_t_rl_read_frm_axi =
	     t_axi_xactor_f_arfifo_EMPTY_N &&
	     !t_apb_xactor_ff_request_rv[108] &&
	     t_rg_state == 2'd0 ;
  assign WILL_FIRE_RL_t_rl_read_frm_axi = CAN_FIRE_RL_t_rl_read_frm_axi ;

  // rule RL_t_rl_read_response_to_axi
  assign CAN_FIRE_RL_t_rl_read_response_to_axi =
	     t_apb_xactor_ff_response_EMPTY_N &&
	     t_axi_xactor_f_rfifo_FULL_N &&
	     t_rg_state == 2'd1 &&
	     t_rg_resp_beat != 8'd0 ;
  assign WILL_FIRE_RL_t_rl_read_response_to_axi =
	     CAN_FIRE_RL_t_rl_read_response_to_axi ;

  // rule RL_t_rl_send_rd_burst_req
  assign CAN_FIRE_RL_t_rl_send_rd_burst_req =
	     !t_apb_xactor_ff_request_rv[108] && t_rg_state == 2'd1 &&
	     t_rg_req_beat != 8'd0 ;
  assign WILL_FIRE_RL_t_rl_send_rd_burst_req =
	     CAN_FIRE_RL_t_rl_send_rd_burst_req ;

  // rule RL_t_rl_write_frm_axi
  assign CAN_FIRE_RL_t_rl_write_frm_axi =
	     !t_apb_xactor_ff_request_rv[108] &&
	     t_axi_xactor_f_awfifo_EMPTY_N &&
	     t_axi_xactor_f_wfifo_EMPTY_N &&
	     t_rg_state == 2'd0 ;
  assign WILL_FIRE_RL_t_rl_write_frm_axi =
	     CAN_FIRE_RL_t_rl_write_frm_axi &&
	     !WILL_FIRE_RL_t_rl_read_frm_axi ;

  // rule RL_t_rl_write_response_to_axi
  assign CAN_FIRE_RL_t_rl_write_response_to_axi =
	     t_apb_xactor_ff_response_EMPTY_N &&
	     t_axi_xactor_f_bfifo_FULL_N &&
	     t_rg_state == 2'd2 &&
	     t_rg_resp_beat != 8'd0 ;
  assign WILL_FIRE_RL_t_rl_write_response_to_axi =
	     CAN_FIRE_RL_t_rl_write_response_to_axi ;

  // rule RL_t_rl_send_wr_burst_req
  assign CAN_FIRE_RL_t_rl_send_wr_burst_req =
	     !t_apb_xactor_ff_request_rv[108] &&
	     t_axi_xactor_f_wfifo_EMPTY_N &&
	     t_rg_state == 2'd2 &&
	     t_rg_req_beat != 8'd0 ;
  assign WILL_FIRE_RL_t_rl_send_wr_burst_req =
	     CAN_FIRE_RL_t_rl_send_wr_burst_req ;

  // rule RL_t_apb_xactor_rl_idle_to_setup
  assign CAN_FIRE_RL_t_apb_xactor_rl_idle_to_setup =
	     t_apb_xactor_ff_request_rv_port1__read[108] &&
	     t_apb_xactor_rg_state == 2'd0 ;
  assign WILL_FIRE_RL_t_apb_xactor_rl_idle_to_setup =
	     CAN_FIRE_RL_t_apb_xactor_rl_idle_to_setup ;

  // rule RL_t_apb_xactor_rl_setup_state
  assign CAN_FIRE_RL_t_apb_xactor_rl_setup_state =
	     t_apb_xactor_rg_state == 2'd1 ;
  assign WILL_FIRE_RL_t_apb_xactor_rl_setup_state =
	     CAN_FIRE_RL_t_apb_xactor_rl_setup_state ;

  // rule RL_t_apb_xactor_rl_access_to_idle
  assign CAN_FIRE_RL_t_apb_xactor_rl_access_to_idle =
	     t_apb_xactor_ff_response_FULL_N &&
	     t_apb_xactor_rg_state == 2'd2 &&
	     APB_PREADY &&
	     !t_apb_xactor_ff_request_rv_port1__read[108] ;
  assign WILL_FIRE_RL_t_apb_xactor_rl_access_to_idle =
	     CAN_FIRE_RL_t_apb_xactor_rl_access_to_idle ;

  // rule RL_t_apb_xactor_rl_access_to_setup
  assign CAN_FIRE_RL_t_apb_xactor_rl_access_to_setup =
	     t_apb_xactor_ff_request_rv_port1__read[108] &&
	     t_apb_xactor_ff_response_FULL_N &&
	     t_apb_xactor_rg_state == 2'd2 &&
	     APB_PREADY ;
  assign WILL_FIRE_RL_t_apb_xactor_rl_access_to_setup =
	     CAN_FIRE_RL_t_apb_xactor_rl_access_to_setup ;

  // inputs to muxes for submodule ports
  assign MUX_t_apb_xactor_rg_enable_write_1__SEL_1 =
	     WILL_FIRE_RL_t_apb_xactor_rl_access_to_setup ||
	     WILL_FIRE_RL_t_apb_xactor_rl_access_to_idle ||
	     WILL_FIRE_RL_t_apb_xactor_rl_idle_to_setup ;
  assign MUX_t_apb_xactor_rg_sel_write_1__SEL_2 =
	     WILL_FIRE_RL_t_apb_xactor_rl_access_to_setup ||
	     WILL_FIRE_RL_t_apb_xactor_rl_idle_to_setup ;
  assign MUX_t_rg_req_beat_write_1__SEL_1 =
	     WILL_FIRE_RL_t_rl_send_wr_burst_req ||
	     WILL_FIRE_RL_t_rl_send_rd_burst_req ;
  assign MUX_t_rg_state_write_1__PSEL_1 =
	     WILL_FIRE_RL_t_rl_write_response_to_axi ||
	     WILL_FIRE_RL_t_rl_read_response_to_axi ;
  assign MUX_t_rg_state_write_1__SEL_1 =
	     MUX_t_rg_state_write_1__PSEL_1 && t_rg_resp_beat == 8'd1 &&
	     (t_rg_child_res_count == t_rg_child_burst ||
	      t_rg_child_burst == 8'd0) ;
  assign MUX_t_apb_xactor_ff_request_rv_port0__write_1__VAL_1 =
	     { 1'd1,
	       t_axi_xactor_f_arfifo_D_OUT[60:29],
	       t_axi_xactor_f_arfifo_D_OUT[10:8],
	       1'd0,
	       64'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ,
	       8'd0 } ;
  assign MUX_t_apb_xactor_ff_request_rv_port0__write_1__VAL_2 =
	     { 1'd1,
	       apb_request_paddr__h3261,
	       t_rg_rd_request[10:8],
	       1'd0,
	       64'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ,
	       8'd0 } ;
  assign MUX_t_apb_xactor_ff_request_rv_port0__write_1__VAL_3 =
	     { 1'd1,
	       t_axi_xactor_f_awfifo_D_OUT[60:29],
	       t_axi_xactor_f_awfifo_D_OUT[10:8],
	       1'd1,
	       t_axi_xactor_f_wfifo_D_OUT[72:1] } ;
  assign MUX_t_apb_xactor_ff_request_rv_port0__write_1__VAL_4 =
	     { 1'd1,
	       apb_request_paddr__h4630,
	       t_rg_wr_request[10:8],
	       1'd1,
	       t_axi_xactor_f_wfifo_D_OUT[72:1] } ;
  assign MUX_t_rg_accum_err_write_1__VAL_1 =
	     t_rg_accum_err || t_apb_xactor_ff_response_D_OUT[0] ;
  assign MUX_t_rg_rd_request_write_1__VAL_2 =
	     { t_rg_rd_request[69:61],
	       apb_request_paddr__h3261,
	       t_rg_rd_request[28:0] } ;
  assign MUX_t_rg_req_beat_write_1__VAL_1 = t_rg_req_beat - 8'd1 ;
  assign MUX_t_rg_resp_beat_write_1__VAL_1 =
	     t_axi_xactor_f_arfifo_D_OUT[28:21] + 8'd1 ;
  assign MUX_t_rg_resp_beat_write_1__VAL_2 = t_rg_resp_beat - 8'd1 ;
  assign MUX_t_rg_resp_beat_write_1__VAL_3 =
	     t_axi_xactor_f_awfifo_D_OUT[28:21] + 8'd1 ;
  assign MUX_t_rg_wr_request_write_1__VAL_2 =
	     { t_rg_wr_request[69:61],
	       apb_request_paddr__h4630,
	       t_rg_wr_request[28:0] } ;

  // inlined wires
  assign t_apb_xactor_ff_request_rv_EN_port0__write =
	     WILL_FIRE_RL_t_rl_read_frm_axi ||
	     WILL_FIRE_RL_t_rl_send_rd_burst_req ||
	     WILL_FIRE_RL_t_rl_write_frm_axi ||
	     WILL_FIRE_RL_t_rl_send_wr_burst_req ;
  always@(WILL_FIRE_RL_t_rl_read_frm_axi or
	  MUX_t_apb_xactor_ff_request_rv_port0__write_1__VAL_1 or
	  WILL_FIRE_RL_t_rl_send_rd_burst_req or
	  MUX_t_apb_xactor_ff_request_rv_port0__write_1__VAL_2 or
	  WILL_FIRE_RL_t_rl_write_frm_axi or
	  MUX_t_apb_xactor_ff_request_rv_port0__write_1__VAL_3 or
	  WILL_FIRE_RL_t_rl_send_wr_burst_req or
	  MUX_t_apb_xactor_ff_request_rv_port0__write_1__VAL_4)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_t_rl_read_frm_axi:
	  t_apb_xactor_ff_request_rv_port0__write_1 =
	      MUX_t_apb_xactor_ff_request_rv_port0__write_1__VAL_1;
      WILL_FIRE_RL_t_rl_send_rd_burst_req:
	  t_apb_xactor_ff_request_rv_port0__write_1 =
	      MUX_t_apb_xactor_ff_request_rv_port0__write_1__VAL_2;
      WILL_FIRE_RL_t_rl_write_frm_axi:
	  t_apb_xactor_ff_request_rv_port0__write_1 =
	      MUX_t_apb_xactor_ff_request_rv_port0__write_1__VAL_3;
      WILL_FIRE_RL_t_rl_send_wr_burst_req:
	  t_apb_xactor_ff_request_rv_port0__write_1 =
	      MUX_t_apb_xactor_ff_request_rv_port0__write_1__VAL_4;
      default: t_apb_xactor_ff_request_rv_port0__write_1 =
		   109'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ;
    endcase
  end
  assign t_apb_xactor_ff_request_rv_port1__read =
	     t_apb_xactor_ff_request_rv_EN_port0__write ?
	       t_apb_xactor_ff_request_rv_port0__write_1 :
	       t_apb_xactor_ff_request_rv ;
  assign t_apb_xactor_ff_request_rv_port1__write_1 =
	     { 1'd0,
	       108'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  } ;
  assign t_apb_xactor_ff_request_rv_port2__read =
	     MUX_t_apb_xactor_rg_sel_write_1__SEL_2 ?
	       t_apb_xactor_ff_request_rv_port1__write_1 :
	       t_apb_xactor_ff_request_rv_port1__read ;

  // register t_apb_xactor_ff_request_rv
  assign t_apb_xactor_ff_request_rv_D_IN =
	     t_apb_xactor_ff_request_rv_port2__read ;
  assign t_apb_xactor_ff_request_rv_EN = 1'b1 ;

  // register t_apb_xactor_rg_enable
  assign t_apb_xactor_rg_enable_D_IN =
	     !MUX_t_apb_xactor_rg_enable_write_1__SEL_1 ;
  assign t_apb_xactor_rg_enable_EN =
	     WILL_FIRE_RL_t_apb_xactor_rl_access_to_setup ||
	     WILL_FIRE_RL_t_apb_xactor_rl_access_to_idle ||
	     WILL_FIRE_RL_t_apb_xactor_rl_idle_to_setup ||
	     WILL_FIRE_RL_t_apb_xactor_rl_setup_state ;

  // register t_apb_xactor_rg_request
  assign t_apb_xactor_rg_request_D_IN =
	     t_apb_xactor_ff_request_rv_port1__read[107:0] ;
  assign t_apb_xactor_rg_request_EN = MUX_t_apb_xactor_rg_sel_write_1__SEL_2 ;

  // register t_apb_xactor_rg_sel
  assign t_apb_xactor_rg_sel_D_IN =
	     !WILL_FIRE_RL_t_apb_xactor_rl_access_to_idle ;
  assign t_apb_xactor_rg_sel_EN =
	     WILL_FIRE_RL_t_apb_xactor_rl_access_to_idle ||
	     WILL_FIRE_RL_t_apb_xactor_rl_access_to_setup ||
	     WILL_FIRE_RL_t_apb_xactor_rl_idle_to_setup ;

  // register t_apb_xactor_rg_state
  always@(WILL_FIRE_RL_t_apb_xactor_rl_access_to_idle or
	  MUX_t_apb_xactor_rg_sel_write_1__SEL_2 or
	  WILL_FIRE_RL_t_apb_xactor_rl_setup_state)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_t_apb_xactor_rl_access_to_idle:
	  t_apb_xactor_rg_state_D_IN = 2'd0;
      MUX_t_apb_xactor_rg_sel_write_1__SEL_2:
	  t_apb_xactor_rg_state_D_IN = 2'd1;
      WILL_FIRE_RL_t_apb_xactor_rl_setup_state:
	  t_apb_xactor_rg_state_D_IN = 2'd2;
      default: t_apb_xactor_rg_state_D_IN = 2'bxx /* unspecified value */ ;
    endcase
  end
  assign t_apb_xactor_rg_state_EN =
	     WILL_FIRE_RL_t_apb_xactor_rl_access_to_idle ||
	     WILL_FIRE_RL_t_apb_xactor_rl_access_to_setup ||
	     WILL_FIRE_RL_t_apb_xactor_rl_idle_to_setup ||
	     WILL_FIRE_RL_t_apb_xactor_rl_setup_state ;

  // register t_rg_accum_data
  assign t_rg_accum_data_D_IN = 64'h0 ;
  assign t_rg_accum_data_EN = 1'b0 ;

  // register t_rg_accum_err
  assign t_rg_accum_err_D_IN =
	     WILL_FIRE_RL_t_rl_write_response_to_axi &&
	     MUX_t_rg_accum_err_write_1__VAL_1 ;
  assign t_rg_accum_err_EN =
	     WILL_FIRE_RL_t_rl_write_response_to_axi ||
	     WILL_FIRE_RL_t_rl_write_frm_axi ;

  // register t_rg_accum_mask
  assign t_rg_accum_mask_D_IN = 8'd255 ;
  assign t_rg_accum_mask_EN =
	     WILL_FIRE_RL_t_rl_write_frm_axi ||
	     WILL_FIRE_RL_t_rl_read_frm_axi ;

  // register t_rg_child_burst
  assign t_rg_child_burst_D_IN = 8'h0 ;
  assign t_rg_child_burst_EN = 1'b0 ;

  // register t_rg_child_req_count
  assign t_rg_child_req_count_D_IN = 8'h0 ;
  assign t_rg_child_req_count_EN = 1'b0 ;

  // register t_rg_child_res_count
  assign t_rg_child_res_count_D_IN = 8'h0 ;
  assign t_rg_child_res_count_EN = 1'b0 ;

  // register t_rg_rd_request
  assign t_rg_rd_request_D_IN =
	     WILL_FIRE_RL_t_rl_read_frm_axi ?
	       t_axi_xactor_f_arfifo_D_OUT :
	       MUX_t_rg_rd_request_write_1__VAL_2 ;
  assign t_rg_rd_request_EN =
	     WILL_FIRE_RL_t_rl_read_frm_axi ||
	     WILL_FIRE_RL_t_rl_send_rd_burst_req ;

  // register t_rg_req_beat
  always@(MUX_t_rg_req_beat_write_1__SEL_1 or
	  MUX_t_rg_req_beat_write_1__VAL_1 or
	  WILL_FIRE_RL_t_rl_read_frm_axi or
	  t_axi_xactor_f_arfifo_D_OUT or
	  WILL_FIRE_RL_t_rl_write_frm_axi or t_axi_xactor_f_awfifo_D_OUT)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_t_rg_req_beat_write_1__SEL_1:
	  t_rg_req_beat_D_IN = MUX_t_rg_req_beat_write_1__VAL_1;
      WILL_FIRE_RL_t_rl_read_frm_axi:
	  t_rg_req_beat_D_IN = t_axi_xactor_f_arfifo_D_OUT[28:21];
      WILL_FIRE_RL_t_rl_write_frm_axi:
	  t_rg_req_beat_D_IN = t_axi_xactor_f_awfifo_D_OUT[28:21];
      default: t_rg_req_beat_D_IN = 8'bxxxxxxxx /* unspecified value */ ;
    endcase
  end
  assign t_rg_req_beat_EN =
	     WILL_FIRE_RL_t_rl_send_wr_burst_req ||
	     WILL_FIRE_RL_t_rl_send_rd_burst_req ||
	     WILL_FIRE_RL_t_rl_read_frm_axi ||
	     WILL_FIRE_RL_t_rl_write_frm_axi ;

  // register t_rg_resp_beat
  always@(WILL_FIRE_RL_t_rl_read_frm_axi or
	  MUX_t_rg_resp_beat_write_1__VAL_1 or
	  MUX_t_rg_state_write_1__PSEL_1 or
	  MUX_t_rg_resp_beat_write_1__VAL_2 or
	  WILL_FIRE_RL_t_rl_write_frm_axi or
	  MUX_t_rg_resp_beat_write_1__VAL_3)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_t_rl_read_frm_axi:
	  t_rg_resp_beat_D_IN = MUX_t_rg_resp_beat_write_1__VAL_1;
      MUX_t_rg_state_write_1__PSEL_1:
	  t_rg_resp_beat_D_IN = MUX_t_rg_resp_beat_write_1__VAL_2;
      WILL_FIRE_RL_t_rl_write_frm_axi:
	  t_rg_resp_beat_D_IN = MUX_t_rg_resp_beat_write_1__VAL_3;
      default: t_rg_resp_beat_D_IN = 8'bxxxxxxxx /* unspecified value */ ;
    endcase
  end
  assign t_rg_resp_beat_EN =
	     WILL_FIRE_RL_t_rl_read_frm_axi ||
	     WILL_FIRE_RL_t_rl_write_response_to_axi ||
	     WILL_FIRE_RL_t_rl_read_response_to_axi ||
	     WILL_FIRE_RL_t_rl_write_frm_axi ;

  // register t_rg_state
  always@(MUX_t_rg_state_write_1__SEL_1 or
	  WILL_FIRE_RL_t_rl_read_frm_axi or WILL_FIRE_RL_t_rl_write_frm_axi)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_t_rg_state_write_1__SEL_1: t_rg_state_D_IN = 2'd0;
      WILL_FIRE_RL_t_rl_read_frm_axi: t_rg_state_D_IN = 2'd1;
      WILL_FIRE_RL_t_rl_write_frm_axi: t_rg_state_D_IN = 2'd2;
      default: t_rg_state_D_IN = 2'bxx /* unspecified value */ ;
    endcase
  end
  assign t_rg_state_EN =
	     _dand1t_rg_state_EN_write || WILL_FIRE_RL_t_rl_read_frm_axi ||
	     WILL_FIRE_RL_t_rl_write_frm_axi ;

  // register t_rg_wd_request
  assign t_rg_wd_request_D_IN = t_axi_xactor_f_wfifo_D_OUT ;
  assign t_rg_wd_request_EN = WILL_FIRE_RL_t_rl_write_frm_axi ;

  // register t_rg_wr_request
  assign t_rg_wr_request_D_IN =
	     WILL_FIRE_RL_t_rl_write_frm_axi ?
	       t_axi_xactor_f_awfifo_D_OUT :
	       MUX_t_rg_wr_request_write_1__VAL_2 ;
  assign t_rg_wr_request_EN =
	     WILL_FIRE_RL_t_rl_write_frm_axi ||
	     WILL_FIRE_RL_t_rl_send_wr_burst_req ;

  // submodule t_apb_xactor_ff_response
  assign t_apb_xactor_ff_response_D_IN = { APB_PRDATA, APB_PSLVERR } ;
  assign t_apb_xactor_ff_response_ENQ =
	     WILL_FIRE_RL_t_apb_xactor_rl_access_to_setup ||
	     WILL_FIRE_RL_t_apb_xactor_rl_access_to_idle ;
  assign t_apb_xactor_ff_response_DEQ = MUX_t_rg_state_write_1__PSEL_1 ;
  assign t_apb_xactor_ff_response_CLR = 1'b0 ;

  // submodule t_axi_xactor_f_arfifo
  assign t_axi_xactor_f_arfifo_D_IN =
	     { AXI4_arid,
	       AXI4_araddr,
	       AXI4_arlen,
	       AXI4_arsize,
	       AXI4_arburst,
	       AXI4_arlock,
	       AXI4_arcache,
	       AXI4_arprot,
	       AXI4_arqos,
	       AXI4_arregion } ;
  assign t_axi_xactor_f_arfifo_ENQ =
	     AXI4_arvalid && t_axi_xactor_f_arfifo_FULL_N ;
  assign t_axi_xactor_f_arfifo_DEQ = CAN_FIRE_RL_t_rl_read_frm_axi ;
  assign t_axi_xactor_f_arfifo_CLR = 1'b0 ;

  // submodule t_axi_xactor_f_awfifo
  assign t_axi_xactor_f_awfifo_D_IN =
	     { AXI4_awid,
	       AXI4_awaddr,
	       AXI4_awlen,
	       AXI4_awsize,
	       AXI4_awburst,
	       AXI4_awlock,
	       AXI4_awcache,
	       AXI4_awprot,
	       AXI4_awqos,
	       AXI4_awregion } ;
  assign t_axi_xactor_f_awfifo_ENQ =
	     AXI4_awvalid && t_axi_xactor_f_awfifo_FULL_N ;
  assign t_axi_xactor_f_awfifo_DEQ = WILL_FIRE_RL_t_rl_write_frm_axi ;
  assign t_axi_xactor_f_awfifo_CLR = 1'b0 ;

  // submodule t_axi_xactor_f_bfifo
  assign t_axi_xactor_f_bfifo_D_IN =
	     { t_rg_wr_request[69:61],
	       (t_rg_accum_err || t_apb_xactor_ff_response_D_OUT[0]) ?
		 2'b10 :
		 2'b0 } ;
  assign t_axi_xactor_f_bfifo_ENQ =
	     WILL_FIRE_RL_t_rl_write_response_to_axi &&
	     t_rg_resp_beat == 8'd1 &&
	     (t_rg_child_res_count == t_rg_child_burst ||
	      t_rg_child_burst == 8'd0) ;
  assign t_axi_xactor_f_bfifo_DEQ =
	     AXI4_bready && t_axi_xactor_f_bfifo_EMPTY_N ;
  assign t_axi_xactor_f_bfifo_CLR = 1'b0 ;

  // submodule t_axi_xactor_f_rfifo
  assign t_axi_xactor_f_rfifo_D_IN =
	     { t_rg_rd_request[69:61],
	       t_apb_xactor_ff_response_D_OUT[64:1],
	       axi_response_rresp__h3609,
	       t_rg_resp_beat == 8'd1 } ;
  assign t_axi_xactor_f_rfifo_ENQ = CAN_FIRE_RL_t_rl_read_response_to_axi ;
  assign t_axi_xactor_f_rfifo_DEQ =
	     AXI4_rready && t_axi_xactor_f_rfifo_EMPTY_N ;
  assign t_axi_xactor_f_rfifo_CLR = 1'b0 ;

  // submodule t_axi_xactor_f_wfifo
  assign t_axi_xactor_f_wfifo_D_IN = { AXI4_wdata, AXI4_wstrb, AXI4_wlast } ;
  assign t_axi_xactor_f_wfifo_ENQ =
	     AXI4_wvalid && t_axi_xactor_f_wfifo_FULL_N ;
  assign t_axi_xactor_f_wfifo_DEQ =
	     WILL_FIRE_RL_t_rl_send_wr_burst_req ||
	     WILL_FIRE_RL_t_rl_write_frm_axi ;
  assign t_axi_xactor_f_wfifo_CLR = 1'b0 ;

  // remaining internal signals
  assign _dand1t_rg_state_EN_write =
	     (WILL_FIRE_RL_t_rl_write_response_to_axi ||
	      WILL_FIRE_RL_t_rl_read_response_to_axi) &&
	     t_rg_resp_beat == 8'd1 &&
	     (t_rg_child_res_count == t_rg_child_burst ||
	      t_rg_child_burst == 8'd0) ;
  assign axi_response_rresp__h3609 =
	     t_apb_xactor_ff_response_D_OUT[0] ? 2'b10 : 2'b0 ;
  assign mask__h3026 = 32'hFFFFFFFF << x__h3069 ;
  assign mask__h4361 = 32'hFFFFFFFF << x__h4404 ;
  assign new_address__h3024 =
	     t_rg_rd_request[60:29] +
	     (32'b00000000000000000000000000000001 <<
	      t_rg_rd_request[20:18]) ;
  assign new_address__h4359 =
	     t_rg_wr_request[60:29] +
	     (32'b00000000000000000000000000000001 <<
	      t_rg_wr_request[20:18]) ;
  assign temp1__h3027 = t_rg_rd_request[60:29] & mask__h3026 ;
  assign temp1__h4362 = t_rg_wr_request[60:29] & mask__h4361 ;
  assign temp2__h3028 = new_address__h3024 & y__h3128 ;
  assign temp2__h4363 = new_address__h4359 & y__h4463 ;
  assign x__h3069 =
	     t_rg_rd_request[20:18] +
	     CASE_t_rg_rd_request_BITS_28_TO_21_3_2_7_3_15_4_1__q1 ;
  assign x__h4404 =
	     t_rg_wr_request[20:18] +
	     CASE_t_rg_wr_request_BITS_28_TO_21_3_2_7_3_15_4_1__q2 ;
  assign y__h3128 = ~mask__h3026 ;
  assign y__h4463 = ~mask__h4361 ;
  always@(t_rg_rd_request)
  begin
    case (t_rg_rd_request[28:21])
      8'd3: CASE_t_rg_rd_request_BITS_28_TO_21_3_2_7_3_15_4_1__q1 = 3'd2;
      8'd7: CASE_t_rg_rd_request_BITS_28_TO_21_3_2_7_3_15_4_1__q1 = 3'd3;
      8'd15: CASE_t_rg_rd_request_BITS_28_TO_21_3_2_7_3_15_4_1__q1 = 3'd4;
      default: CASE_t_rg_rd_request_BITS_28_TO_21_3_2_7_3_15_4_1__q1 = 3'd1;
    endcase
  end
  always@(t_rg_wr_request)
  begin
    case (t_rg_wr_request[28:21])
      8'd3: CASE_t_rg_wr_request_BITS_28_TO_21_3_2_7_3_15_4_1__q2 = 3'd2;
      8'd7: CASE_t_rg_wr_request_BITS_28_TO_21_3_2_7_3_15_4_1__q2 = 3'd3;
      8'd15: CASE_t_rg_wr_request_BITS_28_TO_21_3_2_7_3_15_4_1__q2 = 3'd4;
      default: CASE_t_rg_wr_request_BITS_28_TO_21_3_2_7_3_15_4_1__q2 = 3'd1;
    endcase
  end
  always@(t_rg_rd_request or
	  temp1__h3027 or temp2__h3028 or new_address__h3024)
  begin
    case (t_rg_rd_request[17:16])
      2'b0: apb_request_paddr__h3261 = t_rg_rd_request[60:29];
      2'b01: apb_request_paddr__h3261 = new_address__h3024;
      default: apb_request_paddr__h3261 = temp1__h3027 | temp2__h3028;
    endcase
  end
  always@(t_rg_wr_request or
	  temp1__h4362 or temp2__h4363 or new_address__h4359)
  begin
    case (t_rg_wr_request[17:16])
      2'b0: apb_request_paddr__h4630 = t_rg_wr_request[60:29];
      2'b01: apb_request_paddr__h4630 = new_address__h4359;
      default: apb_request_paddr__h4630 = temp1__h4362 | temp2__h4363;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        t_apb_xactor_ff_request_rv <= `BSV_ASSIGNMENT_DELAY
	    { 1'd0,
	      108'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  };
	t_apb_xactor_rg_enable <= `BSV_ASSIGNMENT_DELAY 1'd0;
	t_apb_xactor_rg_request <= `BSV_ASSIGNMENT_DELAY 108'd0;
	t_apb_xactor_rg_sel <= `BSV_ASSIGNMENT_DELAY 1'd0;
	t_apb_xactor_rg_state <= `BSV_ASSIGNMENT_DELAY 2'd0;
	t_rg_accum_data <= `BSV_ASSIGNMENT_DELAY 64'd0;
	t_rg_accum_err <= `BSV_ASSIGNMENT_DELAY 1'd0;
	t_rg_accum_mask <= `BSV_ASSIGNMENT_DELAY 8'd0;
	t_rg_child_burst <= `BSV_ASSIGNMENT_DELAY 8'd0;
	t_rg_child_req_count <= `BSV_ASSIGNMENT_DELAY 8'd0;
	t_rg_child_res_count <= `BSV_ASSIGNMENT_DELAY 8'd0;
	t_rg_rd_request <= `BSV_ASSIGNMENT_DELAY 70'd0;
	t_rg_req_beat <= `BSV_ASSIGNMENT_DELAY 8'd0;
	t_rg_resp_beat <= `BSV_ASSIGNMENT_DELAY 8'd0;
	t_rg_state <= `BSV_ASSIGNMENT_DELAY 2'd0;
	t_rg_wd_request <= `BSV_ASSIGNMENT_DELAY 73'd0;
	t_rg_wr_request <= `BSV_ASSIGNMENT_DELAY 70'd0;
      end
    else
      begin
        if (t_apb_xactor_ff_request_rv_EN)
	  t_apb_xactor_ff_request_rv <= `BSV_ASSIGNMENT_DELAY
	      t_apb_xactor_ff_request_rv_D_IN;
	if (t_apb_xactor_rg_enable_EN)
	  t_apb_xactor_rg_enable <= `BSV_ASSIGNMENT_DELAY
	      t_apb_xactor_rg_enable_D_IN;
	if (t_apb_xactor_rg_request_EN)
	  t_apb_xactor_rg_request <= `BSV_ASSIGNMENT_DELAY
	      t_apb_xactor_rg_request_D_IN;
	if (t_apb_xactor_rg_sel_EN)
	  t_apb_xactor_rg_sel <= `BSV_ASSIGNMENT_DELAY
	      t_apb_xactor_rg_sel_D_IN;
	if (t_apb_xactor_rg_state_EN)
	  t_apb_xactor_rg_state <= `BSV_ASSIGNMENT_DELAY
	      t_apb_xactor_rg_state_D_IN;
	if (t_rg_accum_data_EN)
	  t_rg_accum_data <= `BSV_ASSIGNMENT_DELAY t_rg_accum_data_D_IN;
	if (t_rg_accum_err_EN)
	  t_rg_accum_err <= `BSV_ASSIGNMENT_DELAY t_rg_accum_err_D_IN;
	if (t_rg_accum_mask_EN)
	  t_rg_accum_mask <= `BSV_ASSIGNMENT_DELAY t_rg_accum_mask_D_IN;
	if (t_rg_child_burst_EN)
	  t_rg_child_burst <= `BSV_ASSIGNMENT_DELAY t_rg_child_burst_D_IN;
	if (t_rg_child_req_count_EN)
	  t_rg_child_req_count <= `BSV_ASSIGNMENT_DELAY
	      t_rg_child_req_count_D_IN;
	if (t_rg_child_res_count_EN)
	  t_rg_child_res_count <= `BSV_ASSIGNMENT_DELAY
	      t_rg_child_res_count_D_IN;
	if (t_rg_rd_request_EN)
	  t_rg_rd_request <= `BSV_ASSIGNMENT_DELAY t_rg_rd_request_D_IN;
	if (t_rg_req_beat_EN)
	  t_rg_req_beat <= `BSV_ASSIGNMENT_DELAY t_rg_req_beat_D_IN;
	if (t_rg_resp_beat_EN)
	  t_rg_resp_beat <= `BSV_ASSIGNMENT_DELAY t_rg_resp_beat_D_IN;
	if (t_rg_state_EN)
	  t_rg_state <= `BSV_ASSIGNMENT_DELAY t_rg_state_D_IN;
	if (t_rg_wd_request_EN)
	  t_rg_wd_request <= `BSV_ASSIGNMENT_DELAY t_rg_wd_request_D_IN;
	if (t_rg_wr_request_EN)
	  t_rg_wr_request <= `BSV_ASSIGNMENT_DELAY t_rg_wr_request_D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    t_apb_xactor_ff_request_rv = 109'h0AAAAAAAAAAAAAAAAAAAAAAAAAAA;
    t_apb_xactor_rg_enable = 1'h0;
    t_apb_xactor_rg_request = 108'hAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    t_apb_xactor_rg_sel = 1'h0;
    t_apb_xactor_rg_state = 2'h2;
    t_rg_accum_data = 64'hAAAAAAAAAAAAAAAA;
    t_rg_accum_err = 1'h0;
    t_rg_accum_mask = 8'hAA;
    t_rg_child_burst = 8'hAA;
    t_rg_child_req_count = 8'hAA;
    t_rg_child_res_count = 8'hAA;
    t_rg_rd_request = 70'h2AAAAAAAAAAAAAAAAA;
    t_rg_req_beat = 8'hAA;
    t_rg_resp_beat = 8'hAA;
    t_rg_state = 2'h2;
    t_rg_wd_request = 73'h0AAAAAAAAAAAAAAAAAA;
    t_rg_wr_request = 70'h2AAAAAAAAAAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // axi2apb_64

