// SPDX-License-Identifier: Apache-2.0
// GENERATED integration wrapper — module name matches the SoC's interconnect
// instance name so it drops in without editing the SoC instantiation.
module ni700_ErbiumET (
  input  logic CPU_CLK,
  input  logic SYSTEM_CLK,
  input  logic XSPI_CLK,
  input  logic PERIPH_CLK,
  input  logic CPU_RESETn,
  input  logic SYSTEM_RESETn,
  input  logic XSPI_RESETn,
  input  logic PERIPH_RESETn,
  input  logic [8-1:0] AXI_SLAVE_S_CPU_AWID,
  input  logic [32-1:0] AXI_SLAVE_S_CPU_AWADDR,
  input  logic [8-1:0] AXI_SLAVE_S_CPU_AWLEN,
  input  logic [3-1:0] AXI_SLAVE_S_CPU_AWSIZE,
  input  logic [2-1:0] AXI_SLAVE_S_CPU_AWBURST,
  input  logic AXI_SLAVE_S_CPU_AWLOCK,
  input  logic [4-1:0] AXI_SLAVE_S_CPU_AWCACHE,
  input  logic [3-1:0] AXI_SLAVE_S_CPU_AWPROT,
  input  logic [4-1:0] AXI_SLAVE_S_CPU_AWQOS,
  input  logic AXI_SLAVE_S_CPU_AWVALID,
  input  logic [512-1:0] AXI_SLAVE_S_CPU_WDATA,
  input  logic [64-1:0] AXI_SLAVE_S_CPU_WSTRB,
  input  logic AXI_SLAVE_S_CPU_WLAST,
  input  logic AXI_SLAVE_S_CPU_WVALID,
  input  logic AXI_SLAVE_S_CPU_BREADY,
  input  logic [8-1:0] AXI_SLAVE_S_CPU_ARID,
  input  logic [32-1:0] AXI_SLAVE_S_CPU_ARADDR,
  input  logic [8-1:0] AXI_SLAVE_S_CPU_ARLEN,
  input  logic [3-1:0] AXI_SLAVE_S_CPU_ARSIZE,
  input  logic [2-1:0] AXI_SLAVE_S_CPU_ARBURST,
  input  logic AXI_SLAVE_S_CPU_ARLOCK,
  input  logic [4-1:0] AXI_SLAVE_S_CPU_ARCACHE,
  input  logic [3-1:0] AXI_SLAVE_S_CPU_ARPROT,
  input  logic [4-1:0] AXI_SLAVE_S_CPU_ARQOS,
  input  logic AXI_SLAVE_S_CPU_ARVALID,
  input  logic AXI_SLAVE_S_CPU_RREADY,
  output logic AXI_SLAVE_S_CPU_AWREADY,
  output logic AXI_SLAVE_S_CPU_WREADY,
  output logic [8-1:0] AXI_SLAVE_S_CPU_BID,
  output logic [2-1:0] AXI_SLAVE_S_CPU_BRESP,
  output logic AXI_SLAVE_S_CPU_BVALID,
  output logic AXI_SLAVE_S_CPU_ARREADY,
  output logic [8-1:0] AXI_SLAVE_S_CPU_RID,
  output logic [512-1:0] AXI_SLAVE_S_CPU_RDATA,
  output logic [2-1:0] AXI_SLAVE_S_CPU_RRESP,
  output logic AXI_SLAVE_S_CPU_RLAST,
  output logic AXI_SLAVE_S_CPU_RVALID,
  input  logic AXI_SLAVE_S_XSPI_AWID,
  input  logic [32-1:0] AXI_SLAVE_S_XSPI_AWADDR,
  input  logic [8-1:0] AXI_SLAVE_S_XSPI_AWLEN,
  input  logic [3-1:0] AXI_SLAVE_S_XSPI_AWSIZE,
  input  logic [2-1:0] AXI_SLAVE_S_XSPI_AWBURST,
  input  logic AXI_SLAVE_S_XSPI_AWLOCK,
  input  logic [4-1:0] AXI_SLAVE_S_XSPI_AWCACHE,
  input  logic [3-1:0] AXI_SLAVE_S_XSPI_AWPROT,
  input  logic [4-1:0] AXI_SLAVE_S_XSPI_AWQOS,
  input  logic AXI_SLAVE_S_XSPI_AWVALID,
  input  logic [64-1:0] AXI_SLAVE_S_XSPI_WDATA,
  input  logic [8-1:0] AXI_SLAVE_S_XSPI_WSTRB,
  input  logic AXI_SLAVE_S_XSPI_WLAST,
  input  logic AXI_SLAVE_S_XSPI_WVALID,
  input  logic AXI_SLAVE_S_XSPI_BREADY,
  input  logic AXI_SLAVE_S_XSPI_ARID,
  input  logic [32-1:0] AXI_SLAVE_S_XSPI_ARADDR,
  input  logic [8-1:0] AXI_SLAVE_S_XSPI_ARLEN,
  input  logic [3-1:0] AXI_SLAVE_S_XSPI_ARSIZE,
  input  logic [2-1:0] AXI_SLAVE_S_XSPI_ARBURST,
  input  logic AXI_SLAVE_S_XSPI_ARLOCK,
  input  logic [4-1:0] AXI_SLAVE_S_XSPI_ARCACHE,
  input  logic [3-1:0] AXI_SLAVE_S_XSPI_ARPROT,
  input  logic [4-1:0] AXI_SLAVE_S_XSPI_ARQOS,
  input  logic AXI_SLAVE_S_XSPI_ARVALID,
  input  logic AXI_SLAVE_S_XSPI_RREADY,
  output logic AXI_SLAVE_S_XSPI_AWREADY,
  output logic AXI_SLAVE_S_XSPI_WREADY,
  output logic AXI_SLAVE_S_XSPI_BID,
  output logic [2-1:0] AXI_SLAVE_S_XSPI_BRESP,
  output logic AXI_SLAVE_S_XSPI_BVALID,
  output logic AXI_SLAVE_S_XSPI_ARREADY,
  output logic AXI_SLAVE_S_XSPI_RID,
  output logic [64-1:0] AXI_SLAVE_S_XSPI_RDATA,
  output logic [2-1:0] AXI_SLAVE_S_XSPI_RRESP,
  output logic AXI_SLAVE_S_XSPI_RLAST,
  output logic AXI_SLAVE_S_XSPI_RVALID,
  output logic [9-1:0] AXI_MASTER_M_MRAM_AWID,
  output logic [32-1:0] AXI_MASTER_M_MRAM_AWADDR,
  output logic [8-1:0] AXI_MASTER_M_MRAM_AWLEN,
  output logic [3-1:0] AXI_MASTER_M_MRAM_AWSIZE,
  output logic [2-1:0] AXI_MASTER_M_MRAM_AWBURST,
  output logic AXI_MASTER_M_MRAM_AWLOCK,
  output logic [4-1:0] AXI_MASTER_M_MRAM_AWCACHE,
  output logic [3-1:0] AXI_MASTER_M_MRAM_AWPROT,
  output logic [4-1:0] AXI_MASTER_M_MRAM_AWQOS,
  output logic AXI_MASTER_M_MRAM_AWVALID,
  output logic [512-1:0] AXI_MASTER_M_MRAM_WDATA,
  output logic [64-1:0] AXI_MASTER_M_MRAM_WSTRB,
  output logic AXI_MASTER_M_MRAM_WLAST,
  output logic AXI_MASTER_M_MRAM_WVALID,
  output logic AXI_MASTER_M_MRAM_BREADY,
  output logic [9-1:0] AXI_MASTER_M_MRAM_ARID,
  output logic [32-1:0] AXI_MASTER_M_MRAM_ARADDR,
  output logic [8-1:0] AXI_MASTER_M_MRAM_ARLEN,
  output logic [3-1:0] AXI_MASTER_M_MRAM_ARSIZE,
  output logic [2-1:0] AXI_MASTER_M_MRAM_ARBURST,
  output logic AXI_MASTER_M_MRAM_ARLOCK,
  output logic [4-1:0] AXI_MASTER_M_MRAM_ARCACHE,
  output logic [3-1:0] AXI_MASTER_M_MRAM_ARPROT,
  output logic [4-1:0] AXI_MASTER_M_MRAM_ARQOS,
  output logic AXI_MASTER_M_MRAM_ARVALID,
  output logic AXI_MASTER_M_MRAM_RREADY,
  input  logic AXI_MASTER_M_MRAM_AWREADY,
  input  logic AXI_MASTER_M_MRAM_WREADY,
  input  logic [9-1:0] AXI_MASTER_M_MRAM_BID,
  input  logic [2-1:0] AXI_MASTER_M_MRAM_BRESP,
  input  logic AXI_MASTER_M_MRAM_BVALID,
  input  logic AXI_MASTER_M_MRAM_ARREADY,
  input  logic [9-1:0] AXI_MASTER_M_MRAM_RID,
  input  logic [512-1:0] AXI_MASTER_M_MRAM_RDATA,
  input  logic [2-1:0] AXI_MASTER_M_MRAM_RRESP,
  input  logic AXI_MASTER_M_MRAM_RLAST,
  input  logic AXI_MASTER_M_MRAM_RVALID,
  output logic [9-1:0] AXI_MASTER_M_CPU_REG_AWID,
  output logic [32-1:0] AXI_MASTER_M_CPU_REG_AWADDR,
  output logic [8-1:0] AXI_MASTER_M_CPU_REG_AWLEN,
  output logic [3-1:0] AXI_MASTER_M_CPU_REG_AWSIZE,
  output logic [2-1:0] AXI_MASTER_M_CPU_REG_AWBURST,
  output logic AXI_MASTER_M_CPU_REG_AWLOCK,
  output logic [4-1:0] AXI_MASTER_M_CPU_REG_AWCACHE,
  output logic [3-1:0] AXI_MASTER_M_CPU_REG_AWPROT,
  output logic [4-1:0] AXI_MASTER_M_CPU_REG_AWQOS,
  output logic AXI_MASTER_M_CPU_REG_AWVALID,
  output logic [64-1:0] AXI_MASTER_M_CPU_REG_WDATA,
  output logic [8-1:0] AXI_MASTER_M_CPU_REG_WSTRB,
  output logic AXI_MASTER_M_CPU_REG_WLAST,
  output logic AXI_MASTER_M_CPU_REG_WVALID,
  output logic AXI_MASTER_M_CPU_REG_BREADY,
  output logic [9-1:0] AXI_MASTER_M_CPU_REG_ARID,
  output logic [32-1:0] AXI_MASTER_M_CPU_REG_ARADDR,
  output logic [8-1:0] AXI_MASTER_M_CPU_REG_ARLEN,
  output logic [3-1:0] AXI_MASTER_M_CPU_REG_ARSIZE,
  output logic [2-1:0] AXI_MASTER_M_CPU_REG_ARBURST,
  output logic AXI_MASTER_M_CPU_REG_ARLOCK,
  output logic [4-1:0] AXI_MASTER_M_CPU_REG_ARCACHE,
  output logic [3-1:0] AXI_MASTER_M_CPU_REG_ARPROT,
  output logic [4-1:0] AXI_MASTER_M_CPU_REG_ARQOS,
  output logic AXI_MASTER_M_CPU_REG_ARVALID,
  output logic AXI_MASTER_M_CPU_REG_RREADY,
  input  logic AXI_MASTER_M_CPU_REG_AWREADY,
  input  logic AXI_MASTER_M_CPU_REG_WREADY,
  input  logic [9-1:0] AXI_MASTER_M_CPU_REG_BID,
  input  logic [2-1:0] AXI_MASTER_M_CPU_REG_BRESP,
  input  logic AXI_MASTER_M_CPU_REG_BVALID,
  input  logic AXI_MASTER_M_CPU_REG_ARREADY,
  input  logic [9-1:0] AXI_MASTER_M_CPU_REG_RID,
  input  logic [64-1:0] AXI_MASTER_M_CPU_REG_RDATA,
  input  logic [2-1:0] AXI_MASTER_M_CPU_REG_RRESP,
  input  logic AXI_MASTER_M_CPU_REG_RLAST,
  input  logic AXI_MASTER_M_CPU_REG_RVALID,
  output logic [9-1:0] AXI_MASTER_M_SYSTEM_REG_AWID,
  output logic [32-1:0] AXI_MASTER_M_SYSTEM_REG_AWADDR,
  output logic [8-1:0] AXI_MASTER_M_SYSTEM_REG_AWLEN,
  output logic [3-1:0] AXI_MASTER_M_SYSTEM_REG_AWSIZE,
  output logic [2-1:0] AXI_MASTER_M_SYSTEM_REG_AWBURST,
  output logic AXI_MASTER_M_SYSTEM_REG_AWLOCK,
  output logic [4-1:0] AXI_MASTER_M_SYSTEM_REG_AWCACHE,
  output logic [3-1:0] AXI_MASTER_M_SYSTEM_REG_AWPROT,
  output logic [4-1:0] AXI_MASTER_M_SYSTEM_REG_AWQOS,
  output logic AXI_MASTER_M_SYSTEM_REG_AWVALID,
  output logic [64-1:0] AXI_MASTER_M_SYSTEM_REG_WDATA,
  output logic [8-1:0] AXI_MASTER_M_SYSTEM_REG_WSTRB,
  output logic AXI_MASTER_M_SYSTEM_REG_WLAST,
  output logic AXI_MASTER_M_SYSTEM_REG_WVALID,
  output logic AXI_MASTER_M_SYSTEM_REG_BREADY,
  output logic [9-1:0] AXI_MASTER_M_SYSTEM_REG_ARID,
  output logic [32-1:0] AXI_MASTER_M_SYSTEM_REG_ARADDR,
  output logic [8-1:0] AXI_MASTER_M_SYSTEM_REG_ARLEN,
  output logic [3-1:0] AXI_MASTER_M_SYSTEM_REG_ARSIZE,
  output logic [2-1:0] AXI_MASTER_M_SYSTEM_REG_ARBURST,
  output logic AXI_MASTER_M_SYSTEM_REG_ARLOCK,
  output logic [4-1:0] AXI_MASTER_M_SYSTEM_REG_ARCACHE,
  output logic [3-1:0] AXI_MASTER_M_SYSTEM_REG_ARPROT,
  output logic [4-1:0] AXI_MASTER_M_SYSTEM_REG_ARQOS,
  output logic AXI_MASTER_M_SYSTEM_REG_ARVALID,
  output logic AXI_MASTER_M_SYSTEM_REG_RREADY,
  input  logic AXI_MASTER_M_SYSTEM_REG_AWREADY,
  input  logic AXI_MASTER_M_SYSTEM_REG_WREADY,
  input  logic [9-1:0] AXI_MASTER_M_SYSTEM_REG_BID,
  input  logic [2-1:0] AXI_MASTER_M_SYSTEM_REG_BRESP,
  input  logic AXI_MASTER_M_SYSTEM_REG_BVALID,
  input  logic AXI_MASTER_M_SYSTEM_REG_ARREADY,
  input  logic [9-1:0] AXI_MASTER_M_SYSTEM_REG_RID,
  input  logic [64-1:0] AXI_MASTER_M_SYSTEM_REG_RDATA,
  input  logic [2-1:0] AXI_MASTER_M_SYSTEM_REG_RRESP,
  input  logic AXI_MASTER_M_SYSTEM_REG_RLAST,
  input  logic AXI_MASTER_M_SYSTEM_REG_RVALID,
  output logic [9-1:0] AXI_MASTER_M_MRAM_REG_AWID,
  output logic [32-1:0] AXI_MASTER_M_MRAM_REG_AWADDR,
  output logic [8-1:0] AXI_MASTER_M_MRAM_REG_AWLEN,
  output logic [3-1:0] AXI_MASTER_M_MRAM_REG_AWSIZE,
  output logic [2-1:0] AXI_MASTER_M_MRAM_REG_AWBURST,
  output logic AXI_MASTER_M_MRAM_REG_AWLOCK,
  output logic [4-1:0] AXI_MASTER_M_MRAM_REG_AWCACHE,
  output logic [3-1:0] AXI_MASTER_M_MRAM_REG_AWPROT,
  output logic [4-1:0] AXI_MASTER_M_MRAM_REG_AWQOS,
  output logic AXI_MASTER_M_MRAM_REG_AWVALID,
  output logic [64-1:0] AXI_MASTER_M_MRAM_REG_WDATA,
  output logic [8-1:0] AXI_MASTER_M_MRAM_REG_WSTRB,
  output logic AXI_MASTER_M_MRAM_REG_WLAST,
  output logic AXI_MASTER_M_MRAM_REG_WVALID,
  output logic AXI_MASTER_M_MRAM_REG_BREADY,
  output logic [9-1:0] AXI_MASTER_M_MRAM_REG_ARID,
  output logic [32-1:0] AXI_MASTER_M_MRAM_REG_ARADDR,
  output logic [8-1:0] AXI_MASTER_M_MRAM_REG_ARLEN,
  output logic [3-1:0] AXI_MASTER_M_MRAM_REG_ARSIZE,
  output logic [2-1:0] AXI_MASTER_M_MRAM_REG_ARBURST,
  output logic AXI_MASTER_M_MRAM_REG_ARLOCK,
  output logic [4-1:0] AXI_MASTER_M_MRAM_REG_ARCACHE,
  output logic [3-1:0] AXI_MASTER_M_MRAM_REG_ARPROT,
  output logic [4-1:0] AXI_MASTER_M_MRAM_REG_ARQOS,
  output logic AXI_MASTER_M_MRAM_REG_ARVALID,
  output logic AXI_MASTER_M_MRAM_REG_RREADY,
  input  logic AXI_MASTER_M_MRAM_REG_AWREADY,
  input  logic AXI_MASTER_M_MRAM_REG_WREADY,
  input  logic [9-1:0] AXI_MASTER_M_MRAM_REG_BID,
  input  logic [2-1:0] AXI_MASTER_M_MRAM_REG_BRESP,
  input  logic AXI_MASTER_M_MRAM_REG_BVALID,
  input  logic AXI_MASTER_M_MRAM_REG_ARREADY,
  input  logic [9-1:0] AXI_MASTER_M_MRAM_REG_RID,
  input  logic [64-1:0] AXI_MASTER_M_MRAM_REG_RDATA,
  input  logic [2-1:0] AXI_MASTER_M_MRAM_REG_RRESP,
  input  logic AXI_MASTER_M_MRAM_REG_RLAST,
  input  logic AXI_MASTER_M_MRAM_REG_RVALID,
  output logic [9-1:0] AXI_MASTER_M_SPI_REG_AWID,
  output logic [32-1:0] AXI_MASTER_M_SPI_REG_AWADDR,
  output logic [8-1:0] AXI_MASTER_M_SPI_REG_AWLEN,
  output logic [3-1:0] AXI_MASTER_M_SPI_REG_AWSIZE,
  output logic [2-1:0] AXI_MASTER_M_SPI_REG_AWBURST,
  output logic AXI_MASTER_M_SPI_REG_AWLOCK,
  output logic [4-1:0] AXI_MASTER_M_SPI_REG_AWCACHE,
  output logic [3-1:0] AXI_MASTER_M_SPI_REG_AWPROT,
  output logic [4-1:0] AXI_MASTER_M_SPI_REG_AWQOS,
  output logic AXI_MASTER_M_SPI_REG_AWVALID,
  output logic [64-1:0] AXI_MASTER_M_SPI_REG_WDATA,
  output logic [8-1:0] AXI_MASTER_M_SPI_REG_WSTRB,
  output logic AXI_MASTER_M_SPI_REG_WLAST,
  output logic AXI_MASTER_M_SPI_REG_WVALID,
  output logic AXI_MASTER_M_SPI_REG_BREADY,
  output logic [9-1:0] AXI_MASTER_M_SPI_REG_ARID,
  output logic [32-1:0] AXI_MASTER_M_SPI_REG_ARADDR,
  output logic [8-1:0] AXI_MASTER_M_SPI_REG_ARLEN,
  output logic [3-1:0] AXI_MASTER_M_SPI_REG_ARSIZE,
  output logic [2-1:0] AXI_MASTER_M_SPI_REG_ARBURST,
  output logic AXI_MASTER_M_SPI_REG_ARLOCK,
  output logic [4-1:0] AXI_MASTER_M_SPI_REG_ARCACHE,
  output logic [3-1:0] AXI_MASTER_M_SPI_REG_ARPROT,
  output logic [4-1:0] AXI_MASTER_M_SPI_REG_ARQOS,
  output logic AXI_MASTER_M_SPI_REG_ARVALID,
  output logic AXI_MASTER_M_SPI_REG_RREADY,
  input  logic AXI_MASTER_M_SPI_REG_AWREADY,
  input  logic AXI_MASTER_M_SPI_REG_WREADY,
  input  logic [9-1:0] AXI_MASTER_M_SPI_REG_BID,
  input  logic [2-1:0] AXI_MASTER_M_SPI_REG_BRESP,
  input  logic AXI_MASTER_M_SPI_REG_BVALID,
  input  logic AXI_MASTER_M_SPI_REG_ARREADY,
  input  logic [9-1:0] AXI_MASTER_M_SPI_REG_RID,
  input  logic [64-1:0] AXI_MASTER_M_SPI_REG_RDATA,
  input  logic [2-1:0] AXI_MASTER_M_SPI_REG_RRESP,
  input  logic AXI_MASTER_M_SPI_REG_RLAST,
  input  logic AXI_MASTER_M_SPI_REG_RVALID,
  output logic [9-1:0] AXI_MASTER_M_UART_REG_AWID,
  output logic [32-1:0] AXI_MASTER_M_UART_REG_AWADDR,
  output logic [8-1:0] AXI_MASTER_M_UART_REG_AWLEN,
  output logic [3-1:0] AXI_MASTER_M_UART_REG_AWSIZE,
  output logic [2-1:0] AXI_MASTER_M_UART_REG_AWBURST,
  output logic AXI_MASTER_M_UART_REG_AWLOCK,
  output logic [4-1:0] AXI_MASTER_M_UART_REG_AWCACHE,
  output logic [3-1:0] AXI_MASTER_M_UART_REG_AWPROT,
  output logic [4-1:0] AXI_MASTER_M_UART_REG_AWQOS,
  output logic AXI_MASTER_M_UART_REG_AWVALID,
  output logic [64-1:0] AXI_MASTER_M_UART_REG_WDATA,
  output logic [8-1:0] AXI_MASTER_M_UART_REG_WSTRB,
  output logic AXI_MASTER_M_UART_REG_WLAST,
  output logic AXI_MASTER_M_UART_REG_WVALID,
  output logic AXI_MASTER_M_UART_REG_BREADY,
  output logic [9-1:0] AXI_MASTER_M_UART_REG_ARID,
  output logic [32-1:0] AXI_MASTER_M_UART_REG_ARADDR,
  output logic [8-1:0] AXI_MASTER_M_UART_REG_ARLEN,
  output logic [3-1:0] AXI_MASTER_M_UART_REG_ARSIZE,
  output logic [2-1:0] AXI_MASTER_M_UART_REG_ARBURST,
  output logic AXI_MASTER_M_UART_REG_ARLOCK,
  output logic [4-1:0] AXI_MASTER_M_UART_REG_ARCACHE,
  output logic [3-1:0] AXI_MASTER_M_UART_REG_ARPROT,
  output logic [4-1:0] AXI_MASTER_M_UART_REG_ARQOS,
  output logic AXI_MASTER_M_UART_REG_ARVALID,
  output logic AXI_MASTER_M_UART_REG_RREADY,
  input  logic AXI_MASTER_M_UART_REG_AWREADY,
  input  logic AXI_MASTER_M_UART_REG_WREADY,
  input  logic [9-1:0] AXI_MASTER_M_UART_REG_BID,
  input  logic [2-1:0] AXI_MASTER_M_UART_REG_BRESP,
  input  logic AXI_MASTER_M_UART_REG_BVALID,
  input  logic AXI_MASTER_M_UART_REG_ARREADY,
  input  logic [9-1:0] AXI_MASTER_M_UART_REG_RID,
  input  logic [64-1:0] AXI_MASTER_M_UART_REG_RDATA,
  input  logic [2-1:0] AXI_MASTER_M_UART_REG_RRESP,
  input  logic AXI_MASTER_M_UART_REG_RLAST,
  input  logic AXI_MASTER_M_UART_REG_RVALID,
  output logic [9-1:0] AXI_MASTER_M_SRAM_AWID,
  output logic [32-1:0] AXI_MASTER_M_SRAM_AWADDR,
  output logic [8-1:0] AXI_MASTER_M_SRAM_AWLEN,
  output logic [3-1:0] AXI_MASTER_M_SRAM_AWSIZE,
  output logic [2-1:0] AXI_MASTER_M_SRAM_AWBURST,
  output logic AXI_MASTER_M_SRAM_AWLOCK,
  output logic [4-1:0] AXI_MASTER_M_SRAM_AWCACHE,
  output logic [3-1:0] AXI_MASTER_M_SRAM_AWPROT,
  output logic [4-1:0] AXI_MASTER_M_SRAM_AWQOS,
  output logic AXI_MASTER_M_SRAM_AWVALID,
  output logic [64-1:0] AXI_MASTER_M_SRAM_WDATA,
  output logic [8-1:0] AXI_MASTER_M_SRAM_WSTRB,
  output logic AXI_MASTER_M_SRAM_WLAST,
  output logic AXI_MASTER_M_SRAM_WVALID,
  output logic AXI_MASTER_M_SRAM_BREADY,
  output logic [9-1:0] AXI_MASTER_M_SRAM_ARID,
  output logic [32-1:0] AXI_MASTER_M_SRAM_ARADDR,
  output logic [8-1:0] AXI_MASTER_M_SRAM_ARLEN,
  output logic [3-1:0] AXI_MASTER_M_SRAM_ARSIZE,
  output logic [2-1:0] AXI_MASTER_M_SRAM_ARBURST,
  output logic AXI_MASTER_M_SRAM_ARLOCK,
  output logic [4-1:0] AXI_MASTER_M_SRAM_ARCACHE,
  output logic [3-1:0] AXI_MASTER_M_SRAM_ARPROT,
  output logic [4-1:0] AXI_MASTER_M_SRAM_ARQOS,
  output logic AXI_MASTER_M_SRAM_ARVALID,
  output logic AXI_MASTER_M_SRAM_RREADY,
  input  logic AXI_MASTER_M_SRAM_AWREADY,
  input  logic AXI_MASTER_M_SRAM_WREADY,
  input  logic [9-1:0] AXI_MASTER_M_SRAM_BID,
  input  logic [2-1:0] AXI_MASTER_M_SRAM_BRESP,
  input  logic AXI_MASTER_M_SRAM_BVALID,
  input  logic AXI_MASTER_M_SRAM_ARREADY,
  input  logic [9-1:0] AXI_MASTER_M_SRAM_RID,
  input  logic [64-1:0] AXI_MASTER_M_SRAM_RDATA,
  input  logic [2-1:0] AXI_MASTER_M_SRAM_RRESP,
  input  logic AXI_MASTER_M_SRAM_RLAST,
  input  logic AXI_MASTER_M_SRAM_RVALID,
  output logic [9-1:0] AXI_MASTER_M_XSPI_AWID,
  output logic [32-1:0] AXI_MASTER_M_XSPI_AWADDR,
  output logic [8-1:0] AXI_MASTER_M_XSPI_AWLEN,
  output logic [3-1:0] AXI_MASTER_M_XSPI_AWSIZE,
  output logic [2-1:0] AXI_MASTER_M_XSPI_AWBURST,
  output logic AXI_MASTER_M_XSPI_AWLOCK,
  output logic [4-1:0] AXI_MASTER_M_XSPI_AWCACHE,
  output logic [3-1:0] AXI_MASTER_M_XSPI_AWPROT,
  output logic [4-1:0] AXI_MASTER_M_XSPI_AWQOS,
  output logic AXI_MASTER_M_XSPI_AWVALID,
  output logic [64-1:0] AXI_MASTER_M_XSPI_WDATA,
  output logic [8-1:0] AXI_MASTER_M_XSPI_WSTRB,
  output logic AXI_MASTER_M_XSPI_WLAST,
  output logic AXI_MASTER_M_XSPI_WVALID,
  output logic AXI_MASTER_M_XSPI_BREADY,
  output logic [9-1:0] AXI_MASTER_M_XSPI_ARID,
  output logic [32-1:0] AXI_MASTER_M_XSPI_ARADDR,
  output logic [8-1:0] AXI_MASTER_M_XSPI_ARLEN,
  output logic [3-1:0] AXI_MASTER_M_XSPI_ARSIZE,
  output logic [2-1:0] AXI_MASTER_M_XSPI_ARBURST,
  output logic AXI_MASTER_M_XSPI_ARLOCK,
  output logic [4-1:0] AXI_MASTER_M_XSPI_ARCACHE,
  output logic [3-1:0] AXI_MASTER_M_XSPI_ARPROT,
  output logic [4-1:0] AXI_MASTER_M_XSPI_ARQOS,
  output logic AXI_MASTER_M_XSPI_ARVALID,
  output logic AXI_MASTER_M_XSPI_RREADY,
  input  logic AXI_MASTER_M_XSPI_AWREADY,
  input  logic AXI_MASTER_M_XSPI_WREADY,
  input  logic [9-1:0] AXI_MASTER_M_XSPI_BID,
  input  logic [2-1:0] AXI_MASTER_M_XSPI_BRESP,
  input  logic AXI_MASTER_M_XSPI_BVALID,
  input  logic AXI_MASTER_M_XSPI_ARREADY,
  input  logic [9-1:0] AXI_MASTER_M_XSPI_RID,
  input  logic [64-1:0] AXI_MASTER_M_XSPI_RDATA,
  input  logic [2-1:0] AXI_MASTER_M_XSPI_RRESP,
  input  logic AXI_MASTER_M_XSPI_RLAST,
  input  logic AXI_MASTER_M_XSPI_RVALID,
  output logic [31:0] APB_MASTER_M_I2C_REG_PADDR,
  output logic [2:0]  APB_MASTER_M_I2C_REG_PPROT,
  output logic        APB_MASTER_M_I2C_REG_PSEL,
  output logic        APB_MASTER_M_I2C_REG_PENABLE,
  output logic        APB_MASTER_M_I2C_REG_PWRITE,
  output logic [31:0] APB_MASTER_M_I2C_REG_PWDATA,
  output logic [3:0]  APB_MASTER_M_I2C_REG_PSTRB,
  input  logic        APB_MASTER_M_I2C_REG_PREADY,
  input  logic [31:0] APB_MASTER_M_I2C_REG_PRDATA,
  input  logic        APB_MASTER_M_I2C_REG_PSLVERR,
  output logic CPU_QACTIVE,
  input  logic CPU_QREQn,
  output logic CPU_QACCEPTn,
  output logic CPU_QDENY,
  input  logic CPU_SPIDEN,
  input  logic CPU_NIDEN,
  input  logic CPU_DBGEN,
  input  logic CPU_SPNIDEN,
  input  logic CPU_PMUSNAPSHOTREQ,
  output logic CPU_PMUSNAPSHOTACK,
  output logic CPU_nPMUINTERRUPT,
  input  logic DFTCPUDISABLE,
  output logic SYSTEM_QACTIVE,
  input  logic SYSTEM_QREQn,
  output logic SYSTEM_QACCEPTn,
  output logic SYSTEM_QDENY,
  input  logic SYSTEM_SPIDEN,
  input  logic SYSTEM_NIDEN,
  input  logic SYSTEM_DBGEN,
  input  logic SYSTEM_SPNIDEN,
  input  logic SYSTEM_PMUSNAPSHOTREQ,
  output logic SYSTEM_PMUSNAPSHOTACK,
  output logic SYSTEM_nPMUINTERRUPT,
  input  logic DFTSYSTEMDISABLE,
  output logic XSPI_QACTIVE,
  input  logic XSPI_QREQn,
  output logic XSPI_QACCEPTn,
  output logic XSPI_QDENY,
  input  logic XSPI_SPIDEN,
  input  logic XSPI_NIDEN,
  input  logic XSPI_DBGEN,
  input  logic XSPI_SPNIDEN,
  input  logic XSPI_PMUSNAPSHOTREQ,
  output logic XSPI_PMUSNAPSHOTACK,
  output logic XSPI_nPMUINTERRUPT,
  input  logic DFTXSPIDISABLE,
  output logic PERIPH_QACTIVE,
  input  logic PERIPH_QREQn,
  output logic PERIPH_QACCEPTn,
  output logic PERIPH_QDENY,
  input  logic PERIPH_SPIDEN,
  input  logic PERIPH_NIDEN,
  input  logic PERIPH_DBGEN,
  input  logic PERIPH_SPNIDEN,
  input  logic PERIPH_PMUSNAPSHOTREQ,
  output logic PERIPH_PMUSNAPSHOTACK,
  output logic PERIPH_nPMUINTERRUPT,
  input  logic DFTPERIPHDISABLE,
  output logic       PD_0_PACTIVE,
  input  logic       PD_0_PREQ,
  input  logic [3:0] PD_0_PSTATE,
  output logic       PD_0_PACCEPT,
  output logic       PD_0_PDENY,
  output logic       PD_0_INTERRUPT,
  output logic       PD_0_NS_INTERRUPT,
  input  logic AXI_SLAVE_S_CPU_AWAKEUP,
  input  logic AXI_SLAVE_S_XSPI_AWAKEUP,
  output logic AXI_MASTER_M_MRAM_AWAKEUP,
  output logic AXI_MASTER_M_CPU_REG_AWAKEUP,
  output logic AXI_MASTER_M_SYSTEM_REG_AWAKEUP,
  output logic AXI_MASTER_M_MRAM_REG_AWAKEUP,
  output logic AXI_MASTER_M_SPI_REG_AWAKEUP,
  output logic AXI_MASTER_M_UART_REG_AWAKEUP,
  output logic AXI_MASTER_M_SRAM_AWAKEUP,
  output logic AXI_MASTER_M_XSPI_AWAKEUP,
  input  logic [31:0] ECOREVNUM,
  input  logic S_CPU_CONFIG_ACCESS,
  input  logic S_XSPI_CONFIG_ACCESS,
  input  logic DFTCGEN,
  input  logic DFTRSTDISABLE
);
  erbium_noc_top u_impl (.*);
endmodule
